//! Generated by nexus v0.10.3 — do not edit

const std = @import("std");
const maxArgs: usize = 32;

// SIMD helpers (fallback if simd.zig not available)
const simd = struct {
    fn findByte(haystack: []const u8, needle: u8) usize {
        for (haystack, 0..) |c, i| if (c == needle) return i;
        return haystack.len;
    }
};

// =============================================================================
// TOKEN CATEGORIES
// =============================================================================

pub const TokenCat = enum(u8) {
    @"ident",
    @"integer",
    @"assign",
    @"plus_assign",
    @"arrow",
    @"newline",
    @"eof",
    @"err",

    // Internal (used by generator)
    @"skip",
};

// =============================================================================
// TOKEN STRUCT (8 bytes)
// =============================================================================

pub const Token = struct {
    pos: u32,         // Byte position in source (4 bytes)
    len: u16,         // Token length in bytes (2 bytes)
    cat: TokenCat,    // Token category (1 byte)
    pre: u8,          // Preceding whitespace count (1 byte)

    comptime {
        std.debug.assert(@sizeOf(Token) == 8);
    }
};

// =============================================================================
// LEXER
// =============================================================================
pub const Lexer = struct {
    const Self = @This();

    source: []const u8,
    pos: u32,
    aux: u16 = 0,
    // State variables

    pub fn init(source: []const u8) Self {
        return .{
            .source = source,
            .pos = 0,
        };
    }

    /// Get the text slice for a token (zero-copy into source)
    pub fn text(self: *const Self, tok: Token) []const u8 {
        const start: usize = tok.pos;
        const end: usize = @min(start + tok.len, self.source.len);
        if (start >= self.source.len) return "";
        return self.source[start..end];
    }

    /// Reset lexer to beginning
    pub fn reset(self: *Self) void {
        self.pos = 0;
    }

    /// Peek at current character (0 if at end)
    inline fn peek(self: *const Self) u8 {
        return if (self.pos < self.source.len) self.source[self.pos] else 0;
    }

    /// Peek at character at offset (0 if at end)
    inline fn peekAt(self: *const Self, offset: u32) u8 {
        const p = self.pos + offset;
        return if (p < self.source.len) self.source[p] else 0;
    }

    /// Get next token
    pub fn next(self: *Self) Token {
        return self.matchRules();
    }

    // Character classification flags (generated from grammar patterns)
    const DIGIT: u8 = 1 << 0;
    const LETTER: u8 = 1 << 1;
    const WHITESPACE: u8 = 1 << 2;

    const charFlags: [256]u8 = blk: {
        var table: [256]u8 = [_]u8{0} ** 256;
        for ('0'..'9' + 1) |c| table[c] = DIGIT;
        for ('A'..'Z' + 1) |c| table[c] = LETTER;
        for ('a'..'z' + 1) |c| table[c] = LETTER;
        table['_'] = LETTER;
        table[' '] = WHITESPACE;
        table['\t'] = WHITESPACE;
        break :blk table;
    };

    inline fn isDigit(c: u8) bool {
        return (charFlags[c] & DIGIT) != 0;
    }

    inline fn isLetter(c: u8) bool {
        return (charFlags[c] & LETTER) != 0;
    }

    inline fn isWhitespace(c: u8) bool {
        return (charFlags[c] & WHITESPACE) != 0;
    }

    inline fn isIdentChar(c: u8) bool {
        return isLetter(c) or isDigit(c);
    }
    /// Match lexer rules
    pub fn matchRules(self: *Self) Token {
        // Count whitespace first
        const wsStart = self.pos;
        while (self.pos < self.source.len and isWhitespace(self.source[self.pos])) {
            self.pos += 1;
        }
        const wsCount: u8 = @intCast(@min(self.pos - wsStart, 255));
        // EOF check
        if (self.pos >= self.source.len) {            return Token{ .cat = .@"eof", .pre = wsCount, .pos = self.pos, .len = 0 };
        }

        const start = self.pos;
        const c = self.source[self.pos];
        // Newline handling (generated from grammar rules)
        if (c == '\n' or c == '\r') {
                self.pos += 1;
                return Token{ .cat = .@"newline", .pre = wsCount, .pos = start, .len = 1 };
        }
        // Number
        if (isDigit(c)) {
            return self.scanNumber(start, wsCount);
        }
        // Identifier
        if (isLetter(c)) {
            return self.scanIdent(start, wsCount);
        }
        // Single/multi-char operators
        self.pos += 1;
        return switch (c) {
            '+' => blk: {
                if (self.peek() == '=') {
                    self.pos += 1;
                    break :blk Token{ .cat = .@"plus_assign", .pre = wsCount, .pos = start, .len = 2 };
                }
                break :blk Token{ .cat = .@"err", .pre = wsCount, .pos = start, .len = 1 };
            },
            '-' => blk: {
                if (self.peek() == '>') {
                    self.pos += 1;
                    break :blk Token{ .cat = .@"arrow", .pre = wsCount, .pos = start, .len = 2 };
                }
                break :blk Token{ .cat = .@"err", .pre = wsCount, .pos = start, .len = 1 };
            },
            '=' => Token{ .cat = .@"assign", .pre = wsCount, .pos = start, .len = 1 },
            else => Token{ .cat = .@"err", .pre = wsCount, .pos = start, .len = 1 },
        };
    }

    /// Scan number (generated from grammar)
    fn scanNumber(self: *Self, start: u32, ws: u8) Token {        // Decimal integer
        if (isDigit(self.source[self.pos])) {
            while (self.pos < self.source.len and isDigit(self.source[self.pos])) {
                self.pos += 1;
            }
        }
        return Token{ .cat = .@"integer", .pre = ws, .pos = start, .len = @intCast(self.pos - start) };
    }

    /// Scan identifier (generated from grammar)
    fn scanIdent(self: *Self, start: u32, ws: u8) Token {
        while (self.pos < self.source.len and isIdentChar(self.source[self.pos])) {
            self.pos += 1;
        }
        return Token{ .cat = .@"ident", .pre = ws, .pos = start, .len = @intCast(self.pos - start) };
    }
};

// =============================================================================
// Tag Enum (auto-extracted from grammar actions)
// =============================================================================

pub const Tag = enum(u8) {
    @"module",
    @"set",
    @"fixed",
    @"move",
    @"+=",
    _,
};

// =============================================================================
// S-Expression (AST Node) - 5 Clean Variants
// =============================================================================

pub const Sexp = union(enum) {
    nil:  void,                                        // Empty (nothing)
    tag:  Tag,                                         // Semantic type (1 byte)
    src:  struct { pos: u32, len: u16, id: u16 },      // Source ref + identity (8 bytes)
    str:  []const u8,                                  // Embedded string (16 bytes)
    list: []const Sexp,                                // Compound: (tag child1 ...)

    /// Get token text from source
    pub fn getText(self: Sexp, source: []const u8) []const u8 {
        return switch (self) {
            .src => |s| source[s.pos..][0..s.len],
            .str => |s| s,
            else => "",
        };
    }

    /// Format for debug output
    pub fn write(self: Sexp, source: []const u8, w: anytype) !void {
        switch (self) {
            .nil => try w.writeAll("_"),
            .tag => |t| try w.print("{s}", .{@tagName(t)}),
            .src => |s| try w.print("{s}", .{source[s.pos..][0..s.len]}),
            .str => |s| try w.print("\"{s}\"", .{s}),
            .list => |items| {
                try w.writeAll("(");
                for (items, 0..) |item, i| {
                    if (i > 0) try w.writeAll(" ");
                    try item.write(source, w);
                }
                try w.writeAll(")");
            },
        }
    }
};

// =============================================================================
// PARSER
// =============================================================================

pub const BaseParser = struct {
    arena: std.heap.ArenaAllocator,
    lexer: Lexer,
    source: []const u8,
    current: Token,
    injectedToken: ?u16 = null,
    lastMatchedId: u16 = 0,

    stateStack: std.ArrayListUnmanaged(u16) = .empty,
    valueStack: std.ArrayListUnmanaged(Sexp) = .empty,

    pub fn init(backingAllocator: std.mem.Allocator, source: []const u8) BaseParser {
        var p = BaseParser{
            .arena = std.heap.ArenaAllocator.init(backingAllocator),
            .lexer = Lexer.init(source),
            .source = source,
            .current = undefined,
        };
        p.current = p.lexer.next();
        return p;
    }

    pub fn deinit(self: *BaseParser) void {
        self.arena.deinit();
    }

    fn allocator(self: *BaseParser) std.mem.Allocator {
        return self.arena.allocator();
    }

    pub fn printError(self: *BaseParser) void {
        const pos: usize = @min(self.current.pos, self.source.len);
        var line: usize = 1;
        var col: usize = 1;
        var i: usize = 0;
        while (i < pos) : (i += 1) {
            if (self.source[i] == '\n') {
                line += 1;
                col = 1;
            } else {
                col += 1;
            }
        }
        std.debug.print("Parse error at line {d}, column {d}: unexpected {s}\n", .{
            line,
            col,
            @tagName(self.current.cat),
        });
    }

    fn doParse(self: *BaseParser, startSym: u16) !Sexp {
        const startState = getStartState(startSym);
        self.stateStack.clearRetainingCapacity();
        self.valueStack.clearRetainingCapacity();
        try self.stateStack.append(self.allocator(), startState);

        while (true) {
            const state = self.stateStack.getLast();
            const sym = if (self.injectedToken) |inj| inj else self.tokenToSymbol(self.current);
            var action = getAction(state, sym);

            // X "c" check: if reducing and next char matches with pre==0, shift instead
            if (action < -1 and self.current.pre == 0 and self.current.pos < self.source.len) {
                if (getImmediateShift(state, self.source[self.current.pos])) |shiftTarget| {
                    action = shiftTarget;
                }
            }

            if (action == 0) {
                return error.ParseError;
            } else if (action == -1) {
                return self.valueStack.getLast();
            } else if (action > 0) {
                // Shift
                if (self.injectedToken != null) {
                    try self.valueStack.append(self.allocator(), .nil);
                    self.injectedToken = null;
                } else {
                    try self.valueStack.append(self.allocator(), .{ .src = .{
                        .pos = self.current.pos,
                        .len = self.current.len,
                        .id  = if (self.lastMatchedId != 0) self.lastMatchedId else self.lexer.base.aux,
                    } });
                    self.lastMatchedId = 0;
                    self.lexer.base.aux = 0;
                    self.current = self.lexer.next();
                }
                try self.stateStack.append(self.allocator(), @intCast(action));
            } else {
                // Reduce
                const ruleId: u16 = @intCast(-action - 2);
                var pass: [maxArgs]Sexp = undefined;
                const len = ruleLen[ruleId];
                for (0..len) |i| {
                    pass[len - 1 - i] = self.valueStack.pop().?;
                    _ = self.stateStack.pop();
                }

                const result = self.executeAction(ruleId, pass[0..len]);

                if (isAcceptRule(ruleId)) return result;

                try self.valueStack.append(self.allocator(), result);

                const gotoState = self.stateStack.getLast();
                const next = getAction(gotoState, ruleLhs[ruleId]);
                if (next <= 0) return error.ParseError;
                try self.stateStack.append(self.allocator(), @intCast(next));
            }
        }
    }

    /// Spread list helper: [head, ...tail]
    fn spreadList(self: *BaseParser, head: Sexp, tail: Sexp) Sexp {
        var out: std.ArrayListUnmanaged(Sexp) = .empty;
        out.append(self.allocator(), head) catch return .nil;
        if (tail == .list) for (tail.list) |item| out.append(self.allocator(), item) catch return .nil;
        return .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} };
    }

    /// Spread only: [...tail]
    fn spreadOnly(self: *BaseParser, tail: Sexp) Sexp {
        var out: std.ArrayListUnmanaged(Sexp) = .empty;
        if (tail == .list) for (tail.list) |item| out.append(self.allocator(), item) catch return .nil;
        return .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} };
    }

    /// Default list handler
    fn list(self: *BaseParser, pass: []Sexp) Sexp {
        if (pass.len == 0) return .nil;
        if (pass.len == 1) return pass[0];
        var out: std.ArrayListUnmanaged(Sexp) = .empty;
        for (pass) |v| out.append(self.allocator(), v) catch return .nil;
        return .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} };
    }

    /// Build S-expression: (tag items...) with trailing nil trimming
    inline fn sexp(self: *BaseParser, comptime tag: Tag, items: []const Sexp) Sexp {
        if (items.len == 0) {
            const result = self.allocator().alloc(Sexp, 1) catch return .nil;
            result[0] = .{ .tag = tag };
            return .{ .list = result };
        }
        var len = items.len;
        while (len > 0 and items[len - 1] == .nil) len -= 1;
        const result = self.allocator().alloc(Sexp, len + 1) catch return .nil;
        result[0] = .{ .tag = tag };
        if (len > 0) @memcpy(result[1..][0..len], items[0..len]);
        return .{ .list = result };
    }

    /// Build S-expression: (tag ...spread) - tag + spread items
    inline fn sexpSpread(self: *BaseParser, comptime tag: Tag, spread: Sexp) Sexp {
        const items = if (spread == .list) spread.list else &[_]Sexp{};
        var len = items.len;
        while (len > 0 and items[len - 1] == .nil) len -= 1;
        const result = self.allocator().alloc(Sexp, len + 1) catch return .nil;
        result[0] = .{ .tag = tag };
        if (len > 0) @memcpy(result[1..][0..len], items[0..len]);
        return .{ .list = result };
    }

    /// Build S-expression: (tag pos ...spread) - tag + position + spread items
    inline fn sexpPosSpread(self: *BaseParser, comptime tag: Tag, pos: Sexp, spread: Sexp) Sexp {
        const items = if (spread == .list) spread.list else &[_]Sexp{};
        var len = items.len;
        while (len > 0 and items[len - 1] == .nil) len -= 1;
        const skipPos = (pos == .nil and len == 0);
        const total = if (skipPos) 1 else len + 2;
        const result = self.allocator().alloc(Sexp, total) catch return .nil;
        result[0] = .{ .tag = tag };
        if (!skipPos) {
            result[1] = pos;
            if (len > 0) @memcpy(result[2..][0..len], items[0..len]);
        }
        return .{ .list = result };
    }

    fn executeAction(self: *BaseParser, ruleId: u16, pass: []Sexp) Sexp {
        return switch (ruleId) {
            0 => self.sexpSpread(.@"module", pass[1]),
            1 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .empty; out.append(self.allocator(), pass[0]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            2 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .empty; if (pass[0] == .list) for (pass[0].list) |item| out.append(self.allocator(), item) catch break :blk .nil; out.append(self.allocator(), pass[2]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            3 => pass[0],
            4 => self.sexp(.@"set", &.{.{ .tag = .@"fixed" }, pass[0], .nil, pass[2]}),
            5 => self.sexp(.@"set", &.{.{ .tag = .@"move" }, pass[0], .nil, pass[2]}),
            6 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .empty; out.append(self.allocator(), .{ .tag = .@"set" }) catch break :blk .nil; out.append(self.allocator(), .{ .tag = .@"+=" }) catch break :blk .nil; out.append(self.allocator(), pass[0]) catch break :blk .nil; out.append(self.allocator(), .nil) catch break :blk .nil; out.append(self.allocator(), pass[2]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            7 => self.list(pass),
            else => .nil,
        };
    }

    fn tokenToSymbol(_: *BaseParser, token: Token) u16 {
        return switch (token.cat) {
            .@"eof" => 1,
            .@"newline" => 6,
            .@"ident" => 7,
            .@"integer" => 9,
            .@"assign" => 8,
            else => 2, // error
        };
    }

    fn identToSymbol(_: *BaseParser, _: Token) u16 {
        return symIdent;
    }

    pub fn parseProgram(self: *BaseParser) !Sexp {
        self.injectedToken = SYM_program_START;
        return self.doParse(SYM_program);
    }
};

// =============================================================================
// Top-level convenience helpers (one per start symbol)
// =============================================================================

/// Convenience: instantiate the (lang-extended) parser and parse a whole
/// program. Caller owns `result.parser` and must call `result.parser.deinit()`
/// when done with the returned tree (the tree references arena-allocated
/// memory owned by the parser).
///
/// The parser is returned by value, so the underlying type
/// must be safely movable (no self-referential storage).
/// `BaseParser` is movable by construction; custom `lang.Parser`
/// wrappers must preserve this invariant.
pub fn parseProgram(allocator: std.mem.Allocator, source: []const u8) !struct { parser: BaseParser, sexp: Sexp } {
    var p = BaseParser.init(allocator, source);
    errdefer p.deinit();
    const sexp = try p.parseProgram();
    return .{ .parser = p, .sexp = sexp };
}

// Symbol IDs
const SYM_program: u16 = 3;
const SYM_program_START: u16 = 12;
const symIdent: u16 = 7;

const ruleLhs = [_]u16{ 3, 4, 4, 4, 5, 5, 5, 13 };
const ruleLen = [_]u8{ 2, 1, 3, 2, 3, 3, 3, 2 };

// Parse Table: 15 states × 14 symbols
const numStates = 15;
const numSymbols = 14;

const sparse = [numStates][]const i16{
    &.{3,1,12,2},
    &.{1,-1},
    &.{4,4,5,6,7,5},
    &.{1,-1},
    &.{1,-2,6,7},
    &.{8,8,10,10,11,9},
    &.{1,-3,6,-3},
    &.{1,-5,5,11,6,-5,7,5},
    &.{9,12},
    &.{9,13},
    &.{9,14},
    &.{1,-4,6,-4},
    &.{1,-6,6,-6},
    &.{1,-8,6,-8},
    &.{1,-7,6,-7},
};

const parseTable = blk: {
    @setEvalBranchQuota(100000);
    var t: [numStates][numSymbols]i16 = .{.{0} ** numSymbols} ** numStates;
    for (sparse, 0..) |row, state| {
        var i: usize = 0;
        while (i < row.len) : (i += 2) {
            t[state][@intCast(row[i])] = row[i + 1];
        }
    }
    break :blk t;
};

fn getAction(state: u16, sym: u16) i16 {
    return parseTable[state][sym];
}
// X "c" excludes: shift instead of reduce when pre==0 and char matches
const xExcludes = [_]struct { state: u16, char: u8, shift: u16 }{
};

fn getImmediateShift(state: u16, char: u8) ?i16 {
    for (xExcludes) |x| {
        if (x.state == state and x.char == char) return @intCast(x.shift);
    }
    return null;
}
const startStates = [_]struct { sym: u16, state: u16 }{
    .{ .sym = 3, .state = 0 },
};

fn getStartState(startSym: u16) u16 {
    for (startStates) |entry| {
        if (entry.sym == startSym) return entry.state;
    }
    return 0;
}

const acceptRules = [_]u16{ 7 };

fn isAcceptRule(ruleId: u16) bool {
    for (acceptRules) |ar| if (ruleId == ar) return true;
    return false;
}
