//! Generated by nexus v0.10.3 — do not edit

const std = @import("std");

// =============================================================================
// TOKEN CATEGORIES
// =============================================================================

pub const TokenCat = enum(u8) {
    @"ident",
    @"integer",
    @"assign",
    @"plus_assign",
    @"arrow",
    @"newline",
    @"eof",
    @"err",

    // Internal (used by generator)
    @"skip",
};

// =============================================================================
// TOKEN STRUCT (8 bytes)
// =============================================================================

pub const Token = struct {
    pos: u32,         // Byte position in source (4 bytes)
    len: u16,         // Token length in bytes (2 bytes)
    cat: TokenCat,    // Token category (1 byte)
    pre: u8,          // Preceding whitespace count (1 byte)

    comptime {
        std.debug.assert(@sizeOf(Token) == 8);
    }
};

// =============================================================================
// LEXER
// =============================================================================
pub const Lexer = struct {
    const Self = @This();

    source: []const u8,
    pos: u32,
    aux: u16 = 0,
    // State variables

    pub fn init(source: []const u8) Self {
        return .{
            .source = source,
            .pos = 0,
        };
    }

    /// Get the text slice for a token (zero-copy into source)
    pub fn text(self: *const Self, tok: Token) []const u8 {
        const start: usize = tok.pos;
        const end: usize = @min(start + tok.len, self.source.len);
        if (start >= self.source.len) return "";
        return self.source[start..end];
    }

    /// Reset lexer to beginning
    pub fn reset(self: *Self) void {
        self.pos = 0;
    }

    /// Peek at current character (0 if at end)
    inline fn peek(self: *const Self) u8 {
        return if (self.pos < self.source.len) self.source[self.pos] else 0;
    }

    /// Peek at character at offset (0 if at end)
    inline fn peekAt(self: *const Self, offset: u32) u8 {
        const p = self.pos + offset;
        return if (p < self.source.len) self.source[p] else 0;
    }

    /// Get next token
    pub fn next(self: *Self) Token {
        return self.matchRules();
    }

    // Character classification flags (generated from grammar patterns)
    const DIGIT: u8 = 1 << 0;
    const LETTER: u8 = 1 << 1;
    const WHITESPACE: u8 = 1 << 2;

    const charFlags: [256]u8 = blk: {
        var table: [256]u8 = [_]u8{0} ** 256;
        for ('0'..'9' + 1) |c| table[c] = DIGIT;
        for ('A'..'Z' + 1) |c| table[c] = LETTER;
        for ('a'..'z' + 1) |c| table[c] = LETTER;
        table['_'] = LETTER;
        table[' '] = WHITESPACE;
        table['\t'] = WHITESPACE;
        break :blk table;
    };

    inline fn isDigit(c: u8) bool {
        return (charFlags[c] & DIGIT) != 0;
    }

    inline fn isLetter(c: u8) bool {
        return (charFlags[c] & LETTER) != 0;
    }

    inline fn isWhitespace(c: u8) bool {
        return (charFlags[c] & WHITESPACE) != 0;
    }

    inline fn isIdentChar(c: u8) bool {
        return isLetter(c) or isDigit(c);
    }
    /// Match lexer rules
    pub fn matchRules(self: *Self) Token {
        // Count whitespace first
        const wsStart = self.pos;
        while (self.pos < self.source.len and isWhitespace(self.source[self.pos])) {
            self.pos += 1;
        }
        const wsCount: u8 = @intCast(@min(self.pos - wsStart, 255));
        // EOF check
        if (self.pos >= self.source.len) {            return Token{ .cat = .@"eof", .pre = wsCount, .pos = self.pos, .len = 0 };
        }

        const start = self.pos;
        const c = self.source[self.pos];
        // Newline handling (generated from grammar rules)
        if (c == '\n' or c == '\r') {
                self.pos += 1;
                return Token{ .cat = .@"newline", .pre = wsCount, .pos = start, .len = 1 };
        }
        // Number
        if (isDigit(c)) {
            return self.scanNumber(start, wsCount);
        }
        // Identifier
        if (isLetter(c)) {
            return self.scanIdent(start, wsCount);
        }
        // Single/multi-char operators
        self.pos += 1;
        return switch (c) {
            '+' => blk: {
                if (self.peek() == '=') {
                    self.pos += 1;
                    break :blk Token{ .cat = .@"plus_assign", .pre = wsCount, .pos = start, .len = 2 };
                }
                break :blk Token{ .cat = .@"err", .pre = wsCount, .pos = start, .len = 1 };
            },
            '-' => blk: {
                if (self.peek() == '>') {
                    self.pos += 1;
                    break :blk Token{ .cat = .@"arrow", .pre = wsCount, .pos = start, .len = 2 };
                }
                break :blk Token{ .cat = .@"err", .pre = wsCount, .pos = start, .len = 1 };
            },
            '=' => Token{ .cat = .@"assign", .pre = wsCount, .pos = start, .len = 1 },
            else => Token{ .cat = .@"err", .pre = wsCount, .pos = start, .len = 1 },
        };
    }

    /// Scan number (generated from grammar)
    fn scanNumber(self: *Self, start: u32, ws: u8) Token {        // Decimal integer
        if (isDigit(self.source[self.pos])) {
            while (self.pos < self.source.len and isDigit(self.source[self.pos])) {
                self.pos += 1;
            }
        }
        return Token{ .cat = .@"integer", .pre = ws, .pos = start, .len = @intCast(self.pos - start) };
    }

    /// Scan identifier (generated from grammar)
    fn scanIdent(self: *Self, start: u32, ws: u8) Token {
        while (self.pos < self.source.len and isIdentChar(self.source[self.pos])) {
            self.pos += 1;
        }
        return Token{ .cat = .@"ident", .pre = ws, .pos = start, .len = @intCast(self.pos - start) };
    }
};

// SIMD helpers (fallback if simd.zig not available)
const simd = struct {
    fn findByte(haystack: []const u8, needle: u8) usize {
        for (haystack, 0..) |c, i| if (c == needle) return i;
        return haystack.len;
    }
};

// =============================================================================
// Tag enum (collected from grammar actions)
// =============================================================================

pub const Tag = enum(u8) {
    @"module",
    @"set",
    @"fixed",
    @"move",
    @"+=",
    _,
};

/// Roles exist only in schema mode.
pub const Role = enum(u16) {};

/// Start symbols; `BaseParser.parse(start)` parses one.
pub const Start = enum(u16) {
    @"program" = 3,
};

// =============================================================================
// S-expressions
// =============================================================================

/// Dense per-parse node number; 0 = no node store entry.
pub const NodeId = u32;

/// A byte range [start, end) of the source.
pub const Span = struct {
    start: u32,
    end: u32,

    pub const empty: Span = .{ .start = 0, .end = 0 };

    pub fn len(self: Span) u32 {
        return self.end - self.start;
    }

    pub fn isEmpty(self: Span) bool {
        return self.start == self.end;
    }
};

/// A source leaf: token position and length, plus the token id attribute
/// (an `@as` keyword ordinal, or the lexer's `aux` value; see `takeLexerId`).
pub const Src = struct { pos: u32, len: u16, id: u16 };

/// A list node: its items and its node id (0 when the parse keeps no node
/// store, or for lists built outside the parser, e.g. by a lang wrapper).
pub const List = struct {
    ptr: [*]const Sexp,
    len: u32,
    id: NodeId = 0,

    pub const empty: List = .{ .ptr = &[_]Sexp{}, .len = 0 };

    /// A list over `xs` with no node id.
    pub fn of(xs: []const Sexp) List {
        return .{ .ptr = xs.ptr, .len = @intCast(xs.len) };
    }

    /// A list over `xs` carrying node id `id` (e.g. a rewritten node
    /// keeping the id, and so the span, of the node it replaces).
    pub fn withId(xs: []const Sexp, id: NodeId) List {
        return .{ .ptr = xs.ptr, .len = @intCast(xs.len), .id = id };
    }

    pub fn items(self: List) []const Sexp {
        return self.ptr[0..self.len];
    }
};

/// The uniform tree value: 24 bytes, O(1) dispatch on the head tag.
pub const Sexp = union(enum) {
    nil,
    tag: Tag,
    src: Src,
    str: []const u8,
    list: List,

    comptime {
        std.debug.assert(@sizeOf(Sexp) == 24);
    }

    /// A list value over `xs` with no node id.
    pub fn listOf(xs: []const Sexp) Sexp {
        return .{ .list = List.of(xs) };
    }

    /// The items of a list; empty for any other value.
    pub fn items(self: Sexp) []const Sexp {
        return switch (self) {
            .list => |l| l.items(),
            else => &.{},
        };
    }

    /// The head tag of a tag-headed list.
    pub fn kind(self: Sexp) ?Tag {
        if (self != .list or self.list.len == 0) return null;
        const head = self.list.ptr[0];
        return if (head == .tag) head.tag else null;
    }

    pub fn isKind(self: Sexp, t: Tag) bool {
        const k = self.kind() orelse return false;
        return k == t;
    }

    /// The text of a leaf or string; empty otherwise.
    pub fn getText(self: Sexp, source: []const u8) []const u8 {
        return switch (self) {
            .src => |s| source[s.pos..][0..s.len],
            .str => |s| s,
            else => "",
        };
    }

    /// Print the tree on one line: `_`, tags by name, leaves as their text
    /// followed by `#id` when the id attribute is non-zero, strings quoted.
    pub fn write(self: Sexp, source: []const u8, w: *std.Io.Writer) std.Io.Writer.Error!void {
        switch (self) {
            .nil => try w.writeAll("_"),
            .tag => |t| try w.writeAll(@tagName(t)),
            .src => |s| {
                try w.writeAll(source[s.pos..][0..s.len]);
                if (s.id != 0) try w.print("#{d}", .{s.id});
            },
            .str => |s| try w.print("\"{s}\"", .{s}),
            .list => |l| {
                try w.writeAll("(");
                for (l.items(), 0..) |item, i| {
                    if (i > 0) try w.writeAll(" ");
                    try item.write(source, w);
                }
                try w.writeAll(")");
            },
        }
    }
};


// =============================================================================
// Parser
// =============================================================================

/// Per node: its source span and the rule that built it.
pub const NodeInfo = struct { span: Span, rule: u16 };

/// A side-band role recorded at reduce time (not placed in the tree).
pub const SideEntry = struct { node: NodeId, role: Role, span: Span };

/// A side-band label of a rule: `role` is recorded from element `pass`.
pub const SideLabel = struct { role: Role, pass: u16 };

/// A parse error: the offending token and the state that rejected it.
pub const Failure = struct {
    span: Span,
    /// Grammar symbol of the offending token.
    symbol: u16,
    cat: TokenCat,
    state: u16,
};

/// Result of `parseTolerant`.
pub const Tolerant = struct {
    /// The tree; `.nil` when the parse could not be completed.
    sexp: Sexp,
    /// The first real error (null when the input was valid).
    failure: ?Failure,
    /// Tokens inserted plus tokens deleted.
    repairs: u32,
    complete: bool,
};

/// The id attribute of the token the lexer just produced, cleared as it is
/// read. It is the `aux: u16` field of the generated BaseLexer, which a lang
/// `Lexer` wrapper reaches as `base.aux` (set it before returning a token,
/// e.g. MUMPS stores the dot level of a line there). The parser stores it in
/// the token's `src.id` unless an `@as` keyword match supplies the id.
fn takeLexerId(lexer: *Lexer) u16 {
    if (comptime @hasField(Lexer, "aux")) {
        const id = lexer.aux;
        lexer.aux = 0;
        return id;
    } else if (comptime @hasField(Lexer, "base") and @hasField(@FieldType(Lexer, "base"), "aux")) {
        const id = lexer.base.aux;
        lexer.base.aux = 0;
        return id;
    } else return 0;
}

pub const BaseParser = struct {
    arena: std.heap.ArenaAllocator,
    lexer: Lexer,
    source: []const u8,
    current: Token,
    /// A start marker to shift before any input (set by `parse`).
    injectedToken: ?u16 = null,
    /// A zero-width token the tolerant driver inserts before `current`.
    pendingInsert: ?u16 = null,
    /// `@as` keyword ordinal of `current`, stored in its `src.id`.
    lastMatchedId: u16 = 0,
    /// Set when a builder could not allocate; the parse then fails.
    outOfMemory: bool = false,

    stateStack: std.ArrayListUnmanaged(u16) = .empty,
    valueStack: std.ArrayListUnmanaged(Sexp) = .empty,
    /// Spare capacity of the lists `keepList` returned, by address.
    listSpare: std.AutoHashMapUnmanaged(usize, ListSpare) = .empty,
    /// Node id of the list `extendList` is growing (0 = none).
    extending: NodeId = 0,

    // Node store (when `nodeStore`): one span per value-stack entry, and
    // per node its span and rule, indexed by NodeId (entry 0 unused).
    spanStack: std.ArrayListUnmanaged(Span) = .empty,
    nodes: std.ArrayListUnmanaged(NodeInfo) = .empty,
    sides: std.ArrayListUnmanaged(SideEntry) = .empty,
    reduction: Reduction = .{},
    /// End of the last shifted token (the position of empty reductions).
    lastEnd: u32 = 0,

    triviaTokens: std.ArrayListUnmanaged(Token) = .empty,
    failure: ?Failure = null,
    scratch: std.ArrayListUnmanaged(u16) = .empty,

    const ListSpare = struct { len: usize, capacity: usize };

    /// The reduction in progress: its rule, element spans, and span.
    const Reduction = struct {
        rule: u16 = 0,
        elems: []const Span = &.{},
        span: Span = .empty,
        firstNode: NodeId = 0,
    };

    pub fn init(backingAllocator: std.mem.Allocator, source: []const u8) BaseParser {
        var p = BaseParser{
            .arena = std.heap.ArenaAllocator.init(backingAllocator),
            .lexer = Lexer.init(source),
            .source = source,
            .current = undefined,
        };
        p.current = p.lexer.next();
        return p;
    }

    pub fn deinit(self: *BaseParser) void {
        self.arena.deinit();
    }

    fn allocator(self: *BaseParser) std.mem.Allocator {
        return self.arena.allocator();
    }

    pub fn parseProgram(self: *BaseParser) !Sexp {
        return self.parse(.@"program");
    }


    /// Parse the whole input as `start`.
    pub fn parse(self: *BaseParser, start: Start) !Sexp {
        try self.begin(start);
        while (true) {
            const state = self.stateStack.getLast();
            const sym = self.lookahead();
            const action = self.actionFor(state, sym);
            if (action > 0) {
                try self.shift(@intCast(action));
            } else if (action < -1) {
                try self.reduce(@intCast(-action - 2));
            } else if (action == -1) {
                return self.valueStack.getLast();
            } else {
                self.recordFailure(state, sym);
                return error.ParseError;
            }
        }
    }

    /// Parse `start`, repairing errors from the grammar's `@repair` table:
    /// insert a zero-width token that lets the offending token be shifted,
    /// else delete the offending token. Records the first real error; gives
    /// up after `budget` repairs.
    pub fn parseTolerant(self: *BaseParser, start: Start, budget: u32) !Tolerant {
        if (!hasRepair) @compileError("parseTolerant needs a @repair section in the grammar");
        try self.begin(start);
        var repairs: u32 = 0;
        while (true) {
            const state = self.stateStack.getLast();
            const sym = self.lookahead();
            const action = self.actionFor(state, sym);
            if (action > 0) {
                try self.shift(@intCast(action));
            } else if (action < -1) {
                try self.reduce(@intCast(-action - 2));
            } else if (action == -1) {
                return .{ .sexp = self.valueStack.getLast(), .failure = self.failure, .repairs = repairs, .complete = true };
            } else {
                if (self.failure == null) self.recordFailure(state, sym);
                if (repairs == budget or self.pendingInsert != null) break;
                repairs += 1;
                if (try self.findInsertion(sym)) |token| {
                    self.pendingInsert = token;
                } else if (sym == endSymbol) {
                    break;
                } else {
                    try self.advance();
                }
            }
        }
        return .{ .sexp = .nil, .failure = self.failure, .repairs = repairs, .complete = false };
    }

    fn begin(self: *BaseParser, start: Start) !void {
        self.stateStack.clearRetainingCapacity();
        self.valueStack.clearRetainingCapacity();
        self.failure = null;
        self.pendingInsert = null;
        self.outOfMemory = false;
        try self.stateStack.append(self.allocator(), startState(start));
        self.injectedToken = startMarker(start);
        if (nodeStore) {
            self.spanStack.clearRetainingCapacity();
            if (self.nodes.items.len == 0) try self.nodes.append(self.allocator(), .{ .span = .empty, .rule = 0 });
        }
        if (hasTrivia) try self.skipTrivia();
    }

    inline fn lookahead(self: *BaseParser) u16 {
        if (self.injectedToken) |marker| return marker;
        if (self.pendingInsert) |token| return token;
        return tokenToSymbol(self, self.current);
    }

    /// The table action, with the `X "c"` override: when the table reduces
    /// and the next byte touches the previous token, shift instead.
    inline fn actionFor(self: *const BaseParser, state: u16, sym: u16) i16 {
        const action = getAction(state, sym);
        if (xExcludes.len > 0 and action < -1 and self.current.pre == 0 and self.current.pos < self.source.len) {
            if (getImmediateShift(state, self.source[self.current.pos])) |target| return target;
        }
        return action;
    }

    fn shift(self: *BaseParser, target: u16) !void {
        const a = self.allocator();
        if (self.injectedToken != null) {
            try self.valueStack.append(a, .nil);
            if (nodeStore) try self.spanStack.append(a, .{ .start = self.current.pos, .end = self.current.pos });
            self.injectedToken = null;
        } else if (self.pendingInsert != null) {
            const pos = self.current.pos;
            try self.valueStack.append(a, .{ .src = .{ .pos = pos, .len = 0, .id = 0 } });
            if (nodeStore) try self.spanStack.append(a, .{ .start = pos, .end = pos });
            self.pendingInsert = null;
        } else {
            const tok = self.current;
            const id = if (self.lastMatchedId != 0) self.lastMatchedId else takeLexerId(&self.lexer);
            self.lastMatchedId = 0;
            try self.valueStack.append(a, .{ .src = .{ .pos = tok.pos, .len = tok.len, .id = id } });
            const end = tok.pos + tok.len;
            if (nodeStore) try self.spanStack.append(a, .{ .start = tok.pos, .end = end });
            self.lastEnd = end;
            try self.advance();
        }
        try self.stateStack.append(a, target);
    }

    fn reduce(self: *BaseParser, ruleId: u16) !void {
        const len = ruleLen[ruleId];
        const base = self.valueStack.items.len - len;
        var pass: [maxArgs]Sexp = undefined;
        @memcpy(pass[0..len], self.valueStack.items[base..]);
        self.valueStack.shrinkRetainingCapacity(base);
        self.stateStack.shrinkRetainingCapacity(self.stateStack.items.len - len);

        if (nodeStore) {
            const elems = self.spanStack.items[base..];
            self.reduction = .{
                .rule = ruleId,
                .elems = elems,
                .span = hull(elems, self.lastEnd),
                .firstNode = @intCast(self.nodes.items.len),
            };
        }

        const result = executeAction(self, ruleId, pass[0..len]);
        if (self.outOfMemory) return error.OutOfMemory;

        if (nodeStore) {
            try self.recordSides(ruleId, result);
            const whole = self.reduction.span;
            self.spanStack.shrinkRetainingCapacity(base);
            try self.spanStack.append(self.allocator(), whole);
        }
        try self.valueStack.append(self.allocator(), result);

        const next = getAction(self.stateStack.getLast(), ruleLhs[ruleId]);
        std.debug.assert(next > 0); // every reduction has a goto
        try self.stateStack.append(self.allocator(), @intCast(next));
    }

    /// Fetch the next token, moving trivia to the trivia channel.
    fn advance(self: *BaseParser) !void {
        self.current = self.lexer.next();
        if (hasTrivia) try self.skipTrivia();
    }

    fn skipTrivia(self: *BaseParser) !void {
        while (isTrivia(self.current.cat)) {
            try self.triviaTokens.append(self.allocator(), self.current);
            _ = takeLexerId(&self.lexer);
            self.current = self.lexer.next();
        }
    }

    /// Tokens of the grammar's `@trivia` kinds, in source order.
    pub fn trivia(self: *const BaseParser) []const Token {
        return self.triviaTokens.items;
    }

    // -------------------------------------------------------------------------
    // Node store, spans, side-band roles
    // -------------------------------------------------------------------------

    /// The smallest span covering the non-empty spans in `elems`; empty at
    /// `at` when there are none.
    fn hull(elems: []const Span, at: u32) Span {
        var first: usize = 0;
        while (first < elems.len and elems[first].isEmpty()) first += 1;
        if (first == elems.len) return .{ .start = at, .end = at };
        var last = elems.len - 1;
        while (elems[last].isEmpty()) last -= 1;
        return .{ .start = elems[first].start, .end = elems[last].end };
    }

    /// A new node id for a list the current reduction builds.
    inline fn newNodeId(self: *BaseParser) NodeId {
        if (!nodeStore) return 0;
        return self.addNode(self.reduction.span);
    }

    fn addNode(self: *BaseParser, extent: Span) NodeId {
        const id: NodeId = @intCast(self.nodes.items.len);
        self.nodes.append(self.allocator(), .{ .span = extent, .rule = self.reduction.rule }) catch {
            self.outOfMemory = true;
            return 0;
        };
        return id;
    }

    fn recordSides(self: *BaseParser, ruleId: u16, result: Sexp) !void {
        const labels = ruleSideLabels(ruleId);
        if (labels.len == 0 or result != .list) return;
        const id = result.list.id;
        if (id == 0 or id < self.reduction.firstNode) return;
        for (labels) |label| {
            try self.sides.append(self.allocator(), .{
                .node = id,
                .role = label.role,
                .span = self.reduction.elems[label.pass],
            });
        }
    }

    /// Source span of a value. Leaves span their token. A list with a node
    /// id spans its reduction: first to last consumed token, including
    /// tokens (keywords, punctuation) that are not in the tree. Any other
    /// list spans the hull of its children.
    pub fn span(self: *const BaseParser, s: Sexp) Span {
        switch (s) {
            .src => |x| return .{ .start = x.pos, .end = x.pos + x.len },
            .list => |l| {
                if (nodeStore and l.id != 0 and l.id < self.nodes.items.len) return self.nodes.items[l.id].span;
                var result: ?Span = null;
                for (l.items()) |child| {
                    const cs = self.span(child);
                    if (cs.isEmpty()) continue;
                    result = if (result) |r| .{ .start = r.start, .end = cs.end } else cs;
                }
                return result orelse .empty;
            },
            else => return .empty,
        }
    }

    /// The rule that built a list node (null without a node id).
    pub fn ruleOf(self: *const BaseParser, s: Sexp) ?u16 {
        if (!nodeStore or s != .list) return null;
        const id = s.list.id;
        if (id == 0 or id >= self.nodes.items.len) return null;
        return self.nodes.items[id].rule;
    }

    /// Number of node ids in use (ids run 1 .. nodeCount()).
    pub fn nodeCount(self: *const BaseParser) u32 {
        return if (self.nodes.items.len == 0) 0 else @intCast(self.nodes.items.len - 1);
    }

    /// The side-band roles recorded for node `id`.
    fn sidesOf(self: *const BaseParser, id: NodeId) []const SideEntry {
        const all = self.sides.items;
        var lo: usize = 0;
        var hi: usize = all.len;
        while (lo < hi) {
            const mid = (lo + hi) / 2;
            if (all[mid].node < id) lo = mid + 1 else hi = mid;
        }
        var end = lo;
        while (end < all.len and all[end].node == id) end += 1;
        return all[lo..end];
    }

    /// The span a side-band role of `s` recorded (e.g. the `=` of a `set`).
    pub fn sideRole(self: *const BaseParser, s: Sexp, role: Role) ?Span {
        if (s != .list or s.list.id == 0) return null;
        for (self.sidesOf(s.list.id)) |e| if (e.role == role) return e.span;
        return null;
    }

    // -------------------------------------------------------------------------
    // Tree builders (called by the generated actions)
    // -------------------------------------------------------------------------

    /// Record an allocation failure; the reduction then fails the parse.
    fn oomNil(self: *BaseParser) Sexp {
        self.outOfMemory = true;
        return .nil;
    }

    /// A list node of the current reduction over freshly built `items`.
    inline fn node(self: *BaseParser, items: []const Sexp) Sexp {
        return .{ .list = List.withId(items, self.newNodeId()) };
    }

    /// A nested node built by the current reduction from elements
    /// lo..hi (0-based, inclusive); it spans just those elements.
    fn nested(self: *BaseParser, items: []const Sexp, lo: usize, hi: usize) Sexp {
        const id: NodeId = if (nodeStore) self.addNode(hull(self.reduction.elems[lo .. hi + 1], self.reduction.span.start)) else 0;
        return .{ .list = List.withId(items, id) };
    }

    /// Length of `items` without trailing nils (all of it when positions
    /// are fixed by a schema).
    fn trimmedLen(items: []const Sexp) usize {
        var len = items.len;
        if (!keepTrailingNils) {
            while (len > 0 and items[len - 1] == .nil) len -= 1;
        }
        return len;
    }

    /// The default action: nothing, the one element, or an untagged list.
    fn list(self: *BaseParser, pass: []Sexp) Sexp {
        if (pass.len == 0) return .nil;
        if (pass.len == 1) return pass[0];
        const out = self.allocator().dupe(Sexp, pass) catch return self.oomNil();
        return self.node(out);
    }

    /// `()`: an empty list.
    fn emptyList(self: *BaseParser) Sexp {
        return self.node(&.{});
    }

    /// `[head, ...tail]`
    fn spreadList(self: *BaseParser, head: Sexp, tail: Sexp) Sexp {
        const rest = tail.items();
        const out = self.allocator().alloc(Sexp, rest.len + 1) catch return self.oomNil();
        out[0] = head;
        @memcpy(out[1..], rest);
        return self.node(out);
    }

    /// Start a list holding the items of `base` (a list, else nothing)
    /// for an action that appends to it. A list from `keepList` is reused
    /// with its spare capacity, so a left-recursive list grows in amortized
    /// O(1) per element; it keeps its node id.
    fn extendList(self: *BaseParser, base: Sexp) !std.ArrayListUnmanaged(Sexp) {
        self.extending = 0;
        if (base != .list) return .empty;
        self.extending = base.list.id;
        const items = base.list.items();
        if (items.len > 0) if (self.listSpare.get(@intFromPtr(items.ptr))) |spare| {
            if (spare.len == items.len) {
                _ = self.listSpare.remove(@intFromPtr(items.ptr));
                return .{ .items = @constCast(items), .capacity = spare.capacity };
            }
        };
        var out: std.ArrayListUnmanaged(Sexp) = .empty;
        try out.appendSlice(self.allocator(), items);
        return out;
    }

    /// Finish a list from `extendList`, recording its spare capacity.
    fn keepList(self: *BaseParser, out: *std.ArrayListUnmanaged(Sexp)) Sexp {
        out.shrinkRetainingCapacity(trimmedLen(out.items));
        if (out.items.len > 0 and out.capacity > out.items.len) {
            self.listSpare.put(self.allocator(), @intFromPtr(out.items.ptr), .{
                .len = out.items.len,
                .capacity = out.capacity,
            }) catch return self.oomNil();
        }
        var id: NodeId = 0;
        if (nodeStore) {
            if (self.extending != 0) {
                id = self.extending;
                self.nodes.items[id] = .{ .span = self.reduction.span, .rule = self.reduction.rule };
            } else id = self.newNodeId();
        }
        self.extending = 0;
        return .{ .list = List.withId(out.items, id) };
    }

    /// Finish a list built from scratch.
    fn finishList(self: *BaseParser, out: *std.ArrayListUnmanaged(Sexp)) Sexp {
        out.shrinkRetainingCapacity(trimmedLen(out.items));
        const items = out.toOwnedSlice(self.allocator()) catch return self.oomNil();
        return self.node(items);
    }

    /// `(tag items...)`
    inline fn sexp(self: *BaseParser, comptime tag: Tag, items: []const Sexp) Sexp {
        const len = trimmedLen(items);
        const out = self.allocator().alloc(Sexp, len + 1) catch return self.oomNil();
        out[0] = .{ .tag = tag };
        @memcpy(out[1..], items[0..len]);
        return self.node(out);
    }

    /// `(tag ...spread)`
    inline fn sexpSpread(self: *BaseParser, comptime tag: Tag, spread: Sexp) Sexp {
        const items = spread.items();
        const len = trimmedLen(items);
        const out = self.allocator().alloc(Sexp, len + 1) catch return self.oomNil();
        out[0] = .{ .tag = tag };
        @memcpy(out[1..], items[0..len]);
        return self.node(out);
    }

    /// `(tag pos ...spread)`; just `(tag)` when both are empty (and
    /// positions are not fixed by a schema).
    inline fn sexpPosSpread(self: *BaseParser, comptime tag: Tag, pos: Sexp, spread: Sexp) Sexp {
        const items = spread.items();
        const len = trimmedLen(items);
        const bare = !keepTrailingNils and pos == .nil and len == 0;
        const out = self.allocator().alloc(Sexp, if (bare) 1 else len + 2) catch return self.oomNil();
        out[0] = .{ .tag = tag };
        if (!bare) {
            out[1] = pos;
            @memcpy(out[2..], items[0..len]);
        }
        return self.node(out);
    }

    // -------------------------------------------------------------------------
    // Diagnostics
    // -------------------------------------------------------------------------

    fn recordFailure(self: *BaseParser, state: u16, sym: u16) void {
        const tok = self.current;
        self.failure = .{
            .span = .{ .start = tok.pos, .end = tok.pos + tok.len },
            .symbol = sym,
            .cat = tok.cat,
            .state = state,
        };
    }

    /// The error of the last failed parse (the first one, for
    /// `parseTolerant`).
    pub fn lastError(self: *const BaseParser) ?Failure {
        return self.failure;
    }

    /// 1-based line and column of a byte offset.
    pub fn lineCol(self: *const BaseParser, pos: u32) struct { line: u32, col: u32 } {
        const end: usize = @min(pos, self.source.len);
        var line: u32 = 1;
        var lineStart: usize = 0;
        for (self.source[0..end], 0..) |c, i| {
            if (c == '\n') {
                line += 1;
                lineStart = i + 1;
            }
        }
        return .{ .line = line, .col = @intCast(end - lineStart + 1) };
    }

    /// `line:col: expected A, B or C, got D` for the last error.
    pub fn writeError(self: *const BaseParser, w: *std.Io.Writer) std.Io.Writer.Error!void {
        const f = self.failure orelse return;
        const at = self.lineCol(f.span.start);
        try w.print("{d}:{d}: expected ", .{ at.line, at.col });
        var buf: [numSymbols]u16 = undefined;
        const want = expected(f.state, &buf);
        for (want, 0..) |sym, i| {
            if (i > 0) try w.writeAll(if (i + 1 == want.len) " or " else ", ");
            try w.writeAll(symbolName(sym));
        }
        if (want.len == 0) try w.writeAll("nothing");
        try w.writeAll(", got ");
        const got = symbolName(f.symbol);
        try w.writeAll(if (f.symbol == errorSymbol or got.len == 0) @tagName(f.cat) else got);
    }

    pub fn printError(self: *const BaseParser) void {
        var buf: [512]u8 = undefined;
        var w: std.Io.Writer = .fixed(&buf);
        self.writeError(&w) catch {};
        std.debug.print("Parse error at {s}\n", .{w.buffered()});
    }

    /// The reader-facing expected set of `state`: each `@errors` rule
    /// that can start here (in declaration order, when it adds a token not
    /// already covered) stands in for the tokens that begin it; the
    /// remaining acceptable tokens follow in symbol order.
    pub fn expected(state: u16, buf: []u16) []u16 {
        var covered: [numSymbols]bool = @splat(false);
        var n: usize = 0;
        for (namedRules) |named| {
            if (getAction(state, named.symbol) <= 0) continue;
            var adds = false;
            for (named.first) |t| {
                if (!covered[t] and getAction(state, t) != 0) adds = true;
            }
            if (!adds) continue;
            for (named.first) |t| covered[t] = true;
            buf[n] = named.symbol;
            n += 1;
        }
        for (terminals) |t| {
            if (covered[t] or getAction(state, t) == 0) continue;
            buf[n] = t;
            n += 1;
        }
        return buf[0..n];
    }

    // -------------------------------------------------------------------------
    // Tolerant repair
    // -------------------------------------------------------------------------

    /// The first candidate of the current state after which `next` can be
    /// shifted (or accepted).
    fn findInsertion(self: *BaseParser, next: u16) !?u16 {
        for (repairCandidates(self.stateStack.getLast())) |candidate| {
            if (try self.accepts(&.{ candidate, next })) return candidate;
        }
        return null;
    }

    /// Whether `symbols` can be consumed from the current state, simulating
    /// reductions on a scratch copy of the state stack.
    fn accepts(self: *BaseParser, symbols: []const u16) !bool {
        const stack = &self.scratch;
        stack.clearRetainingCapacity();
        try stack.appendSlice(self.allocator(), self.stateStack.items);
        for (symbols) |sym| {
            while (true) {
                const action = getAction(stack.getLast(), sym);
                if (action == 0) return false;
                if (action == -1) return true;
                if (action > 0) {
                    try stack.append(self.allocator(), @intCast(action));
                    break;
                }
                const rule: u16 = @intCast(-action - 2);
                stack.shrinkRetainingCapacity(stack.items.len - ruleLen[rule]);
                const next = getAction(stack.getLast(), ruleLhs[rule]);
                if (next <= 0) return false;
                try stack.append(self.allocator(), @intCast(next));
            }
        }
        return true;
    }

    // -------------------------------------------------------------------------
    // Facts export
    // -------------------------------------------------------------------------

    /// Write the tree as flat facts, one per line, in pre-order:
    ///   (node ID KIND START END)        every list with a node id
    ///   (role ID ROLE CHILD...)         each non-nil child (a rest role
    ///                                   lists all its children)
    ///   (side ID ROLE START LEN)        each side-band role
    /// ROLE is the schema role name, else the child's index in the list.
    /// KIND is the head tag, or `group` for an untagged list. A CHILD is a
    /// node id, `leaf POS LEN`, `tag NAME`, `str "TEXT"`, or `(CHILD...)`
    /// for a list without a node id.
    pub fn writeFacts(self: *const BaseParser, w: *std.Io.Writer, root: Sexp) std.Io.Writer.Error!void {
        if (!nodeStore) @compileError("writeFacts needs the node store (@schema or --spans)");
        try self.factsOf(w, root);
    }

    fn factsOf(self: *const BaseParser, w: *std.Io.Writer, s: Sexp) std.Io.Writer.Error!void {
        if (s != .list) return;
        const l = s.list;
        const items = l.items();
        if (l.id != 0) {
            const k = s.kind();
            const sp = self.span(s);
            try w.print("(node {d} ", .{l.id});
            if (k) |t| try writeName(w, @tagName(t)) else try w.writeAll("group");
            try w.print(" {d} {d})\n", .{ sp.start, sp.end });
            var i: usize = if (k != null) 1 else 0;
            while (i < items.len) : (i += 1) {
                if (k) |t| if (restRoleOf(t)) |rest| if (i >= rest.slot) {
                    try w.print("(role {d} ", .{l.id});
                    try writeName(w, @tagName(rest.role));
                    for (items[i..]) |child| {
                        try w.writeByte(' ');
                        try self.factChild(w, child);
                    }
                    try w.writeAll(")\n");
                    break;
                };
                if (items[i] == .nil) continue;
                try w.print("(role {d} ", .{l.id});
                if (if (k) |t| roleAt(t, i) else null) |role| try writeName(w, @tagName(role)) else try w.print("{d}", .{i});
                try w.writeByte(' ');
                try self.factChild(w, items[i]);
                try w.writeAll(")\n");
            }
            for (self.sidesOf(l.id)) |e| {
                try w.print("(side {d} ", .{l.id});
                try writeName(w, @tagName(e.role));
                try w.print(" {d} {d})\n", .{ e.span.start, e.span.len() });
            }
        }
        for (items) |child| try self.factsOf(w, child);
    }

    fn factChild(self: *const BaseParser, w: *std.Io.Writer, s: Sexp) std.Io.Writer.Error!void {
        switch (s) {
            .nil => try w.writeAll("_"),
            .tag => |t| {
                try w.writeAll("tag ");
                try writeName(w, @tagName(t));
            },
            .src => |x| try w.print("leaf {d} {d}", .{ x.pos, x.len }),
            .str => |x| {
                try w.writeAll("str ");
                try writeQuoted(w, x);
            },
            .list => |l| if (l.id != 0) try w.print("{d}", .{l.id}) else {
                try w.writeByte('(');
                for (l.items(), 0..) |child, i| {
                    if (i > 0) try w.writeByte(' ');
                    try self.factChild(w, child);
                }
                try w.writeByte(')');
            },
        }
    }

    /// A name as a bare symbol, or quoted when it has s-expression syntax.
    fn writeName(w: *std.Io.Writer, name: []const u8) std.Io.Writer.Error!void {
        const plain = name.len > 0 and for (name) |c| {
            if (c <= ' ' or c == '(' or c == ')' or c == '"' or c == '\\' or c == 0x7f) break false;
        } else true;
        if (plain) try w.writeAll(name) else try writeQuoted(w, name);
    }

    fn writeQuoted(w: *std.Io.Writer, text: []const u8) std.Io.Writer.Error!void {
        try w.writeByte('"');
        for (text) |c| switch (c) {
            '"', '\\' => {
                try w.writeByte('\\');
                try w.writeByte(c);
            },
            '\n' => try w.writeAll("\\n"),
            '\t' => try w.writeAll("\\t"),
            else => if (c < ' ' or c == 0x7f) try w.print("\\x{x:0>2}", .{c}) else try w.writeByte(c),
        };
        try w.writeByte('"');
    }
};


// =============================================================================
// Grammar
// =============================================================================

/// Node spans and rule ids are recorded (`@schema` or `--spans`).
pub const nodeStore = false;
/// Lists keep trailing nils: positions are fixed by the schema.
const keepTrailingNils = false;
const hasTrivia = false;
const hasRepair = false;
const maxArgs = 3;
const numSymbols = 14;
const endSymbol: u16 = 1;
const errorSymbol: u16 = 2;

fn tokenToSymbol(_: *BaseParser, token: Token) u16 {
    return switch (token.cat) {
        .@"eof" => 1,
        .@"newline" => 6,
        .@"ident" => 7,
        .@"integer" => 9,
        .@"assign" => 8,
        else => 2, // error
    };
}

fn executeAction(self: *BaseParser, ruleId: u16, pass: []Sexp) Sexp {
    return switch (ruleId) {
        0 => self.sexpSpread(.@"module", pass[1]),
        1 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .empty; out.append(self.allocator(), pass[0]) catch break :blk self.oomNil(); break :blk self.finishList(&out); },
        2 => blk: { var out = self.extendList(pass[0]) catch break :blk self.oomNil(); out.append(self.allocator(), pass[2]) catch break :blk self.oomNil(); break :blk self.keepList(&out); },
        3 => pass[0],
        4 => self.sexp(.@"set", &.{.{ .tag = .@"fixed" }, pass[0], .nil, pass[2]}),
        5 => self.sexp(.@"set", &.{.{ .tag = .@"move" }, pass[0], .nil, pass[2]}),
        6 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .empty; out.append(self.allocator(), .{ .tag = .@"set" }) catch break :blk self.oomNil(); out.append(self.allocator(), .{ .tag = .@"+=" }) catch break :blk self.oomNil(); out.append(self.allocator(), pass[0]) catch break :blk self.oomNil(); out.append(self.allocator(), .nil) catch break :blk self.oomNil(); out.append(self.allocator(), pass[2]) catch break :blk self.oomNil(); break :blk self.finishList(&out); },
        else => unreachable,
    };
}

const ruleLhs = [_]u16{ 3, 4, 4, 4, 5, 5, 5, 13 };
const ruleLen = [_]u8{ 2, 1, 3, 2, 3, 3, 3, 2 };

// Parse table: 15 states x 14 symbols. 0 = error, > 0 = shift or
// goto, -1 = accept, <= -2 = reduce rule (-a - 2).
const numStates = 15;

const sparse = [numStates][]const i16{
    &.{3,1,12,2},
    &.{1,-1},
    &.{4,4,5,6,7,5},
    &.{1,-1},
    &.{1,-2,6,7},
    &.{8,8,10,10,11,9},
    &.{1,-3,6,-3},
    &.{1,-5,5,11,6,-5,7,5},
    &.{9,12},
    &.{9,13},
    &.{9,14},
    &.{1,-4,6,-4},
    &.{1,-6,6,-6},
    &.{1,-8,6,-8},
    &.{1,-7,6,-7},
};

const parseTable = blk: {
    @setEvalBranchQuota(100000);
    var t: [numStates][numSymbols]i16 = .{.{0} ** numSymbols} ** numStates;
    for (sparse, 0..) |row, state| {
        var i: usize = 0;
        while (i < row.len) : (i += 2) {
            t[state][@intCast(row[i])] = row[i + 1];
        }
    }
    break :blk t;
};

fn getAction(state: u16, sym: u16) i16 {
    return parseTable[state][sym];
}

// X "c" excludes: shift instead of reduce when pre == 0 and the next byte matches
const xExcludes = [_]struct { state: u16, char: u8, shift: u16 }{
};

fn getImmediateShift(state: u16, char: u8) ?i16 {
    for (xExcludes) |x| {
        if (x.state == state and x.char == char) return @intCast(x.shift);
    }
    return null;
}

fn startState(start: Start) u16 {
    return switch (start) {
        .@"program" => 0,
    };
}

fn startMarker(start: Start) u16 {
    return switch (start) {
        .@"program" => 12,
    };
}

/// Terminals, for expected sets.
const terminals = [_]u16{ 1, 6, 7, 8, 9, 10, 11 };

/// `@errors` rules and the terminals that can begin them.
const namedRules = [_]struct { symbol: u16, first: []const u16 }{
};

fn symbolName(sym: u16) []const u8 {
    return switch (sym) {
        1 => "end of input",
        6 => "newline",
        7 => "ident",
        8 => "\"=\"",
        9 => "integer",
        10 => "\"->\"",
        11 => "\"+=\"",
        else => "",
    };
}

fn isTrivia(_: TokenCat) bool {
    return false;
}

fn repairCandidates(_: u16) []const u16 {
    return &.{};
}

fn ruleSideLabels(rule: u16) []const SideLabel {
    _ = rule;
    return &.{};
}

fn slotOf(_: Tag, _: Role) ?usize {
    return null;
}

fn restSlotOf(_: Tag, _: Role) ?usize {
    return null;
}

fn roleAt(_: Tag, _: usize) ?Role {
    return null;
}

fn restRoleOf(_: Tag) ?struct { role: Role, slot: usize } {
    return null;
}

// =============================================================================
// API
// =============================================================================

pub const Parser = BaseParser;

/// Parse a whole program with a new `Parser`. The caller owns
/// `result.parser` and must `deinit()` it when done with the tree.
pub fn parseProgram(allocator: std.mem.Allocator, source: []const u8) !struct { parser: Parser, sexp: Sexp } {
    var p = Parser.init(allocator, source);
    errdefer p.deinit();
    const sexp = try p.parseProgram();
    return .{ .parser = p, .sexp = sexp };
}
