//! Generated by nexus v0.10.3 — do not edit

const std = @import("std");
const nexis = @import("nexis.zig");

// =============================================================================
// TOKEN CATEGORIES
// =============================================================================

pub const TokenCat = enum(u8) {
    @"integer",
    @"real",
    @"string",
    @"char",
    @"keyword",
    @"ident",
    @"lparen",
    @"rparen",
    @"lbracket",
    @"rbracket",
    @"lbrace",
    @"rbrace",
    @"hash_lbrace",
    @"hash_lparen",
    @"hash_discard",
    @"quote_tok",
    @"syntax_quote_tok",
    @"unquote_splicing_tok",
    @"unquote_tok",
    @"deref_tok",
    @"caret",
    @"eof",
    @"err",

    // Internal (used by generator)
    @"skip",
};

// =============================================================================
// TOKEN STRUCT (8 bytes)
// =============================================================================

pub const Token = struct {
    pos: u32,         // Byte position in source (4 bytes)
    len: u16,         // Token length in bytes (2 bytes)
    cat: TokenCat,    // Token category (1 byte)
    pre: u8,          // Preceding whitespace count (1 byte)

    comptime {
        std.debug.assert(@sizeOf(Token) == 8);
    }
};

// =============================================================================
// LEXER
// =============================================================================
pub const BaseLexer = struct {
    const Self = @This();

    source: []const u8,
    pos: u32,
    aux: u16 = 0,
    // State variables

    pub fn init(source: []const u8) Self {
        return .{
            .source = source,
            .pos = 0,
        };
    }

    /// Get the text slice for a token (zero-copy into source)
    pub fn text(self: *const Self, tok: Token) []const u8 {
        const start: usize = tok.pos;
        const end: usize = @min(start + tok.len, self.source.len);
        if (start >= self.source.len) return "";
        return self.source[start..end];
    }

    /// Reset lexer to beginning
    pub fn reset(self: *Self) void {
        self.pos = 0;
    }

    /// Peek at current character (0 if at end)
    inline fn peek(self: *const Self) u8 {
        return if (self.pos < self.source.len) self.source[self.pos] else 0;
    }

    /// Peek at character at offset (0 if at end)
    inline fn peekAt(self: *const Self, offset: u32) u8 {
        const p = self.pos + offset;
        return if (p < self.source.len) self.source[p] else 0;
    }

    /// Get next token
    pub fn next(self: *Self) Token {
        return self.matchRules();
    }

    // Character classification flags (generated from grammar patterns)
    const DIGIT: u8 = 1 << 0;
    const LETTER: u8 = 1 << 1;
    const WHITESPACE: u8 = 1 << 2;
    const IDENT_EXTRA: u8 = 1 << 3;

    const charFlags: [256]u8 = blk: {
        var table: [256]u8 = [_]u8{0} ** 256;
        for ('A'..'Z' + 1) |c| table[c] = LETTER;
        for ('a'..'z' + 1) |c| table[c] = LETTER;
        table['!'] = LETTER;
        table['$'] = LETTER;
        table['%'] = LETTER;
        table['&'] = LETTER;
        table['*'] = LETTER;
        table['+'] = LETTER;
        table['-'] = LETTER;
        table['.'] = LETTER;
        table['<'] = LETTER;
        table['='] = LETTER;
        table['>'] = LETTER;
        table['?'] = LETTER;
        table['_'] = LETTER;
        table['\''] = IDENT_EXTRA;
        table['/'] = IDENT_EXTRA;
        table['0'] = IDENT_EXTRA;
        table['1'] = IDENT_EXTRA;
        table['2'] = IDENT_EXTRA;
        table['3'] = IDENT_EXTRA;
        table['4'] = IDENT_EXTRA;
        table['5'] = IDENT_EXTRA;
        table['6'] = IDENT_EXTRA;
        table['7'] = IDENT_EXTRA;
        table['8'] = IDENT_EXTRA;
        table['9'] = IDENT_EXTRA;
        table[' '] = WHITESPACE;
        table['\t'] = WHITESPACE;
        break :blk table;
    };

    inline fn isDigit(c: u8) bool {
        return (charFlags[c] & DIGIT) != 0;
    }

    inline fn isLetter(c: u8) bool {
        return (charFlags[c] & LETTER) != 0;
    }

    inline fn isWhitespace(c: u8) bool {
        return (charFlags[c] & WHITESPACE) != 0;
    }

    inline fn isIdentChar(c: u8) bool {
        return (charFlags[c] & (LETTER | DIGIT | IDENT_EXTRA)) != 0;
    }
    /// Match lexer rules
    pub fn matchRules(self: *Self) Token {
        // Count whitespace first
        const wsStart = self.pos;
        while (self.pos < self.source.len and isWhitespace(self.source[self.pos])) {
            self.pos += 1;
        }
        const wsCount: u8 = @intCast(@min(self.pos - wsStart, 255));
        // EOF check
        if (self.pos >= self.source.len) {            return Token{ .cat = .@"eof", .pre = wsCount, .pos = self.pos, .len = 0 };
        }

        const start = self.pos;
        const c = self.source[self.pos];
        if (c == '"') {            self.pos += 1;
            while (self.pos < self.source.len) {
                const ch = self.source[self.pos];
                if (ch == '"') {
                    self.pos += 1;
                    return Token{ .cat = .@"string", .pre = wsCount, .pos = start, .len = @intCast(self.pos - start) };
                }
                if (ch == '\\') { self.pos += 2; continue; }
                if (ch == '\n') break;
                self.pos += 1;
            }
            return Token{ .cat = .@"err", .pre = wsCount, .pos = start, .len = @intCast(self.pos - start) };
        }
        // Number
        if (isDigit(c)) {
            return self.scanNumber(start, wsCount);
        }
        // Identifier
        if (isLetter(c)) {
            return self.scanIdent(start, wsCount);
        }
        if (c == ':') {
            const nc = if (self.pos + 1 < self.source.len) self.source[self.pos + 1] else 0;
            if ((nc >= 'a' and nc <= 'z') or (nc >= 'A' and nc <= 'Z') or nc == '_') {
                self.pos += 1;
                while (self.pos < self.source.len) {
                    const vc = self.source[self.pos];
                    if (!((vc >= 'a' and vc <= 'z') or (vc >= 'A' and vc <= 'Z') or (vc >= '0' and vc <= '9') or vc == '_')) break;
                    self.pos += 1;
                }
                return Token{ .cat = .@"keyword", .pre = wsCount, .pos = start, .len = @intCast(self.pos - start) };
            }
        }
        // Single/multi-char operators
        self.pos += 1;
        return switch (c) {
            '#' => blk: {
                if (self.peek() == '{') {
                    self.pos += 1;
                    break :blk Token{ .cat = .@"hash_lbrace", .pre = wsCount, .pos = start, .len = 2 };
                }
                if (self.peek() == '(') {
                    self.pos += 1;
                    break :blk Token{ .cat = .@"hash_lparen", .pre = wsCount, .pos = start, .len = 2 };
                }
                if (self.peek() == '_') {
                    self.pos += 1;
                    break :blk Token{ .cat = .@"hash_discard", .pre = wsCount, .pos = start, .len = 2 };
                }
                break :blk Token{ .cat = .@"err", .pre = wsCount, .pos = start, .len = 1 };
            },
            '\'' => Token{ .cat = .@"quote_tok", .pre = wsCount, .pos = start, .len = 1 },
            '(' => Token{ .cat = .@"lparen", .pre = wsCount, .pos = start, .len = 1 },
            ')' => Token{ .cat = .@"rparen", .pre = wsCount, .pos = start, .len = 1 },
            '/' => Token{ .cat = .@"ident", .pre = wsCount, .pos = start, .len = 1 },
            '@' => Token{ .cat = .@"deref_tok", .pre = wsCount, .pos = start, .len = 1 },
            '[' => Token{ .cat = .@"lbracket", .pre = wsCount, .pos = start, .len = 1 },
            ']' => Token{ .cat = .@"rbracket", .pre = wsCount, .pos = start, .len = 1 },
            '^' => Token{ .cat = .@"caret", .pre = wsCount, .pos = start, .len = 1 },
            '`' => Token{ .cat = .@"syntax_quote_tok", .pre = wsCount, .pos = start, .len = 1 },
            '{' => Token{ .cat = .@"lbrace", .pre = wsCount, .pos = start, .len = 1 },
            '}' => Token{ .cat = .@"rbrace", .pre = wsCount, .pos = start, .len = 1 },
            '~' => blk: {
                if (self.peek() == '@') {
                    self.pos += 1;
                    break :blk Token{ .cat = .@"unquote_splicing_tok", .pre = wsCount, .pos = start, .len = 2 };
                }
                    break :blk Token{ .cat = .@"unquote_tok", .pre = wsCount, .pos = start, .len = 1 };
            },
            else => Token{ .cat = .@"err", .pre = wsCount, .pos = start, .len = 1 },
        };
    }

    /// Scan number (generated from grammar)
    fn scanNumber(self: *Self, start: u32, ws: u8) Token {        var hasDecimal = false;        var hasExponent = false;        // Decimal integer
        if (isDigit(self.source[self.pos])) {
            while (self.pos < self.source.len and isDigit(self.source[self.pos])) {
                self.pos += 1;
            }
        }
        // Decimal part
        if (self.pos < self.source.len and self.source[self.pos] == '.') {
            const nextC = if (self.pos + 1 < self.source.len) self.source[self.pos + 1] else 0;
            if (isDigit(nextC)) {
                hasDecimal = true;
                self.pos += 1;
                while (self.pos < self.source.len and isDigit(self.source[self.pos])) {
                    self.pos += 1;
                }
            }
        }
        // Exponent part
        if (self.pos < self.source.len) {
            const e = self.source[self.pos];
            if (e == 'E' or e == 'e') {
                var expPos = self.pos + 1;
                if (expPos < self.source.len and (self.source[expPos] == '+' or self.source[expPos] == '-')) {
                    expPos += 1;
                }
                if (expPos < self.source.len and isDigit(self.source[expPos])) {
                    hasExponent = true;
                    self.pos = expPos;
                    while (self.pos < self.source.len and isDigit(self.source[self.pos])) {
                        self.pos += 1;
                    }
                }
            }
        }
        // Classify
        const tokenCat: TokenCat = if (hasDecimal or hasExponent)
            .@"real"
        else
            .@"integer";

        return Token{ .cat = tokenCat, .pre = ws, .pos = start, .len = @intCast(self.pos - start) };
    }

    /// Scan identifier (generated from grammar)
    fn scanIdent(self: *Self, start: u32, ws: u8) Token {
        while (self.pos < self.source.len and isIdentChar(self.source[self.pos])) {
            self.pos += 1;
        }
        return Token{ .cat = .@"ident", .pre = ws, .pos = start, .len = @intCast(self.pos - start) };
    }
};

pub const Lexer = if (@hasDecl(nexis, "Lexer")) nexis.Lexer else BaseLexer;

// =============================================================================
// Tag enum (re-exported from the language module)
// =============================================================================

pub const Tag = nexis.Tag;

/// Roles exist only in schema mode.
pub const Role = enum(u16) {};

/// Start symbols; `BaseParser.parse(start)` parses one.
pub const Start = enum(u16) {
    @"program" = 3,
    @"form" = 4,
};

// =============================================================================
// S-expressions
// =============================================================================

/// Dense per-parse node number; 0 = no node store entry.
pub const NodeId = u32;

/// A byte range [start, end) of the source.
pub const Span = struct {
    start: u32,
    end: u32,

    pub const empty: Span = .{ .start = 0, .end = 0 };

    pub fn len(self: Span) u32 {
        return self.end - self.start;
    }

    pub fn isEmpty(self: Span) bool {
        return self.start == self.end;
    }
};

/// A source leaf: token position and length, plus the token id attribute
/// (an `@as` keyword ordinal, or the lexer's `aux` value; see `takeLexerId`).
pub const Src = struct { pos: u32, len: u16, id: u16 };

/// A list node: its items and its node id (0 when the parse keeps no node
/// store, or for lists built outside the parser, e.g. by a lang wrapper).
pub const List = struct {
    ptr: [*]const Sexp,
    len: u32,
    id: NodeId = 0,

    pub const empty: List = .{ .ptr = &[_]Sexp{}, .len = 0 };

    /// A list over `xs` with no node id.
    pub fn of(xs: []const Sexp) List {
        return .{ .ptr = xs.ptr, .len = @intCast(xs.len) };
    }

    /// A list over `xs` carrying node id `id` (e.g. a rewritten node
    /// keeping the id, and so the span, of the node it replaces).
    pub fn withId(xs: []const Sexp, id: NodeId) List {
        return .{ .ptr = xs.ptr, .len = @intCast(xs.len), .id = id };
    }

    pub fn items(self: List) []const Sexp {
        return self.ptr[0..self.len];
    }
};

/// The uniform tree value: 24 bytes, O(1) dispatch on the head tag.
pub const Sexp = union(enum) {
    nil,
    tag: Tag,
    src: Src,
    str: []const u8,
    list: List,

    comptime {
        std.debug.assert(@sizeOf(Sexp) == 24);
    }

    /// A list value over `xs` with no node id.
    pub fn listOf(xs: []const Sexp) Sexp {
        return .{ .list = List.of(xs) };
    }

    /// The items of a list; empty for any other value.
    pub fn items(self: Sexp) []const Sexp {
        return switch (self) {
            .list => |l| l.items(),
            else => &.{},
        };
    }

    /// The head tag of a tag-headed list.
    pub fn kind(self: Sexp) ?Tag {
        if (self != .list or self.list.len == 0) return null;
        const head = self.list.ptr[0];
        return if (head == .tag) head.tag else null;
    }

    pub fn isKind(self: Sexp, t: Tag) bool {
        const k = self.kind() orelse return false;
        return k == t;
    }

    /// The text of a leaf or string; empty otherwise.
    pub fn getText(self: Sexp, source: []const u8) []const u8 {
        return switch (self) {
            .src => |s| source[s.pos..][0..s.len],
            .str => |s| s,
            else => "",
        };
    }

    /// Print the tree on one line: `_`, tags by name, leaves as their text
    /// followed by `#id` when the id attribute is non-zero, strings quoted.
    pub fn write(self: Sexp, source: []const u8, w: *std.Io.Writer) std.Io.Writer.Error!void {
        switch (self) {
            .nil => try w.writeAll("_"),
            .tag => |t| try w.writeAll(@tagName(t)),
            .src => |s| {
                try w.writeAll(source[s.pos..][0..s.len]);
                if (s.id != 0) try w.print("#{d}", .{s.id});
            },
            .str => |s| try w.print("\"{s}\"", .{s}),
            .list => |l| {
                try w.writeAll("(");
                for (l.items(), 0..) |item, i| {
                    if (i > 0) try w.writeAll(" ");
                    try item.write(source, w);
                }
                try w.writeAll(")");
            },
        }
    }
};


// =============================================================================
// Parser
// =============================================================================

/// Per node: its source span and the rule that built it.
pub const NodeInfo = struct { span: Span, rule: u16 };

/// NodeInfo per NodeId, in fixed-size chunks that never move (appending
/// never copies the store).
const NodeStore = struct {
    chunks: std.ArrayListUnmanaged(*[chunkLen]NodeInfo) = .empty,
    len: u32 = 0,

    const chunkLen = 1024;

    inline fn add(self: *NodeStore, a: std.mem.Allocator, info: NodeInfo) !NodeId {
        const id = self.len;
        if (id % chunkLen == 0) try self.addChunk(a);
        self.chunks.items[id / chunkLen][id % chunkLen] = info;
        self.len = id + 1;
        return id;
    }

    fn addChunk(self: *NodeStore, a: std.mem.Allocator) !void {
        try self.chunks.append(a, try a.create([chunkLen]NodeInfo));
    }

    inline fn at(self: *const NodeStore, id: NodeId) *NodeInfo {
        return &self.chunks.items[id / chunkLen][id % chunkLen];
    }
};

/// A side-band role recorded at reduce time (not placed in the tree).
pub const SideEntry = struct { node: NodeId, role: Role, span: Span };

/// A side-band label of a rule: `role` is recorded from element `pass`.
pub const SideLabel = struct { role: Role, pass: u16 };

/// A parse error: the offending token and the state that rejected it.
pub const Failure = struct {
    span: Span,
    /// Grammar symbol of the offending token.
    symbol: u16,
    cat: TokenCat,
    state: u16,
};

/// Result of `parseTolerant`.
pub const Tolerant = struct {
    /// The tree; `.nil` when the parse could not be completed.
    sexp: Sexp,
    /// The first real error (null when the input was valid).
    failure: ?Failure,
    /// Tokens inserted plus tokens deleted.
    repairs: u32,
    complete: bool,
};

/// The id attribute of the token the lexer just produced, cleared as it is
/// read. It is the `aux: u16` field of the generated BaseLexer, which a lang
/// `Lexer` wrapper reaches as `base.aux` (set it before returning a token,
/// e.g. MUMPS stores the dot level of a line there). The parser stores it in
/// the token's `src.id` unless an `@as` keyword match supplies the id.
fn takeLexerId(lexer: *Lexer) u16 {
    if (comptime @hasField(Lexer, "aux")) {
        const id = lexer.aux;
        lexer.aux = 0;
        return id;
    } else if (comptime @hasField(Lexer, "base") and @hasField(@FieldType(Lexer, "base"), "aux")) {
        const id = lexer.base.aux;
        lexer.base.aux = 0;
        return id;
    } else return 0;
}

pub const BaseParser = struct {
    arena: std.heap.ArenaAllocator,
    lexer: Lexer,
    source: []const u8,
    current: Token,
    /// A start marker to shift before any input (set by `parse`).
    injectedToken: ?u16 = null,
    /// A zero-width token the tolerant driver inserts before `current`.
    pendingInsert: ?u16 = null,
    /// `@as` keyword ordinal of `current`, stored in its `src.id`.
    lastMatchedId: u16 = 0,
    /// Set when a builder could not allocate; the parse then fails.
    outOfMemory: bool = false,

    stateStack: std.ArrayListUnmanaged(u16) = .empty,
    valueStack: std.ArrayListUnmanaged(Sexp) = .empty,
    /// Spare capacity of the lists `keepList` returned, by address.
    listSpare: std.AutoHashMapUnmanaged(usize, ListSpare) = .empty,
    /// Node id of the list `extendList` is growing (0 = none).
    extending: NodeId = 0,

    // Node store (when `nodeStore`): per value-stack entry where it
    // starts, and per node its span and rule, indexed by NodeId (entry 0
    // unused). An entry starts at its first token, or at the next token
    // when it consumed none. A reduction then extends from its first
    // element's start to the end of the last token shifted (`lastEnd`),
    // and is empty when start >= end. With `elemEnds` (side-band labels or
    // nested nodes) each entry's end is kept too.
    starts: std.ArrayListUnmanaged(u32) = .empty,
    ends: std.ArrayListUnmanaged(u32) = .empty,
    nodes: NodeStore = .{},
    sides: std.ArrayListUnmanaged(SideEntry) = .empty,
    reduction: Reduction = .{},
    /// End of the last shifted token (the position of empty reductions).
    lastEnd: u32 = 0,

    triviaTokens: std.ArrayListUnmanaged(Token) = .empty,
    failure: ?Failure = null,
    scratch: std.ArrayListUnmanaged(u16) = .empty,

    const ListSpare = struct { len: usize, capacity: usize };

    /// The reduction in progress: its rule, where its elements' extents
    /// start on the span stack, its extent, and the first node it built.
    const Reduction = struct {
        rule: u16 = 0,
        base: u32 = 0,
        extent: Span = .empty,
        firstNode: NodeId = 0,
    };

    pub fn init(backingAllocator: std.mem.Allocator, source: []const u8) BaseParser {
        var p = BaseParser{
            .arena = std.heap.ArenaAllocator.init(backingAllocator),
            .lexer = Lexer.init(source),
            .source = source,
            .current = undefined,
        };
        p.current = p.lexer.next();
        return p;
    }

    pub fn deinit(self: *BaseParser) void {
        self.arena.deinit();
    }

    fn allocator(self: *BaseParser) std.mem.Allocator {
        return self.arena.allocator();
    }

    pub fn parseProgram(self: *BaseParser) !Sexp {
        return self.parse(.@"program");
    }

    pub fn parseForm(self: *BaseParser) !Sexp {
        return self.parse(.@"form");
    }


    /// Parse the whole input as `start`.
    pub fn parse(self: *BaseParser, start: Start) !Sexp {
        try self.begin(start);
        while (true) {
            const state = self.stateStack.getLast();
            const sym = self.lookahead();
            const action = self.actionFor(state, sym);
            if (action > 0) {
                try self.shift(@intCast(action));
            } else if (action < -1) {
                try self.reduce(@intCast(-action - 2));
            } else if (action == -1) {
                return self.valueStack.getLast();
            } else {
                self.recordFailure(state, sym);
                return error.ParseError;
            }
        }
    }

    /// Parse `start`, repairing errors from the grammar's `@repair` table:
    /// insert a zero-width token that lets the offending token be shifted,
    /// else delete the offending token. Records the first real error; gives
    /// up after `budget` repairs.
    pub fn parseTolerant(self: *BaseParser, start: Start, budget: u32) !Tolerant {
        if (!hasRepair) @compileError("parseTolerant needs a @repair section in the grammar");
        try self.begin(start);
        var repairs: u32 = 0;
        while (true) {
            const state = self.stateStack.getLast();
            const sym = self.lookahead();
            const action = self.actionFor(state, sym);
            if (action > 0) {
                try self.shift(@intCast(action));
            } else if (action < -1) {
                try self.reduce(@intCast(-action - 2));
            } else if (action == -1) {
                return .{ .sexp = self.valueStack.getLast(), .failure = self.failure, .repairs = repairs, .complete = true };
            } else {
                if (self.failure == null) self.recordFailure(state, sym);
                if (repairs == budget or self.pendingInsert != null) break;
                repairs += 1;
                if (try self.findInsertion(sym)) |token| {
                    self.pendingInsert = token;
                } else if (sym == endSymbol) {
                    break;
                } else {
                    try self.advance();
                }
            }
        }
        return .{ .sexp = .nil, .failure = self.failure, .repairs = repairs, .complete = false };
    }

    fn begin(self: *BaseParser, start: Start) !void {
        self.stateStack.clearRetainingCapacity();
        self.valueStack.clearRetainingCapacity();
        self.failure = null;
        self.pendingInsert = null;
        self.outOfMemory = false;
        try self.stateStack.append(self.allocator(), startState(start));
        if (nodeStore) self.lastEnd = 0;
        self.injectedToken = startMarker(start);
        if (nodeStore) {
            self.starts.clearRetainingCapacity();
            self.ends.clearRetainingCapacity();
            if (self.nodes.len == 0) _ = try self.nodes.add(self.allocator(), .{ .span = .empty, .rule = 0 });
        }
        if (hasTrivia) try self.skipTrivia();
    }

    inline fn lookahead(self: *BaseParser) u16 {
        if (self.injectedToken) |marker| return marker;
        if (self.pendingInsert) |token| return token;
        return tokenToSymbol(self, self.current);
    }

    /// The table action, with the `X "c"` override: when the table reduces
    /// and the next byte touches the previous token, shift instead.
    inline fn actionFor(self: *const BaseParser, state: u16, sym: u16) i16 {
        const action = getAction(state, sym);
        if (xExcludes.len > 0 and action < -1 and self.current.pre == 0 and self.current.pos < self.source.len) {
            if (getImmediateShift(state, self.source[self.current.pos])) |target| return target;
        }
        return action;
    }

    fn shift(self: *BaseParser, target: u16) !void {
        if (self.injectedToken != null) {
            try self.pushEntry(target, .nil, self.current.pos, self.lastEnd);
            self.injectedToken = null;
        } else if (self.pendingInsert != null) {
            const pos = self.current.pos;
            try self.pushEntry(target, .{ .src = .{ .pos = pos, .len = 0, .id = 0 } }, pos, pos);
            if (nodeStore) self.lastEnd = pos;
            self.pendingInsert = null;
        } else {
            const tok = self.current;
            const id = if (self.lastMatchedId != 0) self.lastMatchedId else takeLexerId(&self.lexer);
            self.lastMatchedId = 0;
            const end = tok.pos + tok.len;
            try self.pushEntry(target, .{ .src = .{ .pos = tok.pos, .len = tok.len, .id = id } }, tok.pos, end);
            if (nodeStore) self.lastEnd = end;
            try self.advance();
        }
    }

    /// Push a state, its value, and (with a node store) where the value
    /// starts and ends. The stacks grow together: the state stack is always
    /// one longer than the others, so one capacity check covers them all.
    inline fn pushEntry(self: *BaseParser, state: u16, value: Sexp, start: u32, end: u32) !void {
        const n = self.valueStack.items.len;
        if (n == self.valueStack.capacity) try self.growStacks();
        self.valueStack.items.len = n + 1;
        self.valueStack.items[n] = value;
        self.stateStack.items.len = n + 2;
        self.stateStack.items[n + 1] = state;
        if (nodeStore) {
            self.starts.items.len = n + 1;
            self.starts.items[n] = start;
        }
        if (elemEnds) {
            self.ends.items.len = n + 1;
            self.ends.items[n] = end;
        }
    }

    fn growStacks(self: *BaseParser) !void {
        const a = self.allocator();
        try self.valueStack.ensureUnusedCapacity(a, 1);
        const capacity = self.valueStack.capacity;
        try self.stateStack.ensureTotalCapacity(a, capacity + 1);
        if (nodeStore) try self.starts.ensureTotalCapacity(a, capacity);
        if (elemEnds) try self.ends.ensureTotalCapacity(a, capacity);
    }

    fn reduce(self: *BaseParser, ruleId: u16) !void {
        const len = ruleLen[ruleId];
        const base = self.valueStack.items.len - len;
        const top = self.stateStack.items.len - len;

        if (nodeStore) {
            self.reduction = .{
                .rule = ruleId,
                .base = @intCast(base),
                .extent = .{
                    .start = if (len > 0) self.starts.items[base] else self.current.pos,
                    .end = self.lastEnd,
                },
                .firstNode = self.nodes.len,
            };
        }

        // The action reads its elements in place on the value stack; the
        // result then replaces them (a reduction of nothing pushes it).
        const result = executeAction(self, ruleId, self.valueStack.items[base..]);
        if (self.outOfMemory) return error.OutOfMemory;
        const next = getAction(self.stateStack.items[top - 1], ruleLhs[ruleId]);
        std.debug.assert(next > 0); // every reduction has a goto

        if (nodeStore) try self.recordSides(ruleId, result);
        if (len > 0) {
            self.valueStack.items.len = base + 1;
            self.valueStack.items[base] = result;
            self.stateStack.items.len = top + 1;
            self.stateStack.items[top] = @intCast(next);
            if (nodeStore) {
                self.starts.items.len = base + 1;
                self.starts.items[base] = self.reduction.extent.start;
            }
            if (elemEnds) {
                self.ends.items.len = base + 1;
                self.ends.items[base] = self.lastEnd;
            }
        } else {
            try self.pushEntry(@intCast(next), result, self.reduction.extent.start, self.lastEnd);
        }
    }

    /// Fetch the next token, moving trivia to the trivia channel.
    fn advance(self: *BaseParser) !void {
        self.current = self.lexer.next();
        if (hasTrivia) try self.skipTrivia();
    }

    fn skipTrivia(self: *BaseParser) !void {
        while (isTrivia(self.current.cat)) {
            try self.triviaTokens.append(self.allocator(), self.current);
            _ = takeLexerId(&self.lexer);
            self.current = self.lexer.next();
        }
    }

    /// Tokens of the grammar's `@trivia` kinds, in source order.
    pub fn trivia(self: *const BaseParser) []const Token {
        return self.triviaTokens.items;
    }

    // -------------------------------------------------------------------------
    // Node store, spans, side-band roles
    // -------------------------------------------------------------------------

    /// The span of an extent: empty at its start when it consumed no
    /// tokens.
    fn spanOf(extent: Span) Span {
        return if (extent.start < extent.end) extent else .{ .start = extent.start, .end = extent.start };
    }

    /// The extent of elements lo..hi (0-based, inclusive) of the reduction.
    fn elemsExtent(self: *const BaseParser, lo: usize, hi: usize) Span {
        if (!elemEnds) @compileError("element extents need elemEnds");
        const base = self.reduction.base;
        return .{ .start = self.starts.items[base + lo], .end = self.ends.items[base + hi] };
    }

    /// A new node id for a list the current reduction builds.
    inline fn newNodeId(self: *BaseParser) NodeId {
        if (!nodeStore) return 0;
        return self.addNode(spanOf(self.reduction.extent));
    }

    inline fn addNode(self: *BaseParser, extent: Span) NodeId {
        return self.nodes.add(self.allocator(), .{ .span = extent, .rule = self.reduction.rule }) catch {
            self.outOfMemory = true;
            return 0;
        };
    }

    fn recordSides(self: *BaseParser, ruleId: u16, result: Sexp) !void {
        if (!elemEnds) return;
        const labels = ruleSideLabels(ruleId);
        if (labels.len == 0 or result != .list) return;
        const id = result.list.id;
        if (id == 0 or id < self.reduction.firstNode) return;
        for (labels) |label| {
            try self.sides.append(self.allocator(), .{
                .node = id,
                .role = label.role,
                .span = spanOf(self.elemsExtent(label.pass, label.pass)),
            });
        }
    }

    /// Source span of a value. Leaves span their token. A list with a node
    /// id spans its reduction: first to last consumed token, including
    /// tokens (keywords, punctuation) that are not in the tree. Any other
    /// list spans the hull of its children.
    pub fn span(self: *const BaseParser, s: Sexp) Span {
        switch (s) {
            .src => |x| return .{ .start = x.pos, .end = x.pos + x.len },
            .list => |l| {
                if (nodeStore and l.id != 0 and l.id < self.nodes.len) return self.nodes.at(l.id).span;
                var result: ?Span = null;
                for (l.items()) |child| {
                    const cs = self.span(child);
                    if (cs.isEmpty()) continue;
                    result = if (result) |r| .{ .start = r.start, .end = cs.end } else cs;
                }
                return result orelse .empty;
            },
            else => return .empty,
        }
    }

    /// The rule that built a list node (null without a node id).
    pub fn ruleOf(self: *const BaseParser, s: Sexp) ?u16 {
        if (!nodeStore or s != .list) return null;
        const id = s.list.id;
        if (id == 0 or id >= self.nodes.len) return null;
        return self.nodes.at(id).rule;
    }

    /// Number of node ids in use (ids run 1 .. nodeCount()).
    pub fn nodeCount(self: *const BaseParser) u32 {
        return self.nodes.len -| 1;
    }

    /// The side-band roles recorded for node `id`.
    fn sidesOf(self: *const BaseParser, id: NodeId) []const SideEntry {
        const all = self.sides.items;
        var lo: usize = 0;
        var hi: usize = all.len;
        while (lo < hi) {
            const mid = (lo + hi) / 2;
            if (all[mid].node < id) lo = mid + 1 else hi = mid;
        }
        var end = lo;
        while (end < all.len and all[end].node == id) end += 1;
        return all[lo..end];
    }

    /// The span a side-band role of `s` recorded (e.g. the `=` of a `set`).
    pub fn sideRole(self: *const BaseParser, s: Sexp, role: Role) ?Span {
        if (s != .list or s.list.id == 0) return null;
        for (self.sidesOf(s.list.id)) |e| if (e.role == role) return e.span;
        return null;
    }

    // -------------------------------------------------------------------------
    // Tree builders (called by the generated actions)
    // -------------------------------------------------------------------------

    /// Record an allocation failure; the reduction then fails the parse.
    fn oomNil(self: *BaseParser) Sexp {
        self.outOfMemory = true;
        return .nil;
    }

    /// A list node of the current reduction over freshly built `items`.
    inline fn node(self: *BaseParser, items: []const Sexp) Sexp {
        return .{ .list = List.withId(items, self.newNodeId()) };
    }

    /// A list node over exactly `items` (fixed positions).
    fn build(self: *BaseParser, items: []const Sexp) Sexp {
        const out = self.allocator().dupe(Sexp, items) catch return self.oomNil();
        return self.node(out);
    }

    /// A nested node of the current reduction: its span covers just the
    /// elements lo..hi (0-based, inclusive) it references.
    fn nested(self: *BaseParser, s: Sexp, lo: usize, hi: usize) Sexp {
        if (nodeStore and s == .list and s.list.id != 0) {
            self.nodes.at(s.list.id).span = spanOf(self.elemsExtent(lo, hi));
        }
        return s;
    }

    /// A nested node that references no elements: empty, at the start of
    /// the reduction.
    fn nestedEmpty(self: *BaseParser, s: Sexp) Sexp {
        if (nodeStore and s == .list and s.list.id != 0) {
            const at = self.reduction.extent.start;
            self.nodes.at(s.list.id).span = .{ .start = at, .end = at };
        }
        return s;
    }

    /// Length of `items` without trailing nils (all of it when positions
    /// are fixed by a schema).
    fn trimmedLen(items: []const Sexp) usize {
        var len = items.len;
        if (!keepTrailingNils) {
            while (len > 0 and items[len - 1] == .nil) len -= 1;
        }
        return len;
    }

    /// The default action: nothing, the one element, or an untagged list.
    fn list(self: *BaseParser, pass: []Sexp) Sexp {
        if (pass.len == 0) return .nil;
        if (pass.len == 1) return pass[0];
        const out = self.allocator().dupe(Sexp, pass) catch return self.oomNil();
        return self.node(out);
    }

    /// `()`: an empty list.
    fn emptyList(self: *BaseParser) Sexp {
        return self.node(&.{});
    }

    /// `[head, ...tail]`
    fn spreadList(self: *BaseParser, head: Sexp, tail: Sexp) Sexp {
        const rest = tail.items();
        const out = self.allocator().alloc(Sexp, rest.len + 1) catch return self.oomNil();
        out[0] = head;
        @memcpy(out[1..], rest);
        return self.node(out);
    }

    /// Start a list holding the items of `base` (a list, else nothing)
    /// for an action that appends to it. A list from `keepList` is reused
    /// with its spare capacity, so a left-recursive list grows in amortized
    /// O(1) per element; it keeps its node id.
    fn extendList(self: *BaseParser, base: Sexp) !std.ArrayListUnmanaged(Sexp) {
        self.extending = 0;
        if (base != .list) return .empty;
        self.extending = base.list.id;
        const items = base.list.items();
        if (items.len > 0) if (self.listSpare.get(@intFromPtr(items.ptr))) |spare| {
            if (spare.len == items.len) {
                _ = self.listSpare.remove(@intFromPtr(items.ptr));
                return .{ .items = @constCast(items), .capacity = spare.capacity };
            }
        };
        var out: std.ArrayListUnmanaged(Sexp) = .empty;
        try out.appendSlice(self.allocator(), items);
        return out;
    }

    /// Finish a list from `extendList`, recording its spare capacity.
    fn keepList(self: *BaseParser, out: *std.ArrayListUnmanaged(Sexp)) Sexp {
        out.shrinkRetainingCapacity(trimmedLen(out.items));
        if (out.items.len > 0 and out.capacity > out.items.len) {
            self.listSpare.put(self.allocator(), @intFromPtr(out.items.ptr), .{
                .len = out.items.len,
                .capacity = out.capacity,
            }) catch return self.oomNil();
        }
        var id: NodeId = 0;
        if (nodeStore) {
            if (self.extending != 0) {
                id = self.extending;
                self.nodes.at(id).* = .{ .span = spanOf(self.reduction.extent), .rule = self.reduction.rule };
            } else id = self.newNodeId();
        }
        self.extending = 0;
        return .{ .list = List.withId(out.items, id) };
    }

    /// Finish a list built from scratch.
    fn finishList(self: *BaseParser, out: *std.ArrayListUnmanaged(Sexp)) Sexp {
        out.shrinkRetainingCapacity(trimmedLen(out.items));
        const items = out.toOwnedSlice(self.allocator()) catch return self.oomNil();
        return self.node(items);
    }

    /// `(tag items...)`
    inline fn sexp(self: *BaseParser, comptime tag: Tag, items: []const Sexp) Sexp {
        const len = trimmedLen(items);
        const out = self.allocator().alloc(Sexp, len + 1) catch return self.oomNil();
        out[0] = .{ .tag = tag };
        @memcpy(out[1..], items[0..len]);
        return self.node(out);
    }

    /// `(tag ...spread)`
    inline fn sexpSpread(self: *BaseParser, comptime tag: Tag, spread: Sexp) Sexp {
        const items = spread.items();
        const len = trimmedLen(items);
        const out = self.allocator().alloc(Sexp, len + 1) catch return self.oomNil();
        out[0] = .{ .tag = tag };
        @memcpy(out[1..], items[0..len]);
        return self.node(out);
    }

    /// `(tag pos ...spread)`; just `(tag)` when both are empty (and
    /// positions are not fixed by a schema).
    inline fn sexpPosSpread(self: *BaseParser, comptime tag: Tag, pos: Sexp, spread: Sexp) Sexp {
        const items = spread.items();
        const len = trimmedLen(items);
        const bare = !keepTrailingNils and pos == .nil and len == 0;
        const out = self.allocator().alloc(Sexp, if (bare) 1 else len + 2) catch return self.oomNil();
        out[0] = .{ .tag = tag };
        if (!bare) {
            out[1] = pos;
            @memcpy(out[2..], items[0..len]);
        }
        return self.node(out);
    }

    // -------------------------------------------------------------------------
    // Diagnostics
    // -------------------------------------------------------------------------

    fn recordFailure(self: *BaseParser, state: u16, sym: u16) void {
        const tok = self.current;
        self.failure = .{
            .span = .{ .start = tok.pos, .end = tok.pos + tok.len },
            .symbol = sym,
            .cat = tok.cat,
            .state = state,
        };
    }

    /// The error of the last failed parse (the first one, for
    /// `parseTolerant`).
    pub fn lastError(self: *const BaseParser) ?Failure {
        return self.failure;
    }

    /// 1-based line and column of a byte offset.
    pub fn lineCol(self: *const BaseParser, pos: u32) struct { line: u32, col: u32 } {
        const end: usize = @min(pos, self.source.len);
        var line: u32 = 1;
        var lineStart: usize = 0;
        for (self.source[0..end], 0..) |c, i| {
            if (c == '\n') {
                line += 1;
                lineStart = i + 1;
            }
        }
        return .{ .line = line, .col = @intCast(end - lineStart + 1) };
    }

    /// `line:col: expected A, B or C, got D` for the last error.
    pub fn writeError(self: *const BaseParser, w: *std.Io.Writer) std.Io.Writer.Error!void {
        const f = self.failure orelse return;
        const at = self.lineCol(f.span.start);
        try w.print("{d}:{d}: expected ", .{ at.line, at.col });
        const want = expectedIn(f.state);
        for (want, 0..) |sym, i| {
            if (i > 0) try w.writeAll(if (i + 1 == want.len) " or " else ", ");
            try w.writeAll(symbolName(sym));
        }
        if (want.len == 0) try w.writeAll("nothing");
        try w.writeAll(", got ");
        const got = symbolName(f.symbol);
        try w.writeAll(if (f.symbol == errorSymbol or got.len == 0) @tagName(f.cat) else got);
    }

    pub fn printError(self: *const BaseParser) void {
        var buf: [512]u8 = undefined;
        var w: std.Io.Writer = .fixed(&buf);
        self.writeError(&w) catch {};
        std.debug.print("Parse error at {s}\n", .{w.buffered()});
    }

    /// What `state` accepts, reader-named: the `@errors` rules it waits
    /// for, then the tokens none of them begins with.
    pub fn expected(state: u16) []const u16 {
        return expectedIn(state);
    }

    // -------------------------------------------------------------------------
    // Tolerant repair
    // -------------------------------------------------------------------------

    /// The first candidate of the current state after which `next` can be
    /// shifted (or accepted).
    fn findInsertion(self: *BaseParser, next: u16) !?u16 {
        for (repairCandidates(self.stateStack.getLast())) |candidate| {
            if (try self.accepts(&.{ candidate, next })) return candidate;
        }
        return null;
    }

    /// Whether `symbols` can be consumed from the current state, simulating
    /// reductions on a scratch copy of the state stack.
    fn accepts(self: *BaseParser, symbols: []const u16) !bool {
        const stack = &self.scratch;
        stack.clearRetainingCapacity();
        try stack.appendSlice(self.allocator(), self.stateStack.items);
        for (symbols) |sym| {
            while (true) {
                const action = getAction(stack.getLast(), sym);
                if (action == 0) return false;
                if (action == -1) return true;
                if (action > 0) {
                    try stack.append(self.allocator(), @intCast(action));
                    break;
                }
                const rule: u16 = @intCast(-action - 2);
                stack.shrinkRetainingCapacity(stack.items.len - ruleLen[rule]);
                const next = getAction(stack.getLast(), ruleLhs[rule]);
                if (next <= 0) return false;
                try stack.append(self.allocator(), @intCast(next));
            }
        }
        return true;
    }

    // -------------------------------------------------------------------------
    // Facts export
    // -------------------------------------------------------------------------

    /// Write the tree as flat facts, one per line, in pre-order:
    ///   (node ID KIND START END)        every list with a node id
    ///   (role ID ROLE CHILD...)         each non-nil child (a rest role
    ///                                   lists all its children)
    ///   (side ID ROLE START LEN)        each side-band role
    /// ROLE is the schema role name, else the child's index in the list.
    /// KIND is the head tag, or `group` for an untagged list. A CHILD is a
    /// node id, `leaf POS LEN`, `tag NAME`, `str "TEXT"`, or `(CHILD...)`
    /// for a list without a node id.
    pub fn writeFacts(self: *const BaseParser, w: *std.Io.Writer, root: Sexp) std.Io.Writer.Error!void {
        if (!nodeStore) @compileError("writeFacts needs the node store (@schema or --spans)");
        try self.factsOf(w, root);
    }

    fn factsOf(self: *const BaseParser, w: *std.Io.Writer, s: Sexp) std.Io.Writer.Error!void {
        if (s != .list) return;
        const l = s.list;
        const items = l.items();
        if (l.id != 0) {
            const k = s.kind();
            const sp = self.span(s);
            try w.print("(node {d} ", .{l.id});
            if (k) |t| try writeName(w, @tagName(t)) else try w.writeAll("group");
            try w.print(" {d} {d})\n", .{ sp.start, sp.end });
            var i: usize = if (k != null) 1 else 0;
            while (i < items.len) : (i += 1) {
                if (k) |t| if (restRoleOf(t)) |rest| if (i >= rest.slot) {
                    try w.print("(role {d} ", .{l.id});
                    try writeName(w, @tagName(rest.role));
                    for (items[i..]) |child| {
                        try w.writeByte(' ');
                        try self.factChild(w, child);
                    }
                    try w.writeAll(")\n");
                    break;
                };
                if (items[i] == .nil) continue;
                try w.print("(role {d} ", .{l.id});
                if (if (k) |t| roleAt(t, i) else null) |role| try writeName(w, @tagName(role)) else try w.print("{d}", .{i});
                try w.writeByte(' ');
                try self.factChild(w, items[i]);
                try w.writeAll(")\n");
            }
            for (self.sidesOf(l.id)) |e| {
                try w.print("(side {d} ", .{l.id});
                try writeName(w, @tagName(e.role));
                try w.print(" {d} {d})\n", .{ e.span.start, e.span.len() });
            }
        }
        for (items) |child| try self.factsOf(w, child);
    }

    fn factChild(self: *const BaseParser, w: *std.Io.Writer, s: Sexp) std.Io.Writer.Error!void {
        switch (s) {
            .nil => try w.writeAll("_"),
            .tag => |t| {
                try w.writeAll("tag ");
                try writeName(w, @tagName(t));
            },
            .src => |x| try w.print("leaf {d} {d}", .{ x.pos, x.len }),
            .str => |x| {
                try w.writeAll("str ");
                try writeQuoted(w, x);
            },
            .list => |l| if (l.id != 0) try w.print("{d}", .{l.id}) else {
                try w.writeByte('(');
                for (l.items(), 0..) |child, i| {
                    if (i > 0) try w.writeByte(' ');
                    try self.factChild(w, child);
                }
                try w.writeByte(')');
            },
        }
    }

    /// A name as a bare symbol, or quoted when it has s-expression syntax.
    fn writeName(w: *std.Io.Writer, name: []const u8) std.Io.Writer.Error!void {
        const plain = name.len > 0 and for (name) |c| {
            if (c <= ' ' or c == '(' or c == ')' or c == '"' or c == '\\' or c == 0x7f) break false;
        } else true;
        if (plain) try w.writeAll(name) else try writeQuoted(w, name);
    }

    fn writeQuoted(w: *std.Io.Writer, text: []const u8) std.Io.Writer.Error!void {
        try w.writeByte('"');
        for (text) |c| switch (c) {
            '"', '\\' => {
                try w.writeByte('\\');
                try w.writeByte(c);
            },
            '\n' => try w.writeAll("\\n"),
            '\t' => try w.writeAll("\\t"),
            else => if (c < ' ' or c == 0x7f) try w.print("\\x{x:0>2}", .{c}) else try w.writeByte(c),
        };
        try w.writeByte('"');
    }
};


// =============================================================================
// Grammar
// =============================================================================

/// Node spans and rule ids are recorded (`@schema` or `--spans`).
pub const nodeStore = false;
/// Element extents are kept for side-band labels and nested nodes.
const elemEnds = false;
/// Lists keep trailing nils: positions are fixed by the schema.
const keepTrailingNils = false;
const hasTrivia = false;
const hasRepair = false;
const numSymbols = 44;
const endSymbol: u16 = 1;
const errorSymbol: u16 = 2;

fn tokenToSymbol(_: *BaseParser, token: Token) u16 {
    return switch (token.cat) {
        .@"eof" => 1,
        .@"integer" => 19,
        .@"real" => 20,
        .@"string" => 21,
        .@"char" => 22,
        .@"keyword" => 23,
        .@"ident" => 24,
        .@"hash_lbrace" => 31,
        .@"unquote_splicing_tok" => 35,
        .@"hash_lparen" => 37,
        .@"hash_discard" => 38,
        .@"lparen" => 25,
        .@"rparen" => 26,
        .@"lbracket" => 27,
        .@"rbracket" => 28,
        .@"lbrace" => 29,
        .@"rbrace" => 30,
        .@"quote_tok" => 32,
        .@"syntax_quote_tok" => 33,
        .@"unquote_tok" => 34,
        .@"deref_tok" => 36,
        .@"caret" => 39,
        else => 2, // error
    };
}

fn executeAction(self: *BaseParser, ruleId: u16, pass: []Sexp) Sexp {
    @setEvalBranchQuota(1_000_000);
    return switch (ruleId) {
        0 => self.sexpSpread(.@"program", pass[0]),
        1 => blk: { var out = self.extendList(pass[0]) catch break :blk self.oomNil(); out.append(self.allocator(), pass[1]) catch break :blk self.oomNil(); break :blk self.keepList(&out); },
        2 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .empty; out.append(self.allocator(), pass[0]) catch break :blk self.oomNil(); break :blk self.finishList(&out); },
        3 => self.emptyList(),
        4 => pass[0],
        5 => pass[0],
        6 => pass[0],
        7 => pass[0],
        8 => pass[0],
        9 => pass[0],
        10 => pass[0],
        11 => pass[0],
        12 => pass[0],
        13 => pass[0],
        14 => pass[0],
        15 => pass[0],
        16 => pass[0],
        17 => self.sexp(.@"int", &.{pass[0]}),
        18 => self.sexp(.@"real", &.{pass[0]}),
        19 => self.sexp(.@"string", &.{pass[0]}),
        20 => self.sexp(.@"char", &.{pass[0]}),
        21 => self.sexp(.@"keyword", &.{pass[0]}),
        22 => self.sexp(.@"symbol", &.{pass[0]}),
        23 => self.sexpSpread(.@"list", pass[1]),
        24 => self.sexpSpread(.@"vector", pass[1]),
        25 => self.sexpSpread(.@"map", pass[1]),
        26 => self.sexpSpread(.@"set", pass[1]),
        27 => self.sexp(.@"quote", &.{pass[1]}),
        28 => self.sexp(.@"syntax-quote", &.{pass[1]}),
        29 => self.sexp(.@"unquote", &.{pass[1]}),
        30 => self.sexp(.@"unquote-splicing", &.{pass[1]}),
        31 => self.sexp(.@"deref", &.{pass[1]}),
        32 => self.sexpSpread(.@"anon-fn", pass[1]),
        33 => self.sexp(.@"discard", &.{pass[1]}),
        34 => self.sexp(.@"with-meta-raw", &.{pass[2], pass[1]}),
        else => unreachable,
    };
}

const ruleLhs = [_]u16{ 3, 5, 5, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 6, 6, 6, 6, 6, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 41, 43 };
const ruleLen = [_]u8{ 1, 2, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 2, 2, 2, 2, 2, 3, 2, 3, 3, 3 };

// Parse table: 60 states x 44 symbols. 0 = error, > 0 = shift or
// goto, -1 = accept, <= -2 = reduce rule (-a - 2).
const numStates = 60;

const sparse = [numStates][]const i16{
    &.{40,2},
    &.{42,3},
    &.{1,-5,3,16,4,35,5,26,6,23,7,13,8,17,9,5,10,6,11,24,12,14,13,7,14,20,15,18,16,8,17,10,18,34,19,29,20,15,21,11,22,21,23,37,24,32,25,25,27,27,29,31,31,36,32,19,33,33,34,22,35,4,36,9,37,30,38,28,39,12},
    &.{4,38,6,23,7,13,8,17,9,5,10,6,11,24,12,14,13,7,14,20,15,18,16,8,17,10,18,34,19,29,20,15,21,11,22,21,23,37,24,32,25,25,27,27,29,31,31,36,32,19,33,33,34,22,35,4,36,9,37,30,38,28,39,12},
    &.{4,39,6,23,7,13,8,17,9,5,10,6,11,24,12,14,13,7,14,20,15,18,16,8,17,10,18,34,19,29,20,15,21,11,22,21,23,37,24,32,25,25,27,27,29,31,31,36,32,19,33,33,34,22,35,4,36,9,37,30,38,28,39,12},
    &.{1,-9,19,-9,20,-9,21,-9,22,-9,23,-9,24,-9,25,-9,26,-9,27,-9,28,-9,29,-9,30,-9,31,-9,32,-9,33,-9,34,-9,35,-9,36,-9,37,-9,38,-9,39,-9},
    &.{1,-10,19,-10,20,-10,21,-10,22,-10,23,-10,24,-10,25,-10,26,-10,27,-10,28,-10,29,-10,30,-10,31,-10,32,-10,33,-10,34,-10,35,-10,36,-10,37,-10,38,-10,39,-10},
    &.{1,-13,19,-13,20,-13,21,-13,22,-13,23,-13,24,-13,25,-13,26,-13,27,-13,28,-13,29,-13,30,-13,31,-13,32,-13,33,-13,34,-13,35,-13,36,-13,37,-13,38,-13,39,-13},
    &.{1,-16,19,-16,20,-16,21,-16,22,-16,23,-16,24,-16,25,-16,26,-16,27,-16,28,-16,29,-16,30,-16,31,-16,32,-16,33,-16,34,-16,35,-16,36,-16,37,-16,38,-16,39,-16},
    &.{4,40,6,23,7,13,8,17,9,5,10,6,11,24,12,14,13,7,14,20,15,18,16,8,17,10,18,34,19,29,20,15,21,11,22,21,23,37,24,32,25,25,27,27,29,31,31,36,32,19,33,33,34,22,35,4,36,9,37,30,38,28,39,12},
    &.{1,-17,19,-17,20,-17,21,-17,22,-17,23,-17,24,-17,25,-17,26,-17,27,-17,28,-17,29,-17,30,-17,31,-17,32,-17,33,-17,34,-17,35,-17,36,-17,37,-17,38,-17,39,-17},
    &.{1,-21,19,-21,20,-21,21,-21,22,-21,23,-21,24,-21,25,-21,26,-21,27,-21,28,-21,29,-21,30,-21,31,-21,32,-21,33,-21,34,-21,35,-21,36,-21,37,-21,38,-21,39,-21},
    &.{4,41,6,23,7,13,8,17,9,5,10,6,11,24,12,14,13,7,14,20,15,18,16,8,17,10,18,34,19,29,20,15,21,11,22,21,23,37,24,32,25,25,27,27,29,31,31,36,32,19,33,33,34,22,35,4,36,9,37,30,38,28,39,12},
    &.{1,-7,19,-7,20,-7,21,-7,22,-7,23,-7,24,-7,25,-7,26,-7,27,-7,28,-7,29,-7,30,-7,31,-7,32,-7,33,-7,34,-7,35,-7,36,-7,37,-7,38,-7,39,-7},
    &.{1,-12,19,-12,20,-12,21,-12,22,-12,23,-12,24,-12,25,-12,26,-12,27,-12,28,-12,29,-12,30,-12,31,-12,32,-12,33,-12,34,-12,35,-12,36,-12,37,-12,38,-12,39,-12},
    &.{1,-20,19,-20,20,-20,21,-20,22,-20,23,-20,24,-20,25,-20,26,-20,27,-20,28,-20,29,-20,30,-20,31,-20,32,-20,33,-20,34,-20,35,-20,36,-20,37,-20,38,-20,39,-20},
    &.{1,-1},
    &.{1,-8,19,-8,20,-8,21,-8,22,-8,23,-8,24,-8,25,-8,26,-8,27,-8,28,-8,29,-8,30,-8,31,-8,32,-8,33,-8,34,-8,35,-8,36,-8,37,-8,38,-8,39,-8},
    &.{1,-15,19,-15,20,-15,21,-15,22,-15,23,-15,24,-15,25,-15,26,-15,27,-15,28,-15,29,-15,30,-15,31,-15,32,-15,33,-15,34,-15,35,-15,36,-15,37,-15,38,-15,39,-15},
    &.{4,43,6,23,7,13,8,17,9,5,10,6,11,24,12,14,13,7,14,20,15,18,16,8,17,10,18,34,19,29,20,15,21,11,22,21,23,37,24,32,25,25,27,27,29,31,31,36,32,19,33,33,34,22,35,4,36,9,37,30,38,28,39,12},
    &.{1,-14,19,-14,20,-14,21,-14,22,-14,23,-14,24,-14,25,-14,26,-14,27,-14,28,-14,29,-14,30,-14,31,-14,32,-14,33,-14,34,-14,35,-14,36,-14,37,-14,38,-14,39,-14},
    &.{1,-22,19,-22,20,-22,21,-22,22,-22,23,-22,24,-22,25,-22,26,-22,27,-22,28,-22,29,-22,30,-22,31,-22,32,-22,33,-22,34,-22,35,-22,36,-22,37,-22,38,-22,39,-22},
    &.{4,44,6,23,7,13,8,17,9,5,10,6,11,24,12,14,13,7,14,20,15,18,16,8,17,10,18,34,19,29,20,15,21,11,22,21,23,37,24,32,25,25,27,27,29,31,31,36,32,19,33,33,34,22,35,4,36,9,37,30,38,28,39,12},
    &.{1,-6,19,-6,20,-6,21,-6,22,-6,23,-6,24,-6,25,-6,26,-6,27,-6,28,-6,29,-6,30,-6,31,-6,32,-6,33,-6,34,-6,35,-6,36,-6,37,-6,38,-6,39,-6},
    &.{1,-11,19,-11,20,-11,21,-11,22,-11,23,-11,24,-11,25,-11,26,-11,27,-11,28,-11,29,-11,30,-11,31,-11,32,-11,33,-11,34,-11,35,-11,36,-11,37,-11,38,-11,39,-11},
    &.{4,35,5,45,6,23,7,13,8,17,9,5,10,6,11,24,12,14,13,7,14,20,15,18,16,8,17,10,18,34,19,29,20,15,21,11,22,21,23,37,24,32,25,25,26,-5,27,27,29,31,31,36,32,19,33,33,34,22,35,4,36,9,37,30,38,28,39,12},
    &.{1,-2,4,46,6,23,7,13,8,17,9,5,10,6,11,24,12,14,13,7,14,20,15,18,16,8,17,10,18,34,19,29,20,15,21,11,22,21,23,37,24,32,25,25,27,27,29,31,31,36,32,19,33,33,34,22,35,4,36,9,37,30,38,28,39,12},
    &.{4,35,5,47,6,23,7,13,8,17,9,5,10,6,11,24,12,14,13,7,14,20,15,18,16,8,17,10,18,34,19,29,20,15,21,11,22,21,23,37,24,32,25,25,27,27,28,-5,29,31,31,36,32,19,33,33,34,22,35,4,36,9,37,30,38,28,39,12},
    &.{4,48,6,23,7,13,8,17,9,5,10,6,11,24,12,14,13,7,14,20,15,18,16,8,17,10,18,34,19,29,20,15,21,11,22,21,23,37,24,32,25,25,27,27,29,31,31,36,32,19,33,33,34,22,35,4,36,9,37,30,38,28,39,12},
    &.{1,-19,19,-19,20,-19,21,-19,22,-19,23,-19,24,-19,25,-19,26,-19,27,-19,28,-19,29,-19,30,-19,31,-19,32,-19,33,-19,34,-19,35,-19,36,-19,37,-19,38,-19,39,-19},
    &.{4,35,5,49,6,23,7,13,8,17,9,5,10,6,11,24,12,14,13,7,14,20,15,18,16,8,17,10,18,34,19,29,20,15,21,11,22,21,23,37,24,32,25,25,26,-5,27,27,29,31,31,36,32,19,33,33,34,22,35,4,36,9,37,30,38,28,39,12},
    &.{4,35,5,50,6,23,7,13,8,17,9,5,10,6,11,24,12,14,13,7,14,20,15,18,16,8,17,10,18,34,19,29,20,15,21,11,22,21,23,37,24,32,25,25,27,27,29,31,30,-5,31,36,32,19,33,33,34,22,35,4,36,9,37,30,38,28,39,12},
    &.{1,-24,19,-24,20,-24,21,-24,22,-24,23,-24,24,-24,25,-24,26,-24,27,-24,28,-24,29,-24,30,-24,31,-24,32,-24,33,-24,34,-24,35,-24,36,-24,37,-24,38,-24,39,-24},
    &.{4,51,6,23,7,13,8,17,9,5,10,6,11,24,12,14,13,7,14,20,15,18,16,8,17,10,18,34,19,29,20,15,21,11,22,21,23,37,24,32,25,25,27,27,29,31,31,36,32,19,33,33,34,22,35,4,36,9,37,30,38,28,39,12},
    &.{1,-18,19,-18,20,-18,21,-18,22,-18,23,-18,24,-18,25,-18,26,-18,27,-18,28,-18,29,-18,30,-18,31,-18,32,-18,33,-18,34,-18,35,-18,36,-18,37,-18,38,-18,39,-18},
    &.{1,-4,19,-4,20,-4,21,-4,22,-4,23,-4,24,-4,25,-4,26,-4,27,-4,28,-4,29,-4,30,-4,31,-4,32,-4,33,-4,34,-4,35,-4,36,-4,37,-4,38,-4,39,-4},
    &.{4,35,5,52,6,23,7,13,8,17,9,5,10,6,11,24,12,14,13,7,14,20,15,18,16,8,17,10,18,34,19,29,20,15,21,11,22,21,23,37,24,32,25,25,27,27,29,31,30,-5,31,36,32,19,33,33,34,22,35,4,36,9,37,30,38,28,39,12},
    &.{1,-23,19,-23,20,-23,21,-23,22,-23,23,-23,24,-23,25,-23,26,-23,27,-23,28,-23,29,-23,30,-23,31,-23,32,-23,33,-23,34,-23,35,-23,36,-23,37,-23,38,-23,39,-23},
    &.{1,-1},
    &.{1,-32,19,-32,20,-32,21,-32,22,-32,23,-32,24,-32,25,-32,26,-32,27,-32,28,-32,29,-32,30,-32,31,-32,32,-32,33,-32,34,-32,35,-32,36,-32,37,-32,38,-32,39,-32},
    &.{1,-33,19,-33,20,-33,21,-33,22,-33,23,-33,24,-33,25,-33,26,-33,27,-33,28,-33,29,-33,30,-33,31,-33,32,-33,33,-33,34,-33,35,-33,36,-33,37,-33,38,-33,39,-33},
    &.{4,54,6,23,7,13,8,17,9,5,10,6,11,24,12,14,13,7,14,20,15,18,16,8,17,10,18,34,19,29,20,15,21,11,22,21,23,37,24,32,25,25,27,27,29,31,31,36,32,19,33,33,34,22,35,4,36,9,37,30,38,28,39,12},
    &.{1,-1},
    &.{1,-29,19,-29,20,-29,21,-29,22,-29,23,-29,24,-29,25,-29,26,-29,27,-29,28,-29,29,-29,30,-29,31,-29,32,-29,33,-29,34,-29,35,-29,36,-29,37,-29,38,-29,39,-29},
    &.{1,-31,19,-31,20,-31,21,-31,22,-31,23,-31,24,-31,25,-31,26,-31,27,-31,28,-31,29,-31,30,-31,31,-31,32,-31,33,-31,34,-31,35,-31,36,-31,37,-31,38,-31,39,-31},
    &.{4,46,6,23,7,13,8,17,9,5,10,6,11,24,12,14,13,7,14,20,15,18,16,8,17,10,18,34,19,29,20,15,21,11,22,21,23,37,24,32,25,25,26,55,27,27,29,31,31,36,32,19,33,33,34,22,35,4,36,9,37,30,38,28,39,12},
    &.{1,-3,19,-3,20,-3,21,-3,22,-3,23,-3,24,-3,25,-3,26,-3,27,-3,28,-3,29,-3,30,-3,31,-3,32,-3,33,-3,34,-3,35,-3,36,-3,37,-3,38,-3,39,-3},
    &.{4,46,6,23,7,13,8,17,9,5,10,6,11,24,12,14,13,7,14,20,15,18,16,8,17,10,18,34,19,29,20,15,21,11,22,21,23,37,24,32,25,25,27,27,28,56,29,31,31,36,32,19,33,33,34,22,35,4,36,9,37,30,38,28,39,12},
    &.{1,-35,19,-35,20,-35,21,-35,22,-35,23,-35,24,-35,25,-35,26,-35,27,-35,28,-35,29,-35,30,-35,31,-35,32,-35,33,-35,34,-35,35,-35,36,-35,37,-35,38,-35,39,-35},
    &.{4,46,6,23,7,13,8,17,9,5,10,6,11,24,12,14,13,7,14,20,15,18,16,8,17,10,18,34,19,29,20,15,21,11,22,21,23,37,24,32,25,25,26,57,27,27,29,31,31,36,32,19,33,33,34,22,35,4,36,9,37,30,38,28,39,12},
    &.{4,46,6,23,7,13,8,17,9,5,10,6,11,24,12,14,13,7,14,20,15,18,16,8,17,10,18,34,19,29,20,15,21,11,22,21,23,37,24,32,25,25,27,27,29,31,30,58,31,36,32,19,33,33,34,22,35,4,36,9,37,30,38,28,39,12},
    &.{1,-30,19,-30,20,-30,21,-30,22,-30,23,-30,24,-30,25,-30,26,-30,27,-30,28,-30,29,-30,30,-30,31,-30,32,-30,33,-30,34,-30,35,-30,36,-30,37,-30,38,-30,39,-30},
    &.{4,46,6,23,7,13,8,17,9,5,10,6,11,24,12,14,13,7,14,20,15,18,16,8,17,10,18,34,19,29,20,15,21,11,22,21,23,37,24,32,25,25,27,27,29,31,30,59,31,36,32,19,33,33,34,22,35,4,36,9,37,30,38,28,39,12},
    &.{1,-1},
    &.{1,-36,19,-36,20,-36,21,-36,22,-36,23,-36,24,-36,25,-36,26,-36,27,-36,28,-36,29,-36,30,-36,31,-36,32,-36,33,-36,34,-36,35,-36,36,-36,37,-36,38,-36,39,-36},
    &.{1,-25,19,-25,20,-25,21,-25,22,-25,23,-25,24,-25,25,-25,26,-25,27,-25,28,-25,29,-25,30,-25,31,-25,32,-25,33,-25,34,-25,35,-25,36,-25,37,-25,38,-25,39,-25},
    &.{1,-26,19,-26,20,-26,21,-26,22,-26,23,-26,24,-26,25,-26,26,-26,27,-26,28,-26,29,-26,30,-26,31,-26,32,-26,33,-26,34,-26,35,-26,36,-26,37,-26,38,-26,39,-26},
    &.{1,-34,19,-34,20,-34,21,-34,22,-34,23,-34,24,-34,25,-34,26,-34,27,-34,28,-34,29,-34,30,-34,31,-34,32,-34,33,-34,34,-34,35,-34,36,-34,37,-34,38,-34,39,-34},
    &.{1,-27,19,-27,20,-27,21,-27,22,-27,23,-27,24,-27,25,-27,26,-27,27,-27,28,-27,29,-27,30,-27,31,-27,32,-27,33,-27,34,-27,35,-27,36,-27,37,-27,38,-27,39,-27},
    &.{1,-28,19,-28,20,-28,21,-28,22,-28,23,-28,24,-28,25,-28,26,-28,27,-28,28,-28,29,-28,30,-28,31,-28,32,-28,33,-28,34,-28,35,-28,36,-28,37,-28,38,-28,39,-28},
};

const parseTable = blk: {
    @setEvalBranchQuota(100000);
    var t: [numStates][numSymbols]i16 = .{.{0} ** numSymbols} ** numStates;
    for (sparse, 0..) |row, state| {
        var i: usize = 0;
        while (i < row.len) : (i += 2) {
            t[state][@intCast(row[i])] = row[i + 1];
        }
    }
    break :blk t;
};

fn getAction(state: u16, sym: u16) i16 {
    return parseTable[state][sym];
}

// X "c" excludes: shift instead of reduce when pre == 0 and the next byte matches
const xExcludes = [_]struct { char: u8, shift: u16 }{
};

fn getImmediateShift(_: u16, _: u8) ?i16 {
    return null;
}

fn startState(start: Start) u16 {
    return switch (start) {
        .@"program" => 0,
        .@"form" => 1,
    };
}

fn startMarker(start: Start) u16 {
    return switch (start) {
        .@"program" => 40,
        .@"form" => 42,
    };
}

/// Expected symbols per state: state s expects list i = expectedOf[s],
/// expectedSymbols[expectedOffsets[i]..expectedOffsets[i + 1]].
const expectedSymbols = [_]u16{
    1, 19, 20, 21, 22, 23, 24, 25, 27, 29, 31, 32, 33, 34, 35, 36, 37, 38, 39, 19, 20, 21, 22, 23,
    24, 25, 27, 29, 31, 32, 33, 34, 35, 36, 37, 38, 39, 1, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
    29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 1, 19, 20, 21, 22, 23, 24, 25, 26, 27, 29, 31, 32,
    33, 34, 35, 36, 37, 38, 39, 19, 20, 21, 22, 23, 24, 25, 27, 28, 29, 31, 32, 33, 34, 35, 36, 37,
    38, 39, 19, 20, 21, 22, 23, 24, 25, 27, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
};
const expectedOffsets = [_]u32{
    0, 0, 19, 37, 59, 60, 79, 98, 117,
};
const expectedOf = [_]u16{
    0, 0, 1, 2, 2, 3, 3, 3, 3, 2, 3, 3, 2, 3, 3, 3, 4, 3, 3, 2, 3, 3, 2, 3,
    3, 5, 1, 6, 2, 3, 5, 7, 3, 2, 3, 3, 7, 3, 4, 3, 3, 2, 4, 3, 3, 5, 3, 6,
    3, 5, 7, 3, 7, 4, 3, 3, 3, 3, 3, 3,
};

fn expectedIn(state: u16) []const u16 {
    const i = expectedOf[state];
    return expectedSymbols[expectedOffsets[i]..expectedOffsets[i + 1]];
}

fn symbolName(sym: u16) []const u8 {
    return switch (sym) {
        1 => "end of input",
        19 => "integer",
        20 => "real",
        21 => "string",
        22 => "char",
        23 => "keyword",
        24 => "ident",
        25 => "\"(\"",
        26 => "\")\"",
        27 => "\"[\"",
        28 => "\"]\"",
        29 => "\"{\"",
        30 => "\"}\"",
        31 => "\"#{\"",
        32 => "\"'\"",
        33 => "\"`\"",
        34 => "\"~\"",
        35 => "\"~@\"",
        36 => "\"@\"",
        37 => "\"#(\"",
        38 => "\"#_\"",
        39 => "\"^\"",
        else => "",
    };
}

fn isTrivia(_: TokenCat) bool {
    return false;
}

fn repairCandidates(_: u16) []const u16 {
    return &.{};
}

fn ruleSideLabels(rule: u16) []const SideLabel {
    _ = rule;
    return &.{};
}

fn slotOf(_: Tag, _: Role) ?usize {
    return null;
}

fn restSlotOf(_: Tag, _: Role) ?usize {
    return null;
}

fn roleAt(_: Tag, _: usize) ?Role {
    return null;
}

fn restRoleOf(_: Tag) ?struct { role: Role, slot: usize } {
    return null;
}

// =============================================================================
// API
// =============================================================================

pub const Parser = if (@hasDecl(nexis, "Parser")) nexis.Parser else BaseParser;

/// Parse a whole program with a new `Parser`. The caller owns
/// `result.parser` and must `deinit()` it when done with the tree.
pub fn parseProgram(allocator: std.mem.Allocator, source: []const u8) !struct { parser: Parser, sexp: Sexp } {
    var p = Parser.init(allocator, source);
    errdefer p.deinit();
    const sexp = try p.parseProgram();
    return .{ .parser = p, .sexp = sexp };
}

/// Parse a whole form with a new `Parser`. The caller owns
/// `result.parser` and must `deinit()` it when done with the tree.
pub fn parseForm(allocator: std.mem.Allocator, source: []const u8) !struct { parser: Parser, sexp: Sexp } {
    var p = Parser.init(allocator, source);
    errdefer p.deinit();
    const sexp = try p.parseForm();
    return .{ .parser = p, .sexp = sexp };
}
