//! Generated by nexus v0.10.1 — do not edit

const std = @import("std");
const maxArgs: usize = 32;
const nexis = @import("nexis.zig");

// SIMD helpers (fallback if simd.zig not available)
const simd = struct {
    fn findByte(haystack: []const u8, needle: u8) usize {
        for (haystack, 0..) |c, i| if (c == needle) return i;
        return haystack.len;
    }
};

// =============================================================================
// TOKEN CATEGORIES
// =============================================================================

pub const TokenCat = enum(u8) {
    @"integer",
    @"real",
    @"string",
    @"char",
    @"keyword",
    @"ident",
    @"lparen",
    @"rparen",
    @"lbracket",
    @"rbracket",
    @"lbrace",
    @"rbrace",
    @"hash_lbrace",
    @"hash_lparen",
    @"hash_discard",
    @"quote_tok",
    @"syntax_quote_tok",
    @"unquote_splicing_tok",
    @"unquote_tok",
    @"deref_tok",
    @"caret",
    @"eof",
    @"err",

    // Internal (used by generator)
    @"skip",
};

// =============================================================================
// TOKEN STRUCT (8 bytes)
// =============================================================================

pub const Token = struct {
    pos: u32,         // Byte position in source (4 bytes)
    len: u16,         // Token length in bytes (2 bytes)
    cat: TokenCat,    // Token category (1 byte)
    pre: u8,          // Preceding whitespace count (1 byte)

    comptime {
        std.debug.assert(@sizeOf(Token) == 8);
    }
};

// =============================================================================
// LEXER
// =============================================================================
pub const BaseLexer = struct {
    const Self = @This();

    source: []const u8,
    pos: u32,
    aux: u16 = 0,
    // State variables

    pub fn init(source: []const u8) Self {
        return .{
            .source = source,
            .pos = 0,
        };
    }

    /// Get the text slice for a token (zero-copy into source)
    pub fn text(self: *const Self, tok: Token) []const u8 {
        const start: usize = tok.pos;
        const end: usize = @min(start + tok.len, self.source.len);
        if (start >= self.source.len) return "";
        return self.source[start..end];
    }

    /// Reset lexer to beginning
    pub fn reset(self: *Self) void {
        self.pos = 0;
    }

    /// Peek at current character (0 if at end)
    inline fn peek(self: *const Self) u8 {
        return if (self.pos < self.source.len) self.source[self.pos] else 0;
    }

    /// Peek at character at offset (0 if at end)
    inline fn peekAt(self: *const Self, offset: u32) u8 {
        const p = self.pos + offset;
        return if (p < self.source.len) self.source[p] else 0;
    }

    /// Get next token
    pub fn next(self: *Self) Token {
        return self.matchRules();
    }

    // Character classification flags (generated from grammar patterns)
    const DIGIT: u8 = 1 << 0;
    const LETTER: u8 = 1 << 1;
    const WHITESPACE: u8 = 1 << 2;
    const IDENT_EXTRA: u8 = 1 << 3;

    const charFlags: [256]u8 = blk: {
        var table: [256]u8 = [_]u8{0} ** 256;
        for ('A'..'Z' + 1) |c| table[c] = LETTER;
        for ('a'..'z' + 1) |c| table[c] = LETTER;
        table['!'] = LETTER;
        table['$'] = LETTER;
        table['%'] = LETTER;
        table['&'] = LETTER;
        table['*'] = LETTER;
        table['+'] = LETTER;
        table['-'] = LETTER;
        table['.'] = LETTER;
        table['<'] = LETTER;
        table['='] = LETTER;
        table['>'] = LETTER;
        table['?'] = LETTER;
        table['_'] = LETTER;
        table['\''] = IDENT_EXTRA;
        table['/'] = IDENT_EXTRA;
        table['0'] = IDENT_EXTRA;
        table['1'] = IDENT_EXTRA;
        table['2'] = IDENT_EXTRA;
        table['3'] = IDENT_EXTRA;
        table['4'] = IDENT_EXTRA;
        table['5'] = IDENT_EXTRA;
        table['6'] = IDENT_EXTRA;
        table['7'] = IDENT_EXTRA;
        table['8'] = IDENT_EXTRA;
        table['9'] = IDENT_EXTRA;
        table[' '] = WHITESPACE;
        table['\t'] = WHITESPACE;
        break :blk table;
    };

    inline fn isDigit(c: u8) bool {
        return (charFlags[c] & DIGIT) != 0;
    }

    inline fn isLetter(c: u8) bool {
        return (charFlags[c] & LETTER) != 0;
    }

    inline fn isWhitespace(c: u8) bool {
        return (charFlags[c] & WHITESPACE) != 0;
    }

    inline fn isIdentChar(c: u8) bool {
        return (charFlags[c] & (LETTER | DIGIT | IDENT_EXTRA)) != 0;
    }
    /// Match lexer rules
    pub fn matchRules(self: *Self) Token {
        // Count whitespace first
        const wsStart = self.pos;
        while (self.pos < self.source.len and isWhitespace(self.source[self.pos])) {
            self.pos += 1;
        }
        const wsCount: u8 = @intCast(@min(self.pos - wsStart, 255));
        // EOF check
        if (self.pos >= self.source.len) {            return Token{ .cat = .@"eof", .pre = wsCount, .pos = self.pos, .len = 0 };
        }

        const start = self.pos;
        const c = self.source[self.pos];
        if (c == '"') {            self.pos += 1;
            while (self.pos < self.source.len) {
                const ch = self.source[self.pos];
                if (ch == '"') {
                    self.pos += 1;
                    return Token{ .cat = .@"string", .pre = wsCount, .pos = start, .len = @intCast(self.pos - start) };
                }
                if (ch == '\\') { self.pos += 2; continue; }
                if (ch == '\n') break;
                self.pos += 1;
            }
            return Token{ .cat = .@"err", .pre = wsCount, .pos = start, .len = @intCast(self.pos - start) };
        }
        // Number
        if (isDigit(c)) {
            return self.scanNumber(start, wsCount);
        }
        // Identifier
        if (isLetter(c)) {
            return self.scanIdent(start, wsCount);
        }
        if (c == ':') {
            const nc = if (self.pos + 1 < self.source.len) self.source[self.pos + 1] else 0;
            if ((nc >= 'a' and nc <= 'z') or (nc >= 'A' and nc <= 'Z') or nc == '_') {
                self.pos += 1;
                while (self.pos < self.source.len) {
                    const vc = self.source[self.pos];
                    if (!((vc >= 'a' and vc <= 'z') or (vc >= 'A' and vc <= 'Z') or (vc >= '0' and vc <= '9') or vc == '_')) break;
                    self.pos += 1;
                }
                return Token{ .cat = .@"keyword", .pre = wsCount, .pos = start, .len = @intCast(self.pos - start) };
            }
        }
        // Single/multi-char operators
        self.pos += 1;
        return switch (c) {
            '#' => blk: {
                if (self.peek() == '{') {
                    self.pos += 1;
                    break :blk Token{ .cat = .@"hash_lbrace", .pre = wsCount, .pos = start, .len = 2 };
                }
                if (self.peek() == '(') {
                    self.pos += 1;
                    break :blk Token{ .cat = .@"hash_lparen", .pre = wsCount, .pos = start, .len = 2 };
                }
                if (self.peek() == '_') {
                    self.pos += 1;
                    break :blk Token{ .cat = .@"hash_discard", .pre = wsCount, .pos = start, .len = 2 };
                }
                break :blk Token{ .cat = .@"err", .pre = wsCount, .pos = start, .len = 1 };
            },
            '\'' => Token{ .cat = .@"quote_tok", .pre = wsCount, .pos = start, .len = 1 },
            '(' => Token{ .cat = .@"lparen", .pre = wsCount, .pos = start, .len = 1 },
            ')' => Token{ .cat = .@"rparen", .pre = wsCount, .pos = start, .len = 1 },
            '/' => Token{ .cat = .@"ident", .pre = wsCount, .pos = start, .len = 1 },
            '@' => Token{ .cat = .@"deref_tok", .pre = wsCount, .pos = start, .len = 1 },
            '[' => Token{ .cat = .@"lbracket", .pre = wsCount, .pos = start, .len = 1 },
            ']' => Token{ .cat = .@"rbracket", .pre = wsCount, .pos = start, .len = 1 },
            '^' => Token{ .cat = .@"caret", .pre = wsCount, .pos = start, .len = 1 },
            '`' => Token{ .cat = .@"syntax_quote_tok", .pre = wsCount, .pos = start, .len = 1 },
            '{' => Token{ .cat = .@"lbrace", .pre = wsCount, .pos = start, .len = 1 },
            '}' => Token{ .cat = .@"rbrace", .pre = wsCount, .pos = start, .len = 1 },
            '~' => blk: {
                if (self.peek() == '@') {
                    self.pos += 1;
                    break :blk Token{ .cat = .@"unquote_splicing_tok", .pre = wsCount, .pos = start, .len = 2 };
                }
                    break :blk Token{ .cat = .@"unquote_tok", .pre = wsCount, .pos = start, .len = 1 };
            },
            else => Token{ .cat = .@"err", .pre = wsCount, .pos = start, .len = 1 },
        };
    }

    /// Scan number (generated from grammar)
    fn scanNumber(self: *Self, start: u32, ws: u8) Token {        var hasDecimal = false;        // Decimal integer
        if (isDigit(self.source[self.pos])) {
            while (self.pos < self.source.len and isDigit(self.source[self.pos])) {
                self.pos += 1;
            }
        }
        // Decimal part
        if (self.pos < self.source.len and self.source[self.pos] == '.') {
            const nextC = if (self.pos + 1 < self.source.len) self.source[self.pos + 1] else 0;
            if (isDigit(nextC)) {
                hasDecimal = true;
                self.pos += 1;
                while (self.pos < self.source.len and isDigit(self.source[self.pos])) {
                    self.pos += 1;
                }
            }
        }
        // Classify
        const tokenCat: TokenCat = if (hasDecimal)
            .@"real"
        else
            .@"integer";

        return Token{ .cat = tokenCat, .pre = ws, .pos = start, .len = @intCast(self.pos - start) };
    }

    /// Scan identifier (generated from grammar)
    fn scanIdent(self: *Self, start: u32, ws: u8) Token {
        while (self.pos < self.source.len and isIdentChar(self.source[self.pos])) {
            self.pos += 1;
        }
        return Token{ .cat = .@"ident", .pre = ws, .pos = start, .len = @intCast(self.pos - start) };
    }
};

pub const Lexer = if (@hasDecl(nexis, "Lexer")) nexis.Lexer else BaseLexer;

// =============================================================================
// Tag Enum (re-exported from language module)
// =============================================================================
pub const Tag = nexis.Tag;

// =============================================================================
// S-Expression (AST Node) - 5 Clean Variants
// =============================================================================

pub const Sexp = union(enum) {
    nil:  void,                                        // Empty (nothing)
    tag:  Tag,                                         // Semantic type (1 byte)
    src:  struct { pos: u32, len: u16, id: u16 },      // Source ref + identity (8 bytes)
    str:  []const u8,                                  // Embedded string (16 bytes)
    list: []const Sexp,                                // Compound: (tag child1 ...)

    /// Get token text from source
    pub fn getText(self: Sexp, source: []const u8) []const u8 {
        return switch (self) {
            .src => |s| source[s.pos..][0..s.len],
            .str => |s| s,
            else => "",
        };
    }

    /// Format for debug output
    pub fn write(self: Sexp, source: []const u8, w: anytype) !void {
        switch (self) {
            .nil => try w.writeAll("_"),
            .tag => |t| try w.print("{s}", .{@tagName(t)}),
            .src => |s| try w.print("{s}", .{source[s.pos..][0..s.len]}),
            .str => |s| try w.print("\"{s}\"", .{s}),
            .list => |items| {
                try w.writeAll("(");
                for (items, 0..) |item, i| {
                    if (i > 0) try w.writeAll(" ");
                    try item.write(source, w);
                }
                try w.writeAll(")");
            },
        }
    }
};

// =============================================================================
// PARSER
// =============================================================================

pub const BaseParser = struct {
    arena: std.heap.ArenaAllocator,
    lexer: Lexer,
    source: []const u8,
    current: Token,
    injectedToken: ?u16 = null,
    lastMatchedId: u16 = 0,

    stateStack: std.ArrayListUnmanaged(u16) = .empty,
    valueStack: std.ArrayListUnmanaged(Sexp) = .empty,

    pub fn init(backingAllocator: std.mem.Allocator, source: []const u8) BaseParser {
        var p = BaseParser{
            .arena = std.heap.ArenaAllocator.init(backingAllocator),
            .lexer = Lexer.init(source),
            .source = source,
            .current = undefined,
        };
        p.current = p.lexer.next();
        return p;
    }

    pub fn deinit(self: *BaseParser) void {
        self.arena.deinit();
    }

    fn allocator(self: *BaseParser) std.mem.Allocator {
        return self.arena.allocator();
    }

    pub fn printError(self: *BaseParser) void {
        const pos: usize = @min(self.current.pos, self.source.len);
        var line: usize = 1;
        var col: usize = 1;
        var i: usize = 0;
        while (i < pos) : (i += 1) {
            if (self.source[i] == '\n') {
                line += 1;
                col = 1;
            } else {
                col += 1;
            }
        }
        std.debug.print("Parse error at line {d}, column {d}: unexpected {s}\n", .{
            line,
            col,
            @tagName(self.current.cat),
        });
    }

    fn doParse(self: *BaseParser, startSym: u16) !Sexp {
        const startState = getStartState(startSym);
        self.stateStack.clearRetainingCapacity();
        self.valueStack.clearRetainingCapacity();
        try self.stateStack.append(self.allocator(), startState);

        while (true) {
            const state = self.stateStack.getLast();
            const sym = if (self.injectedToken) |inj| inj else self.tokenToSymbol(self.current);
            var action = getAction(state, sym);

            // X "c" check: if reducing and next char matches with pre==0, shift instead
            if (action < -1 and self.current.pre == 0 and self.current.pos < self.source.len) {
                if (getImmediateShift(state, self.source[self.current.pos])) |shiftTarget| {
                    action = shiftTarget;
                }
            }

            if (action == 0) {
                return error.ParseError;
            } else if (action == -1) {
                return self.valueStack.getLast();
            } else if (action > 0) {
                // Shift
                if (self.injectedToken != null) {
                    try self.valueStack.append(self.allocator(), .nil);
                    self.injectedToken = null;
                } else {
                    try self.valueStack.append(self.allocator(), .{ .src = .{
                        .pos = self.current.pos,
                        .len = self.current.len,
                        .id  = if (self.lastMatchedId != 0) self.lastMatchedId else self.lexer.base.aux,
                    } });
                    self.lastMatchedId = 0;
                    self.lexer.base.aux = 0;
                    self.current = self.lexer.next();
                }
                try self.stateStack.append(self.allocator(), @intCast(action));
            } else {
                // Reduce
                const ruleId: u16 = @intCast(-action - 2);
                var pass: [maxArgs]Sexp = undefined;
                const len = ruleLen[ruleId];
                for (0..len) |i| {
                    pass[len - 1 - i] = self.valueStack.pop().?;
                    _ = self.stateStack.pop();
                }

                const result = self.executeAction(ruleId, pass[0..len]);

                if (isAcceptRule(ruleId)) return result;

                try self.valueStack.append(self.allocator(), result);

                const gotoState = self.stateStack.getLast();
                const next = getAction(gotoState, ruleLhs[ruleId]);
                if (next <= 0) return error.ParseError;
                try self.stateStack.append(self.allocator(), @intCast(next));
            }
        }
    }

    /// Spread list helper: [head, ...tail]
    fn spreadList(self: *BaseParser, head: Sexp, tail: Sexp) Sexp {
        var out: std.ArrayListUnmanaged(Sexp) = .empty;
        out.append(self.allocator(), head) catch return .nil;
        if (tail == .list) for (tail.list) |item| out.append(self.allocator(), item) catch return .nil;
        return .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} };
    }

    /// Spread only: [...tail]
    fn spreadOnly(self: *BaseParser, tail: Sexp) Sexp {
        var out: std.ArrayListUnmanaged(Sexp) = .empty;
        if (tail == .list) for (tail.list) |item| out.append(self.allocator(), item) catch return .nil;
        return .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} };
    }

    /// Default list handler
    fn list(self: *BaseParser, pass: []Sexp) Sexp {
        if (pass.len == 0) return .nil;
        if (pass.len == 1) return pass[0];
        var out: std.ArrayListUnmanaged(Sexp) = .empty;
        for (pass) |v| out.append(self.allocator(), v) catch return .nil;
        return .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} };
    }

    /// Build S-expression: (tag items...) with trailing nil trimming
    inline fn sexp(self: *BaseParser, comptime tag: Tag, items: []const Sexp) Sexp {
        if (items.len == 0) {
            const result = self.allocator().alloc(Sexp, 1) catch return .nil;
            result[0] = .{ .tag = tag };
            return .{ .list = result };
        }
        var len = items.len;
        while (len > 0 and items[len - 1] == .nil) len -= 1;
        const result = self.allocator().alloc(Sexp, len + 1) catch return .nil;
        result[0] = .{ .tag = tag };
        if (len > 0) @memcpy(result[1..][0..len], items[0..len]);
        return .{ .list = result };
    }

    /// Build S-expression: (tag ...spread) - tag + spread items
    inline fn sexpSpread(self: *BaseParser, comptime tag: Tag, spread: Sexp) Sexp {
        const items = if (spread == .list) spread.list else &[_]Sexp{};
        var len = items.len;
        while (len > 0 and items[len - 1] == .nil) len -= 1;
        const result = self.allocator().alloc(Sexp, len + 1) catch return .nil;
        result[0] = .{ .tag = tag };
        if (len > 0) @memcpy(result[1..][0..len], items[0..len]);
        return .{ .list = result };
    }

    /// Build S-expression: (tag pos ...spread) - tag + position + spread items
    inline fn sexpPosSpread(self: *BaseParser, comptime tag: Tag, pos: Sexp, spread: Sexp) Sexp {
        const items = if (spread == .list) spread.list else &[_]Sexp{};
        var len = items.len;
        while (len > 0 and items[len - 1] == .nil) len -= 1;
        const skipPos = (pos == .nil and len == 0);
        const total = if (skipPos) 1 else len + 2;
        const result = self.allocator().alloc(Sexp, total) catch return .nil;
        result[0] = .{ .tag = tag };
        if (!skipPos) {
            result[1] = pos;
            if (len > 0) @memcpy(result[2..][0..len], items[0..len]);
        }
        return .{ .list = result };
    }

    fn executeAction(self: *BaseParser, ruleId: u16, pass: []Sexp) Sexp {
        return switch (ruleId) {
            0 => self.sexpSpread(.@"program", pass[1]),
            1 => pass[1],
            2 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .empty; if (pass[0] == .list) for (pass[0].list) |item| out.append(self.allocator(), item) catch break :blk .nil; out.append(self.allocator(), pass[1]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            3 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .empty; out.append(self.allocator(), pass[0]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            4 => .{ .list = &[_]Sexp{} },
            5 => self.list(pass),
            6 => self.list(pass),
            7 => self.list(pass),
            8 => self.list(pass),
            9 => self.list(pass),
            10 => self.list(pass),
            11 => self.list(pass),
            12 => self.list(pass),
            13 => self.list(pass),
            14 => self.list(pass),
            15 => self.list(pass),
            16 => self.list(pass),
            17 => self.list(pass),
            18 => self.sexp(.@"int", &.{pass[0]}),
            19 => self.sexp(.@"real", &.{pass[0]}),
            20 => self.sexp(.@"string", &.{pass[0]}),
            21 => self.sexp(.@"char", &.{pass[0]}),
            22 => self.sexp(.@"keyword", &.{pass[0]}),
            23 => self.sexp(.@"symbol", &.{pass[0]}),
            24 => self.sexpSpread(.@"list", pass[1]),
            25 => self.sexpSpread(.@"vector", pass[1]),
            26 => self.sexpSpread(.@"map", pass[1]),
            27 => self.sexpSpread(.@"set", pass[1]),
            28 => self.sexp(.@"quote", &.{pass[1]}),
            29 => self.sexp(.@"syntax-quote", &.{pass[1]}),
            30 => self.sexp(.@"unquote", &.{pass[1]}),
            31 => self.sexp(.@"unquote-splicing", &.{pass[1]}),
            32 => self.sexp(.@"deref", &.{pass[1]}),
            33 => self.sexpSpread(.@"anon-fn", pass[1]),
            34 => self.sexp(.@"discard", &.{pass[1]}),
            35 => self.sexp(.@"with-meta-raw", &.{pass[2], pass[1]}),
            36 => self.list(pass),
            37 => self.list(pass),
            else => .nil,
        };
    }

    fn tokenToSymbol(_: *BaseParser, token: Token) u16 {
        return switch (token.cat) {
            .@"eof" => 1,
            .@"integer" => 19,
            .@"real" => 20,
            .@"string" => 21,
            .@"char" => 22,
            .@"keyword" => 23,
            .@"ident" => 24,
            .@"hash_lbrace" => 31,
            .@"unquote_splicing_tok" => 35,
            .@"hash_lparen" => 37,
            .@"hash_discard" => 38,
            .@"lparen" => 25,
            .@"rparen" => 26,
            .@"lbracket" => 27,
            .@"rbracket" => 28,
            .@"lbrace" => 29,
            .@"rbrace" => 30,
            .@"quote_tok" => 32,
            .@"syntax_quote_tok" => 33,
            .@"unquote_tok" => 34,
            .@"deref_tok" => 36,
            .@"caret" => 39,
            else => 2, // error
        };
    }

    fn identToSymbol(_: *BaseParser, _: Token) u16 {
        return symIdent;
    }

    pub fn parseProgram(self: *BaseParser) !Sexp {
        self.injectedToken = SYM_program_START;
        return self.doParse(SYM_program);
    }
    pub fn parseForm(self: *BaseParser) !Sexp {
        self.injectedToken = SYM_form_START;
        return self.doParse(SYM_form);
    }
};

pub const Parser = if (@hasDecl(nexis, "Parser")) nexis.Parser else BaseParser;

// =============================================================================
// Top-level convenience helpers (one per start symbol)
// =============================================================================

/// Convenience: instantiate the (lang-extended) parser and parse a whole
/// program. Caller owns `result.parser` and must call `result.parser.deinit()`
/// when done with the returned tree (the tree references arena-allocated
/// memory owned by the parser).
///
/// The parser is returned by value, so the underlying type
/// must be safely movable (no self-referential storage).
/// `BaseParser` is movable by construction; custom `lang.Parser`
/// wrappers must preserve this invariant.
pub fn parseProgram(allocator: std.mem.Allocator, source: []const u8) !struct { parser: Parser, sexp: Sexp } {
    var p = Parser.init(allocator, source);
    errdefer p.deinit();
    const sexp = try p.parseProgram();
    return .{ .parser = p, .sexp = sexp };
}

/// Convenience: instantiate the (lang-extended) parser and parse a whole
/// form. Caller owns `result.parser` and must call `result.parser.deinit()`
/// when done with the returned tree (the tree references arena-allocated
/// memory owned by the parser).
///
/// The parser is returned by value, so the underlying type
/// must be safely movable (no self-referential storage).
/// `BaseParser` is movable by construction; custom `lang.Parser`
/// wrappers must preserve this invariant.
pub fn parseForm(allocator: std.mem.Allocator, source: []const u8) !struct { parser: Parser, sexp: Sexp } {
    var p = Parser.init(allocator, source);
    errdefer p.deinit();
    const sexp = try p.parseForm();
    return .{ .parser = p, .sexp = sexp };
}

// Symbol IDs
const SYM_program: u16 = 3;
const SYM_program_START: u16 = 40;
const SYM_form: u16 = 4;
const SYM_form_START: u16 = 42;
const symIdent: u16 = 24;

const ruleLhs = [_]u16{ 3, 4, 5, 5, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 6, 6, 6, 6, 6, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 41, 43 };
const ruleLen = [_]u8{ 2, 2, 2, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 2, 2, 2, 2, 2, 3, 2, 3, 2, 2 };

// Parse Table: 61 states × 44 symbols
const numStates = 61;
const numSymbols = 44;

const sparse = [numStates][]const i16{
    &.{3,2,40,3},
    &.{4,34,6,23,7,13,8,16,9,5,10,6,11,24,12,14,13,7,14,20,15,17,16,8,17,10,18,33,19,28,20,15,21,11,22,21,23,36,24,31,25,25,27,26,29,30,31,35,32,18,33,32,34,22,35,4,36,9,37,29,38,27,39,12,42,19},
    &.{1,-1},
    &.{1,-6,4,39,5,38,6,23,7,13,8,16,9,5,10,6,11,24,12,14,13,7,14,20,15,17,16,8,17,10,18,33,19,28,20,15,21,11,22,21,23,36,24,31,25,25,27,26,29,30,31,35,32,18,33,32,34,22,35,4,36,9,37,29,38,27,39,12,42,19},
    &.{4,40,6,23,7,13,8,16,9,5,10,6,11,24,12,14,13,7,14,20,15,17,16,8,17,10,18,33,19,28,20,15,21,11,22,21,23,36,24,31,25,25,27,26,29,30,31,35,32,18,33,32,34,22,35,4,36,9,37,29,38,27,39,12,42,19},
    &.{1,-10,19,-10,20,-10,21,-10,22,-10,23,-10,24,-10,25,-10,26,-10,27,-10,28,-10,29,-10,30,-10,31,-10,32,-10,33,-10,34,-10,35,-10,36,-10,37,-10,38,-10,39,-10,42,-10},
    &.{1,-11,19,-11,20,-11,21,-11,22,-11,23,-11,24,-11,25,-11,26,-11,27,-11,28,-11,29,-11,30,-11,31,-11,32,-11,33,-11,34,-11,35,-11,36,-11,37,-11,38,-11,39,-11,42,-11},
    &.{1,-14,19,-14,20,-14,21,-14,22,-14,23,-14,24,-14,25,-14,26,-14,27,-14,28,-14,29,-14,30,-14,31,-14,32,-14,33,-14,34,-14,35,-14,36,-14,37,-14,38,-14,39,-14,42,-14},
    &.{1,-17,19,-17,20,-17,21,-17,22,-17,23,-17,24,-17,25,-17,26,-17,27,-17,28,-17,29,-17,30,-17,31,-17,32,-17,33,-17,34,-17,35,-17,36,-17,37,-17,38,-17,39,-17,42,-17},
    &.{4,41,6,23,7,13,8,16,9,5,10,6,11,24,12,14,13,7,14,20,15,17,16,8,17,10,18,33,19,28,20,15,21,11,22,21,23,36,24,31,25,25,27,26,29,30,31,35,32,18,33,32,34,22,35,4,36,9,37,29,38,27,39,12,42,19},
    &.{1,-18,19,-18,20,-18,21,-18,22,-18,23,-18,24,-18,25,-18,26,-18,27,-18,28,-18,29,-18,30,-18,31,-18,32,-18,33,-18,34,-18,35,-18,36,-18,37,-18,38,-18,39,-18,42,-18},
    &.{1,-22,19,-22,20,-22,21,-22,22,-22,23,-22,24,-22,25,-22,26,-22,27,-22,28,-22,29,-22,30,-22,31,-22,32,-22,33,-22,34,-22,35,-22,36,-22,37,-22,38,-22,39,-22,42,-22},
    &.{4,42,6,23,7,13,8,16,9,5,10,6,11,24,12,14,13,7,14,20,15,17,16,8,17,10,18,33,19,28,20,15,21,11,22,21,23,36,24,31,25,25,27,26,29,30,31,35,32,18,33,32,34,22,35,4,36,9,37,29,38,27,39,12,42,19},
    &.{1,-8,19,-8,20,-8,21,-8,22,-8,23,-8,24,-8,25,-8,26,-8,27,-8,28,-8,29,-8,30,-8,31,-8,32,-8,33,-8,34,-8,35,-8,36,-8,37,-8,38,-8,39,-8,42,-8},
    &.{1,-13,19,-13,20,-13,21,-13,22,-13,23,-13,24,-13,25,-13,26,-13,27,-13,28,-13,29,-13,30,-13,31,-13,32,-13,33,-13,34,-13,35,-13,36,-13,37,-13,38,-13,39,-13,42,-13},
    &.{1,-21,19,-21,20,-21,21,-21,22,-21,23,-21,24,-21,25,-21,26,-21,27,-21,28,-21,29,-21,30,-21,31,-21,32,-21,33,-21,34,-21,35,-21,36,-21,37,-21,38,-21,39,-21,42,-21},
    &.{1,-9,19,-9,20,-9,21,-9,22,-9,23,-9,24,-9,25,-9,26,-9,27,-9,28,-9,29,-9,30,-9,31,-9,32,-9,33,-9,34,-9,35,-9,36,-9,37,-9,38,-9,39,-9,42,-9},
    &.{1,-16,19,-16,20,-16,21,-16,22,-16,23,-16,24,-16,25,-16,26,-16,27,-16,28,-16,29,-16,30,-16,31,-16,32,-16,33,-16,34,-16,35,-16,36,-16,37,-16,38,-16,39,-16,42,-16},
    &.{4,43,6,23,7,13,8,16,9,5,10,6,11,24,12,14,13,7,14,20,15,17,16,8,17,10,18,33,19,28,20,15,21,11,22,21,23,36,24,31,25,25,27,26,29,30,31,35,32,18,33,32,34,22,35,4,36,9,37,29,38,27,39,12,42,19},
    &.{4,44,6,23,7,13,8,16,9,5,10,6,11,24,12,14,13,7,14,20,15,17,16,8,17,10,18,33,19,28,20,15,21,11,22,21,23,36,24,31,25,25,27,26,29,30,31,35,32,18,33,32,34,22,35,4,36,9,37,29,38,27,39,12,42,19},
    &.{1,-15,19,-15,20,-15,21,-15,22,-15,23,-15,24,-15,25,-15,26,-15,27,-15,28,-15,29,-15,30,-15,31,-15,32,-15,33,-15,34,-15,35,-15,36,-15,37,-15,38,-15,39,-15,42,-15},
    &.{1,-23,19,-23,20,-23,21,-23,22,-23,23,-23,24,-23,25,-23,26,-23,27,-23,28,-23,29,-23,30,-23,31,-23,32,-23,33,-23,34,-23,35,-23,36,-23,37,-23,38,-23,39,-23,42,-23},
    &.{4,45,6,23,7,13,8,16,9,5,10,6,11,24,12,14,13,7,14,20,15,17,16,8,17,10,18,33,19,28,20,15,21,11,22,21,23,36,24,31,25,25,27,26,29,30,31,35,32,18,33,32,34,22,35,4,36,9,37,29,38,27,39,12,42,19},
    &.{1,-7,19,-7,20,-7,21,-7,22,-7,23,-7,24,-7,25,-7,26,-7,27,-7,28,-7,29,-7,30,-7,31,-7,32,-7,33,-7,34,-7,35,-7,36,-7,37,-7,38,-7,39,-7,42,-7},
    &.{1,-12,19,-12,20,-12,21,-12,22,-12,23,-12,24,-12,25,-12,26,-12,27,-12,28,-12,29,-12,30,-12,31,-12,32,-12,33,-12,34,-12,35,-12,36,-12,37,-12,38,-12,39,-12,42,-12},
    &.{4,39,5,46,6,23,7,13,8,16,9,5,10,6,11,24,12,14,13,7,14,20,15,17,16,8,17,10,18,33,19,28,20,15,21,11,22,21,23,36,24,31,25,25,26,-6,27,26,29,30,31,35,32,18,33,32,34,22,35,4,36,9,37,29,38,27,39,12,42,19},
    &.{4,39,5,47,6,23,7,13,8,16,9,5,10,6,11,24,12,14,13,7,14,20,15,17,16,8,17,10,18,33,19,28,20,15,21,11,22,21,23,36,24,31,25,25,27,26,28,-6,29,30,31,35,32,18,33,32,34,22,35,4,36,9,37,29,38,27,39,12,42,19},
    &.{4,48,6,23,7,13,8,16,9,5,10,6,11,24,12,14,13,7,14,20,15,17,16,8,17,10,18,33,19,28,20,15,21,11,22,21,23,36,24,31,25,25,27,26,29,30,31,35,32,18,33,32,34,22,35,4,36,9,37,29,38,27,39,12,42,19},
    &.{1,-20,19,-20,20,-20,21,-20,22,-20,23,-20,24,-20,25,-20,26,-20,27,-20,28,-20,29,-20,30,-20,31,-20,32,-20,33,-20,34,-20,35,-20,36,-20,37,-20,38,-20,39,-20,42,-20},
    &.{4,39,5,49,6,23,7,13,8,16,9,5,10,6,11,24,12,14,13,7,14,20,15,17,16,8,17,10,18,33,19,28,20,15,21,11,22,21,23,36,24,31,25,25,26,-6,27,26,29,30,31,35,32,18,33,32,34,22,35,4,36,9,37,29,38,27,39,12,42,19},
    &.{4,39,5,50,6,23,7,13,8,16,9,5,10,6,11,24,12,14,13,7,14,20,15,17,16,8,17,10,18,33,19,28,20,15,21,11,22,21,23,36,24,31,25,25,27,26,29,30,30,-6,31,35,32,18,33,32,34,22,35,4,36,9,37,29,38,27,39,12,42,19},
    &.{1,-25,19,-25,20,-25,21,-25,22,-25,23,-25,24,-25,25,-25,26,-25,27,-25,28,-25,29,-25,30,-25,31,-25,32,-25,33,-25,34,-25,35,-25,36,-25,37,-25,38,-25,39,-25,42,-25},
    &.{4,51,6,23,7,13,8,16,9,5,10,6,11,24,12,14,13,7,14,20,15,17,16,8,17,10,18,33,19,28,20,15,21,11,22,21,23,36,24,31,25,25,27,26,29,30,31,35,32,18,33,32,34,22,35,4,36,9,37,29,38,27,39,12,42,19},
    &.{1,-19,19,-19,20,-19,21,-19,22,-19,23,-19,24,-19,25,-19,26,-19,27,-19,28,-19,29,-19,30,-19,31,-19,32,-19,33,-19,34,-19,35,-19,36,-19,37,-19,38,-19,39,-19,42,-19},
    &.{1,-1},
    &.{4,39,5,53,6,23,7,13,8,16,9,5,10,6,11,24,12,14,13,7,14,20,15,17,16,8,17,10,18,33,19,28,20,15,21,11,22,21,23,36,24,31,25,25,27,26,29,30,30,-6,31,35,32,18,33,32,34,22,35,4,36,9,37,29,38,27,39,12,42,19},
    &.{1,-24,19,-24,20,-24,21,-24,22,-24,23,-24,24,-24,25,-24,26,-24,27,-24,28,-24,29,-24,30,-24,31,-24,32,-24,33,-24,34,-24,35,-24,36,-24,37,-24,38,-24,39,-24,42,-24},
    &.{1,-1},
    &.{1,-2,4,54,6,23,7,13,8,16,9,5,10,6,11,24,12,14,13,7,14,20,15,17,16,8,17,10,18,33,19,28,20,15,21,11,22,21,23,36,24,31,25,25,27,26,29,30,31,35,32,18,33,32,34,22,35,4,36,9,37,29,38,27,39,12,42,19},
    &.{1,-5,19,-5,20,-5,21,-5,22,-5,23,-5,24,-5,25,-5,26,-5,27,-5,28,-5,29,-5,30,-5,31,-5,32,-5,33,-5,34,-5,35,-5,36,-5,37,-5,38,-5,39,-5,42,-5},
    &.{1,-33,19,-33,20,-33,21,-33,22,-33,23,-33,24,-33,25,-33,26,-33,27,-33,28,-33,29,-33,30,-33,31,-33,32,-33,33,-33,34,-33,35,-33,36,-33,37,-33,38,-33,39,-33,42,-33},
    &.{1,-34,19,-34,20,-34,21,-34,22,-34,23,-34,24,-34,25,-34,26,-34,27,-34,28,-34,29,-34,30,-34,31,-34,32,-34,33,-34,34,-34,35,-34,36,-34,37,-34,38,-34,39,-34,42,-34},
    &.{4,55,6,23,7,13,8,16,9,5,10,6,11,24,12,14,13,7,14,20,15,17,16,8,17,10,18,33,19,28,20,15,21,11,22,21,23,36,24,31,25,25,27,26,29,30,31,35,32,18,33,32,34,22,35,4,36,9,37,29,38,27,39,12,42,19},
    &.{1,-30,19,-30,20,-30,21,-30,22,-30,23,-30,24,-30,25,-30,26,-30,27,-30,28,-30,29,-30,30,-30,31,-30,32,-30,33,-30,34,-30,35,-30,36,-30,37,-30,38,-30,39,-30,42,-30},
    &.{1,-3,19,-3,20,-3,21,-3,22,-3,23,-3,24,-3,25,-3,26,-3,27,-3,28,-3,29,-3,30,-3,31,-3,32,-3,33,-3,34,-3,35,-3,36,-3,37,-3,38,-3,39,-3,42,-3},
    &.{1,-32,19,-32,20,-32,21,-32,22,-32,23,-32,24,-32,25,-32,26,-32,27,-32,28,-32,29,-32,30,-32,31,-32,32,-32,33,-32,34,-32,35,-32,36,-32,37,-32,38,-32,39,-32,42,-32},
    &.{4,54,6,23,7,13,8,16,9,5,10,6,11,24,12,14,13,7,14,20,15,17,16,8,17,10,18,33,19,28,20,15,21,11,22,21,23,36,24,31,25,25,26,56,27,26,29,30,31,35,32,18,33,32,34,22,35,4,36,9,37,29,38,27,39,12,42,19},
    &.{4,54,6,23,7,13,8,16,9,5,10,6,11,24,12,14,13,7,14,20,15,17,16,8,17,10,18,33,19,28,20,15,21,11,22,21,23,36,24,31,25,25,27,26,28,57,29,30,31,35,32,18,33,32,34,22,35,4,36,9,37,29,38,27,39,12,42,19},
    &.{1,-36,19,-36,20,-36,21,-36,22,-36,23,-36,24,-36,25,-36,26,-36,27,-36,28,-36,29,-36,30,-36,31,-36,32,-36,33,-36,34,-36,35,-36,36,-36,37,-36,38,-36,39,-36,42,-36},
    &.{4,54,6,23,7,13,8,16,9,5,10,6,11,24,12,14,13,7,14,20,15,17,16,8,17,10,18,33,19,28,20,15,21,11,22,21,23,36,24,31,25,25,26,58,27,26,29,30,31,35,32,18,33,32,34,22,35,4,36,9,37,29,38,27,39,12,42,19},
    &.{4,54,6,23,7,13,8,16,9,5,10,6,11,24,12,14,13,7,14,20,15,17,16,8,17,10,18,33,19,28,20,15,21,11,22,21,23,36,24,31,25,25,27,26,29,30,30,59,31,35,32,18,33,32,34,22,35,4,36,9,37,29,38,27,39,12,42,19},
    &.{1,-31,19,-31,20,-31,21,-31,22,-31,23,-31,24,-31,25,-31,26,-31,27,-31,28,-31,29,-31,30,-31,31,-31,32,-31,33,-31,34,-31,35,-31,36,-31,37,-31,38,-31,39,-31,42,-31},
    &.{1,-1},
    &.{4,54,6,23,7,13,8,16,9,5,10,6,11,24,12,14,13,7,14,20,15,17,16,8,17,10,18,33,19,28,20,15,21,11,22,21,23,36,24,31,25,25,27,26,29,30,30,60,31,35,32,18,33,32,34,22,35,4,36,9,37,29,38,27,39,12,42,19},
    &.{1,-4,19,-4,20,-4,21,-4,22,-4,23,-4,24,-4,25,-4,26,-4,27,-4,28,-4,29,-4,30,-4,31,-4,32,-4,33,-4,34,-4,35,-4,36,-4,37,-4,38,-4,39,-4,42,-4},
    &.{1,-37,19,-37,20,-37,21,-37,22,-37,23,-37,24,-37,25,-37,26,-37,27,-37,28,-37,29,-37,30,-37,31,-37,32,-37,33,-37,34,-37,35,-37,36,-37,37,-37,38,-37,39,-37,42,-37},
    &.{1,-26,19,-26,20,-26,21,-26,22,-26,23,-26,24,-26,25,-26,26,-26,27,-26,28,-26,29,-26,30,-26,31,-26,32,-26,33,-26,34,-26,35,-26,36,-26,37,-26,38,-26,39,-26,42,-26},
    &.{1,-27,19,-27,20,-27,21,-27,22,-27,23,-27,24,-27,25,-27,26,-27,27,-27,28,-27,29,-27,30,-27,31,-27,32,-27,33,-27,34,-27,35,-27,36,-27,37,-27,38,-27,39,-27,42,-27},
    &.{1,-35,19,-35,20,-35,21,-35,22,-35,23,-35,24,-35,25,-35,26,-35,27,-35,28,-35,29,-35,30,-35,31,-35,32,-35,33,-35,34,-35,35,-35,36,-35,37,-35,38,-35,39,-35,42,-35},
    &.{1,-28,19,-28,20,-28,21,-28,22,-28,23,-28,24,-28,25,-28,26,-28,27,-28,28,-28,29,-28,30,-28,31,-28,32,-28,33,-28,34,-28,35,-28,36,-28,37,-28,38,-28,39,-28,42,-28},
    &.{1,-29,19,-29,20,-29,21,-29,22,-29,23,-29,24,-29,25,-29,26,-29,27,-29,28,-29,29,-29,30,-29,31,-29,32,-29,33,-29,34,-29,35,-29,36,-29,37,-29,38,-29,39,-29,42,-29},
};

const parseTable = blk: {
    @setEvalBranchQuota(100000);
    var t: [numStates][numSymbols]i16 = .{.{0} ** numSymbols} ** numStates;
    for (sparse, 0..) |row, state| {
        var i: usize = 0;
        while (i < row.len) : (i += 2) {
            t[state][@intCast(row[i])] = row[i + 1];
        }
    }
    break :blk t;
};

fn getAction(state: u16, sym: u16) i16 {
    return parseTable[state][sym];
}
// X "c" excludes: shift instead of reduce when pre==0 and char matches
const xExcludes = [_]struct { state: u16, char: u8, shift: u16 }{
};

fn getImmediateShift(state: u16, char: u8) ?i16 {
    for (xExcludes) |x| {
        if (x.state == state and x.char == char) return @intCast(x.shift);
    }
    return null;
}
const startStates = [_]struct { sym: u16, state: u16 }{
    .{ .sym = 3, .state = 0 },
    .{ .sym = 4, .state = 1 },
};

fn getStartState(startSym: u16) u16 {
    for (startStates) |entry| {
        if (entry.sym == startSym) return entry.state;
    }
    return 0;
}

const acceptRules = [_]u16{ 36, 37 };

fn isAcceptRule(ruleId: u16) bool {
    for (acceptRules) |ar| if (ruleId == ar) return true;
    return false;
}
