//! Generated by nexus v2.1.0 — do not edit

const std = @import("std");
const lang = @import("nexis.zig");

// =============================================================================
// TOKEN CATEGORIES
// =============================================================================

pub const TokenCat = enum(u8) {
    @"integer",
    @"real",
    @"string",
    @"regex",
    @"char",
    @"keyword",
    @"ident",
    @"lparen",
    @"rparen",
    @"lbracket",
    @"rbracket",
    @"lbrace",
    @"rbrace",
    @"hash_lbrace",
    @"hash_lparen",
    @"hash_discard",
    @"quote_tok",
    @"syntax_quote_tok",
    @"unquote_splicing_tok",
    @"unquote_tok",
    @"deref_tok",
    @"var_quote_tok",
    @"caret",
    @"eof",
    @"err",

    // Built in: the token of `→ skip` rules (returned to the lang Lexer)
    @"skip",
};

// =============================================================================
// TOKEN STRUCT (8 bytes)
// =============================================================================

pub const Token = struct {
    pos: u32, // Byte position in source (4 bytes)
    len: u16, // Token length in bytes (2 bytes)
    cat: TokenCat, // Token category (1 byte)
    pre: u8, // Preceding whitespace count (1 byte)

    comptime {
        std.debug.assert(@sizeOf(Token) == 8);
    }
};

// =============================================================================
// LEXER
// =============================================================================

pub const BaseLexer = struct {
    const Self = @This();

    source: []const u8,
    pos: u32,
    /// Side channel a lang Lexer wrapper may set per token; the parser
    /// copies it into the shifted leaf's `src.id` and clears it.
    aux: u16 = 0,

    pub fn init(source: []const u8) Self {
        return .{
            .source = source,
            .pos = 0,
        };
    }

    /// The text of a token (a slice of the source).
    pub fn text(self: *const Self, tok: Token) []const u8 {
        const start: usize = tok.pos;
        const end: usize = @min(start + tok.len, self.source.len);
        if (start >= self.source.len) return "";
        return self.source[start..end];
    }

    /// The token of `cat` from `start` to `end`, as the scanner builds
    /// it: a match longer than a Token can hold is an `err` token 65535
    /// bytes long, and the scan goes on after the whole match. A lang
    /// Lexer wrapper builds its tokens with it too.
    pub inline fn makeToken(cat: TokenCat, pre: u8, start: usize, end: usize) Token {
        if (end - start > std.math.maxInt(u16)) return .{ .cat = .@"err", .pre = pre, .pos = @intCast(start), .len = std.math.maxInt(u16) };
        return .{ .cat = cat, .pre = pre, .pos = @intCast(start), .len = @intCast(end - start) };
    }

    /// Scan the next token.
    pub fn next(self: *Self) Token {
        const src = self.source;
        const n = src.len;
        var p: usize = self.pos;
        const wsStart = p;
        while (p < n and (src[p] == ' ' or src[p] == '\t')) p += 1;
        const pre: u8 = @intCast(@min(p - wsStart, 255));
        if (p >= n) {
            self.pos = @intCast(p);
            return .{ .cat = .@"eof", .pre = pre, .pos = @intCast(p), .len = 0 };
        }
        const start = p;
        self.pos = @intCast(start + 1);
        return .{ .cat = .@"err", .pre = pre, .pos = @intCast(start), .len = 1 };
    }
};

/// The lexer the parser drives: the lang module's `Lexer` wrapper, if it
/// declares one.
pub const Lexer = if (@hasDecl(lang, "Lexer")) lang.Lexer else BaseLexer;

// =============================================================================
// Tag enum (the tags the actions produce, then @tags)
// =============================================================================

pub const Tag = enum(u8) {
    @"program",
    @"int",
    @"real",
    @"string",
    @"regex",
    @"char",
    @"keyword",
    @"symbol",
    @"list",
    @"vector",
    @"map",
    @"set",
    @"anon-fn",
    @"quote",
    @"syntax-quote",
    @"unquote",
    @"unquote-splicing",
    @"deref",
    @"var-quote",
    @"with-meta-raw",
};

/// Roles exist only in schema mode.
pub const Role = enum(u16) { _ };

/// Start symbols; `BaseParser.parse(start)` parses one.
pub const Start = enum(u16) {
    @"program" = 3,
    @"form" = 4,
};

// =============================================================================
// S-expressions
// =============================================================================

/// Dense per-parse node number; 0 = no node store entry.
pub const NodeId = u32;

/// A byte range [start, end) of the source.
pub const Span = struct {
    start: u32,
    end: u32,

    pub const empty: Span = .{ .start = 0, .end = 0 };

    pub fn len(self: Span) u32 {
        return self.end - self.start;
    }

    pub fn isEmpty(self: Span) bool {
        return self.start == self.end;
    }
};

/// A source leaf: token position and length, plus the token id attribute
/// (an `@as` keyword ordinal, or the lexer's `aux` value; see `takeLexerId`).
pub const Src = struct { pos: u32, len: u16, id: u16 };

/// A list node: its items and its node id (0 when the parse keeps no node
/// store, or for lists built outside the parser, e.g. by a lang wrapper).
pub const List = struct {
    ptr: [*]const Sexp,
    len: u32,
    id: NodeId = 0,

    pub const empty: List = .{ .ptr = &[_]Sexp{}, .len = 0 };

    /// A list over `xs` with no node id.
    pub fn of(xs: []const Sexp) List {
        return .{ .ptr = xs.ptr, .len = @intCast(xs.len) };
    }

    /// A list over `xs` carrying node id `id` (e.g. a rewritten node
    /// keeping the id, and so the span, of the node it replaces).
    pub fn withId(xs: []const Sexp, id: NodeId) List {
        return .{ .ptr = xs.ptr, .len = @intCast(xs.len), .id = id };
    }

    pub fn items(self: List) []const Sexp {
        return self.ptr[0..self.len];
    }
};

/// The uniform tree value: 24 bytes, O(1) dispatch on the head tag.
pub const Sexp = union(enum) {
    nil,
    tag: Tag,
    src: Src,
    str: []const u8,
    list: List,

    comptime {
        std.debug.assert(@sizeOf(Sexp) == 24);
    }

    /// A list value over `xs` with no node id.
    pub fn listOf(xs: []const Sexp) Sexp {
        return .{ .list = List.of(xs) };
    }

    /// The items of a list; empty for any other value.
    pub fn items(self: Sexp) []const Sexp {
        return switch (self) {
            .list => |l| l.items(),
            else => &.{},
        };
    }

    /// The head tag of a tag-headed list.
    pub fn kind(self: Sexp) ?Tag {
        if (self != .list or self.list.len == 0) return null;
        const head = self.list.ptr[0];
        return if (head == .tag) head.tag else null;
    }

    pub fn isKind(self: Sexp, t: Tag) bool {
        const k = self.kind() orelse return false;
        return k == t;
    }

    /// The text of a leaf or string; empty otherwise.
    pub fn getText(self: Sexp, source: []const u8) []const u8 {
        return switch (self) {
            .src => |s| source[s.pos..][0..s.len],
            .str => |s| s,
            else => "",
        };
    }

    /// Print the tree on one line: `_`, tags by name, leaves as their text
    /// followed by `#id` when the id attribute is non-zero, strings quoted.
    /// error.WriteFailed also reports the walk running out of memory.
    pub fn write(self: Sexp, source: []const u8, w: *std.Io.Writer) std.Io.Writer.Error!void {
        try writeNested(self, w, source, writeAtom);
    }

    fn writeAtom(source: []const u8, w: *std.Io.Writer, s: Sexp) std.Io.Writer.Error!?[]const Sexp {
        switch (s) {
            .nil => try w.writeAll("_"),
            .tag => |t| try w.writeAll(nameOf(t)),
            .src => |x| {
                try w.writeAll(source[x.pos..][0..x.len]);
                if (x.id != 0) try w.print("#{d}", .{x.id});
            },
            .str => |x| try w.print("\"{s}\"", .{x}),
            .list => |l| return l.items(),
        }
        return null;
    }
};

/// The name of a Tag or Role value, "?" for one the enum does not name
/// (without a schema Role is empty, and so is Tag when no action builds a
/// tag: both are then non-exhaustive).
fn nameOf(value: anytype) []const u8 {
    return std.enums.tagName(@TypeOf(value), value) orelse "?";
}

/// The explicit stack of a tree walk: per open list, its items not yet
/// visited. Ordinary input builds trees of any depth (a long operator
/// chain is a tree as deep as it is long), so no walk of a tree recurses
/// on the native stack. Shallow walks use the frames inline; deeper ones
/// move them to page memory.
const Walk = struct {
    small: [32][]const Sexp = undefined,
    big: [][]const Sexp = &.{},
    len: usize = 0,

    fn frames(self: *Walk) [][]const Sexp {
        return if (self.big.len > 0) self.big else &self.small;
    }

    fn push(self: *Walk, items: []const Sexp) error{OutOfMemory}!void {
        var f = self.frames();
        if (self.len == f.len) {
            const grown = try std.heap.page_allocator.alloc([]const Sexp, f.len * 2);
            @memcpy(grown[0..self.len], f);
            if (self.big.len > 0) std.heap.page_allocator.free(self.big);
            self.big = grown;
            f = grown;
        }
        f[self.len] = items;
        self.len += 1;
    }

    /// The unvisited items of the innermost open list.
    fn top(self: *Walk) ?*[]const Sexp {
        return if (self.len == 0) null else &self.frames()[self.len - 1];
    }

    fn pop(self: *Walk) void {
        self.len -= 1;
    }

    /// The next item in pre-order, closing the lists it leaves; null at
    /// the end of the walk.
    fn next(self: *Walk) ?Sexp {
        while (self.top()) |rest| {
            if (rest.len > 0) {
                defer rest.* = rest.*[1..];
                return rest.*[0];
            }
            self.pop();
        }
        return null;
    }

    fn deinit(self: *Walk) void {
        if (self.big.len > 0) std.heap.page_allocator.free(self.big);
    }
};

/// Write `root` as nested parentheses with a space between items.
/// `atom(ctx, w, s)` writes a value and returns null, or returns the items
/// of a list to open.
fn writeNested(
    root: Sexp,
    w: *std.Io.Writer,
    ctx: anytype,
    comptime atom: fn (@TypeOf(ctx), *std.Io.Writer, Sexp) std.Io.Writer.Error!?[]const Sexp,
) std.Io.Writer.Error!void {
    var walk: Walk = .{};
    defer walk.deinit();
    var s = root;
    while (true) {
        // Whether the next item of the innermost list follows another.
        var sep = true;
        if (try atom(ctx, w, s)) |items| {
            try w.writeByte('(');
            walk.push(items) catch return error.WriteFailed;
            sep = false;
        }
        while (true) {
            const rest = walk.top() orelse return;
            if (rest.len > 0) {
                if (sep) try w.writeByte(' ');
                s = rest.*[0];
                rest.* = rest.*[1..];
                break;
            }
            walk.pop();
            try w.writeByte(')');
            sep = true;
        }
    }
}


// =============================================================================
// Parser
// =============================================================================

/// Per node: its source span and the rule that built it.
const NodeInfo = struct { span: Span, rule: u16 };

/// NodeInfo per NodeId, in fixed-size chunks that never move (appending
/// never copies the store).
const NodeStore = struct {
    chunks: std.ArrayList(*[chunkLen]NodeInfo) = .empty,
    len: u32 = 0,

    const chunkLen = 128;

    inline fn add(self: *NodeStore, a: std.mem.Allocator, info: NodeInfo) !NodeId {
        const id = self.len;
        if (id % chunkLen == 0) try self.addChunk(a);
        self.chunks.items[id / chunkLen][id % chunkLen] = info;
        self.len = id + 1;
        return id;
    }

    fn addChunk(self: *NodeStore, a: std.mem.Allocator) !void {
        try self.chunks.append(a, try a.create([chunkLen]NodeInfo));
    }

    inline fn at(self: *const NodeStore, id: NodeId) *NodeInfo {
        return &self.chunks.items[id / chunkLen][id % chunkLen];
    }
};

/// The parse table's action for `sym` in `state`: 0 = error, > 0 = shift
/// or goto, -1 = accept, <= -2 = reduce rule (-a - 2), or `hinted`.
inline fn getAction(state: u16, sym: u16) i16 {
    return parseTable[state][sym];
}

/// Whether rule `r` is a pass-through `A → B`: one element, and its value.
inline fn isPassThrough(r: u16) bool {
    return ruleLen[r] == 1 and ruleValue[r] == 2;
}

/// The cell of a reduction an `X "c"` hint overrides: `hintedAction`
/// decides it (no rule has this number: rules are fewer than 32766).
const hinted: i16 = std.math.minInt(i16);

/// What `state` expects, reader-named: list `expectedOf[state]` of
/// `expectedSymbols`.
fn expectedIn(state: u16) []const u16 {
    const i = expectedOf[state];
    return expectedSymbols[expectedOffsets[i]..expectedOffsets[i + 1]];
}

/// The action of a `hinted` cell: shift to the hint's state when the token
/// touches the previous one, else the table's reduction.
fn hintedAction(state: u16, sym: u16, touching: bool) i16 {
    for (xExcludes[xExcludeStart[state]..xExcludeStart[state + 1]]) |x| {
        if (x.sym == sym) return if (touching) @intCast(x.shift) else x.reduce;
    }
    unreachable; // every hinted cell has its exclude
}

/// The tokens tolerant repair may insert in `state`, best first.
fn repairCandidates(state: u16) []const u16 {
    if (!hasRepair) return &.{};
    return repairTokens[repairOffsets[state]..repairOffsets[state + 1]];
}

/// The symbol `tokenToSymbol` gives the promotable token when `@as`
/// decides it per state; no grammar symbol has it.
const needsPromotion: u16 = std.math.maxInt(u16);

/// The length of an `@as` group's symbol map: an entry for every value of
/// its Id enum up to the largest it names.
fn idCount(comptime Id: type) usize {
    var n: usize = 0;
    for (@typeInfo(Id).@"enum".field_values) |v| n = @max(n, v + 1);
    return n;
}

/// A side-band role recorded at reduce time (not placed in the tree).
const SideEntry = struct { node: NodeId, role: Role, span: Span };

/// A side-band label of a rule: `role` is recorded from element `pass`.
const SideLabel = struct { role: Role, pass: u16 };

/// A parse error: the offending token and the state that rejected it.
pub const Failure = struct {
    span: Span,
    /// Grammar symbol of the offending token.
    symbol: u16,
    cat: TokenCat,
    state: u16,
};

/// Result of `parseTolerant`.
pub const Tolerant = struct {
    /// The tree; `.nil` when the parse could not be completed.
    sexp: Sexp,
    /// The first error, as the strict parse reports it (null when the
    /// input was valid).
    failure: ?Failure,
    /// Tokens inserted plus tokens deleted.
    repairs: u32,
    /// Zero-width tokens inserted (holes and structure).
    insertions: u32 = 0,
    /// Offending tokens deleted.
    deletions: u32 = 0,
    complete: bool,
};

/// A token's role in tolerant repair, from `@repair`.
const RepairClass = enum {
    /// Not fabricable: real input.
    none,
    /// `holes`: a value-carrying token that may be minted with empty text.
    hole,
    /// `structure`: layout a lexer mints (INDENT, OUTDENT, ...).
    structure,
    /// `terminator`: structure that ends a statement (NEWLINE); the only
    /// insertion allowed in front of real input.
    terminator,
};

/// The id attribute of the token the lexer just produced, cleared as it is
/// read. It is the `aux: u16` field of the generated BaseLexer, which a lang
/// `Lexer` wrapper reaches as `base.aux` (set it before returning a token,
/// e.g. MUMPS stores the dot level of a line there). The parser stores it in
/// the token's `src.id` unless an `@as` keyword match supplies the id.
fn takeLexerId(lexer: *Lexer) u16 {
    const base: *BaseLexer = if (Lexer == BaseLexer) lexer else &lexer.base;
    defer base.aux = 0;
    return base.aux;
}

comptime {
    if (Lexer != BaseLexer and !(@hasField(Lexer, "base") and @FieldType(Lexer, "base") == BaseLexer))
        @compileError("the lang module's Lexer wrapper must hold the generated lexer in a field `base: BaseLexer`");
}

pub const BaseParser = struct {
    arena: std.heap.ArenaAllocator,
    lexer: Lexer,
    source: []const u8,
    current: Token,
    /// A start marker to shift before any input (set by `parse`).
    injectedToken: ?u16 = null,
    /// A zero-width token the tolerant driver inserts before `current`.
    pendingInsert: ?u16 = null,
    /// `@as` keyword ordinal of `current`, stored in its `src.id`.
    lastMatchedId: u16 = 0,
    /// The `@as` lookups of `current`, one per group: the keyword ordinal
    /// plus one, `noKeyword`, or 0 before the lookup. A lookup does not
    /// depend on the state, so it runs once per token.
    keywordIds: [asGroups]u32 = @splat(0),
    /// Set when a builder could not allocate; the parse then fails.
    outOfMemory: bool = false,
    /// A parse has begun (the next one re-reads the input).
    started: bool = false,

    /// The free bytes of the allocator's current chunk, and the size of
    /// its next one (see `allocator`).
    bumpPos: usize = 0,
    bumpEnd: usize = 0,
    bumpNext: usize = bumpFirst,

    stateStack: std.ArrayList(u16) = .empty,
    valueStack: std.ArrayList(Sexp) = .empty,
    /// Per value-stack entry, the list `keepExtended` left there with its
    /// capacity, for `extendBy` to grow in place. Indexed like
    /// `valueStack`, sized to its capacity. An entry only ever describes a
    /// live buffer: `extendBy` clears the one it takes (its buffer may
    /// move and be freed), a rule passing a list on moves the entry with
    /// it, and each parse starts with none (its memory is reused).
    spares: []Spare = &.{},

    // Node store (when `nodeStore`): per value-stack entry where it
    // starts, and per node its span and rule, indexed by NodeId (entry 0
    // unused). An entry starts at its first token, or at the next token
    // when it consumed none. A reduction then extends from its first
    // element's start to the end of the last token shifted (`lastEnd`),
    // and is empty when start >= end. With `elemEnds` (side-band labels or
    // nested nodes) each entry's end is kept too. Both are indexed like
    // `valueStack` and sized to its capacity (the stack top is its length).
    starts: []u32 = &.{},
    ends: []u32 = &.{},
    nodes: NodeStore = .{},
    sides: std.ArrayList(SideEntry) = .empty,
    reduction: Reduction = .{},
    /// End of the last shifted token: where every reduction ends.
    lastEnd: u32 = 0,

    triviaTokens: std.ArrayList(Token) = .empty,
    failure: ?Failure = null,
    scratch: std.ArrayList(u16) = .empty,

    const Spare = struct {
        items: [*]const Sexp,
        len: u32,
        capacity: u32,

        const none: Spare = .{ .items = &.{}, .len = 0, .capacity = 0 };
    };

    /// The reduction in progress: its rule and where it starts (it ends at
    /// `lastEnd`); with `elemEnds`, also the stack index of its first
    /// element and the first node id it built.
    const Reduction = struct {
        rule: u16 = 0,
        start: u32 = 0,
        base: u32 = 0,
        firstNode: NodeId = 0,
    };

    pub fn init(backingAllocator: std.mem.Allocator, source: []const u8) BaseParser {
        var p = BaseParser{
            .arena = std.heap.ArenaAllocator.init(backingAllocator),
            .lexer = Lexer.init(source),
            .source = source,
            .current = undefined,
        };
        p.setCurrent(p.lexer.next());
        return p;
    }

    pub fn deinit(self: *BaseParser) void {
        self.arena.deinit();
    }

    /// Start over on `source`, keeping the memory the parser holds for the
    /// next parses: the trees, node ids and errors of earlier parses, and
    /// everything from `allocator`, are gone.
    pub fn reset(self: *BaseParser, source: []const u8) void {
        var arena = self.arena;
        _ = arena.reset(.retain_capacity);
        self.* = .{ .arena = arena, .lexer = Lexer.init(source), .source = source, .current = undefined };
        self.setCurrent(self.lexer.next());
    }

    /// The parser's allocator, which holds the trees: a bump allocator over
    /// chunks of the arena (single-threaded, so allocation is a bounds check
    /// and an add; the arena's own allocation is atomic). A lang Parser
    /// wrapper allocates what it builds here too. Everything is freed by
    /// `deinit` (or `reset`).
    pub fn allocator(self: *BaseParser) std.mem.Allocator {
        return .{ .ptr = self, .vtable = &bumpVTable };
    }

    /// `n` items for a list: the allocator's fast path, inline.
    inline fn allocItems(self: *BaseParser, n: usize) error{OutOfMemory}![]Sexp {
        const start = std.mem.alignForward(usize, self.bumpPos, @alignOf(Sexp));
        const end = start + n * @sizeOf(Sexp);
        if (end > self.bumpEnd) return self.allocator().alloc(Sexp, n);
        self.bumpPos = end;
        return @as([*]Sexp, @ptrFromInt(start))[0..n];
    }

    const bumpVTable: std.mem.Allocator.VTable = .{
        .alloc = bumpAlloc,
        .resize = bumpResize,
        .remap = bumpRemap,
        .free = bumpFree,
    };

    /// Chunks grow from `bumpFirst` to `bumpLast` bytes; a request larger
    /// than `bumpLast / 4` goes to the arena by itself.
    const bumpFirst = 4096;
    const bumpLast = 1 << 20;

    fn bumpAlloc(ctx: *anyopaque, len: usize, alignment: std.mem.Alignment, ra: usize) ?[*]u8 {
        const self: *BaseParser = @ptrCast(@alignCast(ctx));
        const start = alignment.forward(self.bumpPos);
        if (start + len <= self.bumpEnd) {
            self.bumpPos = start + len;
            return @ptrFromInt(start);
        }
        return self.bumpRefill(len, alignment, ra);
    }

    fn bumpRefill(self: *BaseParser, len: usize, alignment: std.mem.Alignment, ra: usize) ?[*]u8 {
        const arena = self.arena.allocator();
        if (len > bumpLast / 4) return arena.rawAlloc(len, alignment, ra);
        const size = @max(self.bumpNext, len + alignment.toByteUnits());
        const chunk = arena.rawAlloc(size, .@"16", ra) orelse return null;
        self.bumpNext = @min(size * 2, bumpLast);
        const start = alignment.forward(@intFromPtr(chunk));
        self.bumpPos = start + len;
        self.bumpEnd = @intFromPtr(chunk) + size;
        return @ptrFromInt(start);
    }

    /// The last allocation grows or shrinks in place; any other only
    /// shrinks.
    fn bumpResize(ctx: *anyopaque, memory: []u8, _: std.mem.Alignment, new_len: usize, _: usize) bool {
        const self: *BaseParser = @ptrCast(@alignCast(ctx));
        const start = @intFromPtr(memory.ptr);
        if (start + memory.len != self.bumpPos) return new_len <= memory.len;
        if (start + new_len > self.bumpEnd) return false;
        self.bumpPos = start + new_len;
        return true;
    }

    fn bumpRemap(ctx: *anyopaque, memory: []u8, alignment: std.mem.Alignment, new_len: usize, ra: usize) ?[*]u8 {
        return if (bumpResize(ctx, memory, alignment, new_len, ra)) memory.ptr else null;
    }

    fn bumpFree(ctx: *anyopaque, memory: []u8, _: std.mem.Alignment, _: usize) void {
        const self: *BaseParser = @ptrCast(@alignCast(ctx));
        const start = @intFromPtr(memory.ptr);
        if (start + memory.len == self.bumpPos) self.bumpPos = start;
    }

    pub fn parseProgram(self: *BaseParser) !Sexp {
        return self.parse(.@"program");
    }

    pub fn parseForm(self: *BaseParser) !Sexp {
        return self.parse(.@"form");
    }


    /// Parse the whole input as `start`. The state, the current token's
    /// symbol and the next action live in locals: the symbol changes only
    /// when a token is shifted, except that `@as` promotion depends on the
    /// state, so a promotable token is promoted again after each
    /// reduction. A run of pass-throughs (an operand climbing a chain of
    /// `A → B` rules) keeps the state below it and writes the stack once.
    pub fn parse(self: *BaseParser, start: Start) !Sexp {
        try self.begin(start);
        // The start marker, which the start state shifts before any input.
        if (self.injectedToken) |marker| try self.shift(@intCast(getAction(self.stateStack.last().?, marker)));
        var state = self.stateStack.last().?;
        var raw = tokenToSymbol(self.current);
        var sym = self.promoted(raw);
        var action = self.strictAction(state, sym);
        while (true) {
            if (action > 0) {
                state = @intCast(action);
                try self.shiftToken(state);
                raw = tokenToSymbol(self.current);
                sym = self.promoted(raw);
                action = self.strictAction(state, sym);
            } else if (action < -1) {
                var rule: u16 = @intCast(-action - 2);
                if (isPassThrough(rule) and !(asGroups > 0 and raw == needsPromotion)) {
                    const states = self.stateStack.items;
                    const below = states[states.len - 2];
                    while (true) {
                        state = @intCast(getAction(below, ruleLhs[rule]));
                        action = self.strictAction(state, sym);
                        if (action >= -1) break;
                        rule = @intCast(-action - 2);
                        if (!isPassThrough(rule)) break;
                    }
                    states[states.len - 1] = state;
                } else {
                    state = try self.reduceOrPass(rule);
                    if (asGroups > 0 and raw == needsPromotion) sym = self.promoted(raw);
                    action = self.strictAction(state, sym);
                }
            } else if (action == -1) {
                return self.valueStack.last().?;
            } else {
                self.recordFailure(state, sym);
                return error.ParseError;
            }
        }
    }

    /// The symbol of the current token, `raw` from `tokenToSymbol`, after
    /// `@as` promotion in the current state.
    inline fn promoted(self: *BaseParser, raw: u16) u16 {
        if (asGroups > 0 and raw == needsPromotion) return promote(self, self.current);
        return raw;
    }

    /// Parse `start`, repairing syntax errors for an editor: the parse goes
    /// on past an error with the tree built the normal way. The rules:
    ///
    ///   1. The first error is recorded exactly as the strict parse reports
    ///      it (token, state, expected set); repairs never replace it, and a
    ///      repaired parse still returns it: recovery is not acceptance.
    ///   2. Only tokens the grammar declares in `@repair` are ever inserted,
    ///      as zero-width tokens at the offending token, taken from the
    ///      state's generated candidate list (holes, then structure; fewer
    ///      further fabrications first).
    ///   3. What the offending token admits: end of input and structure
    ///      tokens (lexer scaffolding) admit any candidate; real input
    ///      admits only a `terminator` (a statement boundary splits what
    ///      the user wrote without inventing meaning in front of it: no
    ///      holes, no block structure before real code).
    ///   4. An insertion must let the offending token be consumed (shifted,
    ///      or accepted at end of input). At end of input or a structure
    ///      token, when none does, a candidate the state can shift is
    ///      inserted anyway, so several insertions can complete an
    ///      unfinished construct. Since the last token was consumed, the
    ///      same token is inserted in the same state again only on a
    ///      shallower stack: a repeat at the same depth is a cycle, and one
    ///      on a deeper stack only nests the construct further.
    ///   5. With no admissible insertion the offending token is deleted,
    ///      except end of input, which is never deleted: the parse ends
    ///      there, incomplete.
    ///   6. At most `budget` repairs (insertions plus deletions); when they
    ///      are spent the parse ends, incomplete.
    ///
    /// Strict parsing (`parse`) is a separate entry point and pays nothing.
    pub fn parseTolerant(self: *BaseParser, start: Start, budget: u32) !Tolerant {
        if (!hasRepair) @compileError("parseTolerant needs a @repair section in the grammar");
        try self.begin(start);
        var result: Tolerant = .{ .sexp = .nil, .failure = null, .repairs = 0, .complete = false };
        // Configurations repaired since the last consumed token (rule 4).
        var tried: std.ArrayList(RepairKey) = .empty;
        while (true) {
            const state = self.stateStack.last().?;
            const sym = self.lookahead();
            const action = self.actionFor(state, sym);
            if (action > 0) {
                if (self.pendingInsert == null and self.injectedToken == null) tried.clearRetainingCapacity();
                try self.shift(@intCast(action));
            } else if (action < -1) {
                _ = try self.reduceOrPass(@intCast(-action - 2));
            } else if (action == -1) {
                result.sexp = self.valueStack.last().?;
                result.complete = true;
                break;
            } else {
                // An inserted token is always acceptable (rule 4).
                std.debug.assert(self.pendingInsert == null);
                if (self.failure == null) self.recordFailure(state, sym);
                if (result.repairs == budget) break;
                if (try self.chooseInsertion(sym, tried.items)) |token| {
                    try tried.append(self.allocator(), .{ .depth = @intCast(self.stateStack.items.len), .state = state, .token = token });
                    self.pendingInsert = token;
                    result.insertions += 1;
                } else if (sym == endSymbol) {
                    break;
                } else {
                    try self.deleteToken();
                    tried.clearRetainingCapacity();
                    result.deletions += 1;
                }
                result.repairs += 1;
            }
        }
        result.failure = self.failure;
        return result;
    }

    const RepairKey = struct { depth: u32, state: u16, token: u16 };

    /// The insertion rules 3 and 4 allow before `next`, best first; null
    /// when there is none. An insertion already tried in this state, at
    /// this depth or above, since the last consumed token is not repeated.
    fn chooseInsertion(self: *BaseParser, next: u16, tried: []const RepairKey) !?u16 {
        const state = self.stateStack.last().?;
        const nextClass = if (next == endSymbol) RepairClass.structure else repairClass(next);
        const real = nextClass == .none or nextClass == .hole;
        const depth: u32 = @intCast(self.stateStack.items.len);
        for (repairCandidates(state)) |candidate| {
            if (real and repairClass(candidate) != .terminator) continue;
            if (!wasTried(tried, depth, state, candidate) and try self.accepts(candidate, next)) return candidate;
        }
        if (real) return null;
        for (repairCandidates(state)) |candidate| {
            if (!wasTried(tried, depth, state, candidate) and try self.accepts(candidate, null)) return candidate;
        }
        return null;
    }

    fn wasTried(tried: []const RepairKey, depth: u32, state: u16, token: u16) bool {
        for (tried) |k| if (k.depth <= depth and k.state == state and k.token == token) return true;
        return false;
    }

    fn begin(self: *BaseParser, start: Start) !void {
        // Token positions are u32.
        if (self.source.len > std.math.maxInt(u32)) return error.InputTooLarge;
        // Every parse reads the input from the start (a parser may parse
        // again, e.g. tolerantly after a failed strict parse). Node ids
        // keep counting, so earlier trees stay valid.
        if (self.started) {
            self.lexer = Lexer.init(self.source);
            self.setCurrent(self.lexer.next());
            self.lastMatchedId = 0;
            self.triviaTokens.clearRetainingCapacity();
        }
        self.started = true;
        @memset(self.spares, .none);
        self.stateStack.clearRetainingCapacity();
        self.valueStack.clearRetainingCapacity();
        self.failure = null;
        self.pendingInsert = null;
        self.outOfMemory = false;
        try self.stateStack.append(self.allocator(), startState(start));
        if (nodeStore) self.lastEnd = 0;
        self.injectedToken = startMarker(start);
        try self.ensureNodeStore();
        if (hasTrivia) try self.skipTrivia();
    }

    inline fn lookahead(self: *BaseParser) u16 {
        if (self.injectedToken) |marker| return marker;
        if (self.pendingInsert) |token| return token;
        const sym = tokenToSymbol(self.current);
        if (asGroups > 0 and sym == needsPromotion) return promote(self, self.current);
        return sym;
    }

    /// Make `tok` the current token (forgetting the keyword lookups of the
    /// one before).
    inline fn setCurrent(self: *BaseParser, tok: Token) void {
        self.current = tok;
        if (asGroups > 0) self.keywordIds = @splat(0);
    }

    /// `@as` promotion of the current token, `text`, to one group: the
    /// group's symbol for the keyword, else the group's fallback symbol,
    /// when the state takes it (with any action when `permissive`, else by
    /// a shift). The keyword's ordinal becomes the leaf's id. (A
    /// non-exhaustive Id enum may give an ordinal past the map: it has no
    /// symbol of its own.)
    inline fn tryPromote(
        self: *BaseParser,
        comptime group: usize,
        text: []const u8,
        comptime lookup: anytype,
        comptime toSymbol: []const u16,
        comptime fallback: u16,
        comptime permissive: bool,
    ) ?u16 {
        const id = self.keywordId(group, text, lookup) orelse return null;
        const state = self.stateStack.last().?;
        for ([_]u16{ if (id < toSymbol.len) toSymbol[id] else 0, fallback }) |sym| {
            if (sym == 0) continue;
            const action = getAction(state, sym);
            if (if (permissive) action != 0 else action > 0) {
                self.lastMatchedId = id;
                return sym;
            }
        }
        return null;
    }

    /// The ordinal `lookup` gives the current token's `text` in `group`,
    /// looked up once per token.
    inline fn keywordId(self: *BaseParser, comptime group: usize, text: []const u8, comptime lookup: anytype) ?u16 {
        const known = self.keywordIds[group];
        if (known != 0) return if (known == noKeyword) null else @intCast(known - 1);
        const id: ?u16 = if (lookup(text)) |k| @backingInt(k) else null;
        self.keywordIds[group] = if (id) |i| @as(u32, i) + 1 else noKeyword;
        return id;
    }

    const noKeyword = std.math.maxInt(u32);

    /// The table action, with the `X "c"` override: when the table reduces
    /// on the hinted token and it touches the previous token, shift
    /// instead. (Never for a start marker or an inserted token.)
    inline fn actionFor(self: *const BaseParser, state: u16, sym: u16) i16 {
        const action = getAction(state, sym);
        if (xExcludes.len > 0 and action == hinted)
            return hintedAction(state, sym, self.current.pre == 0 and self.pendingInsert == null and self.injectedToken == null);
        return action;
    }

    /// `actionFor` on a token of the input.
    inline fn strictAction(self: *const BaseParser, state: u16, sym: u16) i16 {
        const action = getAction(state, sym);
        if (xExcludes.len > 0 and action == hinted) return hintedAction(state, sym, self.current.pre == 0);
        return action;
    }

    fn shift(self: *BaseParser, target: u16) !void {
        if (self.injectedToken != null) {
            try self.pushEntry(target, .nil, self.current.pos, self.lastEnd);
            self.injectedToken = null;
        } else if (self.pendingInsert != null) {
            const pos = self.current.pos;
            try self.pushEntry(target, .{ .src = .{ .pos = pos, .len = 0, .id = 0 } }, pos, pos);
            if (nodeStore) self.lastEnd = pos;
            self.pendingInsert = null;
        } else try self.shiftToken(target);
    }

    /// Shift the current token, a token of the input.
    inline fn shiftToken(self: *BaseParser, target: u16) !void {
        const tok = self.current;
        // The lexer's id is taken even when an `@as` ordinal replaces it,
        // so it never reaches the next token.
        const lexerId = takeLexerId(&self.lexer);
        const id = if (asGroups > 0 and self.lastMatchedId != 0) self.lastMatchedId else lexerId;
        if (asGroups > 0) self.lastMatchedId = 0;
        const end = tok.pos + tok.len;
        try self.pushEntry(target, .{ .src = .{ .pos = tok.pos, .len = tok.len, .id = id } }, tok.pos, end);
        if (nodeStore) self.lastEnd = end;
        try self.advance();
    }

    /// Push a state, its value, and (with a node store) where the value
    /// starts and ends. The stacks grow together: the state stack is always
    /// one longer than the others, so one capacity check covers them all.
    inline fn pushEntry(self: *BaseParser, state: u16, value: Sexp, start: u32, end: u32) !void {
        const n = self.valueStack.items.len;
        if (n == self.valueStack.capacity) try self.growStacks();
        self.valueStack.items.len = n + 1;
        self.valueStack.items[n] = value;
        self.stateStack.items.len = n + 2;
        self.stateStack.items[n + 1] = state;
        if (nodeStore) self.starts[n] = start;
        if (elemEnds) self.ends[n] = end;
    }

    fn growStacks(self: *BaseParser) !void {
        const a = self.allocator();
        try self.valueStack.ensureUnusedCapacity(a, 1);
        const capacity = self.valueStack.capacity;
        try self.stateStack.ensureTotalCapacity(a, capacity + 1);
        if (nodeStore) self.starts = try a.realloc(self.starts, capacity);
        if (elemEnds) self.ends = try a.realloc(self.ends, capacity);
        const old = self.spares.len;
        self.spares = try a.realloc(self.spares, capacity);
        @memset(self.spares[old..], .none);
    }

    /// The value-stack index of `pass[0]`, the first element of the
    /// reduction in progress.
    fn stackIndex(self: *const BaseParser, pass: []const Sexp) usize {
        return (@intFromPtr(pass.ptr) - @intFromPtr(self.valueStack.items.ptr)) / @sizeOf(Sexp);
    }

    /// Reduce by `ruleId`. A pass-through `A → B` (the value of its one
    /// element) only replaces the top state with the goto on A: the value,
    /// its start and end, and its spare stay; it builds no node, so it
    /// places no empty element and records no side-band role.
    /// It returns the new top state.
    inline fn reduceOrPass(self: *BaseParser, ruleId: u16) !u16 {
        if (isPassThrough(ruleId)) {
            const states = self.stateStack.items;
            const next = getAction(states[states.len - 2], ruleLhs[ruleId]);
            std.debug.assert(next > 0); // every reduction has a goto
            states[states.len - 1] = @intCast(next);
            return @intCast(next);
        }
        try self.reduce(ruleId);
        return self.stateStack.items[self.stateStack.items.len - 1];
    }

    fn reduce(self: *BaseParser, ruleId: u16) !void {
        const len = ruleLen[ruleId];
        const base = self.valueStack.items.len - len;
        const top = self.stateStack.items.len - len;

        if (nodeStore) {
            // An element that consumed nothing starts at the next token,
            // past the blanks after this reduction's last token (lastEnd).
            // When the reduction consumed something, place its trailing
            // empty elements at lastEnd so that spans nest.
            if (len > 0 and self.starts[base] < self.lastEnd) {
                var k = base + len;
                while (k > base and self.starts[k - 1] > self.lastEnd) : (k -= 1) {
                    self.starts[k - 1] = self.lastEnd;
                    self.placeEmpty(self.valueStack.items[k - 1], self.lastEnd);
                }
            }
            self.reduction.rule = ruleId;
            self.reduction.start = if (len > 0) self.starts[base] else self.current.pos;
            if (elemEnds) {
                self.reduction.base = @intCast(base);
                self.reduction.firstNode = self.nodes.len;
            }
        }

        // The action reads its elements in place on the value stack; the
        // result then replaces them (a reduction of nothing pushes it). A
        // rule whose value is nil or one of its elements has no action.
        // A list passed on keeps its spare, to grow in place in the rule
        // that extends it.
        const result: Sexp = switch (ruleValue[ruleId]) {
            0 => executeAction(self, ruleId, self.valueStack.items[base..]),
            1 => .nil,
            else => |n| blk: {
                if (n > 2) {
                    self.spares[base] = self.spares[base + n - 2];
                    self.spares[base + n - 2] = .none;
                }
                break :blk self.valueStack.items[base + n - 2];
            },
        };
        if (self.outOfMemory) return error.OutOfMemory;
        const next = getAction(self.stateStack.items[top - 1], ruleLhs[ruleId]);
        std.debug.assert(next > 0); // every reduction has a goto

        if (nodeStore) try self.recordSides(ruleId, result);
        if (len > 0) {
            self.valueStack.items.len = base + 1;
            self.valueStack.items[base] = result;
            self.stateStack.items.len = top + 1;
            self.stateStack.items[top] = @intCast(next);
            // starts[base] already holds the reduction's start (its first
            // element's).
            if (elemEnds) self.ends[base] = self.lastEnd;
        } else {
            try self.pushEntry(@intCast(next), result, self.reduction.start, self.lastEnd);
        }
    }

    /// Move the nodes of an empty value (a subtree that consumed nothing)
    /// to `at`.
    fn placeEmpty(self: *BaseParser, value: Sexp, at: u32) void {
        // Most empty values are leaves or flat lists: no walk.
        if (!self.placeNode(value, at)) return;
        for (value.list.items()) |item| {
            if (item == .list) break;
        } else return;
        var walk: Walk = .{};
        defer walk.deinit();
        var s = value;
        while (true) {
            if (self.placeNode(s, at)) walk.push(s.list.items()) catch {
                self.outOfMemory = true;
                return;
            };
            s = walk.next() orelse return;
        }
    }

    /// Place an empty list's node at `at`; whether its items need placing
    /// too (false for a non-list, or a node already placed).
    inline fn placeNode(self: *BaseParser, s: Sexp, at: u32) bool {
        if (s != .list) return false;
        const id = s.list.id;
        if (id != 0 and id < self.nodes.len) {
            const info = self.nodes.at(id);
            if (!info.span.isEmpty()) return false;
            info.span = .{ .start = at, .end = at };
        }
        return true;
    }

    /// Fetch the next token, moving trivia to the trivia channel.
    fn advance(self: *BaseParser) !void {
        self.setCurrent(self.lexer.next());
        if (hasTrivia) try self.skipTrivia();
    }

    /// Drop the current token, and its lexer id with it.
    fn deleteToken(self: *BaseParser) !void {
        _ = takeLexerId(&self.lexer);
        try self.advance();
    }

    fn skipTrivia(self: *BaseParser) !void {
        while (isTrivia(self.current.cat)) {
            try self.triviaTokens.append(self.allocator(), self.current);
            _ = takeLexerId(&self.lexer);
            self.setCurrent(self.lexer.next());
        }
    }

    /// Tokens of the grammar's `@trivia` kinds, in source order.
    pub fn trivia(self: *const BaseParser) []const Token {
        return self.triviaTokens.items;
    }

    // -------------------------------------------------------------------------
    // Node store, spans, side-band roles
    // -------------------------------------------------------------------------

    /// The span of the reduction in progress.
    inline fn reductionSpan(self: *const BaseParser) Span {
        return spanOf(.{ .start = self.reduction.start, .end = self.lastEnd });
    }

    /// The span of an extent: empty at its start when it consumed no
    /// tokens.
    fn spanOf(extent: Span) Span {
        return if (extent.start < extent.end) extent else .{ .start = extent.start, .end = extent.start };
    }

    /// The extent of elements lo..hi (0-based, inclusive) of the reduction.
    fn elemsExtent(self: *const BaseParser, lo: usize, hi: usize) Span {
        if (!elemEnds) @compileError("element extents need elemEnds");
        const base = self.reduction.base;
        return .{ .start = self.starts[base + lo], .end = self.ends[base + hi] };
    }

    /// A new node id for a list the current reduction builds.
    inline fn newNodeId(self: *BaseParser) NodeId {
        if (!nodeStore) return 0;
        return self.addNode(self.reductionSpan());
    }

    inline fn addNode(self: *BaseParser, extent: Span) NodeId {
        return self.nodes.add(self.allocator(), .{ .span = extent, .rule = self.reduction.rule }) catch {
            self.outOfMemory = true;
            return 0;
        };
    }

    fn recordSides(self: *BaseParser, ruleId: u16, result: Sexp) !void {
        if (!elemEnds) return;
        const labels = ruleSideLabels(ruleId);
        if (labels.len == 0 or result != .list) return;
        const id = result.list.id;
        if (id == 0 or id < self.reduction.firstNode) return;
        for (labels) |label| {
            try self.sides.append(self.allocator(), .{
                .node = id,
                .role = label.role,
                .span = spanOf(self.elemsExtent(label.pass, label.pass)),
            });
        }
    }

    /// Source span of a value. Leaves span their token. A list with a node
    /// id spans its reduction: first to last consumed token, including
    /// tokens (keywords, punctuation) that are not in the tree. Any other
    /// list spans the hull of its children: from the least start to the
    /// greatest end of the non-empty spans below it, whatever order an
    /// action put them in. Panics if the walk runs out of memory (its stack
    /// is far smaller than the tree it walks).
    pub fn span(self: *const BaseParser, s: Sexp) Span {
        if (self.ownSpan(s)) |own| return own;
        var hull: ?Span = null;
        var walk: Walk = .{};
        defer walk.deinit();
        var x = s;
        while (true) {
            if (self.ownSpan(x)) |own| {
                if (!own.isEmpty()) hull = if (hull) |h| .{ .start = @min(h.start, own.start), .end = @max(h.end, own.end) } else own;
            } else walk.push(x.list.items()) catch @panic("out of memory");
            x = walk.next() orelse return hull orelse .empty;
        }
    }

    /// The span of a value that is not a hull: a leaf's, a node's, empty
    /// for any other non-list; null for a list without a node id.
    fn ownSpan(self: *const BaseParser, s: Sexp) ?Span {
        return switch (s) {
            .src => |x| .{ .start = x.pos, .end = x.pos + x.len },
            .list => |l| if (nodeStore and l.id != 0 and l.id < self.nodes.len) self.nodes.at(l.id).span else null,
            else => .empty,
        };
    }

    /// The rule that built a list node (null without a node id, or for a
    /// node a lang wrapper made with `newNode`).
    pub fn ruleOf(self: *const BaseParser, s: Sexp) ?u16 {
        if (!nodeStore or s != .list) return null;
        const id = s.list.id;
        if (id == 0 or id >= self.nodes.len) return null;
        const rule = self.nodes.at(id).rule;
        return if (rule == wrapperRule) null else rule;
    }

    /// The rule recorded for nodes built outside a reduction.
    const wrapperRule = std.math.maxInt(u16);

    /// A `(tag children...)` node built outside a reduction, e.g. by a lang
    /// `Parser` wrapper for an `@wrapper` kind: allocated in the parser's
    /// arena, with a fresh node id recording `extent` as its span (so
    /// `span`, facts and `ir` accessors work as for parsed nodes; `ruleOf`
    /// is null). Without a node store the node has no id.
    pub fn newNode(self: *BaseParser, tag: Tag, children: []const Sexp, extent: Span) !Sexp {
        const out = try self.allocItems(children.len + 1);
        out[0] = .{ .tag = tag };
        @memcpy(out[1..], children);
        return .{ .list = List.withId(out, try self.wrapperNodeId(extent)) };
    }

    /// An untagged list built outside a reduction (a `group` value), with a
    /// node id recording `extent` like `newNode`.
    pub fn newList(self: *BaseParser, items: []const Sexp, extent: Span) !Sexp {
        const out = try self.allocator().dupe(Sexp, items);
        return .{ .list = List.withId(out, try self.wrapperNodeId(extent)) };
    }

    fn wrapperNodeId(self: *BaseParser, extent: Span) !NodeId {
        if (!nodeStore) return 0;
        try self.ensureNodeStore();
        return self.nodes.add(self.allocator(), .{ .span = extent, .rule = wrapperRule });
    }

    /// Start the node store with its unused entry 0 (node ids are 1-based).
    fn ensureNodeStore(self: *BaseParser) !void {
        if (nodeStore and self.nodes.len == 0) _ = try self.nodes.add(self.allocator(), .{ .span = .empty, .rule = 0 });
    }

    /// Number of node ids in use (ids run 1 .. nodeCount()).
    pub fn nodeCount(self: *const BaseParser) u32 {
        return self.nodes.len -| 1;
    }

    /// The side-band roles recorded for node `id`.
    fn sidesOf(self: *const BaseParser, id: NodeId) []const SideEntry {
        const all = self.sides.items;
        var lo: usize = 0;
        var hi: usize = all.len;
        while (lo < hi) {
            const mid = (lo + hi) / 2;
            if (all[mid].node < id) lo = mid + 1 else hi = mid;
        }
        var end = lo;
        while (end < all.len and all[end].node == id) end += 1;
        return all[lo..end];
    }

    /// The span a side-band role of `s` recorded (e.g. the `=` of a `set`).
    pub fn sideRole(self: *const BaseParser, s: Sexp, role: Role) ?Span {
        if (s != .list or s.list.id == 0) return null;
        for (self.sidesOf(s.list.id)) |e| if (e.role == role) return e.span;
        return null;
    }

    // -------------------------------------------------------------------------
    // Tree builders (called by the generated actions)
    // -------------------------------------------------------------------------

    /// Record an allocation failure; the reduction then fails the parse.
    fn oomNil(self: *BaseParser) Sexp {
        self.outOfMemory = true;
        return .nil;
    }

    /// Whether an untagged list can reach the tree (and so gets a node id)
    /// or is only ever spread into another list (plumbing: no node id).
    /// The generator decides per rule (see codegen/actions.zig).
    const ListUse = enum { tree, spread };

    /// A list node of the current reduction over freshly built `items`.
    inline fn node(self: *BaseParser, items: []const Sexp, comptime use: ListUse) Sexp {
        return .{ .list = List.withId(items, if (use == .tree) self.newNodeId() else 0) };
    }

    /// A list node over exactly `items` (fixed positions).
    fn build(self: *BaseParser, items: []const Sexp, comptime use: ListUse) Sexp {
        const out = self.allocItems(items.len) catch return self.oomNil();
        @memcpy(out, items);
        return self.node(out, use);
    }

    /// A nested node of the current reduction: its span covers just the
    /// elements lo..hi (0-based, inclusive) it references.
    fn nested(self: *BaseParser, s: Sexp, lo: usize, hi: usize) Sexp {
        if (nodeStore and s == .list and s.list.id != 0) {
            self.nodes.at(s.list.id).span = spanOf(self.elemsExtent(lo, hi));
        }
        return s;
    }

    /// A nested node that references no elements: empty, at the start of
    /// the reduction.
    fn nestedEmpty(self: *BaseParser, s: Sexp) Sexp {
        if (nodeStore and s == .list and s.list.id != 0) {
            const at = self.reduction.start;
            self.nodes.at(s.list.id).span = .{ .start = at, .end = at };
        }
        return s;
    }

    /// Length of `items` without trailing nils (all of it when positions
    /// are fixed by a schema).
    fn trimmedLen(items: []const Sexp) usize {
        var len = items.len;
        if (!keepTrailingNils) {
            while (len > 0 and items[len - 1] == .nil) len -= 1;
        }
        return len;
    }

    /// `~N` of an element that is no leaf: an empty leaf where element `i`
    /// starts. Without a node store element starts are not kept: it is
    /// placed at the first element from `i` on that spans something, else
    /// at the next token.
    fn emptyLeaf(self: *BaseParser, pass: []const Sexp, i: usize) Sexp {
        const pos = if (nodeStore)
            self.starts[self.stackIndex(pass) + i]
        else for (pass[i..]) |e| {
            const s = self.span(e);
            if (!s.isEmpty()) break s.start;
        } else self.current.pos;
        return .{ .src = .{ .pos = pos, .len = 0, .id = 0 } };
    }

    /// `()`: an empty list.
    fn emptyList(self: *BaseParser, comptime use: ListUse) Sexp {
        return self.node(&.{}, use);
    }

    /// `[head, ...tail]`
    fn spreadList(self: *BaseParser, head: Sexp, tail: Sexp, comptime use: ListUse) Sexp {
        const rest = tail.items();
        const out = self.allocItems(rest.len + 1) catch return self.oomNil();
        out[0] = head;
        @memcpy(out[1..], rest);
        return self.node(out, use);
    }

    /// A list `extendBy` opened for an action that appends to it.
    const Extension = struct { items: [*]Sexp, len: usize, capacity: usize };

    /// Open a list holding the items of element `n` (a list, else nothing)
    /// with room for `extra` more. A list `keepExtended` left on the value
    /// stack is reused with its spare capacity, growing in place when it
    /// is the allocator's last block, so a left-recursive list grows in
    /// amortized O(1) per element; it keeps its node id.
    fn extendBy(self: *BaseParser, pass: []const Sexp, n: usize, extra: usize) error{OutOfMemory}!Extension {
        const base = pass[n];
        const items: []const Sexp = if (base == .list) base.list.items() else &.{};
        const need = items.len + extra;
        const spare = &self.spares[self.stackIndex(pass) + n];
        if (items.len > 0 and spare.items == items.ptr and spare.len == items.len) {
            const buf: [*]Sexp = @constCast(items.ptr);
            const capacity = spare.capacity;
            spare.* = .none;
            if (need <= capacity) return .{ .items = buf, .len = items.len, .capacity = capacity };
            const start = @intFromPtr(buf);
            const grown = growCapacity(capacity, need);
            if (start + capacity * @sizeOf(Sexp) == self.bumpPos and start + grown * @sizeOf(Sexp) <= self.bumpEnd) {
                self.bumpPos = start + grown * @sizeOf(Sexp);
                return .{ .items = buf, .len = items.len, .capacity = grown };
            }
        }
        const capacity = growCapacity(0, need);
        const out = try self.allocItems(capacity);
        @memcpy(out[0..items.len], items);
        return .{ .items = out.ptr, .len = items.len, .capacity = capacity };
    }

    /// A capacity of at least `need`, grown from `capacity` by half plus 2.
    fn growCapacity(capacity: usize, need: usize) usize {
        var c = capacity;
        while (c < need) c += c / 2 + 2;
        return c;
    }

    /// Finish a list from `extendBy(pass, n, ...)` holding `len` items,
    /// without its trailing nils unless `keepNils` (a list of one item per
    /// element: `X*`, `L(X?)`, ...), recording its spare capacity where
    /// the reduction's value goes. It takes over the node id of element
    /// `n` (still on the value stack), so that nested extensions each keep
    /// their own.
    fn keepExtended(self: *BaseParser, out: Extension, len: usize, pass: []const Sexp, n: usize, comptime use: ListUse, comptime keepNils: bool) Sexp {
        const items = if (keepNils) out.items[0..len] else out.items[0..trimmedLen(out.items[0..len])];
        self.spares[self.stackIndex(pass)] = .{ .items = items.ptr, .len = @intCast(items.len), .capacity = @intCast(out.capacity) };
        var id: NodeId = 0;
        if (nodeStore and use == .tree) {
            const base = pass[n];
            id = if (base == .list) base.list.id else 0;
            if (id != 0) {
                self.nodes.at(id).* = .{ .span = self.reductionSpan(), .rule = self.reduction.rule };
            } else id = self.newNodeId();
        }
        return .{ .list = List.withId(items, id) };
    }

    /// Finish a list allocated at its length and filled.
    fn finishItems(self: *BaseParser, out: []Sexp, comptime use: ListUse) Sexp {
        return self.node(out[0..trimmedLen(out)], use);
    }

    /// An item of a list an action builds from its elements alone.
    const Item = union(enum) { elem: u16, tag: Tag, nil };

    /// A list node over `items`, known at compile time (so each call
    /// stores its items directly); unless positions are fixed (`trim`
    /// false, or a schema), without its trailing nils.
    fn buildOf(self: *BaseParser, comptime items: []const Item, pass: []const Sexp, comptime use: ListUse, comptime trim: bool) Sexp {
        const out = self.allocItems(items.len) catch return self.oomNil();
        inline for (out[0..items.len], items) |*o, it| o.* = switch (it) {
            .elem => |i| pass[i],
            .tag => |t| .{ .tag = t },
            .nil => .nil,
        };
        return self.node(if (trim) out[0..trimmedLen(out)] else out, use);
    }

    /// `(tag items...)`
    fn sexp(self: *BaseParser, tag: Tag, items: []const Sexp) Sexp {
        const len = trimmedLen(items);
        const out = self.allocItems(len + 1) catch return self.oomNil();
        out[0] = .{ .tag = tag };
        @memcpy(out[1..], items[0..len]);
        return self.node(out, .tree);
    }

    /// `(tag ...spread)`
    fn sexpSpread(self: *BaseParser, tag: Tag, spread: Sexp) Sexp {
        return self.sexp(tag, spread.items());
    }

    /// `(tag pos ...spread)`; just `(tag)` when both are empty (and
    /// positions are not fixed by a schema).
    fn sexpPosSpread(self: *BaseParser, tag: Tag, pos: Sexp, spread: Sexp) Sexp {
        const items = spread.items();
        const len = trimmedLen(items);
        const bare = !keepTrailingNils and pos == .nil and len == 0;
        const out = self.allocItems(if (bare) 1 else len + 2) catch return self.oomNil();
        out[0] = .{ .tag = tag };
        if (!bare) {
            out[1] = pos;
            @memcpy(out[2..], items[0..len]);
        }
        return self.node(out, .tree);
    }

    // -------------------------------------------------------------------------
    // Diagnostics
    // -------------------------------------------------------------------------

    fn recordFailure(self: *BaseParser, state: u16, sym: u16) void {
        const tok = self.current;
        self.failure = .{
            .span = .{ .start = tok.pos, .end = tok.pos + tok.len },
            .symbol = sym,
            .cat = tok.cat,
            .state = state,
        };
    }

    /// The error of the last failed parse (the first one, for
    /// `parseTolerant`).
    pub fn lastError(self: *const BaseParser) ?Failure {
        return self.failure;
    }

    /// 1-based line and column of a byte offset.
    pub fn lineCol(self: *const BaseParser, pos: u32) struct { line: u32, col: u32 } {
        const end: usize = @min(pos, self.source.len);
        var line: u32 = 1;
        var lineStart: usize = 0;
        for (self.source[0..end], 0..) |c, i| {
            if (c == '\n') {
                line += 1;
                lineStart = i + 1;
            }
        }
        return .{ .line = line, .col = @intCast(end - lineStart + 1) };
    }

    /// `line:col: expected A, B or C, got D` for the last error.
    pub fn writeError(self: *const BaseParser, w: *std.Io.Writer) std.Io.Writer.Error!void {
        const f = self.failure orelse return;
        const at = self.lineCol(f.span.start);
        try w.print("{d}:{d}: expected ", .{ at.line, at.col });
        var buf: [maxExpected][]const u8 = undefined;
        const want = expectedNames(f.state, &buf);
        for (want, 0..) |name, i| {
            if (i > 0) try w.writeAll(if (i + 1 == want.len) " or " else ", ");
            try w.writeAll(name);
        }
        if (want.len == 0) try w.writeAll("nothing");
        try w.writeAll(", got ");
        const got = symbolName(f.symbol);
        try w.writeAll(if (f.symbol == errorSymbol or got.len == 0) @tagName(f.cat) else got);
    }

    /// `Parse error at ` and `writeError`'s text on standard error.
    pub fn printError(self: *const BaseParser) void {
        var buffer: [256]u8 = undefined;
        const stderr = std.debug.lockStderr(&buffer);
        defer std.debug.unlockStderr();
        const w = &stderr.file_writer.interface;
        w.writeAll("Parse error at ") catch return;
        self.writeError(w) catch return;
        w.writeByte('\n') catch return;
    }

    /// What `state` accepts, reader-named: the `@errors` rules it waits
    /// for, then the tokens none of them begins with.
    pub fn expected(state: u16) []const u16 {
        return expectedIn(state);
    }

    /// The reader names of what `state` accepts, in `expected` order, each
    /// once (tokens sharing an `@display` name are named once), in `buf`:
    /// `[maxExpected][]const u8` always has room.
    pub fn expectedNames(state: u16, buf: [][]const u8) []const []const u8 {
        var n: usize = 0;
        for (expectedIn(state)) |sym| {
            const name = symbolName(sym);
            if (name.len == 0) continue;
            for (buf[0..n]) |seen| {
                if (std.mem.eql(u8, seen, name)) break;
            } else {
                buf[n] = name;
                n += 1;
            }
        }
        return buf[0..n];
    }

    /// The reader-facing name of a grammar symbol, as `writeError` prints
    /// it: its `@errors` or `@display` name, a literal as written, a token
    /// name in lower case; empty for other rules.
    pub fn symbolText(sym: u16) []const u8 {
        return symbolName(sym);
    }

    // -------------------------------------------------------------------------
    // Tolerant repair
    // -------------------------------------------------------------------------

    /// Whether the inserted `insert`, then the current token as `current`
    /// (when given), can be consumed from the current state; `current` is
    /// decided as `actionFor` decides it, with its `X "c"` override (it
    /// keeps the symbol `@as` promoted it to here). The simulation leaves
    /// the state stack as it is: reductions pop the states it pushed
    /// (`scratch`), then hide states of the real stack (`depth` of them
    /// stay in view).
    fn accepts(self: *BaseParser, insert: u16, current: ?u16) !bool {
        const pushed = &self.scratch;
        pushed.clearRetainingCapacity();
        var depth = self.stateStack.items.len;
        for ([_]?u16{ insert, current }, 0..) |s, i| {
            const sym = s orelse break;
            while (true) {
                const top = pushed.last() orelse self.stateStack.items[depth - 1];
                var action = getAction(top, sym);
                if (xExcludes.len > 0 and action == hinted) action = hintedAction(top, sym, i == 1 and self.current.pre == 0);
                if (action == 0) return false;
                if (action == -1) return true;
                if (action > 0) {
                    try pushed.append(self.allocator(), @intCast(action));
                    break;
                }
                const rule: u16 = @intCast(-action - 2);
                const fromPushed = @min(ruleLen[rule], pushed.items.len);
                pushed.shrinkRetainingCapacity(pushed.items.len - fromPushed);
                depth -= ruleLen[rule] - fromPushed;
                const next = getAction(pushed.last() orelse self.stateStack.items[depth - 1], ruleLhs[rule]);
                if (next <= 0) return false;
                try pushed.append(self.allocator(), @intCast(next));
            }
        }
        return true;
    }

    // -------------------------------------------------------------------------
    // Facts export
    // -------------------------------------------------------------------------

    /// Write the tree as flat facts, one per line, in pre-order:
    ///   (node ID KIND START END)        every list with a node id
    ///   (role ID ROLE CHILD...)         each non-nil child (a rest role
    ///                                   lists all its children)
    ///   (side ID ROLE START LEN)        each side-band role
    /// ROLE is the schema role name, else the child's index in the list.
    /// KIND is the head tag, or `group` for an untagged list. A CHILD is a
    /// node id, `leaf POS LEN`, `tag NAME`, `str "TEXT"`, or `(CHILD...)`
    /// for a list without a node id. error.WriteFailed also reports the
    /// walk running out of memory.
    pub fn writeFacts(self: *const BaseParser, w: *std.Io.Writer, root: Sexp) std.Io.Writer.Error!void {
        if (!nodeStore) @compileError("writeFacts needs the node store (@schema or --spans)");
        var walk: Walk = .{};
        defer walk.deinit();
        var s = root;
        while (true) {
            if (s == .list) {
                if (s.list.id != 0) try self.nodeFacts(w, s);
                walk.push(s.list.items()) catch return error.WriteFailed;
            }
            s = walk.next() orelse return;
        }
    }

    /// The facts of one node: its `node` line, its `role` and `side` lines.
    fn nodeFacts(self: *const BaseParser, w: *std.Io.Writer, s: Sexp) std.Io.Writer.Error!void {
        const l = s.list;
        const items = l.items();
        const k = s.kind();
        const sp = self.span(s);
        try w.print("(node {d} ", .{l.id});
        if (k) |t| try writeName(w, nameOf(t)) else try w.writeAll("group");
        try w.print(" {d} {d})\n", .{ sp.start, sp.end });
        var i: usize = if (k != null) 1 else 0;
        while (i < items.len) : (i += 1) {
            if (k) |t| if (restRoleOf(t)) |rest| if (i >= rest.slot) {
                try w.print("(role {d} ", .{l.id});
                try writeName(w, nameOf(rest.role));
                for (items[i..]) |child| {
                    try w.writeByte(' ');
                    try factChild(w, child);
                }
                try w.writeAll(")\n");
                break;
            };
            if (items[i] == .nil) continue;
            try w.print("(role {d} ", .{l.id});
            if (if (k) |t| roleAt(t, i) else null) |role| try writeName(w, nameOf(role)) else try w.print("{d}", .{i});
            try w.writeByte(' ');
            try factChild(w, items[i]);
            try w.writeAll(")\n");
        }
        for (self.sidesOf(l.id)) |e| {
            try w.print("(side {d} ", .{l.id});
            try writeName(w, nameOf(e.role));
            try w.print(" {d} {d})\n", .{ e.span.start, e.span.len() });
        }
    }

    fn factChild(w: *std.Io.Writer, s: Sexp) std.Io.Writer.Error!void {
        try writeNested(s, w, {}, factAtom);
    }

    fn factAtom(_: void, w: *std.Io.Writer, s: Sexp) std.Io.Writer.Error!?[]const Sexp {
        switch (s) {
            .nil => try w.writeAll("_"),
            .tag => |t| {
                try w.writeAll("tag ");
                try writeName(w, nameOf(t));
            },
            .src => |x| try w.print("leaf {d} {d}", .{ x.pos, x.len }),
            .str => |x| {
                try w.writeAll("str ");
                try writeQuoted(w, x);
            },
            .list => |l| if (l.id != 0) try w.print("{d}", .{l.id}) else return l.items(),
        }
        return null;
    }

    /// A name as a bare symbol, or quoted when it has s-expression syntax.
    fn writeName(w: *std.Io.Writer, name: []const u8) std.Io.Writer.Error!void {
        const plain = name.len > 0 and for (name) |c| {
            if (c <= ' ' or c == '(' or c == ')' or c == '"' or c == '\\' or c == 0x7f) break false;
        } else true;
        if (plain) try w.writeAll(name) else try writeQuoted(w, name);
    }

    fn writeQuoted(w: *std.Io.Writer, text: []const u8) std.Io.Writer.Error!void {
        try w.writeByte('"');
        for (text) |c| switch (c) {
            '"', '\\' => {
                try w.writeByte('\\');
                try w.writeByte(c);
            },
            '\n' => try w.writeAll("\\n"),
            '\t' => try w.writeAll("\\t"),
            else => if (c < ' ' or c == 0x7f) try w.print("\\x{x:0>2}", .{c}) else try w.writeByte(c),
        };
        try w.writeByte('"');
    }
};


// =============================================================================
// Grammar
// =============================================================================

/// Node spans and rule ids are recorded (`@schema` or `--spans`).
pub const nodeStore = false;
/// Element extents are kept for side-band labels and nested nodes.
const elemEnds = false;
/// Lists keep trailing nils: positions are fixed by the schema.
const keepTrailingNils = false;
const hasTrivia = false;
const hasRepair = false;
/// `@as` groups the promotable token may become (see `promote`).
const asGroups = 0;
const numSymbols = 36;
const endSymbol: u16 = 1;
const errorSymbol: u16 = 2;

inline fn tokenToSymbol(token: Token) u16 {
    return switch (token.cat) {
        .@"eof" => 1,
        .@"hash_discard" => 9,
        .@"integer" => 10,
        .@"real" => 11,
        .@"string" => 12,
        .@"regex" => 13,
        .@"char" => 14,
        .@"keyword" => 15,
        .@"ident" => 16,
        .@"lparen" => 17,
        .@"rparen" => 18,
        .@"lbracket" => 19,
        .@"rbracket" => 20,
        .@"lbrace" => 21,
        .@"rbrace" => 22,
        .@"hash_lbrace" => 23,
        .@"hash_lparen" => 24,
        .@"quote_tok" => 25,
        .@"syntax_quote_tok" => 26,
        .@"unquote_tok" => 27,
        .@"unquote_splicing_tok" => 28,
        .@"deref_tok" => 29,
        .@"var_quote_tok" => 30,
        .@"caret" => 31,
        else => 2, // error
    };
}

fn promote(_: *BaseParser, _: Token) u16 {
    unreachable; // no @as group
}

fn executeAction(self: *BaseParser, ruleId: u16, pass: []Sexp) Sexp {
    return switch (ruleId) {
        0 => self.sexpSpread(.@"program", pass[0]),
        2 => blk: { const out = self.extendBy(pass, 0, 1) catch break :blk self.oomNil(); var n = out.len; out.items[n] = pass[1]; n += 1; break :blk self.keepExtended(out, n, pass, 0, .spread, false); },
        4 => self.emptyList(.spread),
        8 => self.buildOf(&.{ .{ .tag = .@"int" }, .{ .elem = 0 } }, pass, .tree, true),
        9 => self.buildOf(&.{ .{ .tag = .@"real" }, .{ .elem = 0 } }, pass, .tree, true),
        10 => self.buildOf(&.{ .{ .tag = .@"string" }, .{ .elem = 0 } }, pass, .tree, true),
        11 => self.buildOf(&.{ .{ .tag = .@"regex" }, .{ .elem = 0 } }, pass, .tree, true),
        12 => self.buildOf(&.{ .{ .tag = .@"char" }, .{ .elem = 0 } }, pass, .tree, true),
        13 => self.buildOf(&.{ .{ .tag = .@"keyword" }, .{ .elem = 0 } }, pass, .tree, true),
        14 => self.buildOf(&.{ .{ .tag = .@"symbol" }, .{ .elem = 0 } }, pass, .tree, true),
        15 => blk: { const out = self.allocItems(3 + pass[1].items().len) catch break :blk self.oomNil(); var n: usize = 0; out[n] = .{ .tag = .@"list" }; n += 1; out[n] = pass[0]; n += 1; @memcpy(out[n..][0..pass[1].items().len], pass[1].items()); n += pass[1].items().len; out[n] = pass[2]; n += 1; break :blk self.finishItems(out, .tree); },
        16 => blk: { const out = self.allocItems(3 + pass[1].items().len) catch break :blk self.oomNil(); var n: usize = 0; out[n] = .{ .tag = .@"vector" }; n += 1; out[n] = pass[0]; n += 1; @memcpy(out[n..][0..pass[1].items().len], pass[1].items()); n += pass[1].items().len; out[n] = pass[2]; n += 1; break :blk self.finishItems(out, .tree); },
        17 => blk: { const out = self.allocItems(3 + pass[1].items().len) catch break :blk self.oomNil(); var n: usize = 0; out[n] = .{ .tag = .@"map" }; n += 1; out[n] = pass[0]; n += 1; @memcpy(out[n..][0..pass[1].items().len], pass[1].items()); n += pass[1].items().len; out[n] = pass[2]; n += 1; break :blk self.finishItems(out, .tree); },
        18 => blk: { const out = self.allocItems(3 + pass[1].items().len) catch break :blk self.oomNil(); var n: usize = 0; out[n] = .{ .tag = .@"set" }; n += 1; out[n] = pass[0]; n += 1; @memcpy(out[n..][0..pass[1].items().len], pass[1].items()); n += pass[1].items().len; out[n] = pass[2]; n += 1; break :blk self.finishItems(out, .tree); },
        19 => blk: { const out = self.allocItems(3 + pass[1].items().len) catch break :blk self.oomNil(); var n: usize = 0; out[n] = .{ .tag = .@"anon-fn" }; n += 1; out[n] = pass[0]; n += 1; @memcpy(out[n..][0..pass[1].items().len], pass[1].items()); n += pass[1].items().len; out[n] = pass[2]; n += 1; break :blk self.finishItems(out, .tree); },
        20 => self.buildOf(&.{ .{ .tag = .@"quote" }, .{ .elem = 0 }, .{ .elem = 2 } }, pass, .tree, true),
        21 => self.buildOf(&.{ .{ .tag = .@"syntax-quote" }, .{ .elem = 0 }, .{ .elem = 2 } }, pass, .tree, true),
        22 => self.buildOf(&.{ .{ .tag = .@"unquote" }, .{ .elem = 0 }, .{ .elem = 2 } }, pass, .tree, true),
        23 => self.buildOf(&.{ .{ .tag = .@"unquote-splicing" }, .{ .elem = 0 }, .{ .elem = 2 } }, pass, .tree, true),
        24 => self.buildOf(&.{ .{ .tag = .@"deref" }, .{ .elem = 0 }, .{ .elem = 2 } }, pass, .tree, true),
        25 => self.buildOf(&.{ .{ .tag = .@"var-quote" }, .{ .elem = 0 }, .{ .elem = 2 } }, pass, .tree, true),
        26 => self.buildOf(&.{ .{ .tag = .@"with-meta-raw" }, .{ .elem = 0 }, .{ .elem = 4 }, .{ .elem = 2 } }, pass, .tree, true),
        else => unreachable,
    };
}

const ruleLhs = [_]u16{ 3, 4, 5, 5, 5, 6, 6, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 33, 35 };
const ruleLen = [_]u8{ 1, 3, 2, 2, 0, 2, 0, 3, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 5, 3, 3 };
/// A rule's value: 0 = executeAction builds it, 1 = nil, n = element n - 2.
const ruleValue = [_]u8{ 0, 3, 0, 2, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };

// Parse table: 63 states x 36 symbols. 0 = error, > 0 = shift or
// goto, -1 = accept, <= -2 = reduce rule (-a - 2), -32768 = a
// reduction an `X "c"` hint overrides (`hinted`).
const parseTable = [_][numSymbols]i16{
    .{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0},
    .{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0},
    .{0,-6,0,4,0,5,0,0,0,-6,-6,-6,-6,-6,-6,-6,-6,-6,0,-6,0,-6,0,-6,-6,-6,-6,-6,-6,-6,-6,-6,0,0,0,0},
    .{0,0,0,0,6,0,7,0,0,-8,-8,-8,-8,-8,-8,-8,-8,-8,0,-8,0,-8,0,-8,-8,-8,-8,-8,-8,-8,-8,-8,0,0,0,0},
    .{0,-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
    .{0,-2,0,0,0,0,0,10,9,30,11,12,13,14,15,16,17,18,0,19,0,20,0,21,22,23,24,25,26,27,28,29,0,0,0,0},
    .{0,-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
    .{0,0,0,0,0,0,0,33,32,30,11,12,13,14,15,16,17,18,0,19,0,20,0,21,22,23,24,25,26,27,28,29,0,0,0,0},
    .{0,-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
    .{0,-4,0,0,0,0,0,0,0,-4,-4,-4,-4,-4,-4,-4,-4,-4,-4,-4,-4,-4,-4,-4,-4,-4,-4,-4,-4,-4,-4,-4,0,0,0,0},
    .{0,-5,0,0,0,0,0,0,0,-5,-5,-5,-5,-5,-5,-5,-5,-5,-5,-5,-5,-5,-5,-5,-5,-5,-5,-5,-5,-5,-5,-5,0,0,0,0},
    .{0,-10,0,0,0,0,0,0,0,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,0,0,0,0},
    .{0,-11,0,0,0,0,0,0,0,-11,-11,-11,-11,-11,-11,-11,-11,-11,-11,-11,-11,-11,-11,-11,-11,-11,-11,-11,-11,-11,-11,-11,0,0,0,0},
    .{0,-12,0,0,0,0,0,0,0,-12,-12,-12,-12,-12,-12,-12,-12,-12,-12,-12,-12,-12,-12,-12,-12,-12,-12,-12,-12,-12,-12,-12,0,0,0,0},
    .{0,-13,0,0,0,0,0,0,0,-13,-13,-13,-13,-13,-13,-13,-13,-13,-13,-13,-13,-13,-13,-13,-13,-13,-13,-13,-13,-13,-13,-13,0,0,0,0},
    .{0,-14,0,0,0,0,0,0,0,-14,-14,-14,-14,-14,-14,-14,-14,-14,-14,-14,-14,-14,-14,-14,-14,-14,-14,-14,-14,-14,-14,-14,0,0,0,0},
    .{0,-15,0,0,0,0,0,0,0,-15,-15,-15,-15,-15,-15,-15,-15,-15,-15,-15,-15,-15,-15,-15,-15,-15,-15,-15,-15,-15,-15,-15,0,0,0,0},
    .{0,-16,0,0,0,0,0,0,0,-16,-16,-16,-16,-16,-16,-16,-16,-16,-16,-16,-16,-16,-16,-16,-16,-16,-16,-16,-16,-16,-16,-16,0,0,0,0},
    .{0,0,0,0,0,34,0,0,0,-6,-6,-6,-6,-6,-6,-6,-6,-6,-6,-6,0,-6,0,-6,-6,-6,-6,-6,-6,-6,-6,-6,0,0,0,0},
    .{0,0,0,0,0,35,0,0,0,-6,-6,-6,-6,-6,-6,-6,-6,-6,0,-6,-6,-6,0,-6,-6,-6,-6,-6,-6,-6,-6,-6,0,0,0,0},
    .{0,0,0,0,0,36,0,0,0,-6,-6,-6,-6,-6,-6,-6,-6,-6,0,-6,0,-6,-6,-6,-6,-6,-6,-6,-6,-6,-6,-6,0,0,0,0},
    .{0,0,0,0,0,37,0,0,0,-6,-6,-6,-6,-6,-6,-6,-6,-6,0,-6,0,-6,-6,-6,-6,-6,-6,-6,-6,-6,-6,-6,0,0,0,0},
    .{0,0,0,0,0,38,0,0,0,-6,-6,-6,-6,-6,-6,-6,-6,-6,-6,-6,0,-6,0,-6,-6,-6,-6,-6,-6,-6,-6,-6,0,0,0,0},
    .{0,0,0,0,0,0,39,0,0,-8,-8,-8,-8,-8,-8,-8,-8,-8,0,-8,0,-8,0,-8,-8,-8,-8,-8,-8,-8,-8,-8,0,0,0,0},
    .{0,0,0,0,0,0,40,0,0,-8,-8,-8,-8,-8,-8,-8,-8,-8,0,-8,0,-8,0,-8,-8,-8,-8,-8,-8,-8,-8,-8,0,0,0,0},
    .{0,0,0,0,0,0,41,0,0,-8,-8,-8,-8,-8,-8,-8,-8,-8,0,-8,0,-8,0,-8,-8,-8,-8,-8,-8,-8,-8,-8,0,0,0,0},
    .{0,0,0,0,0,0,42,0,0,-8,-8,-8,-8,-8,-8,-8,-8,-8,0,-8,0,-8,0,-8,-8,-8,-8,-8,-8,-8,-8,-8,0,0,0,0},
    .{0,0,0,0,0,0,43,0,0,-8,-8,-8,-8,-8,-8,-8,-8,-8,0,-8,0,-8,0,-8,-8,-8,-8,-8,-8,-8,-8,-8,0,0,0,0},
    .{0,0,0,0,0,0,44,0,0,-8,-8,-8,-8,-8,-8,-8,-8,-8,0,-8,0,-8,0,-8,-8,-8,-8,-8,-8,-8,-8,-8,0,0,0,0},
    .{0,0,0,0,0,0,45,0,0,-8,-8,-8,-8,-8,-8,-8,-8,-8,0,-8,0,-8,0,-8,-8,-8,-8,-8,-8,-8,-8,-8,0,0,0,0},
    .{0,0,0,0,0,0,46,0,0,-8,-8,-8,-8,-8,-8,-8,-8,-8,0,-8,0,-8,0,-8,-8,-8,-8,-8,-8,-8,-8,-8,0,0,0,0},
    .{0,-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
    .{0,-8,0,0,0,0,47,0,0,-8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
    .{0,-7,0,0,0,0,0,0,0,-7,-7,-7,-7,-7,-7,-7,-7,-7,0,-7,0,-7,0,-7,-7,-7,-7,-7,-7,-7,-7,-7,0,0,0,0},
    .{0,0,0,0,0,0,0,10,9,30,11,12,13,14,15,16,17,18,48,19,0,20,0,21,22,23,24,25,26,27,28,29,0,0,0,0},
    .{0,0,0,0,0,0,0,10,9,30,11,12,13,14,15,16,17,18,0,19,49,20,0,21,22,23,24,25,26,27,28,29,0,0,0,0},
    .{0,0,0,0,0,0,0,10,9,30,11,12,13,14,15,16,17,18,0,19,0,20,50,21,22,23,24,25,26,27,28,29,0,0,0,0},
    .{0,0,0,0,0,0,0,10,9,30,11,12,13,14,15,16,17,18,0,19,0,20,51,21,22,23,24,25,26,27,28,29,0,0,0,0},
    .{0,0,0,0,0,0,0,10,9,30,11,12,13,14,15,16,17,18,52,19,0,20,0,21,22,23,24,25,26,27,28,29,0,0,0,0},
    .{0,0,0,0,0,0,0,33,53,30,11,12,13,14,15,16,17,18,0,19,0,20,0,21,22,23,24,25,26,27,28,29,0,0,0,0},
    .{0,0,0,0,0,0,0,33,54,30,11,12,13,14,15,16,17,18,0,19,0,20,0,21,22,23,24,25,26,27,28,29,0,0,0,0},
    .{0,0,0,0,0,0,0,33,55,30,11,12,13,14,15,16,17,18,0,19,0,20,0,21,22,23,24,25,26,27,28,29,0,0,0,0},
    .{0,0,0,0,0,0,0,33,56,30,11,12,13,14,15,16,17,18,0,19,0,20,0,21,22,23,24,25,26,27,28,29,0,0,0,0},
    .{0,0,0,0,0,0,0,33,57,30,11,12,13,14,15,16,17,18,0,19,0,20,0,21,22,23,24,25,26,27,28,29,0,0,0,0},
    .{0,0,0,0,0,0,0,33,58,30,11,12,13,14,15,16,17,18,0,19,0,20,0,21,22,23,24,25,26,27,28,29,0,0,0,0},
    .{0,0,0,0,0,0,0,33,59,30,11,12,13,14,15,16,17,18,0,19,0,20,0,21,22,23,24,25,26,27,28,29,0,0,0,0},
    .{0,0,0,0,0,0,0,33,60,30,11,12,13,14,15,16,17,18,0,19,0,20,0,21,22,23,24,25,26,27,28,29,0,0,0,0},
    .{0,-3,0,0,0,0,0,33,0,30,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
    .{0,-17,0,0,0,0,0,0,0,-17,-17,-17,-17,-17,-17,-17,-17,-17,-17,-17,-17,-17,-17,-17,-17,-17,-17,-17,-17,-17,-17,-17,0,0,0,0},
    .{0,-18,0,0,0,0,0,0,0,-18,-18,-18,-18,-18,-18,-18,-18,-18,-18,-18,-18,-18,-18,-18,-18,-18,-18,-18,-18,-18,-18,-18,0,0,0,0},
    .{0,-19,0,0,0,0,0,0,0,-19,-19,-19,-19,-19,-19,-19,-19,-19,-19,-19,-19,-19,-19,-19,-19,-19,-19,-19,-19,-19,-19,-19,0,0,0,0},
    .{0,-20,0,0,0,0,0,0,0,-20,-20,-20,-20,-20,-20,-20,-20,-20,-20,-20,-20,-20,-20,-20,-20,-20,-20,-20,-20,-20,-20,-20,0,0,0,0},
    .{0,-21,0,0,0,0,0,0,0,-21,-21,-21,-21,-21,-21,-21,-21,-21,-21,-21,-21,-21,-21,-21,-21,-21,-21,-21,-21,-21,-21,-21,0,0,0,0},
    .{0,-22,0,0,0,0,0,0,0,-22,-22,-22,-22,-22,-22,-22,-22,-22,-22,-22,-22,-22,-22,-22,-22,-22,-22,-22,-22,-22,-22,-22,0,0,0,0},
    .{0,-23,0,0,0,0,0,0,0,-23,-23,-23,-23,-23,-23,-23,-23,-23,-23,-23,-23,-23,-23,-23,-23,-23,-23,-23,-23,-23,-23,-23,0,0,0,0},
    .{0,-24,0,0,0,0,0,0,0,-24,-24,-24,-24,-24,-24,-24,-24,-24,-24,-24,-24,-24,-24,-24,-24,-24,-24,-24,-24,-24,-24,-24,0,0,0,0},
    .{0,-25,0,0,0,0,0,0,0,-25,-25,-25,-25,-25,-25,-25,-25,-25,-25,-25,-25,-25,-25,-25,-25,-25,-25,-25,-25,-25,-25,-25,0,0,0,0},
    .{0,-26,0,0,0,0,0,0,0,-26,-26,-26,-26,-26,-26,-26,-26,-26,-26,-26,-26,-26,-26,-26,-26,-26,-26,-26,-26,-26,-26,-26,0,0,0,0},
    .{0,-27,0,0,0,0,0,0,0,-27,-27,-27,-27,-27,-27,-27,-27,-27,-27,-27,-27,-27,-27,-27,-27,-27,-27,-27,-27,-27,-27,-27,0,0,0,0},
    .{0,0,0,0,0,0,61,0,0,-8,-8,-8,-8,-8,-8,-8,-8,-8,0,-8,0,-8,0,-8,-8,-8,-8,-8,-8,-8,-8,-8,0,0,0,0},
    .{0,-9,0,0,0,0,0,0,0,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,0,0,0,0},
    .{0,0,0,0,0,0,0,33,62,30,11,12,13,14,15,16,17,18,0,19,0,20,0,21,22,23,24,25,26,27,28,29,0,0,0,0},
    .{0,-28,0,0,0,0,0,0,0,-28,-28,-28,-28,-28,-28,-28,-28,-28,-28,-28,-28,-28,-28,-28,-28,-28,-28,-28,-28,-28,-28,-28,0,0,0,0},
};

// X "c" excludes: shift the hinted token instead of reducing when it
// touches the previous token (pre == 0)
const xExcludes = [_]struct { sym: u16, shift: u16, reduce: i16 }{
};
/// State s's excludes: xExcludes[xExcludeStart[s]..xExcludeStart[s + 1]].
const xExcludeStart = [_]u32{};

fn startState(start: Start) u16 {
    return switch (start) {
        .@"program" => 0,
        .@"form" => 1,
    };
}

fn startMarker(start: Start) u16 {
    return switch (start) {
        .@"program" => 32,
        .@"form" => 34,
    };
}

/// Expected symbols per state: state s expects list i = expectedOf[s],
/// expectedSymbols[expectedOffsets[i]..expectedOffsets[i + 1]].
const expectedSymbols = [_]u16{
    1, 9, 10, 11, 12, 13, 14, 15, 16, 17, 19, 21, 23, 24, 25, 26, 27, 28, 29, 30, 31, 9, 10, 11,
    12, 13, 14, 15, 16, 17, 19, 21, 23, 24, 25, 26, 27, 28, 29, 30, 31, 1, 1, 9, 10, 11, 12, 13,
    14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 9, 10, 11, 12, 13, 14,
    15, 16, 17, 18, 19, 21, 23, 24, 25, 26, 27, 28, 29, 30, 31, 9, 10, 11, 12, 13, 14, 15, 16, 17,
    19, 20, 21, 23, 24, 25, 26, 27, 28, 29, 30, 31, 9, 10, 11, 12, 13, 14, 15, 16, 17, 19, 21, 22,
    23, 24, 25, 26, 27, 28, 29, 30, 31, 1, 9,
};
const expectedOffsets = [_]u32{
    0, 0, 21, 41, 42, 66, 87, 108, 129, 131,
};
const expectedOf = [_]u16{
    0, 0, 1, 2, 3, 1, 3, 2, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 6, 7, 7, 5, 2,
    2, 2, 2, 2, 2, 2, 2, 3, 8, 1, 5, 6, 7, 7, 5, 2, 2, 2, 2, 2, 2, 2, 2, 8,
    4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4, 2, 4,
};
/// The most symbols a state expects: room for `BaseParser.expectedNames`.
pub const maxExpected = 24;

fn symbolName(sym: u16) []const u8 {
    return switch (sym) {
        1 => "end of input",
        9 => "hash_discard",
        10 => "integer",
        11 => "real",
        12 => "string",
        13 => "regex",
        14 => "char",
        15 => "keyword",
        16 => "ident",
        17 => "lparen",
        18 => "rparen",
        19 => "lbracket",
        20 => "rbracket",
        21 => "lbrace",
        22 => "rbrace",
        23 => "hash_lbrace",
        24 => "hash_lparen",
        25 => "quote_tok",
        26 => "syntax_quote_tok",
        27 => "unquote_tok",
        28 => "unquote_splicing_tok",
        29 => "deref_tok",
        30 => "var_quote_tok",
        31 => "caret",
        else => "",
    };
}

fn isTrivia(_: TokenCat) bool {
    return false;
}

const repairTokens = [_]u16{};
const repairOffsets = [_]u32{};

fn repairClass(_: u16) RepairClass {
    return .none;
}

fn ruleSideLabels(rule: u16) []const SideLabel {
    _ = rule;
    return &.{};
}

fn slotOf(_: Tag, _: Role) ?usize {
    return null;
}

fn restSlotOf(_: Tag, _: Role) ?usize {
    return null;
}

fn roleAt(_: Tag, _: usize) ?Role {
    return null;
}

fn restRoleOf(_: Tag) ?struct { role: Role, slot: usize } {
    return null;
}

// =============================================================================
// API
// =============================================================================

pub const Parser = if (@hasDecl(lang, "Parser")) lang.Parser else BaseParser;

/// Parse a whole program with a new `Parser`. The caller owns
/// `result.parser` and must `deinit()` it when done with the tree.
pub fn parseProgram(allocator: std.mem.Allocator, source: []const u8) !struct { parser: Parser, sexp: Sexp } {
    var p = Parser.init(allocator, source);
    errdefer p.deinit();
    const sexp = try p.parseProgram();
    return .{ .parser = p, .sexp = sexp };
}

/// Parse a whole form with a new `Parser`. The caller owns
/// `result.parser` and must `deinit()` it when done with the tree.
pub fn parseForm(allocator: std.mem.Allocator, source: []const u8) !struct { parser: Parser, sexp: Sexp } {
    var p = Parser.init(allocator, source);
    errdefer p.deinit();
    const sexp = try p.parseForm();
    return .{ .parser = p, .sexp = sexp };
}
