//! Generated by nexus v1.1.0 — do not edit

const std = @import("std");
const lang = @import("semantic.zig");

// =============================================================================
// TOKEN CATEGORIES
// =============================================================================

pub const TokenCat = enum(u8) {
    @"ident",
    @"integer",
    @"newline",
    @"eq",
    @"plus_eq",
    @"minus_eq",
    @"star_eq",
    @"colon",
    @"comma",
    @"lparen",
    @"rparen",
    @"lbracket",
    @"rbracket",
    @"plus",
    @"minus",
    @"star",
    @"slash",
    @"let",
    @"if",
    @"unless",
    @"then",
    @"else",
    @"return",
    @"for",
    @"ptr",
    @"in",
    @"do",
    @"call",
    @"swap",
    @"with",
    @"pass",
    @"yield",
    @"comment",
    @"eof",
    @"err",

    // Built in: the token of `→ skip` rules (returned to the lang Lexer)
    @"skip",
};

// =============================================================================
// TOKEN STRUCT (8 bytes)
// =============================================================================

pub const Token = struct {
    pos: u32, // Byte position in source (4 bytes)
    len: u16, // Token length in bytes (2 bytes)
    cat: TokenCat, // Token category (1 byte)
    pre: u8, // Preceding whitespace count (1 byte)

    comptime {
        std.debug.assert(@sizeOf(Token) == 8);
    }
};

// =============================================================================
// LEXER
// =============================================================================

pub const BaseLexer = struct {
    const Self = @This();

    source: []const u8,
    pos: u32,
    /// Side channel a lang Lexer wrapper may set per token; the parser
    /// copies it into the shifted leaf's `src.id` and clears it.
    aux: u16 = 0,

    pub fn init(source: []const u8) Self {
        return .{
            .source = source,
            .pos = 0,
        };
    }

    /// Get the text slice for a token (zero-copy into source)
    pub fn text(self: *const Self, tok: Token) []const u8 {
        const start: usize = tok.pos;
        const end: usize = @min(start + tok.len, self.source.len);
        if (start >= self.source.len) return "";
        return self.source[start..end];
    }

    /// Reset lexer to beginning
    pub fn reset(self: *Self) void {
        self.pos = 0;
    }

    /// Get next token
    pub fn next(self: *Self) Token {
        return self.matchRules();
    }

    /// The token of `cat` from `start` to `end`. A match longer than a
    /// Token can hold (65535 bytes) is an `err` token of that length;
    /// the scan goes on after the whole match.
    inline fn token(cat: TokenCat, pre: u8, start: usize, end: usize) Token {
        if (end - start > std.math.maxInt(u16)) return .{ .cat = .@"err", .pre = pre, .pos = @intCast(start), .len = std.math.maxInt(u16) };
        return .{ .cat = cat, .pre = pre, .pos = @intCast(start), .len = @intCast(end - start) };
    }

    const cls0 = blk: {
        var t: [256]bool = @splat(false);
        for ('A'..91) |c| t[c] = true;
        t['_'] = true;
        for ('a'..123) |c| t[c] = true;
        break :blk t;
    };

    const cls1 = blk: {
        var t: [256]bool = @splat(false);
        for ('0'..58) |c| t[c] = true;
        for ('A'..91) |c| t[c] = true;
        t['_'] = true;
        for ('a'..123) |c| t[c] = true;
        break :blk t;
    };

    /// First index at or after `from` whose byte is in `stops` (or src.len).
    inline fn scanUntil(src: []const u8, from: usize, comptime stops: []const u8) usize {
        const V = @Vector(16, u8);
        var p = from;
        while (p + 16 <= src.len) : (p += 16) {
            const v: V = src[p..][0..16].*;
            var hits: u16 = 0;
            inline for (stops) |c| hits |= @bitCast(v == @as(V, @splat(c)));
            if (hits != 0) return p + @ctz(hits);
        }
        while (p < src.len) : (p += 1) {
            inline for (stops) |c| if (src[p] == c) return p;
        }
        return p;
    }

    /// Match the next token.
    pub fn matchRules(self: *Self) Token {
        const src = self.source;
        const n = src.len;
        var p: usize = self.pos;
        const wsStart = p;
        while (p < n and (src[p] == ' ' or src[p] == '\t')) p += 1;
        const pre: u8 = @intCast(@min(p - wsStart, 255));
        if (p >= n) {
            self.pos = @intCast(p);
            return .{ .cat = .@"eof", .pre = pre, .pos = @intCast(p), .len = 0 };
        }
        const start = p;
        dfa: switch (@as(u16, 0)) {
            0 => {
                if (p < n and cls0[src[p]]) {
                    p += 1;
                    continue :dfa 14;
                }
                if (p < n) switch (src[p]) {
                    0x00...'\t', 0x0B...'"', '$'...'\'', '.', ';'...'<', '>'...'@', '\\', '^', '`', '{'...0xFF => { p += 1; self.pos = @intCast(p); return token(.@"err", pre, start, p); },
                    '\n' => { p += 1; self.pos = @intCast(p); return token(.@"newline", pre, start, p); },
                    '#' => { p += 1; continue :dfa 3; },
                    '(' => { p += 1; self.pos = @intCast(p); return token(.@"lparen", pre, start, p); },
                    ')' => { p += 1; self.pos = @intCast(p); return token(.@"rparen", pre, start, p); },
                    '*' => { p += 1; continue :dfa 6; },
                    '+' => { p += 1; continue :dfa 7; },
                    ',' => { p += 1; self.pos = @intCast(p); return token(.@"comma", pre, start, p); },
                    '-' => { p += 1; continue :dfa 9; },
                    '/' => { p += 1; self.pos = @intCast(p); return token(.@"slash", pre, start, p); },
                    '0'...'9' => { p += 1; continue :dfa 11; },
                    ':' => { p += 1; self.pos = @intCast(p); return token(.@"colon", pre, start, p); },
                    '=' => { p += 1; self.pos = @intCast(p); return token(.@"eq", pre, start, p); },
                    '[' => { p += 1; self.pos = @intCast(p); return token(.@"lbracket", pre, start, p); },
                    ']' => { p += 1; self.pos = @intCast(p); return token(.@"rbracket", pre, start, p); },
                    else => {},
                };
                break :dfa;
            },
            3 => {
                p = scanUntil(src, p, &.{'\n'});
                self.pos = @intCast(p);
                return token(.@"comment", pre, start, p);
            },
            6 => {
                if (p < n) switch (src[p]) {
                    '=' => { p += 1; self.pos = @intCast(p); return token(.@"star_eq", pre, start, p); },
                    else => {},
                };
                self.pos = @intCast(p);
                return token(.@"star", pre, start, p);
            },
            7 => {
                if (p < n) switch (src[p]) {
                    '=' => { p += 1; self.pos = @intCast(p); return token(.@"plus_eq", pre, start, p); },
                    else => {},
                };
                self.pos = @intCast(p);
                return token(.@"plus", pre, start, p);
            },
            9 => {
                if (p < n) switch (src[p]) {
                    '=' => { p += 1; self.pos = @intCast(p); return token(.@"minus_eq", pre, start, p); },
                    else => {},
                };
                self.pos = @intCast(p);
                return token(.@"minus", pre, start, p);
            },
            11 => {
                while (p < n and src[p] -% '0' <= 9) p += 1;
                self.pos = @intCast(p);
                return token(.@"integer", pre, start, p);
            },
            14 => {
                while (p < n and cls1[src[p]]) p += 1;
                self.pos = @intCast(p);
                return token(.@"ident", pre, start, p);
            },
            else => unreachable,
        }
        self.pos = @intCast(start + 1);
        return .{ .cat = .@"err", .pre = pre, .pos = @intCast(start), .len = 1 };
    }
};

pub const Lexer = if (@hasDecl(lang, "Lexer")) lang.Lexer else BaseLexer;

// =============================================================================
// Tag and Role enums (from @schema)
// =============================================================================

pub const Tag = enum(u8) {
    @"module",
    @"set",
    @"let",
    @"if",
    @"for",
    @"call",
    @"swap",
    @"return",
    @"yield",
    @"pass",
    @"array",
    @"neg",
    @"num",
    @"name",
    @"+",
    @"-",
    @"*",
    @"/",
    @"note",
    @"ptr",
    @"flag",
    @"+=",
    @"-=",
    @"*=",
};

pub const Role = enum(u16) {
    @"stmts",
    @"op",
    @"target",
    @"value",
    @"eq",
    @"name",
    @"type",
    @"kw",
    @"cond",
    @"then",
    @"else",
    @"mode",
    @"var",
    @"index",
    @"iter",
    @"body",
    @"callee",
    @"args",
    @"a",
    @"b",
    @"c",
    @"d",
    @"items",
    @"id",
    @"left",
    @"right",
    @"text",
};

/// Start symbols; `BaseParser.parse(start)` parses one.
pub const Start = enum(u16) {
    @"program" = 3,
};

// =============================================================================
// S-expressions
// =============================================================================

/// Dense per-parse node number; 0 = no node store entry.
pub const NodeId = u32;

/// A byte range [start, end) of the source.
pub const Span = struct {
    start: u32,
    end: u32,

    pub const empty: Span = .{ .start = 0, .end = 0 };

    pub fn len(self: Span) u32 {
        return self.end - self.start;
    }

    pub fn isEmpty(self: Span) bool {
        return self.start == self.end;
    }
};

/// A source leaf: token position and length, plus the token id attribute
/// (an `@as` keyword ordinal, or the lexer's `aux` value; see `takeLexerId`).
pub const Src = struct { pos: u32, len: u16, id: u16 };

/// A list node: its items and its node id (0 when the parse keeps no node
/// store, or for lists built outside the parser, e.g. by a lang wrapper).
pub const List = struct {
    ptr: [*]const Sexp,
    len: u32,
    id: NodeId = 0,

    pub const empty: List = .{ .ptr = &[_]Sexp{}, .len = 0 };

    /// A list over `xs` with no node id.
    pub fn of(xs: []const Sexp) List {
        return .{ .ptr = xs.ptr, .len = @intCast(xs.len) };
    }

    /// A list over `xs` carrying node id `id` (e.g. a rewritten node
    /// keeping the id, and so the span, of the node it replaces).
    pub fn withId(xs: []const Sexp, id: NodeId) List {
        return .{ .ptr = xs.ptr, .len = @intCast(xs.len), .id = id };
    }

    pub fn items(self: List) []const Sexp {
        return self.ptr[0..self.len];
    }
};

/// The uniform tree value: 24 bytes, O(1) dispatch on the head tag.
pub const Sexp = union(enum) {
    nil,
    tag: Tag,
    src: Src,
    str: []const u8,
    list: List,

    comptime {
        std.debug.assert(@sizeOf(Sexp) == 24);
    }

    /// A list value over `xs` with no node id.
    pub fn listOf(xs: []const Sexp) Sexp {
        return .{ .list = List.of(xs) };
    }

    /// The items of a list; empty for any other value.
    pub fn items(self: Sexp) []const Sexp {
        return switch (self) {
            .list => |l| l.items(),
            else => &.{},
        };
    }

    /// The head tag of a tag-headed list.
    pub fn kind(self: Sexp) ?Tag {
        if (self != .list or self.list.len == 0) return null;
        const head = self.list.ptr[0];
        return if (head == .tag) head.tag else null;
    }

    pub fn isKind(self: Sexp, t: Tag) bool {
        const k = self.kind() orelse return false;
        return k == t;
    }

    /// The text of a leaf or string; empty otherwise.
    pub fn getText(self: Sexp, source: []const u8) []const u8 {
        return switch (self) {
            .src => |s| source[s.pos..][0..s.len],
            .str => |s| s,
            else => "",
        };
    }

    /// Print the tree on one line: `_`, tags by name, leaves as their text
    /// followed by `#id` when the id attribute is non-zero, strings quoted.
    pub fn write(self: Sexp, source: []const u8, w: *std.Io.Writer) std.Io.Writer.Error!void {
        switch (self) {
            .nil => try w.writeAll("_"),
            .tag => |t| try w.writeAll(nameOf(t)),
            .src => |s| {
                try w.writeAll(source[s.pos..][0..s.len]);
                if (s.id != 0) try w.print("#{d}", .{s.id});
            },
            .str => |s| try w.print("\"{s}\"", .{s}),
            .list => |l| {
                try w.writeAll("(");
                for (l.items(), 0..) |item, i| {
                    if (i > 0) try w.writeAll(" ");
                    try item.write(source, w);
                }
                try w.writeAll(")");
            },
        }
    }
};

/// The name of a Tag or Role value, "?" for one the enum does not name
/// (without a schema, Role is empty and a collected Tag is non-exhaustive).
fn nameOf(value: anytype) []const u8 {
    return std.enums.tagName(@TypeOf(value), value) orelse "?";
}


// =============================================================================
// Parser
// =============================================================================

/// Per node: its source span and the rule that built it.
pub const NodeInfo = struct { span: Span, rule: u16 };

/// NodeInfo per NodeId, in fixed-size chunks that never move (appending
/// never copies the store).
const NodeStore = struct {
    chunks: std.ArrayList(*[chunkLen]NodeInfo) = .empty,
    len: u32 = 0,

    const chunkLen = 128;

    inline fn add(self: *NodeStore, a: std.mem.Allocator, info: NodeInfo) !NodeId {
        const id = self.len;
        if (id % chunkLen == 0) try self.addChunk(a);
        self.chunks.items[id / chunkLen][id % chunkLen] = info;
        self.len = id + 1;
        return id;
    }

    fn addChunk(self: *NodeStore, a: std.mem.Allocator) !void {
        try self.chunks.append(a, try a.create([chunkLen]NodeInfo));
    }

    inline fn at(self: *const NodeStore, id: NodeId) *NodeInfo {
        return &self.chunks.items[id / chunkLen][id % chunkLen];
    }
};

/// A side-band role recorded at reduce time (not placed in the tree).
pub const SideEntry = struct { node: NodeId, role: Role, span: Span };

/// A side-band label of a rule: `role` is recorded from element `pass`.
pub const SideLabel = struct { role: Role, pass: u16 };

/// A parse error: the offending token and the state that rejected it.
pub const Failure = struct {
    span: Span,
    /// Grammar symbol of the offending token.
    symbol: u16,
    cat: TokenCat,
    state: u16,
};

/// Result of `parseTolerant`.
pub const Tolerant = struct {
    /// The tree; `.nil` when the parse could not be completed.
    sexp: Sexp,
    /// The first error, as the strict parse reports it (null when the
    /// input was valid).
    failure: ?Failure,
    /// Tokens inserted plus tokens deleted.
    repairs: u32,
    /// Zero-width tokens inserted (holes and structure).
    insertions: u32 = 0,
    /// Offending tokens deleted.
    deletions: u32 = 0,
    complete: bool,
};

/// A token's role in tolerant repair, from `@repair`.
pub const RepairClass = enum {
    /// Not fabricable: real input.
    none,
    /// `holes`: a value-carrying token that may be minted with empty text.
    hole,
    /// `structure`: layout a lexer mints (INDENT, OUTDENT, ...).
    structure,
    /// `terminator`: structure that ends a statement (NEWLINE); the only
    /// insertion allowed in front of real input.
    terminator,
};

/// The id attribute of the token the lexer just produced, cleared as it is
/// read. It is the `aux: u16` field of the generated BaseLexer, which a lang
/// `Lexer` wrapper reaches as `base.aux` (set it before returning a token,
/// e.g. MUMPS stores the dot level of a line there). The parser stores it in
/// the token's `src.id` unless an `@as` keyword match supplies the id.
fn takeLexerId(lexer: *Lexer) u16 {
    if (comptime @hasField(Lexer, "aux")) {
        const id = lexer.aux;
        lexer.aux = 0;
        return id;
    } else if (comptime @hasField(Lexer, "base") and @hasField(@FieldType(Lexer, "base"), "aux")) {
        const id = lexer.base.aux;
        lexer.base.aux = 0;
        return id;
    } else return 0;
}

pub const BaseParser = struct {
    arena: std.heap.ArenaAllocator,
    lexer: Lexer,
    source: []const u8,
    current: Token,
    /// A start marker to shift before any input (set by `parse`).
    injectedToken: ?u16 = null,
    /// A zero-width token the tolerant driver inserts before `current`.
    pendingInsert: ?u16 = null,
    /// `@as` keyword ordinal of `current`, stored in its `src.id`.
    lastMatchedId: u16 = 0,
    /// Set when a builder could not allocate; the parse then fails.
    outOfMemory: bool = false,
    /// A parse has begun (the next one re-reads the input).
    started: bool = false,

    stateStack: std.ArrayList(u16) = .empty,
    valueStack: std.ArrayList(Sexp) = .empty,
    /// Spare capacity of the lists `keepList` returned, by address.
    listSpare: std.AutoHashMapUnmanaged(usize, ListSpare) = .empty,
    /// Node id of the list `extendList` is growing (0 = none).
    extending: NodeId = 0,

    // Node store (when `nodeStore`): per value-stack entry where it
    // starts, and per node its span and rule, indexed by NodeId (entry 0
    // unused). An entry starts at its first token, or at the next token
    // when it consumed none. A reduction then extends from its first
    // element's start to the end of the last token shifted (`lastEnd`),
    // and is empty when start >= end. With `elemEnds` (side-band labels or
    // nested nodes) each entry's end is kept too. Both are indexed like
    // `valueStack` and sized to its capacity (the stack top is its length).
    starts: []u32 = &.{},
    ends: []u32 = &.{},
    nodes: NodeStore = .{},
    sides: std.ArrayList(SideEntry) = .empty,
    reduction: Reduction = .{},
    /// End of the last shifted token: where every reduction ends.
    lastEnd: u32 = 0,

    triviaTokens: std.ArrayList(Token) = .empty,
    failure: ?Failure = null,
    scratch: std.ArrayList(u16) = .empty,

    const ListSpare = struct { len: usize, capacity: usize };

    /// The reduction in progress: its rule and where it starts (it ends at
    /// `lastEnd`); with `elemEnds`, also the stack index of its first
    /// element and the first node id it built.
    const Reduction = struct {
        rule: u16 = 0,
        start: u32 = 0,
        base: u32 = 0,
        firstNode: NodeId = 0,
    };

    pub fn init(backingAllocator: std.mem.Allocator, source: []const u8) BaseParser {
        var p = BaseParser{
            .arena = std.heap.ArenaAllocator.init(backingAllocator),
            .lexer = Lexer.init(source),
            .source = source,
            .current = undefined,
        };
        p.current = p.lexer.next();
        return p;
    }

    pub fn deinit(self: *BaseParser) void {
        self.arena.deinit();
    }

    fn allocator(self: *BaseParser) std.mem.Allocator {
        return self.arena.allocator();
    }

    pub fn parseProgram(self: *BaseParser) !Sexp {
        return self.parse(.@"program");
    }


    /// Parse the whole input as `start`.
    pub fn parse(self: *BaseParser, start: Start) !Sexp {
        try self.begin(start);
        while (true) {
            const state = self.stateStack.last().?;
            const sym = self.lookahead();
            const action = self.actionFor(state, sym);
            if (action > 0) {
                try self.shift(@intCast(action));
            } else if (action < -1) {
                try self.reduce(@intCast(-action - 2));
            } else if (action == -1) {
                return self.valueStack.last().?;
            } else {
                self.recordFailure(state, sym);
                return error.ParseError;
            }
        }
    }

    /// Parse `start`, repairing syntax errors for an editor: the parse goes
    /// on past an error with the tree built the normal way. The rules:
    ///
    ///   1. The first error is recorded exactly as the strict parse reports
    ///      it (token, state, expected set); repairs never replace it, and a
    ///      repaired parse still returns it: recovery is not acceptance.
    ///   2. Only tokens the grammar declares in `@repair` are ever inserted,
    ///      as zero-width tokens at the offending token, taken from the
    ///      state's generated candidate list (holes, then structure; fewer
    ///      further fabrications first).
    ///   3. What the offending token admits: end of input and structure
    ///      tokens (lexer scaffolding) admit any candidate; real input
    ///      admits only a `terminator` (a statement boundary splits what
    ///      the user wrote without inventing meaning in front of it: no
    ///      holes, no block structure before real code).
    ///   4. An insertion must let the offending token be consumed (shifted,
    ///      or accepted at end of input). At end of input or a structure
    ///      token, when none does, a candidate the state can shift is
    ///      inserted anyway, never twice in the same configuration (stack
    ///      depth, state, token) since the last token was consumed, so
    ///      several insertions can complete an unfinished construct.
    ///   5. With no admissible insertion the offending token is deleted,
    ///      except end of input, which is never deleted: the parse ends
    ///      there, incomplete.
    ///   6. At most `budget` repairs (insertions plus deletions); when they
    ///      are spent the parse ends, incomplete.
    ///
    /// Strict parsing (`parse`) is a separate entry point and pays nothing.
    pub fn parseTolerant(self: *BaseParser, start: Start, budget: u32) !Tolerant {
        if (!hasRepair) @compileError("parseTolerant needs a @repair section in the grammar");
        try self.begin(start);
        var result: Tolerant = .{ .sexp = .nil, .failure = null, .repairs = 0, .complete = false };
        // Configurations repaired since the last consumed token (rule 4).
        var tried: std.ArrayList(RepairKey) = .empty;
        while (true) {
            const state = self.stateStack.last().?;
            const sym = self.lookahead();
            const action = self.actionFor(state, sym);
            if (action > 0) {
                if (self.pendingInsert == null and self.injectedToken == null) tried.clearRetainingCapacity();
                try self.shift(@intCast(action));
            } else if (action < -1) {
                try self.reduce(@intCast(-action - 2));
            } else if (action == -1) {
                result.sexp = self.valueStack.last().?;
                result.complete = true;
                break;
            } else {
                // An inserted token is always acceptable (rule 4).
                std.debug.assert(self.pendingInsert == null);
                if (self.failure == null) self.recordFailure(state, sym);
                if (result.repairs == budget) break;
                if (try self.chooseInsertion(sym, tried.items)) |token| {
                    try tried.append(self.allocator(), .{ .depth = @intCast(self.stateStack.items.len), .state = state, .token = token });
                    self.pendingInsert = token;
                    result.insertions += 1;
                } else if (sym == endSymbol) {
                    break;
                } else {
                    try self.advance();
                    tried.clearRetainingCapacity();
                    result.deletions += 1;
                }
                result.repairs += 1;
            }
        }
        result.failure = self.failure;
        return result;
    }

    const RepairKey = struct { depth: u32, state: u16, token: u16 };

    /// The insertion rules 3 and 4 allow before `next`, best first; null
    /// when there is none.
    fn chooseInsertion(self: *BaseParser, next: u16, tried: []const RepairKey) !?u16 {
        const state = self.stateStack.last().?;
        const nextClass = if (next == endSymbol) RepairClass.structure else repairClass(next);
        const real = nextClass == .none or nextClass == .hole;
        for (repairCandidates(state)) |candidate| {
            if (real and repairClass(candidate) != .terminator) continue;
            if (try self.accepts(&.{ candidate, next })) return candidate;
        }
        if (real) return null;
        const depth: u32 = @intCast(self.stateStack.items.len);
        for (repairCandidates(state)) |candidate| {
            const seen = for (tried) |k| {
                if (k.depth == depth and k.state == state and k.token == candidate) break true;
            } else false;
            if (!seen and try self.accepts(&.{candidate})) return candidate;
        }
        return null;
    }

    fn begin(self: *BaseParser, start: Start) !void {
        // Token positions are u32.
        if (self.source.len > std.math.maxInt(u32)) return error.InputTooLarge;
        // Every parse reads the input from the start (a parser may parse
        // again, e.g. tolerantly after a failed strict parse). Node ids
        // keep counting, so earlier trees stay valid.
        if (self.started) {
            self.lexer = Lexer.init(self.source);
            self.current = self.lexer.next();
            self.lastMatchedId = 0;
            self.triviaTokens.clearRetainingCapacity();
        }
        self.started = true;
        self.stateStack.clearRetainingCapacity();
        self.valueStack.clearRetainingCapacity();
        self.failure = null;
        self.pendingInsert = null;
        self.outOfMemory = false;
        try self.stateStack.append(self.allocator(), startState(start));
        if (nodeStore) self.lastEnd = 0;
        self.injectedToken = startMarker(start);
        if (nodeStore) {
            if (self.nodes.len == 0) _ = try self.nodes.add(self.allocator(), .{ .span = .empty, .rule = 0 });
        }
        if (hasTrivia) try self.skipTrivia();
    }

    inline fn lookahead(self: *BaseParser) u16 {
        if (self.injectedToken) |marker| return marker;
        if (self.pendingInsert) |token| return token;
        return tokenToSymbol(self, self.current);
    }

    /// The table action, with the `X "c"` override: when the table reduces
    /// on the hinted token and it touches the previous token, shift
    /// instead. (Never for a start marker or an inserted token.)
    inline fn actionFor(self: *const BaseParser, state: u16, sym: u16) i16 {
        const action = getAction(state, sym);
        if (xExcludes.len > 0 and action < -1 and self.current.pre == 0 and self.pendingInsert == null and self.injectedToken == null) {
            if (getImmediateShift(state, sym)) |target| return target;
        }
        return action;
    }

    fn shift(self: *BaseParser, target: u16) !void {
        if (self.injectedToken != null) {
            try self.pushEntry(target, .nil, self.current.pos, self.lastEnd);
            self.injectedToken = null;
        } else if (self.pendingInsert != null) {
            const pos = self.current.pos;
            try self.pushEntry(target, .{ .src = .{ .pos = pos, .len = 0, .id = 0 } }, pos, pos);
            if (nodeStore) self.lastEnd = pos;
            self.pendingInsert = null;
        } else {
            const tok = self.current;
            const id = if (self.lastMatchedId != 0) self.lastMatchedId else takeLexerId(&self.lexer);
            self.lastMatchedId = 0;
            const end = tok.pos + tok.len;
            try self.pushEntry(target, .{ .src = .{ .pos = tok.pos, .len = tok.len, .id = id } }, tok.pos, end);
            if (nodeStore) self.lastEnd = end;
            try self.advance();
        }
    }

    /// Push a state, its value, and (with a node store) where the value
    /// starts and ends. The stacks grow together: the state stack is always
    /// one longer than the others, so one capacity check covers them all.
    inline fn pushEntry(self: *BaseParser, state: u16, value: Sexp, start: u32, end: u32) !void {
        const n = self.valueStack.items.len;
        if (n == self.valueStack.capacity) try self.growStacks();
        self.valueStack.items.len = n + 1;
        self.valueStack.items[n] = value;
        self.stateStack.items.len = n + 2;
        self.stateStack.items[n + 1] = state;
        if (nodeStore) self.starts[n] = start;
        if (elemEnds) self.ends[n] = end;
    }

    fn growStacks(self: *BaseParser) !void {
        const a = self.allocator();
        try self.valueStack.ensureUnusedCapacity(a, 1);
        const capacity = self.valueStack.capacity;
        try self.stateStack.ensureTotalCapacity(a, capacity + 1);
        if (nodeStore) self.starts = try a.realloc(self.starts, capacity);
        if (elemEnds) self.ends = try a.realloc(self.ends, capacity);
    }

    fn reduce(self: *BaseParser, ruleId: u16) !void {
        const len = ruleLen[ruleId];
        const base = self.valueStack.items.len - len;
        const top = self.stateStack.items.len - len;

        if (nodeStore) {
            // An element that consumed nothing starts at the next token,
            // past the blanks after this reduction's last token (lastEnd).
            // When the reduction consumed something, place its trailing
            // empty elements at lastEnd so that spans nest.
            if (len > 0 and self.starts[base] < self.lastEnd) {
                var k = base + len;
                while (k > base and self.starts[k - 1] > self.lastEnd) : (k -= 1) {
                    self.starts[k - 1] = self.lastEnd;
                    self.placeEmpty(self.valueStack.items[k - 1], self.lastEnd);
                }
            }
            self.reduction.rule = ruleId;
            self.reduction.start = if (len > 0) self.starts[base] else self.current.pos;
            if (elemEnds) {
                self.reduction.base = @intCast(base);
                self.reduction.firstNode = self.nodes.len;
            }
        }

        // The action reads its elements in place on the value stack; the
        // result then replaces them (a reduction of nothing pushes it).
        const result = executeAction(self, ruleId, self.valueStack.items[base..]);
        if (self.outOfMemory) return error.OutOfMemory;
        const next = getAction(self.stateStack.items[top - 1], ruleLhs[ruleId]);
        std.debug.assert(next > 0); // every reduction has a goto

        if (nodeStore) try self.recordSides(ruleId, result);
        if (len > 0) {
            self.valueStack.items.len = base + 1;
            self.valueStack.items[base] = result;
            self.stateStack.items.len = top + 1;
            self.stateStack.items[top] = @intCast(next);
            // starts[base] already holds the reduction's start (its first
            // element's).
            if (elemEnds) self.ends[base] = self.lastEnd;
        } else {
            try self.pushEntry(@intCast(next), result, self.reduction.start, self.lastEnd);
        }
    }

    /// Move the nodes of an empty value (a subtree that consumed nothing)
    /// to `at`.
    fn placeEmpty(self: *BaseParser, value: Sexp, at: u32) void {
        if (value != .list) return;
        const l = value.list;
        if (l.id != 0 and l.id < self.nodes.len) {
            const info = self.nodes.at(l.id);
            if (!info.span.isEmpty()) return;
            info.span = .{ .start = at, .end = at };
        }
        for (l.items()) |child| self.placeEmpty(child, at);
    }

    /// Fetch the next token, moving trivia to the trivia channel.
    fn advance(self: *BaseParser) !void {
        self.current = self.lexer.next();
        if (hasTrivia) try self.skipTrivia();
    }

    fn skipTrivia(self: *BaseParser) !void {
        while (isTrivia(self.current.cat)) {
            try self.triviaTokens.append(self.allocator(), self.current);
            _ = takeLexerId(&self.lexer);
            self.current = self.lexer.next();
        }
    }

    /// Tokens of the grammar's `@trivia` kinds, in source order.
    pub fn trivia(self: *const BaseParser) []const Token {
        return self.triviaTokens.items;
    }

    // -------------------------------------------------------------------------
    // Node store, spans, side-band roles
    // -------------------------------------------------------------------------

    /// The span of the reduction in progress.
    inline fn reductionSpan(self: *const BaseParser) Span {
        return spanOf(.{ .start = self.reduction.start, .end = self.lastEnd });
    }

    /// The span of an extent: empty at its start when it consumed no
    /// tokens.
    fn spanOf(extent: Span) Span {
        return if (extent.start < extent.end) extent else .{ .start = extent.start, .end = extent.start };
    }

    /// The extent of elements lo..hi (0-based, inclusive) of the reduction.
    fn elemsExtent(self: *const BaseParser, lo: usize, hi: usize) Span {
        if (!elemEnds) @compileError("element extents need elemEnds");
        const base = self.reduction.base;
        return .{ .start = self.starts[base + lo], .end = self.ends[base + hi] };
    }

    /// A new node id for a list the current reduction builds.
    inline fn newNodeId(self: *BaseParser) NodeId {
        if (!nodeStore) return 0;
        return self.addNode(self.reductionSpan());
    }

    inline fn addNode(self: *BaseParser, extent: Span) NodeId {
        return self.nodes.add(self.allocator(), .{ .span = extent, .rule = self.reduction.rule }) catch {
            self.outOfMemory = true;
            return 0;
        };
    }

    fn recordSides(self: *BaseParser, ruleId: u16, result: Sexp) !void {
        if (!elemEnds) return;
        const labels = ruleSideLabels(ruleId);
        if (labels.len == 0 or result != .list) return;
        const id = result.list.id;
        if (id == 0 or id < self.reduction.firstNode) return;
        for (labels) |label| {
            try self.sides.append(self.allocator(), .{
                .node = id,
                .role = label.role,
                .span = spanOf(self.elemsExtent(label.pass, label.pass)),
            });
        }
    }

    /// Source span of a value. Leaves span their token. A list with a node
    /// id spans its reduction: first to last consumed token, including
    /// tokens (keywords, punctuation) that are not in the tree. Any other
    /// list spans the hull of its children.
    pub fn span(self: *const BaseParser, s: Sexp) Span {
        switch (s) {
            .src => |x| return .{ .start = x.pos, .end = x.pos + x.len },
            .list => |l| {
                if (nodeStore and l.id != 0 and l.id < self.nodes.len) return self.nodes.at(l.id).span;
                var result: ?Span = null;
                for (l.items()) |child| {
                    const cs = self.span(child);
                    if (cs.isEmpty()) continue;
                    result = if (result) |r| .{ .start = r.start, .end = cs.end } else cs;
                }
                return result orelse .empty;
            },
            else => return .empty,
        }
    }

    /// The rule that built a list node (null without a node id, or for a
    /// node a lang wrapper made with `newNode`).
    pub fn ruleOf(self: *const BaseParser, s: Sexp) ?u16 {
        if (!nodeStore or s != .list) return null;
        const id = s.list.id;
        if (id == 0 or id >= self.nodes.len) return null;
        const rule = self.nodes.at(id).rule;
        return if (rule == wrapperRule) null else rule;
    }

    /// The rule recorded for nodes built outside a reduction.
    const wrapperRule = std.math.maxInt(u16);

    /// A `(tag children...)` node built outside a reduction, e.g. by a lang
    /// `Parser` wrapper for an `@wrapper` kind: allocated in the parser's
    /// arena, with a fresh node id recording `extent` as its span (so
    /// `span`, facts and `ir` accessors work as for parsed nodes; `ruleOf`
    /// is null). Without a node store the node has no id.
    pub fn newNode(self: *BaseParser, tag: Tag, children: []const Sexp, extent: Span) !Sexp {
        const out = try self.allocator().alloc(Sexp, children.len + 1);
        out[0] = .{ .tag = tag };
        @memcpy(out[1..], children);
        return .{ .list = List.withId(out, try self.wrapperNodeId(extent)) };
    }

    /// An untagged list built outside a reduction (a `group` value), with a
    /// node id recording `extent` like `newNode`.
    pub fn newList(self: *BaseParser, items: []const Sexp, extent: Span) !Sexp {
        const out = try self.allocator().dupe(Sexp, items);
        return .{ .list = List.withId(out, try self.wrapperNodeId(extent)) };
    }

    fn wrapperNodeId(self: *BaseParser, extent: Span) !NodeId {
        if (!nodeStore) return 0;
        if (self.nodes.len == 0) _ = try self.nodes.add(self.allocator(), .{ .span = .empty, .rule = 0 });
        return self.nodes.add(self.allocator(), .{ .span = extent, .rule = wrapperRule });
    }

    /// Number of node ids in use (ids run 1 .. nodeCount()).
    pub fn nodeCount(self: *const BaseParser) u32 {
        return self.nodes.len -| 1;
    }

    /// The side-band roles recorded for node `id`.
    fn sidesOf(self: *const BaseParser, id: NodeId) []const SideEntry {
        const all = self.sides.items;
        var lo: usize = 0;
        var hi: usize = all.len;
        while (lo < hi) {
            const mid = (lo + hi) / 2;
            if (all[mid].node < id) lo = mid + 1 else hi = mid;
        }
        var end = lo;
        while (end < all.len and all[end].node == id) end += 1;
        return all[lo..end];
    }

    /// The span a side-band role of `s` recorded (e.g. the `=` of a `set`).
    pub fn sideRole(self: *const BaseParser, s: Sexp, role: Role) ?Span {
        if (s != .list or s.list.id == 0) return null;
        for (self.sidesOf(s.list.id)) |e| if (e.role == role) return e.span;
        return null;
    }

    // -------------------------------------------------------------------------
    // Tree builders (called by the generated actions)
    // -------------------------------------------------------------------------

    /// Record an allocation failure; the reduction then fails the parse.
    fn oomNil(self: *BaseParser) Sexp {
        self.outOfMemory = true;
        return .nil;
    }

    /// Whether an untagged list can reach the tree (and so gets a node id)
    /// or is only ever spread into another list (plumbing: no node id).
    /// The generator decides per rule (see codegen/actions.zig).
    const ListUse = enum { tree, spread };

    /// A list node of the current reduction over freshly built `items`.
    inline fn node(self: *BaseParser, items: []const Sexp, comptime use: ListUse) Sexp {
        return .{ .list = List.withId(items, if (use == .tree) self.newNodeId() else 0) };
    }

    /// A list node over exactly `items` (fixed positions).
    fn build(self: *BaseParser, items: []const Sexp, comptime use: ListUse) Sexp {
        const out = self.allocator().dupe(Sexp, items) catch return self.oomNil();
        return self.node(out, use);
    }

    /// A nested node of the current reduction: its span covers just the
    /// elements lo..hi (0-based, inclusive) it references.
    fn nested(self: *BaseParser, s: Sexp, lo: usize, hi: usize) Sexp {
        if (nodeStore and s == .list and s.list.id != 0) {
            self.nodes.at(s.list.id).span = spanOf(self.elemsExtent(lo, hi));
        }
        return s;
    }

    /// A nested node that references no elements: empty, at the start of
    /// the reduction.
    fn nestedEmpty(self: *BaseParser, s: Sexp) Sexp {
        if (nodeStore and s == .list and s.list.id != 0) {
            const at = self.reduction.start;
            self.nodes.at(s.list.id).span = .{ .start = at, .end = at };
        }
        return s;
    }

    /// Length of `items` without trailing nils (all of it when positions
    /// are fixed by a schema).
    fn trimmedLen(items: []const Sexp) usize {
        var len = items.len;
        if (!keepTrailingNils) {
            while (len > 0 and items[len - 1] == .nil) len -= 1;
        }
        return len;
    }

    /// The default action: nothing, the one element, or an untagged list.
    fn list(self: *BaseParser, pass: []Sexp, comptime use: ListUse) Sexp {
        if (pass.len == 0) return .nil;
        if (pass.len == 1) return pass[0];
        const out = self.allocator().dupe(Sexp, pass) catch return self.oomNil();
        return self.node(out, use);
    }

    /// `()`: an empty list.
    fn emptyList(self: *BaseParser, comptime use: ListUse) Sexp {
        return self.node(&.{}, use);
    }

    /// `[head, ...tail]`
    fn spreadList(self: *BaseParser, head: Sexp, tail: Sexp, comptime use: ListUse) Sexp {
        const rest = tail.items();
        const out = self.allocator().alloc(Sexp, rest.len + 1) catch return self.oomNil();
        out[0] = head;
        @memcpy(out[1..], rest);
        return self.node(out, use);
    }

    /// Start a list holding the items of `base` (a list, else nothing)
    /// for an action that appends to it. A list from `keepList` is reused
    /// with its spare capacity, so a left-recursive list grows in amortized
    /// O(1) per element; it keeps its node id.
    fn extendList(self: *BaseParser, base: Sexp) !std.ArrayList(Sexp) {
        self.extending = 0;
        if (base != .list) return .empty;
        self.extending = base.list.id;
        const items = base.list.items();
        if (items.len > 0) if (self.listSpare.get(@intFromPtr(items.ptr))) |spare| {
            if (spare.len == items.len) {
                _ = self.listSpare.remove(@intFromPtr(items.ptr));
                var out: std.ArrayList(Sexp) = .initBuffer(@constCast(items.ptr)[0..spare.capacity]);
                out.items.len = items.len;
                return out;
            }
        };
        var out: std.ArrayList(Sexp) = .empty;
        try out.appendSlice(self.allocator(), items);
        return out;
    }

    /// Finish a list from `extendList`, recording its spare capacity.
    fn keepList(self: *BaseParser, out: *std.ArrayList(Sexp), comptime use: ListUse) Sexp {
        out.shrinkRetainingCapacity(trimmedLen(out.items));
        if (out.items.len > 0 and out.capacity > out.items.len) {
            self.listSpare.put(self.allocator(), @intFromPtr(out.items.ptr), .{
                .len = out.items.len,
                .capacity = out.capacity,
            }) catch return self.oomNil();
        }
        var id: NodeId = 0;
        if (nodeStore and use == .tree) {
            if (self.extending != 0) {
                id = self.extending;
                self.nodes.at(id).* = .{ .span = self.reductionSpan(), .rule = self.reduction.rule };
            } else id = self.newNodeId();
        }
        self.extending = 0;
        return .{ .list = List.withId(out.items, id) };
    }

    /// Finish a list built from scratch.
    fn finishList(self: *BaseParser, out: *std.ArrayList(Sexp), comptime use: ListUse) Sexp {
        out.shrinkRetainingCapacity(trimmedLen(out.items));
        const items = out.toOwnedSlice(self.allocator()) catch return self.oomNil();
        return self.node(items, use);
    }

    /// `(tag items...)`
    inline fn sexp(self: *BaseParser, comptime tag: Tag, items: []const Sexp) Sexp {
        const len = trimmedLen(items);
        const out = self.allocator().alloc(Sexp, len + 1) catch return self.oomNil();
        out[0] = .{ .tag = tag };
        @memcpy(out[1..], items[0..len]);
        return self.node(out, .tree);
    }

    /// `(tag ...spread)`
    inline fn sexpSpread(self: *BaseParser, comptime tag: Tag, spread: Sexp) Sexp {
        const items = spread.items();
        const len = trimmedLen(items);
        const out = self.allocator().alloc(Sexp, len + 1) catch return self.oomNil();
        out[0] = .{ .tag = tag };
        @memcpy(out[1..], items[0..len]);
        return self.node(out, .tree);
    }

    /// `(tag pos ...spread)`; just `(tag)` when both are empty (and
    /// positions are not fixed by a schema).
    inline fn sexpPosSpread(self: *BaseParser, comptime tag: Tag, pos: Sexp, spread: Sexp) Sexp {
        const items = spread.items();
        const len = trimmedLen(items);
        const bare = !keepTrailingNils and pos == .nil and len == 0;
        const out = self.allocator().alloc(Sexp, if (bare) 1 else len + 2) catch return self.oomNil();
        out[0] = .{ .tag = tag };
        if (!bare) {
            out[1] = pos;
            @memcpy(out[2..], items[0..len]);
        }
        return self.node(out, .tree);
    }

    // -------------------------------------------------------------------------
    // Diagnostics
    // -------------------------------------------------------------------------

    fn recordFailure(self: *BaseParser, state: u16, sym: u16) void {
        const tok = self.current;
        self.failure = .{
            .span = .{ .start = tok.pos, .end = tok.pos + tok.len },
            .symbol = sym,
            .cat = tok.cat,
            .state = state,
        };
    }

    /// The error of the last failed parse (the first one, for
    /// `parseTolerant`).
    pub fn lastError(self: *const BaseParser) ?Failure {
        return self.failure;
    }

    /// 1-based line and column of a byte offset.
    pub fn lineCol(self: *const BaseParser, pos: u32) struct { line: u32, col: u32 } {
        const end: usize = @min(pos, self.source.len);
        var line: u32 = 1;
        var lineStart: usize = 0;
        for (self.source[0..end], 0..) |c, i| {
            if (c == '\n') {
                line += 1;
                lineStart = i + 1;
            }
        }
        return .{ .line = line, .col = @intCast(end - lineStart + 1) };
    }

    /// `line:col: expected A, B or C, got D` for the last error.
    pub fn writeError(self: *const BaseParser, w: *std.Io.Writer) std.Io.Writer.Error!void {
        const f = self.failure orelse return;
        const at = self.lineCol(f.span.start);
        try w.print("{d}:{d}: expected ", .{ at.line, at.col });
        const want = expectedIn(f.state);
        for (want, 0..) |sym, i| {
            if (i > 0) try w.writeAll(if (i + 1 == want.len) " or " else ", ");
            try w.writeAll(symbolName(sym));
        }
        if (want.len == 0) try w.writeAll("nothing");
        try w.writeAll(", got ");
        const got = symbolName(f.symbol);
        try w.writeAll(if (f.symbol == errorSymbol or got.len == 0) @tagName(f.cat) else got);
    }

    pub fn printError(self: *const BaseParser) void {
        var buf: [512]u8 = undefined;
        var w: std.Io.Writer = .fixed(&buf);
        self.writeError(&w) catch {};
        std.debug.print("Parse error at {s}\n", .{w.buffered()});
    }

    /// What `state` accepts, reader-named: the `@errors` rules it waits
    /// for, then the tokens none of them begins with.
    pub fn expected(state: u16) []const u16 {
        return expectedIn(state);
    }

    /// The reader-facing name of a grammar symbol, as `writeError` prints
    /// it: its `@errors` or `@display` name, a literal as written, a token
    /// name in lower case; empty for other rules.
    pub fn symbolText(sym: u16) []const u8 {
        return symbolName(sym);
    }

    // -------------------------------------------------------------------------
    // Tolerant repair
    // -------------------------------------------------------------------------

    /// Whether `symbols` can be consumed from the current state, simulating
    /// reductions on a scratch copy of the state stack.
    fn accepts(self: *BaseParser, symbols: []const u16) !bool {
        const stack = &self.scratch;
        stack.clearRetainingCapacity();
        try stack.appendSlice(self.allocator(), self.stateStack.items);
        for (symbols) |sym| {
            while (true) {
                const action = getAction(stack.last().?, sym);
                if (action == 0) return false;
                if (action == -1) return true;
                if (action > 0) {
                    try stack.append(self.allocator(), @intCast(action));
                    break;
                }
                const rule: u16 = @intCast(-action - 2);
                stack.shrinkRetainingCapacity(stack.items.len - ruleLen[rule]);
                const next = getAction(stack.last().?, ruleLhs[rule]);
                if (next <= 0) return false;
                try stack.append(self.allocator(), @intCast(next));
            }
        }
        return true;
    }

    // -------------------------------------------------------------------------
    // Facts export
    // -------------------------------------------------------------------------

    /// Write the tree as flat facts, one per line, in pre-order:
    ///   (node ID KIND START END)        every list with a node id
    ///   (role ID ROLE CHILD...)         each non-nil child (a rest role
    ///                                   lists all its children)
    ///   (side ID ROLE START LEN)        each side-band role
    /// ROLE is the schema role name, else the child's index in the list.
    /// KIND is the head tag, or `group` for an untagged list. A CHILD is a
    /// node id, `leaf POS LEN`, `tag NAME`, `str "TEXT"`, or `(CHILD...)`
    /// for a list without a node id.
    pub fn writeFacts(self: *const BaseParser, w: *std.Io.Writer, root: Sexp) std.Io.Writer.Error!void {
        if (!nodeStore) @compileError("writeFacts needs the node store (@schema or --spans)");
        try self.factsOf(w, root);
    }

    fn factsOf(self: *const BaseParser, w: *std.Io.Writer, s: Sexp) std.Io.Writer.Error!void {
        if (s != .list) return;
        const l = s.list;
        const items = l.items();
        if (l.id != 0) {
            const k = s.kind();
            const sp = self.span(s);
            try w.print("(node {d} ", .{l.id});
            if (k) |t| try writeName(w, nameOf(t)) else try w.writeAll("group");
            try w.print(" {d} {d})\n", .{ sp.start, sp.end });
            var i: usize = if (k != null) 1 else 0;
            while (i < items.len) : (i += 1) {
                if (k) |t| if (restRoleOf(t)) |rest| if (i >= rest.slot) {
                    try w.print("(role {d} ", .{l.id});
                    try writeName(w, nameOf(rest.role));
                    for (items[i..]) |child| {
                        try w.writeByte(' ');
                        try self.factChild(w, child);
                    }
                    try w.writeAll(")\n");
                    break;
                };
                if (items[i] == .nil) continue;
                try w.print("(role {d} ", .{l.id});
                if (if (k) |t| roleAt(t, i) else null) |role| try writeName(w, nameOf(role)) else try w.print("{d}", .{i});
                try w.writeByte(' ');
                try self.factChild(w, items[i]);
                try w.writeAll(")\n");
            }
            for (self.sidesOf(l.id)) |e| {
                try w.print("(side {d} ", .{l.id});
                try writeName(w, nameOf(e.role));
                try w.print(" {d} {d})\n", .{ e.span.start, e.span.len() });
            }
        }
        for (items) |child| try self.factsOf(w, child);
    }

    fn factChild(self: *const BaseParser, w: *std.Io.Writer, s: Sexp) std.Io.Writer.Error!void {
        switch (s) {
            .nil => try w.writeAll("_"),
            .tag => |t| {
                try w.writeAll("tag ");
                try writeName(w, nameOf(t));
            },
            .src => |x| try w.print("leaf {d} {d}", .{ x.pos, x.len }),
            .str => |x| {
                try w.writeAll("str ");
                try writeQuoted(w, x);
            },
            .list => |l| if (l.id != 0) try w.print("{d}", .{l.id}) else {
                try w.writeByte('(');
                for (l.items(), 0..) |child, i| {
                    if (i > 0) try w.writeByte(' ');
                    try self.factChild(w, child);
                }
                try w.writeByte(')');
            },
        }
    }

    /// A name as a bare symbol, or quoted when it has s-expression syntax.
    fn writeName(w: *std.Io.Writer, name: []const u8) std.Io.Writer.Error!void {
        const plain = name.len > 0 and for (name) |c| {
            if (c <= ' ' or c == '(' or c == ')' or c == '"' or c == '\\' or c == 0x7f) break false;
        } else true;
        if (plain) try w.writeAll(name) else try writeQuoted(w, name);
    }

    fn writeQuoted(w: *std.Io.Writer, text: []const u8) std.Io.Writer.Error!void {
        try w.writeByte('"');
        for (text) |c| switch (c) {
            '"', '\\' => {
                try w.writeByte('\\');
                try w.writeByte(c);
            },
            '\n' => try w.writeAll("\\n"),
            '\t' => try w.writeAll("\\t"),
            else => if (c < ' ' or c == 0x7f) try w.print("\\x{x:0>2}", .{c}) else try w.writeByte(c),
        };
        try w.writeByte('"');
    }
};


// =============================================================================
// IR accessors (from @schema)
// =============================================================================

// Inside `ir`, generated kind and role names (a kind `tag` has the view
// `ir.Tag`) could shadow the module's own names, so `ir` refers to them
// through these aliases, whose names no kind or role can take.
const @"ir.Sexp" = Sexp;
const @"ir.Tag" = Tag;
const @"ir.Role" = Role;

/// Role-based access to schema nodes. `get`/`rest` look the slot up by the
/// node's kind; the per-kind views (`ir.Set.target(node)`) are resolved at
/// compile time. Asking for a role the node's kind does not have panics in
/// safety-checked builds and yields nil (or no items) otherwise.
pub const ir = struct {
    /// The child in `role` (nil when absent).
    pub fn get(node: @"ir.Sexp", role: @"ir.Role") @"ir.Sexp" {
        const k = kindFor(node, "ir.get", role) orelse return .nil;
        const at = slotOf(k, role) orelse return missing(k, role, "ir.get", @as(@"ir.Sexp", .nil));
        const items = node.list.items();
        return if (at < items.len) items[at] else .nil;
    }

    /// The children in rest role `role`.
    pub fn rest(node: @"ir.Sexp", role: @"ir.Role") []const @"ir.Sexp" {
        const k = kindFor(node, "ir.rest", role) orelse return &.{};
        const at = restSlotOf(k, role) orelse return missing(k, role, "ir.rest", @as([]const @"ir.Sexp", &.{}));
        const items = node.list.items();
        return if (at < items.len) items[at..] else &.{};
    }

    /// Whether nodes of `kind` have `role` (slot or rest role).
    pub fn has(kind: @"ir.Tag", role: @"ir.Role") bool {
        return slotOf(kind, role) != null or restSlotOf(kind, role) != null;
    }

    /// The slot of `role` in nodes of `kind` (the head is slot 0), at
    /// compile time; a compile error when `kind` has no such slot role. For
    /// lang Parser wrappers that build or rewrite nodes:
    /// `items[ir.slot(.set, .value)] = v`.
    pub fn slot(comptime kind: @"ir.Tag", comptime role: @"ir.Role") usize {
        return comptime slotOf(kind, role) orelse
            @compileError("kind '" ++ @tagName(kind) ++ "' has no slot role '" ++ @tagName(role) ++ "'");
    }

    /// The first slot of rest role `role` in nodes of `kind`, at compile
    /// time; a compile error when `kind` has no such rest role.
    pub fn restSlot(comptime kind: @"ir.Tag", comptime role: @"ir.Role") usize {
        return comptime restSlotOf(kind, role) orelse
            @compileError("kind '" ++ @tagName(kind) ++ "' has no rest role '" ++ @tagName(role) ++ "'");
    }

    /// The fixed length of `kind` nodes: the head plus one slot per slot
    /// role (rest children follow).
    pub fn width(comptime kind: @"ir.Tag") usize {
        return comptime blk: {
            var n: usize = 1;
            while (roleAt(kind, n) != null) n += 1;
            break :blk n;
        };
    }

    fn kindFor(node: @"ir.Sexp", comptime what: []const u8, role: @"ir.Role") ?@"ir.Tag" {
        if (node.kind()) |k| return k;
        if (@import("builtin").optimize.runtimeSafety()) std.debug.panic(what ++ "(.{s}): not a schema node: {s}", .{ @tagName(role), @tagName(node) });
        return null;
    }

    fn missing(kind: @"ir.Tag", role: @"ir.Role", comptime what: []const u8, value: anytype) @TypeOf(value) {
        if (@import("builtin").optimize.runtimeSafety()) {
            const hint = if (slotOf(kind, role) != null) " (a slot role; use ir.get)" else if (restSlotOf(kind, role) != null) " (a rest role; use ir.rest)" else "";
            std.debug.panic(what ++ ": kind '{s}' has no role '{s}'{s}", .{ @tagName(kind), @tagName(role), hint });
        }
        return value;
    }

    pub const Module = struct {
        pub fn @"stmts"(@"ir.node": @"ir.Sexp") []const @"ir.Sexp" {
            return @"ir.restAt"(@"ir.node", .@"module", 1, "ir.Module.stmts");
        }
    };
    pub const Set = struct {
        pub fn @"op"(@"ir.node": @"ir.Sexp") @"ir.Sexp" {
            return @"ir.at"(@"ir.node", .@"set", 1, "ir.Set.op");
        }
        pub fn @"target"(@"ir.node": @"ir.Sexp") @"ir.Sexp" {
            return @"ir.at"(@"ir.node", .@"set", 2, "ir.Set.target");
        }
        pub fn @"value"(@"ir.node": @"ir.Sexp") @"ir.Sexp" {
            return @"ir.at"(@"ir.node", .@"set", 3, "ir.Set.value");
        }
    };
    pub const Let = struct {
        pub fn @"name"(@"ir.node": @"ir.Sexp") @"ir.Sexp" {
            return @"ir.at"(@"ir.node", .@"let", 1, "ir.Let.name");
        }
        pub fn @"type"(@"ir.node": @"ir.Sexp") @"ir.Sexp" {
            return @"ir.at"(@"ir.node", .@"let", 2, "ir.Let.type");
        }
        pub fn @"value"(@"ir.node": @"ir.Sexp") @"ir.Sexp" {
            return @"ir.at"(@"ir.node", .@"let", 3, "ir.Let.value");
        }
    };
    pub const If = struct {
        pub fn @"kw"(@"ir.node": @"ir.Sexp") @"ir.Sexp" {
            return @"ir.at"(@"ir.node", .@"if", 1, "ir.If.kw");
        }
        pub fn @"cond"(@"ir.node": @"ir.Sexp") @"ir.Sexp" {
            return @"ir.at"(@"ir.node", .@"if", 2, "ir.If.cond");
        }
        pub fn @"then"(@"ir.node": @"ir.Sexp") @"ir.Sexp" {
            return @"ir.at"(@"ir.node", .@"if", 3, "ir.If.then");
        }
        pub fn @"else"(@"ir.node": @"ir.Sexp") @"ir.Sexp" {
            return @"ir.at"(@"ir.node", .@"if", 4, "ir.If.else");
        }
    };
    pub const For = struct {
        pub fn @"mode"(@"ir.node": @"ir.Sexp") @"ir.Sexp" {
            return @"ir.at"(@"ir.node", .@"for", 1, "ir.For.mode");
        }
        pub fn @"var"(@"ir.node": @"ir.Sexp") @"ir.Sexp" {
            return @"ir.at"(@"ir.node", .@"for", 2, "ir.For.var");
        }
        pub fn @"index"(@"ir.node": @"ir.Sexp") @"ir.Sexp" {
            return @"ir.at"(@"ir.node", .@"for", 3, "ir.For.index");
        }
        pub fn @"iter"(@"ir.node": @"ir.Sexp") @"ir.Sexp" {
            return @"ir.at"(@"ir.node", .@"for", 4, "ir.For.iter");
        }
        pub fn @"body"(@"ir.node": @"ir.Sexp") @"ir.Sexp" {
            return @"ir.at"(@"ir.node", .@"for", 5, "ir.For.body");
        }
    };
    pub const Call = struct {
        pub fn @"callee"(@"ir.node": @"ir.Sexp") @"ir.Sexp" {
            return @"ir.at"(@"ir.node", .@"call", 1, "ir.Call.callee");
        }
        pub fn @"args"(@"ir.node": @"ir.Sexp") []const @"ir.Sexp" {
            return @"ir.restAt"(@"ir.node", .@"call", 2, "ir.Call.args");
        }
    };
    pub const Swap = struct {
        pub fn @"a"(@"ir.node": @"ir.Sexp") @"ir.Sexp" {
            return @"ir.at"(@"ir.node", .@"swap", 1, "ir.Swap.a");
        }
        pub fn @"b"(@"ir.node": @"ir.Sexp") @"ir.Sexp" {
            return @"ir.at"(@"ir.node", .@"swap", 2, "ir.Swap.b");
        }
        pub fn @"c"(@"ir.node": @"ir.Sexp") @"ir.Sexp" {
            return @"ir.at"(@"ir.node", .@"swap", 3, "ir.Swap.c");
        }
        pub fn @"d"(@"ir.node": @"ir.Sexp") @"ir.Sexp" {
            return @"ir.at"(@"ir.node", .@"swap", 4, "ir.Swap.d");
        }
    };
    pub const Return = struct {
        pub fn @"value"(@"ir.node": @"ir.Sexp") @"ir.Sexp" {
            return @"ir.at"(@"ir.node", .@"return", 1, "ir.Return.value");
        }
    };
    pub const Yield = struct {
        pub fn @"value"(@"ir.node": @"ir.Sexp") @"ir.Sexp" {
            return @"ir.at"(@"ir.node", .@"yield", 1, "ir.Yield.value");
        }
    };
    pub const Pass = struct {
    };
    pub const Array = struct {
        pub fn @"items"(@"ir.node": @"ir.Sexp") []const @"ir.Sexp" {
            return @"ir.restAt"(@"ir.node", .@"array", 1, "ir.Array.items");
        }
    };
    pub const Neg = struct {
        pub fn @"value"(@"ir.node": @"ir.Sexp") @"ir.Sexp" {
            return @"ir.at"(@"ir.node", .@"neg", 1, "ir.Neg.value");
        }
    };
    pub const Num = struct {
        pub fn @"value"(@"ir.node": @"ir.Sexp") @"ir.Sexp" {
            return @"ir.at"(@"ir.node", .@"num", 1, "ir.Num.value");
        }
    };
    pub const Name = struct {
        pub fn @"id"(@"ir.node": @"ir.Sexp") @"ir.Sexp" {
            return @"ir.at"(@"ir.node", .@"name", 1, "ir.Name.id");
        }
    };
    pub const @"+" = struct {
        pub fn @"left"(@"ir.node": @"ir.Sexp") @"ir.Sexp" {
            return @"ir.at"(@"ir.node", .@"+", 1, "ir.@\"+\".left");
        }
        pub fn @"right"(@"ir.node": @"ir.Sexp") @"ir.Sexp" {
            return @"ir.at"(@"ir.node", .@"+", 2, "ir.@\"+\".right");
        }
    };
    pub const @"-" = struct {
        pub fn @"left"(@"ir.node": @"ir.Sexp") @"ir.Sexp" {
            return @"ir.at"(@"ir.node", .@"-", 1, "ir.@\"-\".left");
        }
        pub fn @"right"(@"ir.node": @"ir.Sexp") @"ir.Sexp" {
            return @"ir.at"(@"ir.node", .@"-", 2, "ir.@\"-\".right");
        }
    };
    pub const @"*" = struct {
        pub fn @"left"(@"ir.node": @"ir.Sexp") @"ir.Sexp" {
            return @"ir.at"(@"ir.node", .@"*", 1, "ir.@\"*\".left");
        }
        pub fn @"right"(@"ir.node": @"ir.Sexp") @"ir.Sexp" {
            return @"ir.at"(@"ir.node", .@"*", 2, "ir.@\"*\".right");
        }
    };
    pub const @"/" = struct {
        pub fn @"left"(@"ir.node": @"ir.Sexp") @"ir.Sexp" {
            return @"ir.at"(@"ir.node", .@"/", 1, "ir.@\"/\".left");
        }
        pub fn @"right"(@"ir.node": @"ir.Sexp") @"ir.Sexp" {
            return @"ir.at"(@"ir.node", .@"/", 2, "ir.@\"/\".right");
        }
    };
    pub const Note = struct {
        pub fn @"text"(@"ir.node": @"ir.Sexp") @"ir.Sexp" {
            return @"ir.at"(@"ir.node", .@"note", 1, "ir.Note.text");
        }
    };
};

/// Slot `slot` of `node`, a node of `kind` (checked in safety builds).
fn @"ir.at"(node: Sexp, comptime kind: Tag, comptime slot: usize, comptime what: []const u8) Sexp {
    @"ir.check"(node, kind, what);
    const items = node.items();
    return if (slot < items.len) items[slot] else .nil;
}

/// The children of `node` from `slot` on.
fn @"ir.restAt"(node: Sexp, comptime kind: Tag, comptime slot: usize, comptime what: []const u8) []const Sexp {
    @"ir.check"(node, kind, what);
    const items = node.items();
    return if (slot < items.len) items[slot..] else &.{};
}

fn @"ir.check"(node: Sexp, comptime kind: Tag, comptime what: []const u8) void {
    if (@import("builtin").optimize.runtimeSafety() and !node.isKind(kind)) {
        const actual = if (node.kind()) |k| @tagName(k) else @tagName(node);
        std.debug.panic(what ++ ": node is '{s}', not '" ++ @tagName(kind) ++ "'", .{actual});
    }
}


// =============================================================================
// Grammar
// =============================================================================

/// Node spans and rule ids are recorded (`@schema` or `--spans`).
pub const nodeStore = true;
/// Element extents are kept for side-band labels and nested nodes.
const elemEnds = true;
/// Lists keep trailing nils: positions are fixed by the schema.
const keepTrailingNils = true;
const hasTrivia = true;
const hasRepair = true;
const numSymbols = 48;
const endSymbol: u16 = 1;
const errorSymbol: u16 = 2;

fn tokenToSymbol(_: *BaseParser, token: Token) u16 {
    return switch (token.cat) {
        .@"eof" => 1,
        .@"newline" => 8,
        .@"let" => 14,
        .@"ident" => 15,
        .@"if" => 17,
        .@"then" => 18,
        .@"unless" => 19,
        .@"else" => 20,
        .@"for" => 21,
        .@"ptr" => 22,
        .@"in" => 23,
        .@"do" => 24,
        .@"call" => 26,
        .@"swap" => 32,
        .@"with" => 33,
        .@"return" => 34,
        .@"yield" => 35,
        .@"integer" => 36,
        .@"pass" => 37,
        .@"eq" => 9,
        .@"colon" => 16,
        .@"comma" => 25,
        .@"lparen" => 27,
        .@"rparen" => 31,
        .@"minus" => 38,
        .@"lbracket" => 39,
        .@"rbracket" => 40,
        .@"plus" => 45,
        .@"star" => 46,
        .@"slash" => 47,
        .@"plus_eq" => 11,
        .@"minus_eq" => 12,
        .@"star_eq" => 13,
        else => 2, // error
    };
}

fn executeAction(self: *BaseParser, ruleId: u16, pass: []Sexp) Sexp {
    @setEvalBranchQuota(1_000_000);
    return switch (ruleId) {
        0 => blk: { var out: std.ArrayList(Sexp) = .empty; out.append(self.allocator(), .{ .tag = .@"module" }) catch break :blk self.oomNil(); for (pass[0].items()) |item| out.append(self.allocator(), item) catch break :blk self.oomNil(); break :blk self.finishList(&out, .tree); },
        1 => self.build(&.{ pass[0] }, .spread),
        2 => blk: { var out = self.extendList(pass[0]) catch break :blk self.oomNil(); out.append(self.allocator(), pass[2]) catch break :blk self.oomNil(); break :blk self.keepList(&out, .spread); },
        3 => pass[0],
        4 => self.build(&.{ .{ .tag = .@"set" }, .nil, pass[0], pass[2] }, .tree),
        5 => self.build(&.{ .{ .tag = .@"set" }, .{ .tag = .@"+=" }, pass[0], pass[2] }, .tree),
        6 => self.build(&.{ .{ .tag = .@"set" }, .{ .tag = .@"-=" }, pass[0], pass[2] }, .tree),
        7 => self.build(&.{ .{ .tag = .@"set" }, .{ .tag = .@"*=" }, pass[0], pass[2] }, .tree),
        8 => self.build(&.{ .{ .tag = .@"set" }, .{ .tag = .@"+=" }, self.nested(self.build(&.{ .{ .tag = .@"name" }, pass[1] }, .tree), 1, 1), pass[3] }, .tree),
        9 => self.build(&.{ .{ .tag = .@"let" }, pass[1], .nil, pass[3] }, .tree),
        10 => self.build(&.{ .{ .tag = .@"let" }, pass[1], pass[3], pass[5] }, .tree),
        11 => self.build(&.{ .{ .tag = .@"if" }, pass[0], pass[1], pass[3], .nil }, .tree),
        12 => self.build(&.{ .{ .tag = .@"if" }, pass[0], pass[1], pass[3], .nil }, .tree),
        13 => self.build(&.{ .{ .tag = .@"if" }, pass[0], pass[1], pass[3], pass[5] }, .tree),
        14 => self.build(&.{ .{ .tag = .@"if" }, pass[0], pass[1], pass[3], pass[5] }, .tree),
        15 => self.build(&.{ .{ .tag = .@"for" }, .{ .tag = .@"ptr" }, pass[2], .nil, pass[4], pass[6] }, .tree),
        16 => self.build(&.{ .{ .tag = .@"for" }, .{ .tag = .@"ptr" }, pass[2], pass[4], pass[6], pass[8] }, .tree),
        17 => self.build(&.{ .{ .tag = .@"for" }, .nil, pass[1], .nil, pass[3], pass[5] }, .tree),
        18 => self.spreadList(pass[0], pass[1], .spread),
        19 => self.spreadList(pass[1], pass[2], .spread),
        20 => self.emptyList(.spread),
        21 => pass[0],
        22 => .nil,
        23 => blk: { var out: std.ArrayList(Sexp) = .empty; out.append(self.allocator(), .{ .tag = .@"call" }) catch break :blk self.oomNil(); out.append(self.allocator(), pass[1]) catch break :blk self.oomNil(); for (pass[3].items()) |item| out.append(self.allocator(), item) catch break :blk self.oomNil(); break :blk self.finishList(&out, .tree); },
        24 => self.build(&.{ .{ .tag = .@"swap" }, pass[2], pass[4], pass[8], pass[10] }, .tree),
        25 => self.build(&.{ .{ .tag = .@"return" }, .nil }, .tree),
        26 => self.build(&.{ .{ .tag = .@"return" }, pass[1] }, .tree),
        27 => self.build(&.{ .{ .tag = .@"yield" }, .nil }, .tree),
        28 => self.build(&.{ .{ .tag = .@"yield" }, pass[1] }, .tree),
        29 => self.build(&.{ .{ .tag = .@"yield" }, pass[1] }, .tree),
        30 => self.build(&.{ .{ .tag = .@"pass" } }, .tree),
        31 => self.build(&.{ .{ .tag = .@"pass" } }, .tree),
        32 => pass[0],
        33 => self.build(&.{ .{ .tag = .@"name" }, pass[0] }, .tree),
        34 => pass[0],
        35 => self.build(&.{ .{ .tag = .@"num" }, pass[0] }, .tree),
        36 => self.build(&.{ .{ .tag = .@"neg" }, self.nested(self.build(&.{ .{ .tag = .@"num" }, pass[1] }, .tree), 1, 1) }, .tree),
        37 => pass[1],
        38 => blk: { var out: std.ArrayList(Sexp) = .empty; out.append(self.allocator(), .{ .tag = .@"array" }) catch break :blk self.oomNil(); for (pass[1].items()) |item| out.append(self.allocator(), item) catch break :blk self.oomNil(); break :blk self.finishList(&out, .tree); },
        40 => self.build(&.{ .{ .tag = .@"+" }, pass[0], pass[2] }, .tree),
        41 => self.build(&.{ .{ .tag = .@"-" }, pass[0], pass[2] }, .tree),
        42 => pass[0],
        43 => self.build(&.{ .{ .tag = .@"*" }, pass[0], pass[2] }, .tree),
        44 => self.build(&.{ .{ .tag = .@"/" }, pass[0], pass[2] }, .tree),
        45 => pass[0],
        46 => pass[0],
        else => unreachable,
    };
}

const ruleLhs = [_]u16{ 3, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 28, 29, 29, 30, 30, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 7, 7, 7, 7, 7, 42, 43, 43, 43, 44, 44, 44, 10 };
const ruleLen = [_]u8{ 1, 1, 3, 2, 3, 3, 3, 3, 4, 4, 6, 4, 4, 6, 6, 7, 9, 6, 2, 3, 0, 1, 0, 5, 12, 1, 2, 1, 2, 2, 2, 4, 1, 1, 1, 1, 2, 3, 3, 3, 3, 3, 1, 3, 3, 1, 1 };

// Parse table: 113 states x 48 symbols. 0 = error, > 0 = shift or
// goto, -1 = accept, <= -2 = reduce rule (-a - 2).
const numStates = 113;

const sparse = [numStates][]const i16{
    &.{41,1},
    &.{3,18,4,20,5,6,6,3,7,16,10,7,14,23,15,21,17,12,19,11,21,14,26,5,27,10,32,19,34,2,35,4,36,8,37,13,38,9,39,15,43,17,44,22},
    &.{1,-27,6,24,7,16,8,-27,10,25,15,21,20,-27,27,10,36,8,38,9,39,15,43,17,44,22},
    &.{1,-36,8,-36,9,26,11,27,12,28,13,29,20,-36,38,-36,45,-36,46,-36,47,-36},
    &.{1,-29,8,-29,15,30,20,-29,36,31},
    &.{15,32},
    &.{1,-3,8,-3},
    &.{1,-34,8,-34,20,-34},
    &.{1,-37,8,-37,18,-37,20,-37,24,-37,25,-37,31,-37,38,-37,40,-37,45,-37,46,-37,47,-37},
    &.{36,33},
    &.{6,24,7,16,10,34,15,21,27,10,36,8,38,9,39,15,43,17,44,22},
    &.{6,24,7,16,10,35,15,21,27,10,36,8,38,9,39,15,43,17,44,22},
    &.{6,24,7,16,10,36,15,21,27,10,36,8,38,9,39,15,43,17,44,22},
    &.{15,37,27,38},
    &.{15,39,22,40},
    &.{6,24,7,16,10,43,15,21,27,10,28,41,30,42,36,8,38,9,39,15,40,-24,43,17,44,22},
    &.{1,-47,8,-47,18,-47,20,-47,24,-47,25,-47,31,-47,38,-47,40,-47,45,-47,46,-47,47,-47},
    &.{1,-48,8,-48,18,-48,20,-48,24,-48,25,-48,31,-48,38,44,40,-48,45,45},
    &.{1,-1},
    &.{27,47},
    &.{1,-2,8,48},
    &.{1,-35,8,-35,9,-35,11,-35,12,-35,13,-35,18,-35,20,-35,24,-35,25,-35,31,-35,38,-35,40,-35,45,-35,46,-35,47,-35},
    &.{1,-44,8,-44,18,-44,20,-44,24,-44,25,-44,31,-44,38,-44,40,-44,45,-44,46,50,47,49},
    &.{15,51},
    &.{1,-36,8,-36,18,-36,20,-36,24,-36,25,-36,31,-36,38,-36,40,-36,45,-36,46,-36,47,-36},
    &.{1,-28,8,-28,20,-28},
    &.{6,24,7,16,10,52,15,21,27,10,36,8,38,9,39,15,43,17,44,22},
    &.{6,24,7,16,10,53,15,21,27,10,36,8,38,9,39,15,43,17,44,22},
    &.{6,24,7,16,10,54,15,21,27,10,36,8,38,9,39,15,43,17,44,22},
    &.{6,24,7,16,10,55,15,21,27,10,36,8,38,9,39,15,43,17,44,22},
    &.{1,-30,8,-30,20,-30},
    &.{1,-31,8,-31,20,-31},
    &.{27,56},
    &.{1,-38,8,-38,18,-38,20,-38,24,-38,25,-38,31,-38,38,-38,40,-38,45,-38,46,-38,47,-38},
    &.{31,57},
    &.{18,58},
    &.{18,59},
    &.{1,-32,8,-32,20,-32},
    &.{15,60},
    &.{23,61},
    &.{15,62},
    &.{31,-23,40,-23},
    &.{40,63},
    &.{25,65,29,64,31,-22,40,-22},
    &.{6,24,7,16,15,21,27,10,36,8,38,9,39,15,44,66},
    &.{6,24,7,16,15,21,27,10,36,8,38,9,39,15,44,67},
    &.{1,-1},
    &.{15,68},
    &.{1,-5,5,69,6,3,7,16,8,-5,10,7,14,23,15,21,17,12,19,11,21,14,26,5,27,10,32,19,34,2,35,4,36,8,37,13,38,9,39,15,43,17,44,22},
    &.{6,24,7,70,15,21,27,10,36,8,38,9,39,15},
    &.{6,24,7,71,15,21,27,10,36,8,38,9,39,15},
    &.{9,73,11,72,16,74},
    &.{1,-6,8,-6,20,-6},
    &.{1,-7,8,-7,20,-7},
    &.{1,-8,8,-8,20,-8},
    &.{1,-9,8,-9,20,-9},
    &.{6,24,7,16,10,43,15,21,27,10,28,41,30,75,31,-24,36,8,38,9,39,15,43,17,44,22},
    &.{1,-39,8,-39,18,-39,20,-39,24,-39,25,-39,31,-39,38,-39,40,-39,45,-39,46,-39,47,-39},
    &.{5,76,6,3,7,16,10,7,14,23,15,21,17,12,19,11,21,14,26,5,27,10,32,19,34,2,35,4,36,8,37,13,38,9,39,15,43,17,44,22},
    &.{5,77,6,3,7,16,10,7,14,23,15,21,17,12,19,11,21,14,26,5,27,10,32,19,34,2,35,4,36,8,37,13,38,9,39,15,43,17,44,22},
    &.{31,78},
    &.{6,24,7,16,10,79,15,21,27,10,36,8,38,9,39,15,43,17,44,22},
    &.{23,81,25,80},
    &.{1,-40,8,-40,18,-40,20,-40,24,-40,25,-40,31,-40,38,-40,40,-40,45,-40,46,-40,47,-40},
    &.{31,-20,40,-20},
    &.{6,24,7,16,10,82,15,21,27,10,36,8,38,9,39,15,43,17,44,22},
    &.{1,-43,8,-43,18,-43,20,-43,24,-43,25,-43,31,-43,38,-43,40,-43,45,-43,46,50,47,49},
    &.{1,-42,8,-42,18,-42,20,-42,24,-42,25,-42,31,-42,38,-42,40,-42,45,-42,46,50,47,49},
    &.{25,83},
    &.{1,-4,8,-4},
    &.{1,-46,8,-46,18,-46,20,-46,24,-46,25,-46,31,-46,38,-46,40,-46,45,-46,46,-46,47,-46},
    &.{1,-45,8,-45,18,-45,20,-45,24,-45,25,-45,31,-45,38,-45,40,-45,45,-45,46,-45,47,-45},
    &.{6,24,7,16,10,84,15,21,27,10,36,8,38,9,39,15,43,17,44,22},
    &.{6,24,7,16,10,85,15,21,27,10,36,8,38,9,39,15,43,17,44,22},
    &.{6,86,15,21},
    &.{31,87},
    &.{1,-14,8,-14,20,88},
    &.{1,-13,8,-13,20,89},
    &.{1,-33,8,-33,20,-33},
    &.{24,90},
    &.{15,91},
    &.{6,24,7,16,10,92,15,21,27,10,36,8,38,9,39,15,43,17,44,22},
    &.{25,65,29,93,31,-22,40,-22},
    &.{15,94},
    &.{1,-10,8,-10,20,-10},
    &.{1,-11,8,-11,20,-11},
    &.{9,95},
    &.{1,-25,8,-25,20,-25},
    &.{5,96,6,3,7,16,10,7,14,23,15,21,17,12,19,11,21,14,26,5,27,10,32,19,34,2,35,4,36,8,37,13,38,9,39,15,43,17,44,22},
    &.{5,97,6,3,7,16,10,7,14,23,15,21,17,12,19,11,21,14,26,5,27,10,32,19,34,2,35,4,36,8,37,13,38,9,39,15,43,17,44,22},
    &.{5,98,6,3,7,16,10,7,14,23,15,21,17,12,19,11,21,14,26,5,27,10,32,19,34,2,35,4,36,8,37,13,38,9,39,15,43,17,44,22},
    &.{23,99},
    &.{24,100},
    &.{31,-21,40,-21},
    &.{31,101},
    &.{6,24,7,16,10,102,15,21,27,10,36,8,38,9,39,15,43,17,44,22},
    &.{1,-16,8,-16,20,-16},
    &.{1,-15,8,-15,20,-15},
    &.{1,-19,8,-19,20,-19},
    &.{6,24,7,16,10,103,15,21,27,10,36,8,38,9,39,15,43,17,44,22},
    &.{5,104,6,3,7,16,10,7,14,23,15,21,17,12,19,11,21,14,26,5,27,10,32,19,34,2,35,4,36,8,37,13,38,9,39,15,43,17,44,22},
    &.{33,105},
    &.{1,-12,8,-12,20,-12},
    &.{24,106},
    &.{1,-17,8,-17,20,-17},
    &.{27,107},
    &.{5,108,6,3,7,16,10,7,14,23,15,21,17,12,19,11,21,14,26,5,27,10,32,19,34,2,35,4,36,8,37,13,38,9,39,15,43,17,44,22},
    &.{15,109},
    &.{1,-18,8,-18,20,-18},
    &.{25,110},
    &.{15,111},
    &.{31,112},
    &.{1,-26,8,-26,20,-26},
};

const parseTable = blk: {
    @setEvalBranchQuota(100000);
    var t: [numStates][numSymbols]i16 = @splat(@splat(0));
    for (sparse, 0..) |row, state| {
        var i: usize = 0;
        while (i < row.len) : (i += 2) {
            t[state][@intCast(row[i])] = row[i + 1];
        }
    }
    break :blk t;
};

fn getAction(state: u16, sym: u16) i16 {
    return parseTable[state][sym];
}

// X "c" excludes: shift the hinted token instead of reducing when it
// touches the previous token (pre == 0)
const xExcludes = [_]struct { sym: u16, shift: u16 }{
};

fn getImmediateShift(_: u16, _: u16) ?i16 {
    return null;
}

fn startState(start: Start) u16 {
    return switch (start) {
        .@"program" => 0,
    };
}

fn startMarker(start: Start) u16 {
    return switch (start) {
        .@"program" => 41,
    };
}

/// Expected symbols per state: state s expects list i = expectedOf[s],
/// expectedSymbols[expectedOffsets[i]..expectedOffsets[i + 1]].
const expectedSymbols = [_]u16{
    10, 14, 17, 19, 21, 26, 32, 34, 35, 37, 10, 1, 8, 20, 1, 8, 9, 11, 12, 13, 20, 38, 45, 46,
    47, 1, 8, 15, 20, 36, 15, 1, 8, 1, 8, 20, 1, 8, 18, 20, 24, 25, 31, 38, 40, 45, 46, 47,
    36, 10, 15, 27, 15, 22, 10, 40, 1, 8, 18, 20, 24, 25, 31, 38, 40, 45, 1, 27, 1, 8, 9, 11,
    12, 13, 18, 20, 24, 25, 31, 38, 40, 45, 46, 47, 31, 18, 23, 31, 40, 40, 25, 31, 40, 15, 27, 36,
    38, 39, 10, 1, 8, 14, 17, 19, 21, 26, 32, 34, 35, 37, 9, 11, 16, 10, 31, 23, 25, 25, 24, 9,
    33,
};
const expectedOffsets = [_]u32{
    0, 0, 10, 14, 25, 30, 31, 33, 36, 48, 49, 50, 52, 54, 56, 66, 67, 68, 84, 85, 86, 87, 89, 90,
    93, 98, 110, 113, 115, 117, 118, 119, 120, 121,
};
const expectedOf = [_]u16{
    0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 10, 10, 11, 12, 13, 8, 14, 15, 16, 6, 17, 8, 5,
    8, 7, 10, 10, 10, 10, 7, 7, 16, 8, 18, 19, 19, 7, 5, 20, 5, 21, 22, 23, 24, 24, 15, 5,
    25, 24, 24, 26, 7, 7, 7, 7, 27, 8, 1, 1, 18, 10, 28, 8, 21, 10, 8, 8, 29, 6, 8, 8,
    10, 10, 5, 18, 7, 7, 7, 30, 5, 10, 23, 5, 7, 7, 31, 7, 1, 1, 1, 20, 30, 21, 18, 10,
    7, 7, 7, 10, 1, 32, 7, 30, 7, 16, 1, 5, 7, 29, 5, 18, 7,
};

fn expectedIn(state: u16) []const u16 {
    const i = expectedOf[state];
    return expectedSymbols[expectedOffsets[i]..expectedOffsets[i + 1]];
}

fn symbolName(sym: u16) []const u8 {
    return switch (sym) {
        1 => "end of input",
        8 => "newline",
        9 => "'='",
        10 => "an expression",
        11 => "\"+=\"",
        12 => "\"-=\"",
        13 => "\"*=\"",
        14 => "let",
        15 => "a name",
        16 => "\":\"",
        17 => "if",
        18 => "then",
        19 => "unless",
        20 => "else",
        21 => "for",
        22 => "ptr",
        23 => "in",
        24 => "do",
        25 => "\",\"",
        26 => "call",
        27 => "\"(\"",
        31 => "\")\"",
        32 => "swap",
        33 => "with",
        34 => "return",
        35 => "yield",
        36 => "integer",
        37 => "pass",
        38 => "\"-\"",
        39 => "\"[\"",
        40 => "\"]\"",
        45 => "\"+\"",
        46 => "\"*\"",
        47 => "\"/\"",
        else => "",
    };
}

/// `@trivia` tokens: kept on the trivia channel, never parsed.
fn isTrivia(cat: TokenCat) bool {
    return switch (cat) {
        .@"comment" => true,
        else => false,
    };
}

/// Tolerant repair: state s may insert, best first,
/// repairTokens[repairOffsets[s]..repairOffsets[s + 1]].
const repairTokens = [_]u16{
    15, 15, 8, 8, 15, 8, 15, 8, 8, 8, 15, 15, 15, 15, 15, 15, 8, 8, 8, 8, 8, 15, 8, 8,
    15, 15, 15, 15, 8, 8, 8, 8, 15, 15, 15, 15, 15, 15, 8, 15, 15, 8, 8, 8, 8, 15, 8, 15,
    15, 15, 8, 15, 8, 8, 8, 8, 8, 15, 15, 15, 8, 8, 8, 15, 15, 15, 8, 8, 8, 15, 15, 15,
    15, 8, 8, 8, 15, 15, 8, 8, 15, 15, 8, 15, 8,
};
const repairOffsets = [_]u32{
    0, 0, 1, 3, 4, 6, 7, 8, 9, 10, 10, 11, 12, 13, 14, 15, 16, 17, 18, 18, 18, 19, 20, 21,
    22, 23, 24, 25, 26, 27, 28, 29, 30, 30, 31, 31, 31, 31, 32, 33, 33, 34, 34, 34, 34, 35, 36, 36,
    37, 39, 40, 41, 41, 42, 43, 44, 45, 46, 47, 48, 49, 49, 50, 50, 51, 51, 52, 53, 54, 54, 55, 56,
    57, 58, 59, 60, 60, 61, 62, 63, 63, 64, 65, 65, 66, 67, 68, 68, 69, 70, 71, 72, 72, 72, 72, 72,
    73, 74, 75, 76, 77, 78, 78, 79, 79, 80, 80, 81, 82, 83, 83, 84, 84, 85,
};

fn repairCandidates(state: u16) []const u16 {
    return repairTokens[repairOffsets[state]..repairOffsets[state + 1]];
}

/// The `@repair` class of a grammar symbol.
fn repairClass(sym: u16) RepairClass {
    return switch (sym) {
        15 => .hole,
        8 => .terminator,
        else => .none,
    };
}

fn ruleSideLabels(rule: u16) []const SideLabel {
    return switch (rule) {
        4 => &.{ .{ .role = .@"eq", .pass = 1 }, },
        else => &.{},
    };
}

// =============================================================================
// Schema slots
// =============================================================================

/// Slot of `role` in nodes of `kind` (the head is slot 0).
fn slotOf(kind: Tag, role: Role) ?usize {
    return switch (kind) {
        .@"set" => switch (role) {
            .@"op" => 1,
            .@"target" => 2,
            .@"value" => 3,
            else => null,
        },
        .@"let" => switch (role) {
            .@"name" => 1,
            .@"type" => 2,
            .@"value" => 3,
            else => null,
        },
        .@"if" => switch (role) {
            .@"kw" => 1,
            .@"cond" => 2,
            .@"then" => 3,
            .@"else" => 4,
            else => null,
        },
        .@"for" => switch (role) {
            .@"mode" => 1,
            .@"var" => 2,
            .@"index" => 3,
            .@"iter" => 4,
            .@"body" => 5,
            else => null,
        },
        .@"call" => switch (role) {
            .@"callee" => 1,
            else => null,
        },
        .@"swap" => switch (role) {
            .@"a" => 1,
            .@"b" => 2,
            .@"c" => 3,
            .@"d" => 4,
            else => null,
        },
        .@"return" => switch (role) {
            .@"value" => 1,
            else => null,
        },
        .@"yield" => switch (role) {
            .@"value" => 1,
            else => null,
        },
        .@"neg" => switch (role) {
            .@"value" => 1,
            else => null,
        },
        .@"num" => switch (role) {
            .@"value" => 1,
            else => null,
        },
        .@"name" => switch (role) {
            .@"id" => 1,
            else => null,
        },
        .@"+" => switch (role) {
            .@"left" => 1,
            .@"right" => 2,
            else => null,
        },
        .@"-" => switch (role) {
            .@"left" => 1,
            .@"right" => 2,
            else => null,
        },
        .@"*" => switch (role) {
            .@"left" => 1,
            .@"right" => 2,
            else => null,
        },
        .@"/" => switch (role) {
            .@"left" => 1,
            .@"right" => 2,
            else => null,
        },
        .@"note" => switch (role) {
            .@"text" => 1,
            else => null,
        },
        else => null,
    };
}

/// First slot of rest role `role` in nodes of `kind`.
fn restSlotOf(kind: Tag, role: Role) ?usize {
    return switch (kind) {
        .@"module" => if (role == .@"stmts") 1 else null,
        .@"call" => if (role == .@"args") 2 else null,
        .@"array" => if (role == .@"items") 1 else null,
        else => null,
    };
}

/// The slot role at `slot` of nodes of `kind`.
fn roleAt(kind: Tag, slot: usize) ?Role {
    return switch (kind) {
        .@"set" => switch (slot) {
            1 => .@"op",
            2 => .@"target",
            3 => .@"value",
            else => null,
        },
        .@"let" => switch (slot) {
            1 => .@"name",
            2 => .@"type",
            3 => .@"value",
            else => null,
        },
        .@"if" => switch (slot) {
            1 => .@"kw",
            2 => .@"cond",
            3 => .@"then",
            4 => .@"else",
            else => null,
        },
        .@"for" => switch (slot) {
            1 => .@"mode",
            2 => .@"var",
            3 => .@"index",
            4 => .@"iter",
            5 => .@"body",
            else => null,
        },
        .@"call" => switch (slot) {
            1 => .@"callee",
            else => null,
        },
        .@"swap" => switch (slot) {
            1 => .@"a",
            2 => .@"b",
            3 => .@"c",
            4 => .@"d",
            else => null,
        },
        .@"return" => switch (slot) {
            1 => .@"value",
            else => null,
        },
        .@"yield" => switch (slot) {
            1 => .@"value",
            else => null,
        },
        .@"neg" => switch (slot) {
            1 => .@"value",
            else => null,
        },
        .@"num" => switch (slot) {
            1 => .@"value",
            else => null,
        },
        .@"name" => switch (slot) {
            1 => .@"id",
            else => null,
        },
        .@"+" => switch (slot) {
            1 => .@"left",
            2 => .@"right",
            else => null,
        },
        .@"-" => switch (slot) {
            1 => .@"left",
            2 => .@"right",
            else => null,
        },
        .@"*" => switch (slot) {
            1 => .@"left",
            2 => .@"right",
            else => null,
        },
        .@"/" => switch (slot) {
            1 => .@"left",
            2 => .@"right",
            else => null,
        },
        .@"note" => switch (slot) {
            1 => .@"text",
            else => null,
        },
        else => null,
    };
}

fn restRoleOf(kind: Tag) ?struct { role: Role, slot: usize } {
    return switch (kind) {
        .@"module" => .{ .role = .@"stmts", .slot = 1 },
        .@"call" => .{ .role = .@"args", .slot = 2 },
        .@"array" => .{ .role = .@"items", .slot = 1 },
        else => null,
    };
}

// =============================================================================
// API
// =============================================================================

pub const Parser = if (@hasDecl(lang, "Parser")) lang.Parser else BaseParser;

/// Parse a whole program with a new `Parser`. The caller owns
/// `result.parser` and must `deinit()` it when done with the tree.
pub fn parseProgram(allocator: std.mem.Allocator, source: []const u8) !struct { parser: Parser, sexp: Sexp } {
    var p = Parser.init(allocator, source);
    errdefer p.deinit();
    const sexp = try p.parseProgram();
    return .{ .parser = p, .sexp = sexp };
}
