//! The grammar-file frontend: the self-hosted parser of a whole grammar
//! file (the directives before `@lexer`, the @lexer section and the
//! @parser section) and the canonical Sexp dump used by `--dump-sexp`.

const std = @import("std");
const Allocator = std.mem.Allocator;
const diag = @import("../diag.zig");
const regex = @import("../lexgen/regex.zig");

/// The grammar-file parser, generated by Nexus from nexus.grammar (with
/// lang.zig as its @lang module). Never hand-edit.
pub const parser = @import("parser.zig");
pub const Sexp = parser.Sexp;

pub const GrammarLowerer = @import("lower.zig").GrammarLowerer;
const lang = @import("lang.zig");

/// A grammar file parsed by the generated frontend. The tree's `.src`
/// positions are offsets into `source.text`. Deinit `parser` when finished
/// with the tree.
pub const Parsed = struct {
    parser: parser.Parser,
    sexp: parser.Sexp,
    source: diag.Source,
};

/// Parse a whole grammar file. A syntax error is reported as
/// `path:line:col: error: ...` and returned as error.ParseError.
pub fn parseGrammarSexp(allocator: Allocator, sourceText: []const u8, path: []const u8) !Parsed {
    const source = try diag.Source.init(allocator, path, sourceText);
    var p = parser.Parser.init(allocator, sourceText);
    errdefer p.deinit();
    const sexp = p.parseGrammar() catch |err| {
        if (err == error.ParseError) try reportSyntaxError(allocator, &p, source);
        return err;
    };
    return .{ .parser = p, .sexp = sexp, .source = source };
}

/// `syntax error: unexpected <token>; expected <what the state accepts>`,
/// or the scanner's own message for an `err` token it explained.
fn reportSyntaxError(allocator: Allocator, p: *const parser.Parser, source: diag.Source) Allocator.Error!void {
    const tok = p.current;
    if (tok.cat == .err) if (p.lexer.problem) |problem| if (problem.pos == tok.pos) {
        diag.errAt(source, tok.pos, "{s}", .{problem.message()});
        return;
    };
    // An invalid pattern earlier on the line is the first error there.
    if (p.lexer.lastPattern) |pat| if (std.mem.findScalar(u8, source.text[pat.pos..tok.pos], '\n') == null) {
        var d: regex.Diagnostic = .{};
        if (regex.parse(allocator, source.text[pat.pos..][0..pat.len], &d)) |_| {} else |err| switch (err) {
            error.InvalidPattern => return diag.errAt(source, pat.pos + d.offset, "{s}", .{d.message}),
            error.OutOfMemory => return error.OutOfMemory,
        }
    };
    if (tok.pos == 0 and std.mem.startsWith(u8, source.text, "\xEF\xBB\xBF"))
        return diag.errAt(source, 0, "the file starts with a UTF-8 byte order mark; save it without one", .{});

    var out: std.Io.Writer.Allocating = .init(allocator);
    const w = &out.writer;
    unexpected(w, p, source.text[tok.pos..][0..tok.len]) catch return error.OutOfMemory;
    if (p.lastError()) |failure| {
        const want = parser.BaseParser.expected(failure.state);
        if (want.len > 0) w.writeAll("; expected ") catch return error.OutOfMemory;
        for (want, 0..) |sym, i| {
            if (i > 0) w.writeAll(if (i + 1 == want.len) " or " else ", ") catch return error.OutOfMemory;
            w.writeAll(parser.BaseParser.symbolText(sym)) catch return error.OutOfMemory;
        }
    }
    diag.errAt(source, tok.pos, "syntax error: {s}", .{out.written()});
}

/// `unexpected <token>`: the token by the grammar's @display name (without
/// its article), and its text when the name does not show it; a byte that
/// is not ASCII in hex.
fn unexpected(w: *std.Io.Writer, p: *const parser.Parser, text: []const u8) std.Io.Writer.Error!void {
    const tok = p.current;
    if (tok.cat == .err) {
        if (text[0] >= 0x80) return w.print("unexpected byte 0x{X:0>2}", .{text[0]});
        return w.print("unexpected character '{s}'", .{text});
    }
    const failure = p.lastError() orelse return w.writeAll("unexpected token");
    const display = parser.BaseParser.symbolText(failure.symbol);
    const name = if (std.mem.startsWith(u8, display, "a ")) display[2..] else if (std.mem.startsWith(u8, display, "an ")) display[3..] else display;
    const shown = text.len == 0 or name[0] == '"' or std.mem.eql(u8, name, text) or switch (tok.cat) {
        .newline, .cont, .next_alt => true,
        else => false,
    };
    if (shown) return w.print("unexpected {s}", .{name});
    const t = lang.Lexer.clip(text);
    // A string or a quoted byte carries its own quotes.
    if (text[0] == '"' or text[0] == '\'') return w.print("unexpected {s} {s}{s}", .{ name, t.text, t.more });
    return w.print("unexpected {s} '{s}{s}'", .{ name, t.text, t.more });
}

// =============================================================================
// S-expression pretty-printer
//
// Renders the output of the generated frontend parser in a canonical textual
// form suitable for golden-file comparison. Lists that contain no nested lists
// stay on a single line; any list with a nested list child breaks across
// lines with two-space indentation per level.
//
// Syntactic forms — each Sexp variant prints in an unmistakable wrapper:
//   .nil        → _
//   .tag        → bare tagName  (only ever appears as the first child of a
//                 non-empty list, so it never collides with src content)
//   .src        → `text`        backticks with `\\` and `` \` `` escaping
//   .str        → "text"        double-quoted
//   .list       → (child child ...)
// =============================================================================

pub fn dumpSexp(writer: *std.Io.Writer, sexp: Sexp, source: []const u8, indent: usize) std.Io.Writer.Error!void {
    switch (sexp) {
        .nil => try writer.writeAll("_"),
        .tag => |t| try writer.writeAll(@tagName(t)),
        .src => |s| try dumpSrcText(writer, source[s.pos..][0..s.len]),
        .str => |s| try writer.print("\"{s}\"", .{s}),
        .list => |l| {
            const items = l.items();
            if (items.len == 0) {
                try writer.writeAll("()");
                return;
            }

            var hasNestedList = false;
            for (items) |item| switch (item) {
                .list => |sub| if (sub.len > 0) {
                    hasNestedList = true;
                    break;
                },
                else => {},
            };

            try writer.writeAll("(");
            if (!hasNestedList) {
                for (items, 0..) |item, i| {
                    if (i > 0) try writer.writeAll(" ");
                    try dumpSexp(writer, item, source, 0);
                }
            } else {
                try dumpSexp(writer, items[0], source, indent + 2);
                for (items[1..]) |item| {
                    try writer.writeAll("\n");
                    try writer.splatByteAll(' ', indent + 2);
                    try dumpSexp(writer, item, source, indent + 2);
                }
            }
            try writer.writeAll(")");
        },
    }
}

fn dumpSrcText(writer: *std.Io.Writer, text: []const u8) std.Io.Writer.Error!void {
    try writer.writeByte('`');
    for (text) |c| {
        if (c == '`' or c == '\\') try writer.writeByte('\\');
        try writer.writeByte(c);
    }
    try writer.writeByte('`');
}

// A token longer than a Token holds is an `err` token that explains itself,
// whichever scanner finds it.
test "a token longer than 65535 bytes is a located problem" {
    const testing = std.testing;
    const Lexer = @import("lang.zig").Lexer;
    const long: [Lexer.maxTokenLen + 1]u8 = @splat('a');
    const sources = [_][]const u8{
        "@parser\ns = \"" ++ long ++ "\"\n", // the generated lexer
        "@lexer\n'" ++ long ++ "' -> a\n", // a pattern
        "@conflicts\n    shift s -> " ++ long ++ " 1 # why\n", // a conflict rule
    };
    for (sources) |source| {
        var lexer = Lexer.init(source);
        const tok = while (true) {
            const t = lexer.next();
            if (t.cat == .err or t.cat == .eof) break t;
        };
        try testing.expectEqual(parser.TokenCat.err, tok.cat);
        try testing.expectEqualStrings("token longer than 65535 bytes", lexer.problem.?.message());
    }
}
