//! Generated by nexus v0.10.3 — do not edit

const std = @import("std");
const maxArgs: usize = 32;
const lang = @import("lang.zig");

// SIMD helpers (fallback if simd.zig not available)
const simd = struct {
    fn findByte(haystack: []const u8, needle: u8) usize {
        for (haystack, 0..) |c, i| if (c == needle) return i;
        return haystack.len;
    }
};

// =============================================================================
// TOKEN CATEGORIES
// =============================================================================

pub const TokenCat = enum(u8) {
    @"ident",
    @"token",
    @"kw_x",
    @"string",
    @"integer",
    @"eq",
    @"pipe",
    @"arrow",
    @"larrow",
    @"question",
    @"star",
    @"plus",
    @"lparen",
    @"rparen",
    @"lbracket",
    @"rbracket",
    @"langle",
    @"rangle",
    @"lbrace",
    @"rbrace",
    @"comma",
    @"colon",
    @"bang",
    @"tilde",
    @"dots",
    @"at",
    @"semicolon",
    @"newline",
    @"comment",
    @"code_block",
    @"action_text",
    @"kw_lang",
    @"kw_conflicts",
    @"kw_as",
    @"kw_op",
    @"kw_code",
    @"kw_errors",
    @"kw_infix",
    @"kw_left",
    @"kw_right",
    @"kw_none",
    @"kw_skip",
    @"eof",
    @"err",

    // Built in: the token of `→ skip` rules (returned to the lang Lexer)
    @"skip",
};

// =============================================================================
// TOKEN STRUCT (8 bytes)
// =============================================================================

pub const Token = struct {
    pos: u32, // Byte position in source (4 bytes)
    len: u16, // Token length in bytes (2 bytes)
    cat: TokenCat, // Token category (1 byte)
    pre: u8, // Preceding whitespace count (1 byte)

    comptime {
        std.debug.assert(@sizeOf(Token) == 8);
    }
};

// =============================================================================
// LEXER
// =============================================================================

pub const BaseLexer = struct {
    const Self = @This();

    source: []const u8,
    pos: u32,
    /// Side channel a lang Lexer wrapper may set per token; the parser
    /// copies it into the shifted leaf's `src.id` and clears it.
    aux: u16 = 0,

    pub fn init(source: []const u8) Self {
        return .{
            .source = source,
            .pos = 0,
        };
    }

    /// Get the text slice for a token (zero-copy into source)
    pub fn text(self: *const Self, tok: Token) []const u8 {
        const start: usize = tok.pos;
        const end: usize = @min(start + tok.len, self.source.len);
        if (start >= self.source.len) return "";
        return self.source[start..end];
    }

    /// Reset lexer to beginning
    pub fn reset(self: *Self) void {
        self.pos = 0;
    }

    /// Get next token
    pub fn next(self: *Self) Token {
        return self.matchRules();
    }

    const cls0 = blk: {
        var t: [256]bool = @splat(false);
        for ('A'..91) |c| t[c] = true;
        t['_'] = true;
        for ('a'..123) |c| t[c] = true;
        break :blk t;
    };

    const cls1 = blk: {
        var t: [256]bool = @splat(false);
        t['\t'] = true;
        t['\r'] = true;
        t[' '] = true;
        break :blk t;
    };

    const cls2 = blk: {
        var t: [256]bool = @splat(false);
        for (0x00..10) |c| t[c] = true;
        for (0x0B..34) |c| t[c] = true;
        for ('#'..92) |c| t[c] = true;
        for (']'..256) |c| t[c] = true;
        break :blk t;
    };

    const cls3 = blk: {
        var t: [256]bool = @splat(false);
        for ('0'..58) |c| t[c] = true;
        for ('A'..91) |c| t[c] = true;
        t['_'] = true;
        for ('a'..123) |c| t[c] = true;
        break :blk t;
    };

    /// First index at or after `from` whose byte is in `stops` (or src.len).
    inline fn scanUntil(src: []const u8, from: usize, comptime stops: []const u8) usize {
        const V = @Vector(16, u8);
        var p = from;
        while (p + 16 <= src.len) : (p += 16) {
            const v: V = src[p..][0..16].*;
            var hits: u16 = 0;
            inline for (stops) |c| hits |= @bitCast(v == @as(V, @splat(c)));
            if (hits != 0) return p + @ctz(hits);
        }
        while (p < src.len) : (p += 1) {
            inline for (stops) |c| if (src[p] == c) return p;
        }
        return p;
    }

    /// Match the next token.
    pub fn matchRules(self: *Self) Token {
        const src = self.source;
        const n = src.len;
        var p: usize = self.pos;
        const wsStart = p;
        scan: while (true) {
            while (p < n and (src[p] == ' ' or src[p] == '\t')) p += 1;
            const pre: u8 = @intCast(@min(p - wsStart, 255));
            if (p >= n) {
                self.pos = @intCast(p);
                return .{ .cat = .@"eof", .pre = pre, .pos = @intCast(p), .len = 0 };
            }
            const start = p;
            var acc: u16 = 65535;
            var accEnd: usize = start;
            dfa: switch (@as(u16, 0)) {
                0 => {
                    if (p < n and cls0[src[p]]) {
                        p += 1;
                        continue :dfa 22;
                    }
                    if (p < n) switch (src[p]) {
                        0x00...0x08, 0x0B...0x0C, 0x0E...0x1F, '$'...'\'', '/', '\\', '^', '`', 0x7F...0xFF => { p += 1; self.pos = @intCast(p); return .{ .cat = .@"err", .pre = pre, .pos = @intCast(start), .len = @intCast(p - start) }; },
                        '\t', '\r', ' ' => { p += 1; continue :dfa 2; },
                        '\n' => { p += 1; self.pos = @intCast(p); return .{ .cat = .@"newline", .pre = pre, .pos = @intCast(start), .len = @intCast(p - start) }; },
                        '!' => { p += 1; self.pos = @intCast(p); return .{ .cat = .@"bang", .pre = pre, .pos = @intCast(start), .len = @intCast(p - start) }; },
                        '"' => { p += 1; continue :dfa 5; },
                        '#' => { p += 1; continue :dfa 6; },
                        '(' => { p += 1; self.pos = @intCast(p); return .{ .cat = .@"lparen", .pre = pre, .pos = @intCast(start), .len = @intCast(p - start) }; },
                        ')' => { p += 1; self.pos = @intCast(p); return .{ .cat = .@"rparen", .pre = pre, .pos = @intCast(start), .len = @intCast(p - start) }; },
                        '*' => { p += 1; self.pos = @intCast(p); return .{ .cat = .@"star", .pre = pre, .pos = @intCast(start), .len = @intCast(p - start) }; },
                        '+' => { p += 1; self.pos = @intCast(p); return .{ .cat = .@"plus", .pre = pre, .pos = @intCast(start), .len = @intCast(p - start) }; },
                        ',' => { p += 1; self.pos = @intCast(p); return .{ .cat = .@"comma", .pre = pre, .pos = @intCast(start), .len = @intCast(p - start) }; },
                        '-' => { p += 1; continue :dfa 12; },
                        '.' => { p += 1; continue :dfa 13; },
                        '0'...'9' => { p += 1; continue :dfa 14; },
                        ':' => { p += 1; self.pos = @intCast(p); return .{ .cat = .@"colon", .pre = pre, .pos = @intCast(start), .len = @intCast(p - start) }; },
                        ';' => { p += 1; self.pos = @intCast(p); return .{ .cat = .@"semicolon", .pre = pre, .pos = @intCast(start), .len = @intCast(p - start) }; },
                        '<' => { p += 1; self.pos = @intCast(p); return .{ .cat = .@"langle", .pre = pre, .pos = @intCast(start), .len = @intCast(p - start) }; },
                        '=' => { p += 1; self.pos = @intCast(p); return .{ .cat = .@"eq", .pre = pre, .pos = @intCast(start), .len = @intCast(p - start) }; },
                        '>' => { p += 1; self.pos = @intCast(p); return .{ .cat = .@"rangle", .pre = pre, .pos = @intCast(start), .len = @intCast(p - start) }; },
                        '?' => { p += 1; self.pos = @intCast(p); return .{ .cat = .@"question", .pre = pre, .pos = @intCast(start), .len = @intCast(p - start) }; },
                        '@' => { p += 1; self.pos = @intCast(p); return .{ .cat = .@"at", .pre = pre, .pos = @intCast(start), .len = @intCast(p - start) }; },
                        '[' => { p += 1; self.pos = @intCast(p); return .{ .cat = .@"lbracket", .pre = pre, .pos = @intCast(start), .len = @intCast(p - start) }; },
                        ']' => { p += 1; self.pos = @intCast(p); return .{ .cat = .@"rbracket", .pre = pre, .pos = @intCast(start), .len = @intCast(p - start) }; },
                        '{' => { p += 1; self.pos = @intCast(p); return .{ .cat = .@"lbrace", .pre = pre, .pos = @intCast(start), .len = @intCast(p - start) }; },
                        '|' => { p += 1; self.pos = @intCast(p); return .{ .cat = .@"pipe", .pre = pre, .pos = @intCast(start), .len = @intCast(p - start) }; },
                        '}' => { p += 1; self.pos = @intCast(p); return .{ .cat = .@"rbrace", .pre = pre, .pos = @intCast(start), .len = @intCast(p - start) }; },
                        '~' => { p += 1; self.pos = @intCast(p); return .{ .cat = .@"tilde", .pre = pre, .pos = @intCast(start), .len = @intCast(p - start) }; },
                        else => {},
                    };
                    break :dfa;
                },
                2 => {
                    while (p < n and cls1[src[p]]) p += 1;
                    continue :scan;
                },
                5 => {
                    acc = 27;
                    accEnd = p;
                    if (p < n and cls2[src[p]]) {
                        p += 1;
                        continue :dfa 29;
                    }
                    if (p < n) switch (src[p]) {
                        '"' => { p += 1; self.pos = @intCast(p); return .{ .cat = .@"string", .pre = pre, .pos = @intCast(start), .len = @intCast(p - start) }; },
                        '\\' => { p += 1; continue :dfa 31; },
                        else => {},
                    };
                    self.pos = @intCast(p);
                    return .{ .cat = .@"err", .pre = pre, .pos = @intCast(start), .len = @intCast(p - start) };
                },
                6 => {
                    p = scanUntil(src, p, &.{'\n'});
                    self.pos = @intCast(p);
                    return .{ .cat = .@"comment", .pre = pre, .pos = @intCast(start), .len = @intCast(p - start) };
                },
                12 => {
                    if (p < n) switch (src[p]) {
                        '>' => { p += 1; self.pos = @intCast(p); return .{ .cat = .@"arrow", .pre = pre, .pos = @intCast(start), .len = @intCast(p - start) }; },
                        else => {},
                    };
                    self.pos = @intCast(p);
                    return .{ .cat = .@"err", .pre = pre, .pos = @intCast(start), .len = @intCast(p - start) };
                },
                13 => {
                    acc = 27;
                    accEnd = p;
                    if (p < n) switch (src[p]) {
                        '.' => { p += 1; continue :dfa 33; },
                        else => {},
                    };
                    self.pos = @intCast(p);
                    return .{ .cat = .@"err", .pre = pre, .pos = @intCast(start), .len = @intCast(p - start) };
                },
                14 => {
                    while (p < n and src[p] -% '0' <= 9) p += 1;
                    self.pos = @intCast(p);
                    return .{ .cat = .@"integer", .pre = pre, .pos = @intCast(start), .len = @intCast(p - start) };
                },
                22 => {
                    while (p < n and cls3[src[p]]) p += 1;
                    self.pos = @intCast(p);
                    return .{ .cat = .@"ident", .pre = pre, .pos = @intCast(start), .len = @intCast(p - start) };
                },
                29 => {
                    p = scanUntil(src, p, &.{'\n', '"', '\\'});
                    if (p < n) switch (src[p]) {
                        '"' => { p += 1; self.pos = @intCast(p); return .{ .cat = .@"string", .pre = pre, .pos = @intCast(start), .len = @intCast(p - start) }; },
                        '\\' => { p += 1; continue :dfa 31; },
                        else => {},
                    };
                    break :dfa;
                },
                31 => {
                    if (p < n) switch (src[p]) {
                        0x00...0xFF => { p += 1; continue :dfa 29; },
                    };
                    break :dfa;
                },
                33 => {
                    if (p < n) switch (src[p]) {
                        '.' => { p += 1; self.pos = @intCast(p); return .{ .cat = .@"dots", .pre = pre, .pos = @intCast(start), .len = @intCast(p - start) }; },
                        else => {},
                    };
                    break :dfa;
                },
                else => unreachable,
            }
            switch (acc) {
                27 => {
                    p = accEnd;
                    self.pos = @intCast(p);
                    return .{ .cat = .@"err", .pre = pre, .pos = @intCast(start), .len = @intCast(p - start) };
                },
                else => {},
            }
            self.pos = @intCast(start + 1);
            return .{ .cat = .@"err", .pre = pre, .pos = @intCast(start), .len = 1 };
        }
    }
};

pub const Lexer = if (@hasDecl(lang, "Lexer")) lang.Lexer else BaseLexer;

// =============================================================================
// Tag Enum (re-exported from language module)
// =============================================================================
pub const Tag = lang.Tag;

// =============================================================================
// S-Expression (AST Node) - 5 Clean Variants
// =============================================================================

pub const Sexp = union(enum) {
    nil:  void,                                        // Empty (nothing)
    tag:  Tag,                                         // Semantic type (1 byte)
    src:  struct { pos: u32, len: u16, id: u16 },      // Source ref + identity (8 bytes)
    str:  []const u8,                                  // Embedded string (16 bytes)
    list: []const Sexp,                                // Compound: (tag child1 ...)

    /// Get token text from source
    pub fn getText(self: Sexp, source: []const u8) []const u8 {
        return switch (self) {
            .src => |s| source[s.pos..][0..s.len],
            .str => |s| s,
            else => "",
        };
    }

    /// Format for debug output
    pub fn write(self: Sexp, source: []const u8, w: anytype) !void {
        switch (self) {
            .nil => try w.writeAll("_"),
            .tag => |t| try w.print("{s}", .{@tagName(t)}),
            .src => |s| try w.print("{s}", .{source[s.pos..][0..s.len]}),
            .str => |s| try w.print("\"{s}\"", .{s}),
            .list => |items| {
                try w.writeAll("(");
                for (items, 0..) |item, i| {
                    if (i > 0) try w.writeAll(" ");
                    try item.write(source, w);
                }
                try w.writeAll(")");
            },
        }
    }
};

// =============================================================================
// PARSER
// =============================================================================

pub const BaseParser = struct {
    arena: std.heap.ArenaAllocator,
    lexer: Lexer,
    source: []const u8,
    current: Token,
    injectedToken: ?u16 = null,
    lastMatchedId: u16 = 0,

    stateStack: std.ArrayListUnmanaged(u16) = .empty,
    valueStack: std.ArrayListUnmanaged(Sexp) = .empty,
    /// Spare capacity of the lists `keepList` returned, by address.
    listSpare: std.AutoHashMapUnmanaged(usize, ListSpare) = .empty,

    const ListSpare = struct { len: usize, capacity: usize };

    pub fn init(backingAllocator: std.mem.Allocator, source: []const u8) BaseParser {
        var p = BaseParser{
            .arena = std.heap.ArenaAllocator.init(backingAllocator),
            .lexer = Lexer.init(source),
            .source = source,
            .current = undefined,
        };
        p.current = p.lexer.next();
        return p;
    }

    pub fn deinit(self: *BaseParser) void {
        self.arena.deinit();
    }

    fn allocator(self: *BaseParser) std.mem.Allocator {
        return self.arena.allocator();
    }

    pub fn printError(self: *BaseParser) void {
        const pos: usize = @min(self.current.pos, self.source.len);
        var line: usize = 1;
        var col: usize = 1;
        var i: usize = 0;
        while (i < pos) : (i += 1) {
            if (self.source[i] == '\n') {
                line += 1;
                col = 1;
            } else {
                col += 1;
            }
        }
        std.debug.print("Parse error at line {d}, column {d}: unexpected {s}\n", .{
            line,
            col,
            @tagName(self.current.cat),
        });
    }

    fn doParse(self: *BaseParser, startSym: u16) !Sexp {
        const startState = getStartState(startSym);
        self.stateStack.clearRetainingCapacity();
        self.valueStack.clearRetainingCapacity();
        try self.stateStack.append(self.allocator(), startState);

        while (true) {
            const state = self.stateStack.getLast();
            const sym = if (self.injectedToken) |inj| inj else self.tokenToSymbol(self.current);
            var action = getAction(state, sym);

            // X "c" check: if reducing and next char matches with pre==0, shift instead
            if (action < -1 and self.current.pre == 0 and self.current.pos < self.source.len) {
                if (getImmediateShift(state, self.source[self.current.pos])) |shiftTarget| {
                    action = shiftTarget;
                }
            }

            if (action == 0) {
                return error.ParseError;
            } else if (action == -1) {
                return self.valueStack.getLast();
            } else if (action > 0) {
                // Shift
                if (self.injectedToken != null) {
                    try self.valueStack.append(self.allocator(), .nil);
                    self.injectedToken = null;
                } else {
                    try self.valueStack.append(self.allocator(), .{ .src = .{
                        .pos = self.current.pos,
                        .len = self.current.len,
                        .id  = if (self.lastMatchedId != 0) self.lastMatchedId else self.lexer.base.aux,
                    } });
                    self.lastMatchedId = 0;
                    self.lexer.base.aux = 0;
                    self.current = self.lexer.next();
                }
                try self.stateStack.append(self.allocator(), @intCast(action));
            } else {
                // Reduce
                const ruleId: u16 = @intCast(-action - 2);
                var pass: [maxArgs]Sexp = undefined;
                const len = ruleLen[ruleId];
                for (0..len) |i| {
                    pass[len - 1 - i] = self.valueStack.pop().?;
                    _ = self.stateStack.pop();
                }

                const result = self.executeAction(ruleId, pass[0..len]);

                if (isAcceptRule(ruleId)) return result;

                try self.valueStack.append(self.allocator(), result);

                const gotoState = self.stateStack.getLast();
                const next = getAction(gotoState, ruleLhs[ruleId]);
                if (next <= 0) return error.ParseError;
                try self.stateStack.append(self.allocator(), @intCast(next));
            }
        }
    }

    /// Spread list helper: [head, ...tail]
    fn spreadList(self: *BaseParser, head: Sexp, tail: Sexp) Sexp {
        var out: std.ArrayListUnmanaged(Sexp) = .empty;
        out.append(self.allocator(), head) catch return .nil;
        if (tail == .list) for (tail.list) |item| out.append(self.allocator(), item) catch return .nil;
        return .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} };
    }

    /// Spread only: [...tail]
    fn spreadOnly(self: *BaseParser, tail: Sexp) Sexp {
        var out: std.ArrayListUnmanaged(Sexp) = .empty;
        if (tail == .list) for (tail.list) |item| out.append(self.allocator(), item) catch return .nil;
        return .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} };
    }

    /// Default list handler
    fn list(self: *BaseParser, pass: []Sexp) Sexp {
        if (pass.len == 0) return .nil;
        if (pass.len == 1) return pass[0];
        var out: std.ArrayListUnmanaged(Sexp) = .empty;
        for (pass) |v| out.append(self.allocator(), v) catch return .nil;
        return .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} };
    }

    /// Start a list holding the items of `base` (a list, else
    /// nothing) for an action that appends to it. A list from
    /// `keepList` is reused with its spare capacity, so a
    /// left-recursive list grows in amortized O(1) per element.
    fn extendList(self: *BaseParser, base: Sexp) !std.ArrayListUnmanaged(Sexp) {
        if (base != .list) return .empty;
        const items = base.list;
        if (items.len > 0) if (self.listSpare.get(@intFromPtr(items.ptr))) |spare| {
            if (spare.len == items.len) {
                _ = self.listSpare.remove(@intFromPtr(items.ptr));
                return .{ .items = @constCast(items), .capacity = spare.capacity };
            }
        };
        var out: std.ArrayListUnmanaged(Sexp) = .empty;
        try out.appendSlice(self.allocator(), items);
        return out;
    }

    /// Finish a list from `extendList`, recording its spare capacity.
    fn keepList(self: *BaseParser, out: *std.ArrayListUnmanaged(Sexp)) Sexp {
        if (out.items.len > 0 and out.capacity > out.items.len) {
            self.listSpare.put(self.allocator(), @intFromPtr(out.items.ptr), .{
                .len = out.items.len,
                .capacity = out.capacity,
            }) catch {};
        }
        return .{ .list = out.items };
    }

    /// Build S-expression: (tag items...) with trailing nil trimming
    inline fn sexp(self: *BaseParser, comptime tag: Tag, items: []const Sexp) Sexp {
        if (items.len == 0) {
            const result = self.allocator().alloc(Sexp, 1) catch return .nil;
            result[0] = .{ .tag = tag };
            return .{ .list = result };
        }
        var len = items.len;
        while (len > 0 and items[len - 1] == .nil) len -= 1;
        const result = self.allocator().alloc(Sexp, len + 1) catch return .nil;
        result[0] = .{ .tag = tag };
        if (len > 0) @memcpy(result[1..][0..len], items[0..len]);
        return .{ .list = result };
    }

    /// Build S-expression: (tag ...spread) - tag + spread items
    inline fn sexpSpread(self: *BaseParser, comptime tag: Tag, spread: Sexp) Sexp {
        const items = if (spread == .list) spread.list else &[_]Sexp{};
        var len = items.len;
        while (len > 0 and items[len - 1] == .nil) len -= 1;
        const result = self.allocator().alloc(Sexp, len + 1) catch return .nil;
        result[0] = .{ .tag = tag };
        if (len > 0) @memcpy(result[1..][0..len], items[0..len]);
        return .{ .list = result };
    }

    /// Build S-expression: (tag pos ...spread) - tag + position + spread items
    inline fn sexpPosSpread(self: *BaseParser, comptime tag: Tag, pos: Sexp, spread: Sexp) Sexp {
        const items = if (spread == .list) spread.list else &[_]Sexp{};
        var len = items.len;
        while (len > 0 and items[len - 1] == .nil) len -= 1;
        const skipPos = (pos == .nil and len == 0);
        const total = if (skipPos) 1 else len + 2;
        const result = self.allocator().alloc(Sexp, total) catch return .nil;
        result[0] = .{ .tag = tag };
        if (!skipPos) {
            result[1] = pos;
            if (len > 0) @memcpy(result[2..][0..len], items[0..len]);
        }
        return .{ .list = result };
    }

    fn executeAction(self: *BaseParser, ruleId: u16, pass: []Sexp) Sexp {
        return switch (ruleId) {
            0 => self.sexpSpread(.@"grammar", pass[0]),
            1 => blk: { var out = self.extendList(pass[0]) catch break :blk .nil; out.append(self.allocator(), pass[1]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk self.keepList(&out); },
            2 => pass[0],
            3 => pass[0],
            4 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .empty; out.append(self.allocator(), pass[0]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            5 => .{ .list = &[_]Sexp{} },
            6 => pass[0],
            7 => pass[0],
            8 => self.sexp(.@"lang", &.{pass[3]}),
            9 => self.sexp(.@"conflicts", &.{pass[3]}),
            10 => self.sexpSpread(.@"as", pass[2]),
            11 => self.sexpSpread(.@"op", pass[4]),
            12 => self.sexp(.@"code", &.{pass[2], pass[3]}),
            13 => self.sexpSpread(.@"errors", pass[2]),
            14 => self.sexpSpread(.@"infix", pass[2]),
            15 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .empty; out.append(self.allocator(), pass[0]) catch break :blk .nil; if (pass[3] == .list) for (pass[3].list) |item| out.append(self.allocator(), item) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            16 => blk: { var out = self.extendList(pass[0]) catch break :blk .nil; out.append(self.allocator(), pass[2]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk self.keepList(&out); },
            17 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .empty; out.append(self.allocator(), pass[0]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            18 => self.sexp(.@"as_entry", &.{.{ .tag = .@"perm" }, pass[0]}),
            19 => self.sexp(.@"as_entry", &.{.nil, pass[0]}),
            20 => blk: { var out = self.extendList(pass[0]) catch break :blk .nil; out.append(self.allocator(), pass[1]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk self.keepList(&out); },
            21 => pass[0],
            22 => pass[0],
            23 => pass[0],
            24 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .empty; out.append(self.allocator(), pass[0]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            25 => .{ .list = &[_]Sexp{} },
            26 => self.sexp(.@"op_map", &.{pass[0], pass[2]}),
            27 => blk: { var out = self.extendList(pass[0]) catch break :blk .nil; out.append(self.allocator(), pass[1]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk self.keepList(&out); },
            28 => pass[0],
            29 => pass[0],
            30 => pass[0],
            31 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .empty; out.append(self.allocator(), pass[0]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            32 => self.sexp(.@"error_name", &.{pass[0], pass[2]}),
            33 => self.sexp(.@"error_name", &.{pass[0], pass[2]}),
            34 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .empty; out.append(self.allocator(), pass[0]) catch break :blk .nil; if (pass[2] == .list) for (pass[2].list) |item| out.append(self.allocator(), item) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            35 => pass[0],
            36 => pass[0],
            37 => self.list(pass),
            38 => self.list(pass),
            39 => blk: { var out = self.extendList(pass[0]) catch break :blk .nil; out.append(self.allocator(), pass[2]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk self.keepList(&out); },
            40 => pass[0],
            41 => pass[0],
            42 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .empty; out.append(self.allocator(), pass[0]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            43 => self.sexpSpread(.@"level", pass[0]),
            44 => blk: { var out = self.extendList(pass[0]) catch break :blk .nil; out.append(self.allocator(), pass[2]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk self.keepList(&out); },
            45 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .empty; out.append(self.allocator(), pass[0]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            46 => self.sexp(.@"infix_op", &.{pass[0], pass[1]}),
            47 => self.sexp(.@"infix_op", &.{pass[0], pass[1]}),
            48 => self.sexp(.@"infix_op", &.{pass[0], pass[1]}),
            49 => self.sexp(.@"infix_op", &.{pass[0], pass[1]}),
            50 => pass[0],
            51 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .empty; out.append(self.allocator(), .{ .tag = .@"rule" }) catch break :blk .nil; out.append(self.allocator(), pass[0]) catch break :blk .nil; if (pass[2] == .list) for (pass[2].list) |item| out.append(self.allocator(), item) catch break :blk .nil; if (pass[3] == .list) for (pass[3].list) |item| out.append(self.allocator(), item) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            52 => blk: { var out = self.extendList(pass[0]) catch break :blk .nil; out.append(self.allocator(), pass[2]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk self.keepList(&out); },
            53 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .empty; out.append(self.allocator(), pass[0]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            54 => blk: { var out = self.extendList(pass[0]) catch break :blk .nil; if (pass[3] == .list) for (pass[3].list) |item| out.append(self.allocator(), item) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk self.keepList(&out); },
            55 => pass[0],
            56 => pass[0],
            57 => .{ .list = &[_]Sexp{} },
            58 => self.sexp(.@"start", &.{pass[0]}),
            59 => self.sexp(.@"name", &.{pass[0]}),
            60 => self.sexp(.@"start", &.{pass[0]}),
            61 => self.sexp(.@"name", &.{pass[0]}),
            62 => self.sexp(.@"alt", &.{.nil, pass[0], pass[2]}),
            63 => self.sexp(.@"alt", &.{.{ .tag = .@"reduce" }, pass[0], pass[3]}),
            64 => self.sexp(.@"alt", &.{.{ .tag = .@"shift" }, pass[0], pass[3]}),
            65 => self.sexp(.@"alt", &.{.{ .tag = .@"reduce" }, pass[0]}),
            66 => self.sexp(.@"alt", &.{.{ .tag = .@"shift" }, pass[0]}),
            67 => self.sexp(.@"alt", &.{.nil, pass[0]}),
            68 => blk: { var out = self.extendList(pass[0]) catch break :blk .nil; out.append(self.allocator(), pass[1]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk self.keepList(&out); },
            69 => .{ .list = &[_]Sexp{} },
            70 => self.sexp(.@"quantified", &.{pass[0], pass[1]}),
            71 => self.sexp(.@"skip_q", &.{pass[1], pass[2]}),
            72 => self.sexp(.@"skip", &.{pass[1]}),
            73 => self.sexp(.@"exclude", &.{pass[1]}),
            74 => self.list(pass),
            75 => self.sexp(.@"ref", &.{pass[0]}),
            76 => self.sexp(.@"list_req", &.{pass[0], pass[2]}),
            77 => self.sexp(.@"tok", &.{pass[0]}),
            78 => self.sexp(.@"lit", &.{pass[0]}),
            79 => self.sexp(.@"at_ref", &.{pass[1]}),
            80 => self.sexp(.@"at_ref", &.{pass[1]}),
            81 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .empty; out.append(self.allocator(), .{ .tag = .@"group" }) catch break :blk .nil; out.append(self.allocator(), .nil) catch break :blk .nil; if (pass[1] == .list) for (pass[1].list) |item| out.append(self.allocator(), item) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            82 => pass[1],
            83 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .empty; out.append(self.allocator(), .{ .tag = .@"group" }) catch break :blk .nil; out.append(self.allocator(), .{ .tag = .@"many" }) catch break :blk .nil; if (pass[0] == .list) for (pass[0].list) |item| out.append(self.allocator(), item) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            84 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .empty; out.append(self.allocator(), .{ .tag = .@"group" }) catch break :blk .nil; out.append(self.allocator(), .{ .tag = .@"opt" }) catch break :blk .nil; if (pass[0] == .list) for (pass[0].list) |item| out.append(self.allocator(), item) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            85 => self.sexp(.@"opt_items", &.{pass[0], pass[3]}),
            86 => self.sexp(.@"sep_items", &.{pass[0], pass[2]}),
            87 => self.sexp(.@"opt_items_nosep", &.{pass[0]}),
            88 => self.sexp(.@"plain", &.{pass[0]}),
            89 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .empty; out.append(self.allocator(), pass[0]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            90 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .empty; out.append(self.allocator(), pass[0]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            91 => blk: { var out = self.extendList(pass[0]) catch break :blk .nil; out.append(self.allocator(), pass[2]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk self.keepList(&out); },
            92 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .empty; out.append(self.allocator(), pass[0]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            93 => blk: { var out = self.extendList(pass[0]) catch break :blk .nil; out.append(self.allocator(), pass[1]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk self.keepList(&out); },
            94 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .empty; out.append(self.allocator(), pass[0]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            95 => self.sexp(.@"opt", &.{}),
            96 => self.sexp(.@"zero_plus", &.{}),
            97 => self.sexp(.@"one_plus", &.{}),
            98 => self.list(pass),
            else => .nil,
        };
    }

    fn tokenToSymbol(_: *BaseParser, token: Token) u16 {
        return switch (token.cat) {
            .@"eof" => 1,
            .@"newline" => 35,
            .@"comment" => 36,
            .@"kw_lang" => 38,
            .@"string" => 40,
            .@"kw_conflicts" => 41,
            .@"integer" => 42,
            .@"kw_as" => 43,
            .@"kw_op" => 44,
            .@"kw_code" => 47,
            .@"ident" => 48,
            .@"kw_errors" => 49,
            .@"kw_infix" => 50,
            .@"arrow" => 53,
            .@"token" => 55,
            .@"kw_left" => 56,
            .@"kw_right" => 57,
            .@"kw_none" => 58,
            .@"code_block" => 59,
            .@"action_text" => 61,
            .@"kw_x" => 64,
            .@"at" => 37,
            .@"eq" => 39,
            .@"lbracket" => 45,
            .@"rbracket" => 46,
            .@"comma" => 51,
            .@"bang" => 52,
            .@"colon" => 54,
            .@"pipe" => 60,
            .@"langle" => 62,
            .@"rangle" => 63,
            .@"lparen" => 65,
            .@"rparen" => 66,
            .@"question" => 68,
            .@"star" => 69,
            .@"plus" => 70,
            .@"dots" => 67,
            else => 2, // error
        };
    }

    fn identToSymbol(_: *BaseParser, _: Token) u16 {
        return symIdent;
    }

    pub fn parseGrammar(self: *BaseParser) !Sexp {
        self.injectedToken = SYM_grammar_START;
        return self.doParse(SYM_grammar);
    }
};

pub const Parser = if (@hasDecl(lang, "Parser")) lang.Parser else BaseParser;

// =============================================================================
// Top-level convenience helpers (one per start symbol)
// =============================================================================

/// Convenience: instantiate the (lang-extended) parser and parse a whole
/// grammar. Caller owns `result.parser` and must call `result.parser.deinit()`
/// when done with the returned tree (the tree references arena-allocated
/// memory owned by the parser).
///
/// The parser is returned by value, so the underlying type
/// must be safely movable (no self-referential storage).
/// `BaseParser` is movable by construction; custom `lang.Parser`
/// wrappers must preserve this invariant.
pub fn parseGrammar(allocator: std.mem.Allocator, source: []const u8) !struct { parser: Parser, sexp: Sexp } {
    var p = Parser.init(allocator, source);
    errdefer p.deinit();
    const sexp = try p.parseGrammar();
    return .{ .parser = p, .sexp = sexp };
}

// Symbol IDs
const SYM_grammar: u16 = 3;
const SYM_grammar_START: u16 = 71;
const symIdent: u16 = 48;

const ruleLhs = [_]u16{ 3, 4, 4, 4, 4, 4, 5, 5, 6, 6, 6, 6, 6, 6, 6, 7, 8, 8, 9, 9, 10, 10, 10, 10, 10, 10, 11, 12, 12, 12, 12, 12, 13, 13, 14, 15, 15, 15, 15, 16, 16, 16, 16, 17, 18, 18, 19, 19, 19, 19, 20, 21, 22, 22, 23, 23, 23, 23, 24, 24, 24, 24, 25, 25, 25, 25, 25, 25, 26, 26, 27, 27, 27, 27, 27, 28, 28, 28, 28, 28, 28, 28, 28, 29, 29, 30, 30, 30, 30, 31, 31, 32, 32, 33, 33, 34, 34, 34, 72 };
const ruleLen = [_]u8{ 1, 2, 2, 2, 1, 0, 1, 1, 4, 4, 3, 6, 4, 3, 3, 5, 3, 1, 2, 1, 2, 2, 2, 2, 1, 0, 3, 2, 2, 2, 2, 1, 3, 3, 3, 2, 2, 1, 1, 3, 2, 2, 1, 1, 3, 1, 2, 2, 2, 2, 1, 4, 3, 1, 4, 3, 2, 0, 2, 1, 2, 1, 3, 4, 4, 2, 2, 1, 2, 0, 2, 3, 2, 2, 1, 1, 4, 1, 1, 2, 2, 3, 3, 2, 1, 4, 3, 2, 1, 1, 1, 3, 1, 2, 1, 1, 1, 1, 3 };

// Parse Table: 147 states × 73 symbols
const numStates = 147;
const numSymbols = 73;

const sparse = [numStates][]const i16{
    &.{71,1},
    &.{1,-7,3,6,4,8,5,4,6,3,21,10,24,2,35,-7,36,-7,37,9,48,5,55,7},
    &.{39,11},
    &.{1,-8,35,-8,36,-8,37,-8,48,-8,55,-8},
    &.{1,-6,35,-6,36,-6,37,-6,48,-6,55,-6},
    &.{39,-61,52,12},
    &.{1,-1},
    &.{39,-63,52,14},
    &.{1,-2,5,16,6,3,21,10,24,2,35,15,36,17,37,9,48,5,55,7},
    &.{38,19,41,21,43,20,44,23,47,22,49,18,50,24},
    &.{1,-9,35,-9,36,-9,37,-9,48,-9,55,-9},
    &.{1,-71,22,26,25,25,26,27,35,-71,36,-71,37,-71,40,-71,45,-71,48,-71,52,-71,53,-71,55,-71,60,-71,62,-71,63,-71,64,-71,65,-71},
    &.{39,-60},
    &.{1,-1},
    &.{39,-62},
    &.{1,-4,35,-4,36,-4,37,-4,48,-4,55,-4},
    &.{1,-3,35,-3,36,-3,37,-3,48,-3,55,-3},
    &.{1,-5,35,-5,36,-5,37,-5,48,-5,55,-5},
    &.{12,29,13,30,48,31,55,28},
    &.{39,32},
    &.{7,33,48,34},
    &.{39,35},
    &.{48,36},
    &.{39,37},
    &.{14,38,48,39},
    &.{1,-55,35,-55,36,-55,37,-55,48,-55,55,-55,60,-55},
    &.{1,-59,23,40,35,-59,36,-59,37,-59,48,-59,55,-59,60,41},
    &.{1,-69,27,44,28,42,35,-69,36,-69,37,50,40,52,45,51,48,54,52,53,53,45,55,46,60,-69,62,49,63,47,64,43,65,48},
    &.{54,55},
    &.{1,-15,13,58,35,57,36,59,37,-15,48,31,51,56,55,28},
    &.{1,-33,35,-33,36,-33,37,-33,48,-33,51,-33,55,-33},
    &.{54,60},
    &.{40,61},
    &.{1,-12,35,-12,36,-12,37,-12,48,-12,55,-12},
    &.{39,62},
    &.{42,63},
    &.{20,65,59,64},
    &.{45,66},
    &.{1,-16,35,-16,36,-16,37,-16,48,-16,55,-16},
    &.{15,67,35,68,36,69},
    &.{1,-53,35,70,36,-53,37,-53,48,-53,55,-53},
    &.{1,-71,25,71,26,27,35,-71,36,-71,37,-71,40,-71,45,-71,48,-71,52,-71,53,-71,55,-71,60,-71,62,-71,63,-71,64,-71,65,-71},
    &.{1,-76,34,73,35,-76,36,-76,37,-76,40,-76,45,-76,46,-76,48,-76,52,-76,53,-76,55,-76,60,-76,62,-76,63,-76,64,-76,65,-76,66,-76,67,-76,68,74,69,75,70,72},
    &.{40,76},
    &.{1,-70,35,-70,36,-70,37,-70,40,-70,45,-70,48,-70,52,-70,53,-70,55,-70,60,-70,62,-70,63,-70,64,-70,65,-70},
    &.{61,77},
    &.{1,-79,35,-79,36,-79,37,-79,40,-79,45,-79,46,-79,48,-79,52,-79,53,-79,55,-79,60,-79,62,-79,63,-79,64,-79,65,78,66,-79,67,-79,68,-79,69,-79,70,-79},
    &.{1,-68,35,-68,36,-68,37,-68,48,-68,53,79,55,-68,60,-68},
    &.{27,81,28,42,32,82,33,80,37,50,40,52,45,51,48,54,52,53,55,46,64,43,65,48},
    &.{1,-67,35,-67,36,-67,37,-67,48,-67,53,83,55,-67,60,-67},
    &.{48,85,50,84},
    &.{27,81,28,42,29,86,32,87,33,80,37,50,40,52,45,51,48,54,52,53,55,46,64,43,65,48},
    &.{1,-80,35,-80,36,-80,37,-80,40,-80,45,-80,46,-80,48,-80,52,-80,53,-80,55,-80,60,-80,62,-80,63,-80,64,-80,65,-80,66,-80,67,-80,68,-80,69,-80,70,-80},
    &.{28,88,37,50,40,52,45,51,48,54,55,46,65,48},
    &.{1,-77,35,-77,36,-77,37,-77,40,-77,45,-77,46,-77,48,-77,52,-77,53,-77,55,-77,60,-77,62,-77,63,-77,64,-77,65,-77,66,-77,67,-77,68,-77,69,-77,70,-77},
    &.{40,89},
    &.{1,-30,35,-30,36,-30,37,-30,48,-30,51,-30,55,-30},
    &.{1,-31,35,-31,36,-31,37,-31,48,-31,51,-31,55,-31},
    &.{1,-29,35,-29,36,-29,37,-29,48,-29,51,-29,55,-29},
    &.{1,-32,35,-32,36,-32,37,-32,48,-32,51,-32,55,-32},
    &.{40,90},
    &.{1,-10,35,-10,36,-10,37,-10,48,-10,55,-10},
    &.{45,91},
    &.{1,-11,35,-11,36,-11,37,-11,48,-11,55,-11},
    &.{1,-52,35,-52,36,-52,37,-52,48,-52,55,-52},
    &.{1,-14,35,-14,36,-14,37,-14,48,-14,55,-14},
    &.{10,94,11,93,35,-27,36,-27,40,92,46,-27,51,-27},
    &.{16,98,17,101,18,97,19,100,35,96,36,99,40,95},
    &.{35,-39,36,-39,40,-39},
    &.{35,-40,36,-40,40,-40},
    &.{1,-58,35,-58,36,103,37,-58,48,-58,55,-58,60,102},
    &.{1,-54,35,-54,36,-54,37,-54,48,-54,55,-54,60,-54},
    &.{1,-99,35,-99,36,-99,37,-99,40,-99,45,-99,46,-99,48,-99,52,-99,53,-99,55,-99,60,-99,62,-99,63,-99,64,-99,65,-99,66,-99,67,-99},
    &.{1,-72,35,-72,36,-72,37,-72,40,-72,45,-72,46,-72,48,-72,52,-72,53,-72,55,-72,60,-72,62,-72,63,-72,64,-72,65,-72,66,-72,67,-72},
    &.{1,-97,35,-97,36,-97,37,-97,40,-97,45,-97,46,-97,48,-97,52,-97,53,-97,55,-97,60,-97,62,-97,63,-97,64,-97,65,-97,66,-97,67,-97},
    &.{1,-98,35,-98,36,-98,37,-98,40,-98,45,-98,46,-98,48,-98,52,-98,53,-98,55,-98,60,-98,62,-98,63,-98,64,-98,65,-98,66,-98,67,-98},
    &.{1,-75,35,-75,36,-75,37,-75,40,-75,45,-75,46,-75,48,-75,52,-75,53,-75,55,-75,60,-75,62,-75,63,-75,64,-75,65,-75,66,-75,67,-75},
    &.{1,-64,35,-64,36,-64,37,-64,48,-64,55,-64,60,-64},
    &.{30,104,48,105},
    &.{61,106},
    &.{27,107,28,42,37,50,40,52,45,51,46,-94,48,54,52,53,55,46,60,-94,64,43,65,48,66,-94,67,-94},
    &.{37,-96,40,-96,45,-96,46,-96,48,-96,52,-96,55,-96,60,-96,64,-96,65,-96,66,-96,67,-96},
    &.{60,109,66,108},
    &.{61,110},
    &.{1,-82,35,-82,36,-82,37,-82,40,-82,45,-82,46,-82,48,-82,52,-82,53,-82,55,-82,60,-82,62,-82,63,-82,64,-82,65,-82,66,-82,67,-82,68,-82,69,-82,70,-82},
    &.{1,-81,35,-81,36,-81,37,-81,40,-81,45,-81,46,-81,48,-81,52,-81,53,-81,55,-81,60,-81,62,-81,63,-81,64,-81,65,-81,66,-81,67,-81,68,-81,69,-81,70,-81},
    &.{46,111},
    &.{46,-86,60,109,67,112},
    &.{1,-74,34,113,35,-74,36,-74,37,-74,40,-74,45,-74,46,-74,48,-74,52,-74,53,-74,55,-74,60,-74,62,-74,63,-74,64,-74,65,-74,66,-74,67,-74,68,74,69,75,70,72},
    &.{1,-35,35,-35,36,-35,37,-35,48,-35,51,-35,55,-35},
    &.{1,-34,35,-34,36,-34,37,-34,48,-34,51,-34,55,-34},
    &.{8,114,9,115,48,116},
    &.{53,117},
    &.{35,-26,36,-26,40,-26,46,-26,51,-26},
    &.{11,119,35,121,36,122,40,92,46,120,51,118},
    &.{48,124,56,123,57,125,58,126},
    &.{35,-37,36,-37,40,-37},
    &.{1,-45,35,-45,36,-45,37,-45,48,-45,51,127,55,-45},
    &.{1,-36,35,128,36,129,37,-36,48,-36,55,-36},
    &.{35,-38,36,-38,40,-38},
    &.{1,-47,35,-47,36,-47,37,-47,48,-47,51,-47,55,-47},
    &.{1,-44,35,-44,36,-44,37,-44,48,-44,55,-44},
    &.{1,-71,22,130,25,25,26,27,35,-71,36,-71,37,-71,40,-71,45,-71,48,-71,52,-71,53,-71,55,-71,60,-71,62,-71,63,-71,64,-71,65,-71},
    &.{1,-57,35,-57,36,-57,37,-57,48,-57,55,-57},
    &.{66,131},
    &.{51,133,66,-90,68,132},
    &.{1,-66,35,-66,36,-66,37,-66,48,-66,55,-66,60,-66},
    &.{37,-95,40,-95,45,-95,46,-95,48,-95,52,-95,55,-95,60,-95,64,-95,65,-95,66,-95,67,-95},
    &.{1,-83,35,-83,36,-83,37,-83,40,-83,45,-83,46,-83,48,-83,52,-83,53,-83,55,-83,60,-83,62,-83,63,-83,64,-83,65,-83,66,-83,67,-83,68,-83,69,-83,70,-83},
    &.{27,81,28,42,33,134,37,50,40,52,45,51,48,54,52,53,55,46,64,43,65,48},
    &.{1,-65,35,-65,36,-65,37,-65,48,-65,55,-65,60,-65},
    &.{1,-84,35,-84,36,-84,37,-84,40,-84,45,-84,46,-84,48,-84,52,-84,53,-84,55,-84,60,-84,62,-84,63,-84,64,-84,65,-84,66,-84,67,-84,68,-84,69,-84,70,-84},
    &.{46,-85},
    &.{1,-73,35,-73,36,-73,37,-73,40,-73,45,-73,46,-73,48,-73,52,-73,53,-73,55,-73,60,-73,62,-73,63,-73,64,-73,65,-73,66,-73,67,-73},
    &.{46,136,51,135},
    &.{46,-19,51,-19},
    &.{46,-21,51,-21,52,137},
    &.{40,138},
    &.{35,-23,36,-23,40,-23,46,-23,51,-23},
    &.{35,-22,36,-22,40,-22,46,-22,51,-22},
    &.{1,-13,35,-13,36,-13,37,-13,48,-13,55,-13},
    &.{35,-24,36,-24,40,-24,46,-24,51,-24},
    &.{35,-25,36,-25,40,-25,46,-25,51,-25},
    &.{1,-48,35,-48,36,-48,37,-48,48,-48,51,-48,55,-48},
    &.{1,-51,35,-51,36,-51,37,-51,48,-51,51,-51,55,-51},
    &.{1,-49,35,-49,36,-49,37,-49,48,-49,51,-49,55,-49},
    &.{1,-50,35,-50,36,-50,37,-50,48,-50,51,-50,55,-50},
    &.{19,139,40,95},
    &.{1,-42,17,140,18,97,19,100,35,-42,36,-42,37,-42,40,95,48,-42,55,-42},
    &.{1,-43,35,-43,36,-43,37,-43,48,-43,55,-43},
    &.{1,-56,35,-56,36,-56,37,-56,48,-56,55,-56,60,41},
    &.{1,-78,35,-78,36,-78,37,-78,40,-78,45,-78,46,-78,48,-78,52,-78,53,-78,55,-78,60,-78,62,-78,63,-78,64,-78,65,-78,66,-78,67,-78,68,-78,69,-78,70,-78},
    &.{51,141,66,-89},
    &.{31,143,40,142,55,144},
    &.{27,107,28,42,37,50,40,52,45,51,46,-93,48,54,52,53,55,46,60,-93,64,43,65,48,66,-93,67,-93},
    &.{9,145,48,116},
    &.{1,-17,35,-17,36,-17,37,-17,48,-17,55,-17},
    &.{46,-20,51,-20},
    &.{35,-28,36,-28,40,-28,46,-28,51,-28},
    &.{1,-46,35,-46,36,-46,37,-46,48,-46,51,-46,55,-46},
    &.{1,-41,35,-41,36,-41,37,-41,48,-41,55,-41},
    &.{31,146,40,142,55,144},
    &.{66,-91},
    &.{66,-88},
    &.{66,-92},
    &.{46,-18,51,-18},
    &.{66,-87},
};

const parseTable = blk: {
    @setEvalBranchQuota(100000);
    var t: [numStates][numSymbols]i16 = .{.{0} ** numSymbols} ** numStates;
    for (sparse, 0..) |row, state| {
        var i: usize = 0;
        while (i < row.len) : (i += 2) {
            t[state][@intCast(row[i])] = row[i + 1];
        }
    }
    break :blk t;
};

fn getAction(state: u16, sym: u16) i16 {
    return parseTable[state][sym];
}
// X "c" excludes: shift instead of reduce when pre==0 and char matches
const xExcludes = [_]struct { state: u16, char: u8, shift: u16 }{
};

fn getImmediateShift(state: u16, char: u8) ?i16 {
    for (xExcludes) |x| {
        if (x.state == state and x.char == char) return @intCast(x.shift);
    }
    return null;
}
const startStates = [_]struct { sym: u16, state: u16 }{
    .{ .sym = 3, .state = 0 },
};

fn getStartState(startSym: u16) u16 {
    for (startStates) |entry| {
        if (entry.sym == startSym) return entry.state;
    }
    return 0;
}

const acceptRules = [_]u16{ 98 };

fn isAcceptRule(ruleId: u16) bool {
    for (acceptRules) |ar| if (ruleId == ar) return true;
    return false;
}
