//! Parser code generation. A generated module is composed of explicit
//! sections, in this order:
//!
//!   header        version line, `std`, the `@lang` import
//!   lexer         the lexer declarations from lexgen (TokenCat, Token,
//!                 the lexer struct, the Lexer alias)
//!   support       fallback `simd` helpers, when the lexer calls them
//!   enums         Tag, Role, Start
//!   runtime       the template sections `sexp`, `parser` (with the
//!                 `parse<Start>` methods in its `startMethods` slot) and,
//!                 in schema mode, `ir` (with per-kind views)
//!   grammar       configuration, token mapping, actions, tables,
//!                 diagnostics names, trivia, repair, side labels, slots
//!   api           the `Parser` alias and `parse<Start>(allocator, source)`
//!
//! The runtime text comes from runtime_template.zig (see runtime.zig); this
//! file writes only what depends on the grammar.

const std = @import("std");
const Allocator = std.mem.Allocator;
const version = @import("../version.zig").version;
const diag = @import("../diag.zig");
const grammar = @import("../grammar.zig");
const Grammar = grammar.Grammar;
const LexerSpec = grammar.LexerSpec;
const Schema = grammar.Schema;
const findTokenForChar = grammar.findTokenForChar;
const findTokenForLiteral = grammar.findTokenForLiteral;
const Automaton = @import("../lr/automaton.zig").Automaton;
const Table = @import("../lr/table.zig").Table;
const actions = @import("actions.zig");
const semantics = @import("../semantics.zig");
const runtime = @import("runtime.zig");

pub const Options = struct {
    /// Write each rule as a comment above its action.
    emitComments: bool = false,
    /// Record node spans and rule ids (always on in schema mode).
    spans: bool = false,
};

/// Generate the parser module. `lexerDecls` is lexgen's declarations
/// output (no module header).
pub fn generate(
    allocator: Allocator,
    g: *const Grammar,
    automaton: *const Automaton,
    table: *const Table,
    lexerSpec: ?*const LexerSpec,
    lexerDecls: []const u8,
    options: Options,
) ![]const u8 {
    var c: Codegen = .{
        .allocator = allocator,
        .g = g,
        .automaton = automaton,
        .table = table,
        .lexerSpec = lexerSpec,
        .options = options,
    };
    return c.run(lexerDecls);
}

/// A module holding only the lexer (a grammar with no parser rules).
pub fn lexerModule(allocator: Allocator, lang: ?[]const u8, lexerDecls: []const u8) ![]const u8 {
    var output: std.Io.Writer.Allocating = .init(allocator);
    const w = &output.writer;
    try writeHeader(w, lang);
    try w.writeAll(lexerDecls);
    try writeSimdSupport(w, lexerDecls);
    return output.toOwnedSlice();
}

fn writeHeader(w: *std.Io.Writer, lang: ?[]const u8) !void {
    try w.print("//! Generated by nexus v{s} — do not edit\n\nconst std = @import(\"std\");\n", .{version});
    if (lang) |name| try w.print("const {s} = @import(\"{s}.zig\");\n", .{ name, name });
    try w.writeAll("\n");
}

/// The `simd` helpers, when the lexer calls them (`simd_to` rules).
fn writeSimdSupport(w: *std.Io.Writer, lexerDecls: []const u8) !void {
    if (std.mem.indexOf(u8, lexerDecls, "simd.") != null) try w.writeAll(simdSupport);
}

/// Fallback for the `simd.findByte` calls a generated lexer may make.
const simdSupport =
    \\
    \\// SIMD helpers (fallback if simd.zig not available)
    \\const simd = struct {
    \\    fn findByte(haystack: []const u8, needle: u8) usize {
    \\        for (haystack, 0..) |c, i| if (c == needle) return i;
    \\        return haystack.len;
    \\    }
    \\};
    \\
;

fn banner(w: *std.Io.Writer, title: []const u8) !void {
    try w.print(
        \\
        \\// =============================================================================
        \\// {s}
        \\// =============================================================================
        \\
        \\
    , .{title});
}

/// `name` with its first letter upper-cased (start and `@as` rule names).
fn capitalized(allocator: Allocator, name: []const u8) ![]const u8 {
    const out = try allocator.dupe(u8, name);
    if (out.len > 0) out[0] = std.ascii.toUpper(out[0]);
    return out;
}

const Codegen = struct {
    allocator: Allocator,
    g: *const Grammar,
    automaton: *const Automaton,
    table: *const Table,
    lexerSpec: ?*const LexerSpec,
    options: Options,
    tags: actions.TagSet = .{},
    /// Schema mode: the Tag and Role enums, in declaration order.
    schemaTags: std.ArrayListUnmanaged([]const u8) = .empty,
    roles: std.ArrayListUnmanaged([]const u8) = .empty,
    /// Some action builds a nested node (`self.nested`).
    usesNested: bool = false,
    /// The token `@as` promotes (TokenCat name, e.g. `ident`).
    promotable: ?[]const u8 = null,
    /// The executeAction function, generated before the configuration.
    actionsCode: []const u8 = "",

    fn schema(self: *const Codegen) ?Schema {
        return self.g.schema;
    }

    fn nodeStore(self: *const Codegen) bool {
        return self.g.schema != null or self.options.spans;
    }

    fn run(self: *Codegen, lexerDecls: []const u8) ![]const u8 {
        var output: std.Io.Writer.Allocating = .init(self.allocator);
        const w = &output.writer;

        try self.tags.collect(self.allocator, self.g.rules.items);
        if (self.schema()) |s| try self.collectSchema(s);
        try self.validate();

        self.actionsCode = try self.generateActions();
        self.usesNested = std.mem.indexOf(u8, self.actionsCode, "self.nested(") != null;

        try writeHeader(w, self.g.lang);
        try w.writeAll(lexerDecls);
        try writeSimdSupport(w, lexerDecls);
        try self.emitEnums(w);
        try self.emitRuntime(w);
        try self.emitConfig(w);
        try self.emitTokenToSymbol(w);
        try self.emitIdentToSymbol(w);
        try w.writeAll(self.actionsCode);
        try self.emitAsMaps(w);
        try self.emitRuleTables(w);
        try self.emitParseTable(w);
        try self.emitExcludes(w);
        try self.emitStarts(w);
        try self.emitDiagnostics(w);
        try self.emitTrivia(w);
        try self.emitRepair(w);
        try self.emitSideLabels(w);
        try self.emitSlots(w);
        try self.emitApi(w);

        return output.toOwnedSlice();
    }

    // -------------------------------------------------------------------------
    // Checks
    // -------------------------------------------------------------------------

    fn collectSchema(self: *Codegen, s: Schema) !void {
        try self.schemaTags.appendSlice(self.allocator, try semantics.schemaTags(self.allocator, s));
        for (s.kinds) |k| {
            for (k.roles) |r| try self.addUnique(&self.roles, r.name);
            for (k.side) |r| try self.addUnique(&self.roles, r);
        }
    }

    fn addUnique(self: *Codegen, list: *std.ArrayListUnmanaged([]const u8), name: []const u8) !void {
        for (list.items) |existing| if (std.mem.eql(u8, existing, name)) return;
        try list.append(self.allocator, name);
    }

    fn roleDeclared(self: *const Codegen, name: []const u8) bool {
        for (self.roles.items) |r| if (std.mem.eql(u8, r, name)) return true;
        return false;
    }

    fn validate(self: *Codegen) !void {
        // Schema mode: every tag an action produces is in the Tag enum.
        if (self.schema() != null) {
            var missing: usize = 0;
            for (self.tags.list.items) |t| {
                const declared = for (self.schemaTags.items) |s| {
                    if (std.mem.eql(u8, s, t)) break true;
                } else false;
                if (!declared) {
                    diag.err("tag '{s}' is produced by an action but not declared in @schema or @tags", .{t});
                    missing += 1;
                }
            }
            if (missing > 0) return error.UndeclaredTag;
        }

        for (self.g.rules.items) |rule| {
            if (rule.rhs.len > 255) {
                diag.err("rule {d} has {d} elements; the limit is 255", .{ rule.id, rule.rhs.len });
                return error.RuleTooLong;
            }
            if (rule.sideLabels.len == 0) continue;
            if (self.schema() == null) {
                diag.err("rule {d} (line {d}) records side-band roles, which need @schema", .{ rule.id, rule.line });
                return error.SideLabelWithoutSchema;
            }
            for (rule.sideLabels) |label| if (!self.roleDeclared(label.role)) {
                diag.err("rule {d} (line {d}): side-band role '{s}' is not declared in @schema", .{ rule.id, rule.line, label.role });
                return error.UnknownRole;
            };
        }

        for (self.g.trivia) |name| {
            if (self.tokenCatOf(name) == null) {
                diag.err("@trivia names '{s}', which is not a lexer token", .{name});
                return error.UnknownTriviaToken;
            }
            if (self.terminalUsed(name)) |ruleId| {
                diag.err("@trivia token '{s}' is used by rule {d}; trivia never reaches the parser", .{ name, ruleId });
                return error.TriviaTokenInGrammar;
            }
        }

        for (self.g.asDirectives) |directive| {
            const token = self.promotable orelse directive.token;
            if (!std.mem.eql(u8, token, directive.token)) {
                diag.err("@as promotes '{s}' and '{s}'; one grammar promotes one token", .{ token, directive.token });
                return error.MultiplePromotableTokens;
            }
            self.promotable = token;
            if (directive.via != null and self.g.lang == null) {
                diag.err("@as {s} via {s}: the lookup function lives in the @lang module, and the grammar has no @lang", .{ directive.token, directive.via.? });
                return error.ViaWithoutLang;
            }
        }

        if (self.g.repair != null and self.table.repair == null) {
            diag.err("the grammar has @repair but no repair table was computed", .{});
            return error.MissingRepairTable;
        }
    }

    /// The lexer token (TokenCat name) a grammar token name refers to.
    fn tokenCatOf(self: *const Codegen, name: []const u8) ?[]const u8 {
        const spec = self.lexerSpec orelse return null;
        for (spec.tokens.items) |tok| {
            if (std.ascii.eqlIgnoreCase(tok.name, name)) return tok.name;
        }
        return null;
    }

    /// A rule whose right-hand side uses terminal `name`.
    fn terminalUsed(self: *const Codegen, name: []const u8) ?u16 {
        for (self.g.symbols.items) |sym| {
            if (sym.kind != .terminal or !std.ascii.eqlIgnoreCase(sym.name, name)) continue;
            for (self.g.rules.items) |rule| {
                for (rule.rhs) |id| if (id == sym.id) return rule.id;
            }
        }
        return null;
    }

    // -------------------------------------------------------------------------
    // Enums and runtime
    // -------------------------------------------------------------------------

    fn emitEnums(self: *Codegen, w: *std.Io.Writer) !void {
        if (self.schema() != null) {
            try banner(w, "Tag and Role enums (from @schema)");
            const width: u8 = if (self.schemaTags.items.len <= 256) 8 else 16;
            try w.print("pub const Tag = enum(u{d}) {{\n", .{width});
            for (self.schemaTags.items) |t| try w.print("    @\"{f}\",\n", .{std.zig.fmtString(t)});
            try w.writeAll("};\n\npub const Role = enum(u16) {\n");
            for (self.roles.items) |r| try w.print("    @\"{f}\",\n", .{std.zig.fmtString(r)});
            try w.writeAll("};\n");
        } else if (self.g.lang) |name| {
            try banner(w, "Tag enum (re-exported from the language module)");
            try w.print("pub const Tag = {s}.Tag;\n\n/// Roles exist only in schema mode.\npub const Role = enum(u16) {{}};\n", .{name});
        } else {
            try banner(w, "Tag enum (collected from grammar actions)");
            try w.writeAll("pub const Tag = enum(u8) {\n");
            for (self.tags.list.items) |t| try w.print("    @\"{f}\",\n", .{std.zig.fmtString(t)});
            try w.writeAll("    _,\n};\n\n/// Roles exist only in schema mode.\npub const Role = enum(u16) {};\n");
        }

        try w.writeAll("\n/// Start symbols; `BaseParser.parse(start)` parses one.\npub const Start = enum(u16) {\n");
        for (self.g.startSymbols.items) |symId| {
            if (self.markerOf(symId) == null) continue;
            try w.print("    @\"{s}\" = {d},\n", .{ self.g.symbols.items[symId].name, symId });
        }
        try w.writeAll("};\n");
    }

    fn markerOf(self: *const Codegen, startSym: u16) ?u16 {
        var buf: [256]u8 = undefined;
        const name = std.fmt.bufPrint(&buf, "{s}!", .{self.g.symbols.items[startSym].name}) catch return null;
        return self.g.getSymbol(name);
    }

    fn emitRuntime(self: *Codegen, w: *std.Io.Writer) !void {
        try runtime.writeSection(w, "sexp", &.{});

        var methods: std.Io.Writer.Allocating = .init(self.allocator);
        for (self.g.startSymbols.items) |symId| {
            if (self.markerOf(symId) == null) continue;
            const name = self.g.symbols.items[symId].name;
            try methods.writer.print(
                \\    pub fn parse{s}(self: *BaseParser) !Sexp {{
                \\        return self.parse(.@"{s}");
                \\    }}
                \\
                \\
            , .{ try capitalized(self.allocator, name), name });
        }
        try runtime.writeSection(w, "parser", &.{.{ .name = "startMethods", .text = methods.written() }});

        if (self.schema()) |s| {
            var views: std.Io.Writer.Allocating = .init(self.allocator);
            try self.writeViews(&views.writer, s);
            try runtime.writeSection(w, "ir", &.{.{ .name = "views", .text = views.written() }});
        }
    }

    /// `ir.Set.target(node)`: one namespace per kind, one function per role.
    fn writeViews(self: *Codegen, w: *std.Io.Writer, s: Schema) !void {
        var names: std.StringHashMapUnmanaged([]const u8) = .empty;
        for (s.kinds) |k| {
            const view = try viewName(self.allocator, k.tag);
            if (names.get(view)) |other| {
                diag.err("@schema kinds '{s}' and '{s}' both map to the accessor namespace ir.{s}", .{ other, k.tag, view });
                return error.ViewNameClash;
            }
            try names.put(self.allocator, view, k.tag);
            const tag = std.zig.fmtString(k.tag);
            try w.print("    pub const {s} = struct {{\n", .{view});
            for (k.roles, 0..) |r, i| {
                const role = std.zig.fmtString(r.name);
                const what = std.zig.fmtString(try std.fmt.allocPrint(self.allocator, "ir.{s}.{s}", .{ view, r.name }));
                if (r.rest) {
                    try w.print("        pub fn @\"{f}\"(@\"ir.node\": @\"ir.Sexp\") []const @\"ir.Sexp\" {{\n            return @\"ir.restAt\"(@\"ir.node\", .@\"{f}\", {d}, \"{f}\");\n        }}\n", .{ role, tag, i + 1, what });
                } else {
                    try w.print("        pub fn @\"{f}\"(@\"ir.node\": @\"ir.Sexp\") @\"ir.Sexp\" {{\n            return @\"ir.at\"(@\"ir.node\", .@\"{f}\", {d}, \"{f}\");\n        }}\n", .{ role, tag, i + 1, what });
                }
            }
            try w.writeAll("    };\n");
        }
    }

    // -------------------------------------------------------------------------
    // Grammar-specific code
    // -------------------------------------------------------------------------

    fn emitConfig(self: *Codegen, w: *std.Io.Writer) !void {
        try banner(w, "Grammar");
        try w.print(
            \\/// Node spans and rule ids are recorded (`@schema` or `--spans`).
            \\pub const nodeStore = {};
            \\/// Element extents are kept for side-band labels and nested nodes.
            \\const elemEnds = {};
            \\/// Lists keep trailing nils: positions are fixed by the schema.
            \\const keepTrailingNils = {};
            \\const hasTrivia = {};
            \\const hasRepair = {};
            \\const numSymbols = {d};
            \\const endSymbol: u16 = {d};
            \\const errorSymbol: u16 = {d};
            \\
        , .{
            self.nodeStore(),
            self.nodeStore() and self.needsElemEnds(),
            self.schema() != null,
            self.g.trivia.len > 0,
            self.table.repair != null,
            self.g.symbols.items.len,
            self.g.endId,
            self.g.errorId,
        });
    }

    /// Whether some action records a side-band label or builds a nested node.
    fn needsElemEnds(self: *const Codegen) bool {
        for (self.g.rules.items) |rule| if (rule.sideLabels.len > 0) return true;
        return self.usesNested;
    }

    fn hasIdentAs(self: *const Codegen) bool {
        return self.promotable != null;
    }

    /// tokenToSymbol: TokenCat -> grammar symbol.
    fn emitTokenToSymbol(self: *Codegen, w: *std.Io.Writer) !void {
        const identAs = self.hasIdentAs();
        try w.writeAll(if (identAs)
            "\nfn tokenToSymbol(self: *BaseParser, token: Token) u16 {\n"
        else
            "\nfn tokenToSymbol(_: *BaseParser, token: Token) u16 {\n");
        try w.writeAll("    return switch (token.cat) {\n");
        try w.print("        .@\"eof\" => {d},\n", .{self.g.endId});

        var emitted: std.StringHashMapUnmanaged(void) = .empty;
        if (self.promotable) |tok| try w.print("        .@\"{s}\" => promote(self, token),\n", .{tok});

        for (self.g.symbols.items) |sym| {
            if (sym.kind != .terminal or sym.name.len == 0) continue;
            if (sym.name[0] == '$' or sym.name[0] == '"') continue;
            if (std.mem.endsWith(u8, sym.name, "!")) continue;
            if (std.mem.eql(u8, sym.name, "error")) continue;

            const lowerName = try std.ascii.allocLowerString(self.allocator, sym.name);
            if (self.promotable) |tok| if (std.mem.eql(u8, lowerName, tok)) continue;
            if (self.isPromotedKeyword(sym.name, identAs)) continue;

            // Only names that can be TokenCat fields
            var valid = lowerName[0] >= 'a' and lowerName[0] <= 'z';
            for (lowerName) |ch| {
                if (!((ch >= 'a' and ch <= 'z') or (ch >= '0' and ch <= '9') or ch == '_')) valid = false;
            }
            if (valid and !emitted.contains(lowerName)) {
                try w.print("        .@\"{s}\" => {d},\n", .{ lowerName, sym.id });
                try emitted.put(self.allocator, lowerName, {});
            }
        }

        // `@op` mappings for operator literals (e.g. "'=" => noteq)
        for (self.g.symbols.items) |sym| {
            if (sym.kind != .terminal or sym.name.len < 2 or sym.name[0] != '"') continue;
            const literal = try unescapeLiteral(self.allocator, sym.name[1 .. sym.name.len - 1]);
            for (self.g.opMappings) |m| {
                if (std.mem.eql(u8, literal, m.lit) and !emitted.contains(m.tok)) {
                    try w.print("        .@\"{s}\" => {d},\n", .{ m.tok, sym.id });
                    try emitted.put(self.allocator, m.tok, {});
                    break;
                }
            }
        }

        // Single-character literals: the token whose lexer pattern is that char
        for (self.g.symbols.items) |sym| {
            if (sym.kind != .terminal or sym.name.len < 3 or sym.name[0] != '"') continue;
            const char: ?u8 = if (sym.name.len == 3 and sym.name[2] == '"')
                sym.name[1]
            else if (sym.name.len == 4 and sym.name[1] == '\\' and sym.name[3] == '"')
                sym.name[2]
            else
                null;
            const c = char orelse continue;
            const spec = self.lexerSpec orelse continue;
            const tokName = findTokenForChar(spec, c) orelse continue;
            if (!emitted.contains(tokName)) {
                try w.print("        .@\"{s}\" => {d},\n", .{ tokName, sym.id });
                try emitted.put(self.allocator, tokName, {});
            }
        }

        // Multi-character literals: the token whose lexer pattern is that string
        for (self.g.symbols.items) |sym| {
            if (sym.kind != .terminal or sym.name.len < 4 or sym.name[0] != '"') continue;
            const raw = sym.name[1 .. sym.name.len - 1];
            if (raw.len < 2) continue;
            const spec = self.lexerSpec orelse continue;
            const tokName = findTokenForLiteral(spec, raw) orelse continue;
            if (!emitted.contains(tokName)) {
                try w.print("        .@\"{s}\" => {d},\n", .{ tokName, sym.id });
                try emitted.put(self.allocator, tokName, {});
            }
        }

        try w.print("        else => {d}, // error\n    }};\n}}\n", .{self.g.errorId});
    }

    /// Whether terminal `name` reaches the parser by `@as` promotion of an
    /// identifier rather than as its own token category:
    ///   1. it names an `@as` group (CMD for `@as ident = [cmd]`);
    ///   2. a declared lexer token of that name makes it direct;
    ///   3. else it is promoted if a nonterminal has the same name, or if
    ///      the grammar uses `@as` at all.
    fn isPromotedKeyword(self: *const Codegen, name: []const u8, identAs: bool) bool {
        if (name[0] < 'A' or name[0] > 'Z') return false;
        for (self.g.asDirectives) |directive| {
            if (std.ascii.eqlIgnoreCase(name, directive.rule)) return true;
        }
        if (self.lexerSpec) |spec| {
            for (spec.tokens.items) |tok| if (std.ascii.eqlIgnoreCase(tok.name, name)) return false;
            for (spec.rules.items) |rule| if (std.ascii.eqlIgnoreCase(rule.token, name)) return false;
        }
        for (self.g.symbols.items) |other| {
            if (other.kind == .nonterminal and std.ascii.eqlIgnoreCase(name, other.name)) return true;
        }
        return identAs;
    }

    /// promote and the tryPromote* keyword promoters (`@as`): the promotable
    /// token becomes the first group keyword the state accepts.
    fn emitIdentToSymbol(self: *Codegen, w: *std.Io.Writer) !void {
        if (!self.hasIdentAs()) return;
        try w.writeAll(
            \\
            \\fn promote(self: *BaseParser, token: Token) u16 {
            \\    const text = self.source[token.pos..][0..token.len];
            \\    if (text.len == 0) return promotableSymbol;
            \\
        );
        // Ordered resolution: `@as` candidates in declared order; `self`
        // keeps the token itself if the state takes it.
        for (self.g.asDirectives) |directive| {
            if (isSelf(directive)) {
                try w.writeAll("    if (getAction(self.stateStack.getLast(), promotableSymbol) != 0) return promotableSymbol;\n");
            } else {
                try w.print("    if (tryPromote{s}(self, text)) |sym| return sym;\n", .{try capitalized(self.allocator, directive.rule)});
            }
        }
        try w.writeAll("    return promotableSymbol;\n}\n");

        // Matching mode per group: `group!` or any group after `self` is
        // permissive (any action), otherwise strict (shift only).
        var seenSelf = false;
        for (self.g.asDirectives) |directive| {
            if (isSelf(directive)) {
                seenSelf = true;
                continue;
            }
            const check: []const u8 = if (directive.permissive or seenSelf) "!= 0" else "> 0";
            const cap = try capitalized(self.allocator, directive.rule);
            // The lang lookup is `via` when given, else `<group>As`.
            const lookup = if (self.g.lang) |lang|
                try std.fmt.allocPrint(self.allocator, "{s}.{s}", .{ lang, directive.via orelse try std.fmt.allocPrint(self.allocator, "{s}As", .{directive.rule}) })
            else
                try std.fmt.allocPrint(self.allocator, "{s}As", .{directive.rule});
            try w.print(
                \\
                \\fn tryPromote{s}(self: *BaseParser, text: []const u8) ?u16 {{
                \\    const state = self.stateStack.getLast();
                \\    const id = {s}(text) orelse return null;
                \\    const idIdx = @intFromEnum(id);
                \\    const sym = {s}ToSymbol[idIdx];
                \\    if (sym != 0 and getAction(state, sym) {s}) {{
                \\        self.lastMatchedId = @intCast(idIdx);
                \\        return sym;
                \\    }}
                \\
            , .{ cap, lookup, directive.rule, check });
            if (self.g.lang != null) try w.print(
                \\    const fallback = {s}FallbackSymbol;
                \\    if (fallback != 0 and getAction(state, fallback) {s}) {{
                \\        self.lastMatchedId = @intCast(idIdx);
                \\        return fallback;
                \\    }}
                \\
            , .{ directive.rule, check });
            try w.writeAll("    return null;\n}\n");
        }
    }

    fn isSelf(directive: grammar.AsDirective) bool {
        return std.mem.eql(u8, directive.rule, "self") or std.mem.eql(u8, directive.rule, directive.token);
    }

    /// executeAction: one switch arm per reducible rule. Accept rules are
    /// never reduced (the table accepts on end of input before them).
    fn generateActions(self: *Codegen) ![]const u8 {
        var out: std.Io.Writer.Allocating = .init(self.allocator);
        const w = &out.writer;
        var arms: std.Io.Writer.Allocating = .init(self.allocator);
        const a = &arms.writer;
        for (self.g.rules.items, 0..) |rule, ruleIdx| {
            if (self.g.isAcceptRule(@intCast(ruleIdx))) continue;
            if (self.options.emitComments) {
                try a.print("        // {s} =", .{self.g.symbols.items[rule.lhs].name});
                for (rule.rhs) |symId| try a.print(" {s}", .{self.g.symbols.items[symId].name});
                if (rule.action) |action| try a.print(" \xe2\x86\x92 {s}", .{action});
                try a.writeAll("\n");
            }
            try a.print("        {d} => ", .{ruleIdx});
            try actions.generateRuleAction(self.allocator, a, self.g, rule);
            try a.writeAll(",\n");
        }
        const body = arms.written();
        try w.writeAll("\nfn executeAction(self: *BaseParser, ruleId: u16, pass: []Sexp) Sexp {\n");
        try w.writeAll("    @setEvalBranchQuota(1_000_000);\n");
        if (std.mem.indexOf(u8, body, "self.") == null) try w.writeAll("    _ = self;\n");
        if (std.mem.indexOf(u8, body, "pass") == null) try w.writeAll("    _ = pass;\n");
        try w.writeAll("    return switch (ruleId) {\n");
        try w.writeAll(body);
        try w.writeAll("        else => unreachable,\n    };\n}\n");
        return out.written();
    }

    /// `@as`: <rule>Id -> symbol maps (and inline keyword matchers without @lang).
    fn emitAsMaps(self: *Codegen, w: *std.Io.Writer) !void {
        if (!self.hasIdentAs()) return;
        // The promotable token's own symbol (error when no rule uses it).
        var symbol = self.g.errorId;
        for (self.g.symbols.items) |sym| {
            if (sym.kind == .terminal and std.ascii.eqlIgnoreCase(sym.name, self.promotable.?)) {
                symbol = sym.id;
                break;
            }
        }
        try w.print("\nconst promotableSymbol: u16 = {d};\n", .{symbol});

        var emittedRules: std.StringHashMapUnmanaged(void) = .empty;
        for (self.g.asDirectives) |directive| {
            if (isSelf(directive)) continue;
            if (emittedRules.contains(directive.rule)) continue;
            try emittedRules.put(self.allocator, directive.rule, {});

            const cap = try capitalized(self.allocator, directive.rule);
            const upper = try std.ascii.allocUpperString(self.allocator, directive.rule);
            const idType = if (self.g.lang) |lang|
                try std.fmt.allocPrint(self.allocator, "{s}.{s}Id", .{ lang, cap })
            else
                try std.fmt.allocPrint(self.allocator, "{s}Id", .{cap});

            if (self.g.lang == null) {
                // Inline: one keyword per group, matched exactly
                try w.print("\nconst {s}Id = enum(u16) {{ {s} = 0 }};\n", .{ cap, upper });
                try w.print("fn {s}As(name: []const u8) ?{s}Id {{\n    return if (std.mem.eql(u8, name, \"{s}\")) .{s} else null;\n}}\n", .{ directive.rule, cap, directive.rule, upper });
            }

            // Every UPPERCASE terminal is a potential target; `@hasField` at
            // comptime keeps those the Id enum names. Without @lang only
            // terminals that name a nonterminal are candidates.
            var targets: std.ArrayListUnmanaged(grammar.Symbol) = .empty;
            for (self.g.symbols.items) |sym| {
                if (sym.kind != .terminal or sym.name.len == 0) continue;
                if (sym.name[0] < 'A' or sym.name[0] > 'Z') continue;
                if (std.mem.endsWith(u8, sym.name, "!")) continue;
                if (self.g.lang == null) {
                    const matches = for (self.g.symbols.items) |other| {
                        if (other.kind == .nonterminal and std.ascii.eqlIgnoreCase(sym.name, other.name)) break true;
                    } else false;
                    if (!matches) continue;
                }
                try targets.append(self.allocator, sym);
            }

            var fallbackId: ?u16 = null;
            for (self.g.symbols.items) |sym| {
                if (sym.kind == .terminal and std.mem.eql(u8, sym.name, upper)) {
                    fallbackId = sym.id;
                    break;
                }
            }

            try w.print("\n/// {s} ordinal -> grammar symbol (0 = none)\nconst {s}ToSymbol = blk: {{\n", .{ idType, directive.rule });
            try w.writeAll(if (targets.items.len > 0 or fallbackId != null)
                "    var arr: [512]u16 = .{0} ** 512;\n"
            else
                "    const arr: [512]u16 = .{0} ** 512;\n");
            for (targets.items) |term| {
                try w.print("    if (@hasField({s}, \"{s}\")) arr[@intFromEnum({s}.{s})] = {d};\n", .{ idType, term.name, idType, term.name, term.id });
            }
            if (fallbackId) |fid| {
                try w.print(
                    \\    for (@typeInfo({s}).@"enum".fields) |field| {{
                    \\        if (arr[field.value] == 0) arr[field.value] = {d};
                    \\    }}
                    \\
                , .{ idType, fid });
            }
            try w.writeAll("    break :blk arr;\n};\n");
            if (self.g.lang != null) {
                try w.print("const {s}FallbackSymbol: u16 = {d};\n", .{ directive.rule, fallbackId orelse 0 });
            }
        }
    }

    /// Per-rule lhs symbol and rhs length.
    fn emitRuleTables(self: *Codegen, w: *std.Io.Writer) !void {
        try w.writeAll("\nconst ruleLhs = [_]u16{ ");
        for (self.g.rules.items, 0..) |rule, i| {
            if (i > 0) try w.writeAll(", ");
            try w.print("{d}", .{rule.lhs});
        }
        try w.writeAll(" };\nconst ruleLen = [_]u8{ ");
        for (self.g.rules.items, 0..) |rule, i| {
            if (i > 0) try w.writeAll(", ");
            try w.print("{d}", .{rule.rhs.len});
        }
        try w.writeAll(" };\n");
    }

    /// The parse table (sparse rows expanded to a dense table at comptime).
    fn emitParseTable(self: *Codegen, w: *std.Io.Writer) !void {
        const rows = self.table.rows;
        try w.print(
            \\
            \\// Parse table: {d} states x {d} symbols. 0 = error, > 0 = shift or
            \\// goto, -1 = accept, <= -2 = reduce rule (-a - 2).
            \\const numStates = {d};
            \\
            \\const sparse = [numStates][]const i16{{
            \\
        , .{ rows.len, self.g.symbols.items.len, rows.len });

        for (rows) |row| {
            try w.writeAll("    &.{");
            var first = true;
            for (row, 0..) |action, sym| {
                const value: i16 = switch (action) {
                    .shift => |s| @intCast(s),
                    .reduce => |r| -@as(i16, @intCast(r)) - 2,
                    .gotoState => |s| @intCast(s),
                    .accept => -1,
                    .err => continue,
                };
                if (!first) try w.writeAll(",");
                try w.print("{d},{d}", .{ sym, value });
                first = false;
            }
            try w.writeAll("},\n");
        }
        try w.writeAll(
            \\};
            \\
            \\const parseTable = blk: {
            \\    @setEvalBranchQuota(100000);
            \\    var t: [numStates][numSymbols]i16 = .{.{0} ** numSymbols} ** numStates;
            \\    for (sparse, 0..) |row, state| {
            \\        var i: usize = 0;
            \\        while (i < row.len) : (i += 2) {
            \\            t[state][@intCast(row[i])] = row[i + 1];
            \\        }
            \\    }
            \\    break :blk t;
            \\};
            \\
            \\fn getAction(state: u16, sym: u16) i16 {
            \\    return parseTable[state][sym];
            \\}
            \\
        );
    }

    /// `X "c"` exclusions (grouped by state) and the runtime shift override.
    fn emitExcludes(self: *Codegen, w: *std.Io.Writer) !void {
        try w.writeAll("\n// X \"c\" excludes: shift instead of reduce when pre == 0 and the next byte matches\n");
        try w.writeAll("const xExcludes = [_]struct { char: u8, shift: u16 }{\n");
        for (self.table.xExcludes.items) |x| {
            try w.print("    .{{ .char = {d}, .shift = {d} }},\n", .{ x.char, x.shift });
        }
        try w.writeAll("};\n");
        if (self.table.xExcludes.items.len == 0) {
            try w.writeAll(
                \\
                \\fn getImmediateShift(_: u16, _: u8) ?i16 {
                \\    return null;
                \\}
                \\
            );
            return;
        }
        try w.writeAll("/// State s's excludes: xExcludes[xExcludeStart[s]..xExcludeStart[s + 1]].\nconst xExcludeStart = [_]u32{");
        try writeList(w, u32, self.table.xExcludeStart);
        try w.writeAll(
            \\};
            \\
            \\fn getImmediateShift(state: u16, char: u8) ?i16 {
            \\    for (xExcludes[xExcludeStart[state]..xExcludeStart[state + 1]]) |x| {
            \\        if (x.char == char) return @intCast(x.shift);
            \\    }
            \\    return null;
            \\}
            \\
        );
    }

    /// Initial state and marker token per start symbol.
    fn emitStarts(self: *Codegen, w: *std.Io.Writer) !void {
        var states: std.Io.Writer.Allocating = .init(self.allocator);
        var markers: std.Io.Writer.Allocating = .init(self.allocator);
        for (self.g.startSymbols.items, self.automaton.startStates.items) |sym, state| {
            const marker = self.markerOf(sym) orelse continue;
            const name = self.g.symbols.items[sym].name;
            try states.writer.print("        .@\"{s}\" => {d},\n", .{ name, state });
            try markers.writer.print("        .@\"{s}\" => {d},\n", .{ name, marker });
        }
        try w.print(
            \\
            \\fn startState(start: Start) u16 {{
            \\    return switch (start) {{
            \\{s}    }};
            \\}}
            \\
            \\fn startMarker(start: Start) u16 {{
            \\    return switch (start) {{
            \\{s}    }};
            \\}}
            \\
        , .{ states.written(), markers.written() });
    }

    // -------------------------------------------------------------------------
    // Diagnostics names
    // -------------------------------------------------------------------------

    /// The reader-facing name of a symbol: `@display`, `@errors`, else the
    /// literal as written or the token name in lower case.
    fn displayName(self: *const Codegen, sym: grammar.Symbol) !?[]const u8 {
        if (sym.kind == .nonterminal) {
            // By symbol: an @errors rule may be an alias (`expr = @infix`).
            for (self.g.errorNames) |e| if (self.g.getSymbol(e.rule) == sym.id) return e.name;
            return null;
        }
        if (sym.id == self.g.errorId) return null;
        if (sym.id == self.g.endId) {
            for (self.g.displayNames) |d| if (std.ascii.eqlIgnoreCase(d.token, "eof")) return d.name;
            return "end of input";
        }
        if (sym.name.len == 0 or sym.name[0] == '$' or std.mem.endsWith(u8, sym.name, "!")) return null;
        for (self.g.displayNames) |d| if (std.mem.eql(u8, d.token, sym.name)) return d.name;
        for (self.g.displayNames) |d| if (std.ascii.eqlIgnoreCase(d.token, sym.name)) return d.name;
        if (sym.name[0] == '"') return sym.name;
        return try std.ascii.allocLowerString(self.allocator, sym.name);
    }

    /// Expected sets (from the LR stage) and symbol display names.
    fn emitDiagnostics(self: *Codegen, w: *std.Io.Writer) !void {
        const e = self.table.expected;
        try w.writeAll("\n/// Expected symbols per state: state s expects list i = expectedOf[s],\n/// expectedSymbols[expectedOffsets[i]..expectedOffsets[i + 1]].\nconst expectedSymbols = [_]u16{");
        try writeList(w, u16, e.symbols);
        try w.writeAll("};\nconst expectedOffsets = [_]u32{");
        try writeList(w, u32, e.offsets);
        try w.writeAll("};\nconst expectedOf = [_]u16{");
        try writeList(w, u16, e.ofState);
        try w.writeAll(
            \\};
            \\
            \\fn expectedIn(state: u16) []const u16 {
            \\    const i = expectedOf[state];
            \\    return expectedSymbols[expectedOffsets[i]..expectedOffsets[i + 1]];
            \\}
            \\
        );

        try w.writeAll("\nfn symbolName(sym: u16) []const u8 {\n    return switch (sym) {\n");
        for (self.g.symbols.items) |sym| {
            const name = try self.displayName(sym) orelse continue;
            try w.print("        {d} => \"{f}\",\n", .{ sym.id, std.zig.fmtString(name) });
        }
        try w.writeAll("        else => \"\",\n    };\n}\n");
    }

    // -------------------------------------------------------------------------
    // Trivia, repair, side labels, schema slots
    // -------------------------------------------------------------------------

    fn emitTrivia(self: *Codegen, w: *std.Io.Writer) !void {
        if (self.g.trivia.len == 0) {
            try w.writeAll("\nfn isTrivia(_: TokenCat) bool {\n    return false;\n}\n");
            return;
        }
        try w.writeAll("\n/// `@trivia` tokens: kept on the trivia channel, never parsed.\nfn isTrivia(cat: TokenCat) bool {\n    return switch (cat) {\n");
        for (self.g.trivia) |name| try w.print("        .@\"{s}\" => true,\n", .{self.tokenCatOf(name).?});
        try w.writeAll("        else => false,\n    };\n}\n");
    }

    fn emitRepair(self: *Codegen, w: *std.Io.Writer) !void {
        const r = self.table.repair orelse {
            try w.writeAll("\nfn repairCandidates(_: u16) []const u16 {\n    return &.{};\n}\n");
            return;
        };
        try w.writeAll("\n/// Tolerant repair: state s may insert, best first,\n/// repairTokens[repairOffsets[s]..repairOffsets[s + 1]].\nconst repairTokens = [_]u16{");
        try writeList(w, u16, r.tokens);
        try w.writeAll("};\nconst repairOffsets = [_]u32{");
        try writeList(w, u32, r.offsets);
        try w.writeAll(
            \\};
            \\
            \\fn repairCandidates(state: u16) []const u16 {
            \\    return repairTokens[repairOffsets[state]..repairOffsets[state + 1]];
            \\}
            \\
        );
    }

    fn emitSideLabels(self: *Codegen, w: *std.Io.Writer) !void {
        try w.writeAll("\nfn ruleSideLabels(rule: u16) []const SideLabel {\n");
        var any = false;
        for (self.g.rules.items) |rule| {
            if (rule.sideLabels.len == 0) continue;
            if (!any) try w.writeAll("    return switch (rule) {\n");
            any = true;
            try w.print("        {d} => &.{{", .{rule.id});
            for (rule.sideLabels) |label| {
                try w.print(" .{{ .role = .@\"{f}\", .pass = {d} }},", .{ std.zig.fmtString(label.role), label.pos - 1 + rule.actionOffset });
            }
            try w.writeAll(" },\n");
        }
        if (any) {
            try w.writeAll("        else => &.{},\n    };\n}\n");
        } else {
            try w.writeAll("    _ = rule;\n    return &.{};\n}\n");
        }
    }

    /// slotOf / restSlotOf / roleAt / restRoleOf: the schema's slot layout.
    fn emitSlots(self: *Codegen, w: *std.Io.Writer) !void {
        const s = self.schema() orelse {
            try w.writeAll(
                \\
                \\fn slotOf(_: Tag, _: Role) ?usize {
                \\    return null;
                \\}
                \\
                \\fn restSlotOf(_: Tag, _: Role) ?usize {
                \\    return null;
                \\}
                \\
                \\fn roleAt(_: Tag, _: usize) ?Role {
                \\    return null;
                \\}
                \\
                \\fn restRoleOf(_: Tag) ?struct { role: Role, slot: usize } {
                \\    return null;
                \\}
                \\
            );
            return;
        };
        try banner(w, "Schema slots");
        try w.writeAll("/// Slot of `role` in nodes of `kind` (the head is slot 0).\nfn slotOf(kind: Tag, role: Role) ?usize {\n    return switch (kind) {\n");
        for (s.kinds) |k| {
            var any = false;
            for (k.roles, 0..) |r, i| {
                if (r.rest) continue;
                if (!any) try w.print("        .@\"{f}\" => switch (role) {{\n", .{std.zig.fmtString(k.tag)});
                any = true;
                try w.print("            .@\"{f}\" => {d},\n", .{ std.zig.fmtString(r.name), i + 1 });
            }
            if (any) try w.writeAll("            else => null,\n        },\n");
        }
        try w.writeAll("        else => null,\n    };\n}\n");

        try w.writeAll("\n/// First slot of rest role `role` in nodes of `kind`.\nfn restSlotOf(kind: Tag, role: Role) ?usize {\n    return switch (kind) {\n");
        for (s.kinds) |k| {
            for (k.roles, 0..) |r, i| if (r.rest) {
                try w.print("        .@\"{f}\" => if (role == .@\"{f}\") {d} else null,\n", .{ std.zig.fmtString(k.tag), std.zig.fmtString(r.name), i + 1 });
            };
        }
        try w.writeAll("        else => null,\n    };\n}\n");

        try w.writeAll("\n/// The slot role at `slot` of nodes of `kind`.\nfn roleAt(kind: Tag, slot: usize) ?Role {\n    return switch (kind) {\n");
        for (s.kinds) |k| {
            var any = false;
            for (k.roles, 0..) |r, i| {
                if (r.rest) continue;
                if (!any) try w.print("        .@\"{f}\" => switch (slot) {{\n", .{std.zig.fmtString(k.tag)});
                any = true;
                try w.print("            {d} => .@\"{f}\",\n", .{ i + 1, std.zig.fmtString(r.name) });
            }
            if (any) try w.writeAll("            else => null,\n        },\n");
        }
        try w.writeAll("        else => null,\n    };\n}\n");

        try w.writeAll("\nfn restRoleOf(kind: Tag) ?struct { role: Role, slot: usize } {\n    return switch (kind) {\n");
        for (s.kinds) |k| {
            for (k.roles, 0..) |r, i| if (r.rest) {
                try w.print("        .@\"{f}\" => .{{ .role = .@\"{f}\", .slot = {d} }},\n", .{ std.zig.fmtString(k.tag), std.zig.fmtString(r.name), i + 1 });
            };
        }
        try w.writeAll("        else => null,\n    };\n}\n");
    }

    // -------------------------------------------------------------------------
    // Public API
    // -------------------------------------------------------------------------

    /// The `Parser` alias and top-level parse<Start>(allocator, source)
    /// helpers. The returned tree lives in `result.parser`'s arena; the
    /// caller must `result.parser.deinit()` when done with it. The parser
    /// is returned by value, so a lang `Parser` wrapper must be movable.
    fn emitApi(self: *Codegen, w: *std.Io.Writer) !void {
        try banner(w, "API");
        if (self.g.lang) |lang| {
            try w.print("pub const Parser = if (@hasDecl({s}, \"Parser\")) {s}.Parser else BaseParser;\n", .{ lang, lang });
        } else {
            try w.writeAll("pub const Parser = BaseParser;\n");
        }
        for (self.g.startSymbols.items) |symId| {
            if (self.markerOf(symId) == null) continue;
            const name = self.g.symbols.items[symId].name;
            const fname = try capitalized(self.allocator, name);
            try w.print(
                \\
                \\/// Parse a whole {s} with a new `Parser`. The caller owns
                \\/// `result.parser` and must `deinit()` it when done with the tree.
                \\pub fn parse{s}(allocator: std.mem.Allocator, source: []const u8) !struct {{ parser: Parser, sexp: Sexp }} {{
                \\    var p = Parser.init(allocator, source);
                \\    errdefer p.deinit();
                \\    const sexp = try p.parse{s}();
                \\    return .{{ .parser = p, .sexp = sexp }};
                \\}}
                \\
            , .{ name, fname, fname });
        }
    }
};

/// ` a, b, c,` (24 values per line) for an array literal.
fn writeList(w: *std.Io.Writer, comptime T: type, values: []const T) !void {
    for (values, 0..) |v, i| {
        if (i % 24 == 0) try w.writeAll("\n   ");
        try w.print(" {d},", .{v});
    }
    if (values.len > 0) try w.writeAll("\n");
}

/// Accessor namespace for a kind: `if_stmt` -> `IfStmt`; kinds that are
/// not identifiers keep their text (`@"+"`).
fn viewName(allocator: Allocator, kind: []const u8) ![]const u8 {
    const ident = kind.len > 0 and (std.ascii.isAlphabetic(kind[0]) or kind[0] == '_') and for (kind) |c| {
        if (!std.ascii.isAlphanumeric(c) and c != '_') break false;
    } else true;
    if (!ident) return std.fmt.allocPrint(allocator, "@\"{f}\"", .{std.zig.fmtString(kind)});
    var out: std.ArrayListUnmanaged(u8) = .empty;
    var upper = true;
    for (kind) |c| {
        if (c == '_') {
            upper = true;
            continue;
        }
        try out.append(allocator, if (upper) std.ascii.toUpper(c) else c);
        upper = false;
    }
    if (out.items.len == 0) return std.fmt.allocPrint(allocator, "@\"{f}\"", .{std.zig.fmtString(kind)});
    return out.items;
}

/// Undo backslash escapes of a grammar literal.
fn unescapeLiteral(allocator: Allocator, raw: []const u8) ![]const u8 {
    var out: std.ArrayListUnmanaged(u8) = .empty;
    var i: usize = 0;
    while (i < raw.len) : (i += 1) {
        if (raw[i] == '\\' and i + 1 < raw.len) i += 1;
        try out.append(allocator, raw[i]);
    }
    return out.items;
}

// =============================================================================
// Tests
// =============================================================================

test "view names" {
    var arena: std.heap.ArenaAllocator = .init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();
    try std.testing.expectEqualStrings("Set", try viewName(a, "set"));
    try std.testing.expectEqualStrings("IfStmt", try viewName(a, "if_stmt"));
    try std.testing.expectEqualStrings("@\"+\"", try viewName(a, "+"));
    try std.testing.expectEqualStrings("@\"@name\"", try viewName(a, "@name"));
}
