//! Parser code generation: splices the generated lexer text together with
//! the Tag enum, Sexp type, BaseParser runtime, token/keyword mapping, and
//! the rule, parse, and start tables into one standalone Zig module.

const std = @import("std");
const Allocator = std.mem.Allocator;
const version = @import("../version.zig").version;
const grammar = @import("../grammar.zig");
const Grammar = grammar.Grammar;
const LexerSpec = grammar.LexerSpec;
const findTokenForChar = grammar.findTokenForChar;
const findTokenForLiteral = grammar.findTokenForLiteral;
const Automaton = @import("../lr/automaton.zig").Automaton;
const Table = @import("../lr/table.zig").Table;
const actions = @import("actions.zig");
const runtime = @import("runtime.zig");

/// Capitalize first letter of a rule name for building compound identifiers.
/// Assumes input is [a-z][a-z0-9]* (grammar @as rule names).
fn capitalized(name: []const u8) [64]u8 {
    var buf: [64]u8 = .{0} ** 64;
    if (name.len > 0 and name.len <= 64) {
        @memcpy(buf[0..name.len], name);
        if (buf[0] >= 'a' and buf[0] <= 'z') buf[0] -= 32;
    }
    return buf;
}

/// Generate the complete parser module. `lexerCode` is the output of
/// lexgen; its body (from the first `// ====` banner on) is spliced in.
pub fn generate(
    allocator: Allocator,
    g: *const Grammar,
    automaton: *const Automaton,
    table: *const Table,
    lexerSpec: ?*const LexerSpec,
    lexerCode: []const u8,
    emitComments: bool,
) ![]const u8 {
    var c: Codegen = .{
        .allocator = allocator,
        .g = g,
        .automaton = automaton,
        .table = table,
        .lexerSpec = lexerSpec,
        .emitComments = emitComments,
    };
    return c.run(lexerCode);
}

const Codegen = struct {
    allocator: Allocator,
    g: *const Grammar,
    automaton: *const Automaton,
    table: *const Table,
    lexerSpec: ?*const LexerSpec,
    emitComments: bool,
    tags: actions.TagSet = .{},

    fn run(self: *Codegen, lexerCode: []const u8) ![]const u8 {
        var output: std.Io.Writer.Allocating = .init(self.allocator);
        const writer = &output.writer;

        // Collect tags from actions
        try self.tags.collect(self.allocator, self.g.rules.items);

        // Strip the header from lexer code (it already has std import)
        // The lexer code starts with //! Parser...
        const lexerBody = if (std.mem.indexOf(u8, lexerCode, "// =============================================================================")) |pos|
            lexerCode[pos..]
        else
            lexerCode;

        try self.emitHeader(writer, lexerBody);
        try self.emitTagEnum(writer);
        try self.emitRuntime(writer);
        try self.emitExecuteAction(writer);
        try self.emitTokenToSymbol(writer);
        try self.emitIdentToSymbol(writer);
        try self.emitStartMethods(writer);
        try self.emitParserAlias(writer);
        try self.emitSymbolIds(writer);
        try self.emitAsMaps(writer);
        try self.emitRuleTables(writer);
        try self.emitParseTable(writer);
        try self.emitExcludes(writer);
        try self.emitStartStates(writer);
        try self.emitAcceptRules(writer);

        return try output.toOwnedSlice();
    }

    /// Header, @lang import, SIMD stub, and the generated lexer.
    fn emitHeader(self: *Codegen, writer: *std.Io.Writer, lexerBody: []const u8) !void {
        // Write header
        try writer.print("//! Generated by nexus v{s} — do not edit\n", .{version});
        try writer.writeAll(runtime.prelude);

        // Import @lang module (for Tag re-export and @as directives)
        if (self.g.lang) |name| {
            try writer.print("const {s} = @import(\"{s}.zig\");\n", .{ name, name });
        }

        try writer.writeAll(runtime.simdStub);

        // Write lexer code (body only)
        try writer.writeAll(lexerBody);
    }

    /// The Tag enum: re-exported from the lang module, or extracted from actions.
    fn emitTagEnum(self: *Codegen, writer: *std.Io.Writer) !void {
        // Generate Tag enum (re-export from language module if @lang specified)
        if (self.g.lang) |name| {
            try writer.writeAll(
                \\
                \\// =============================================================================
                \\// Tag Enum (re-exported from language module)
                \\// =============================================================================
                \\
            );
            try writer.print("pub const Tag = {s}.Tag;\n", .{name});
        } else {
            try writer.writeAll(
                \\
                \\// =============================================================================
                \\// Tag Enum (auto-extracted from grammar actions)
                \\// =============================================================================
                \\
                \\pub const Tag = enum(u8) {
                \\
            );
            for (self.tags.list.items) |tag| {
                try writer.writeAll("    @\"");
                try writer.writeAll(tag);
                try writer.writeAll("\",\n");
            }
            try writer.writeAll("    _,\n};\n");
        }
    }

    /// The Sexp type and the fixed part of BaseParser.
    fn emitRuntime(_: *Codegen, writer: *std.Io.Writer) !void {
        try writer.writeAll(runtime.sexpType);
        try writer.writeAll(runtime.parserRuntime);
    }

    /// BaseParser.executeAction: one switch arm per rule.
    fn emitExecuteAction(self: *Codegen, writer: *std.Io.Writer) !void {
        // Generate per-rule semantic actions
        for (self.g.rules.items, 0..) |rule, ruleIdx| {
            if (self.emitComments) {
                try writer.print("            // {s} =", .{self.g.symbols.items[rule.lhs].name});
                for (rule.rhs) |symId| {
                    try writer.print(" {s}", .{self.g.symbols.items[symId].name});
                }
                if (rule.action) |action| {
                    try writer.print(" \xe2\x86\x92 {s}", .{action});
                }
                try writer.writeAll("\n");
            }
            try writer.print("            {d} => ", .{ruleIdx});
            try actions.generateRuleAction(self.allocator, writer, rule);
            try writer.writeAll(",\n");
        }

        try writer.writeAll(
            \\            else => .nil,
            \\        };
            \\    }
            \\
        );
    }

    /// BaseParser.tokenToSymbol: TokenCat -> grammar symbol.
    fn emitTokenToSymbol(self: *Codegen, writer: *std.Io.Writer) !void {
        // Check if we have @as directives for "ident" - if so, route through identToSymbol
        var hasIdentAs = false;
        for (self.g.asDirectives) |directive| {
            if (std.mem.eql(u8, directive.token, "ident")) {
                hasIdentAs = true;
                break;
            }
        }

        if (hasIdentAs) {
            try writer.writeAll("\n    fn tokenToSymbol(self: *BaseParser, token: Token) u16 {\n");
        } else {
            try writer.writeAll("\n    fn tokenToSymbol(_: *BaseParser, token: Token) u16 {\n");
        }
        try writer.writeAll("        return switch (token.cat) {\n");

        // Generate token to symbol mapping
        try writer.print("            .@\"eof\" => {d},\n", .{self.g.endId});
        var emittedCats: std.StringHashMapUnmanaged(void) = .empty;
        defer {
            var it = emittedCats.keyIterator();
            while (it.next()) |key| self.allocator.free(key.*);
            emittedCats.deinit(self.allocator);
        }

        if (hasIdentAs) {
            try writer.writeAll("            .@\"ident\" => self.identToSymbol(token),\n");
        }

        for (self.g.symbols.items) |sym| {
            if (sym.kind == .terminal and sym.name.len > 0) {
                // Skip special symbols
                if (sym.name[0] == '$' or sym.name[0] == '"') continue;
                // Skip marker tokens (end with !)
                if (std.mem.endsWith(u8, sym.name, "!")) continue;
                // Skip "error" - it's the fallback
                if (std.mem.eql(u8, sym.name, "error")) continue;

                // Convert to lowercase for TokenCat matching
                var lowerBuf: [64]u8 = undefined;
                var len: usize = 0;
                for (sym.name) |c| {
                    if (len >= lowerBuf.len) break;
                    lowerBuf[len] = if (c >= 'A' and c <= 'Z') c + 32 else c;
                    len += 1;
                }
                const lowerName = lowerBuf[0..len];

                // Skip ident if we're routing through identToSymbol
                if (hasIdentAs and std.mem.eql(u8, lowerName, "ident")) continue;

                // Determine if this terminal is an @as keyword (handled by identToSymbol)
                // vs a real lexer token (needs tokenToSymbol mapping).
                //
                // A terminal is keyword-only if it has no declared lexer token.
                // Terminals declared in the tokens block (including rewriter-classified
                // tokens like if_mod, then_sep) always get direct tokenToSymbol entries,
                // even if a nonterminal shares the same name (case-insensitive).
                var isAsKeyword = false;
                if (sym.name.len > 0 and sym.name[0] >= 'A' and sym.name[0] <= 'Z') {
                    // Check if it matches an @as directive rule name (e.g., CMD↔cmd)
                    for (self.g.asDirectives) |directive| {
                        if (std.ascii.eqlIgnoreCase(sym.name, directive.rule)) {
                            isAsKeyword = true;
                            break;
                        }
                    }
                    // Check if there's a corresponding lowercase nonterminal (e.g., IF↔if)
                    // but only if the terminal is NOT a declared lexer token.
                    if (!isAsKeyword) {
                        var hasLexerToken = false;
                        if (self.lexerSpec) |spec| {
                            for (spec.tokens.items) |tok| {
                                if (std.ascii.eqlIgnoreCase(tok.name, sym.name)) {
                                    hasLexerToken = true;
                                    break;
                                }
                            }
                            if (!hasLexerToken) {
                                for (spec.rules.items) |rule| {
                                    if (std.ascii.eqlIgnoreCase(rule.token, sym.name)) {
                                        hasLexerToken = true;
                                        break;
                                    }
                                }
                            }
                        }
                        if (!hasLexerToken) {
                            // No lexer token: check nonterminal name match
                            for (self.g.symbols.items) |other| {
                                if (other.kind == .nonterminal and std.ascii.eqlIgnoreCase(sym.name, other.name)) {
                                    isAsKeyword = true;
                                    break;
                                }
                            }
                            // Final fallback: if @as exists and no lexer token, it's a keyword
                            if (!isAsKeyword and hasIdentAs) {
                                isAsKeyword = true;
                            }
                        }
                    }
                }

                // Skip @as keywords - they're handled by identToSymbol
                if (isAsKeyword) continue;

                // Only generate for tokens that look like lexer token types (start with letter, no special chars)
                var valid = len > 0 and lowerName[0] >= 'a' and lowerName[0] <= 'z';
                if (valid) {
                    for (lowerName) |ch| {
                        if (!((ch >= 'a' and ch <= 'z') or (ch >= '0' and ch <= '9') or ch == '_')) {
                            valid = false;
                            break;
                        }
                    }
                }
                if (valid and !emittedCats.contains(lowerName)) {
                    try writer.print("            .@\"{s}\" => {d},\n", .{ lowerName, sym.id });
                    try emittedCats.put(self.allocator, try self.allocator.dupe(u8, lowerName), {});
                }
            }
        }

        // Generate @op mappings for operator literals (e.g., "'=" => noteq)
        for (self.g.symbols.items) |sym| {
            if (sym.kind == .terminal and sym.name.len >= 2 and sym.name[0] == '"') {
                const rawLiteral = sym.name[1 .. sym.name.len - 1];
                // Unescape the literal (handle \\ -> \)
                var literalBuf: [256]u8 = undefined;
                var literalLen: usize = 0;
                var i: usize = 0;
                while (i < rawLiteral.len) : (i += 1) {
                    if (rawLiteral[i] == '\\' and i + 1 < rawLiteral.len) {
                        i += 1;
                        literalBuf[literalLen] = rawLiteral[i];
                    } else {
                        literalBuf[literalLen] = rawLiteral[i];
                    }
                    literalLen += 1;
                }
                const literal = literalBuf[0..literalLen];
                // Look up in @op mappings
                for (self.g.opMappings) |m| {
                    if (std.mem.eql(u8, literal, m.lit) and !emittedCats.contains(m.tok)) {
                        try writer.print("            .@\"{s}\" => {d},\n", .{ m.tok, sym.id });
                        try emittedCats.put(self.allocator, try self.allocator.dupe(u8, m.tok), {});
                        break;
                    }
                }
            }
        }

        // Map single-character terminals to the token names declared in the lexer spec.
        for (self.g.symbols.items) |sym| {
            if (sym.kind != .terminal or sym.name.len < 3 or sym.name[0] != '"') continue;

            const char: ?u8 = if (sym.name.len == 3 and sym.name[2] == '"')
                sym.name[1]
            else if (sym.name.len == 4 and sym.name[1] == '\\' and sym.name[3] == '"')
                sym.name[2]
            else
                null;

            if (char) |c| {
                if (self.lexerSpec) |spec| {
                    if (findTokenForChar(spec, c)) |tokName| {
                        if (!emittedCats.contains(tokName)) {
                            try writer.print("            .@\"{s}\" => {d},\n", .{ tokName, sym.id });
                            try emittedCats.put(self.allocator, try self.allocator.dupe(u8, tokName), {});
                        }
                        continue;
                    }
                }
            }
        }

        // Map multi-character literals to lexer token names when possible.
        for (self.g.symbols.items) |sym| {
            if (sym.kind != .terminal or sym.name.len < 4 or sym.name[0] != '"') continue;
            const raw = sym.name[1 .. sym.name.len - 1];
            if (raw.len < 2) continue;
            if (self.lexerSpec) |spec| {
                if (findTokenForLiteral(spec, raw)) |tokName| {
                    if (!emittedCats.contains(tokName)) {
                        try writer.print("            .@\"{s}\" => {d},\n", .{ tokName, sym.id });
                        try emittedCats.put(self.allocator, try self.allocator.dupe(u8, tokName), {});
                    }
                }
            }
        }

        try writer.print(
            \\            else => {d}, // error
            \\        }};
            \\    }}
            \\
        , .{self.g.errorId});
    }

    /// BaseParser.identToSymbol and the tryIdentAs* keyword promoters (@as).
    fn emitIdentToSymbol(self: *Codegen, writer: *std.Io.Writer) !void {
        // Generate identToSymbol based on @as directives
        if (self.g.asDirectives.len > 0) {
            try writer.writeAll(
                \\
                \\    fn identToSymbol(self: *BaseParser, token: Token) u16 {
                \\        const text = self.source[token.pos..][0..token.len];
                \\        if (text.len == 0) return symIdent;
                \\
            );

            // Ordered resolution: try @as candidates in declared order.
            // "self" means check if plain IDENT is valid before continuing.
            for (self.g.asDirectives) |directive| {
                if (!std.mem.eql(u8, directive.token, "ident")) continue;
                if (std.mem.eql(u8, directive.rule, "self") or std.mem.eql(u8, directive.rule, directive.token)) {
                    try writer.writeAll("        if (getAction(self.stateStack.getLast(), symIdent) != 0) return symIdent;\n");
                } else {
                    const cap = capitalized(directive.rule);
                    const capName = cap[0..directive.rule.len];
                    try writer.print("        if (self.tryIdentAs{s}(token, text)) |sym| return sym;\n", .{capName});
                }
            }

            try writer.writeAll(
                \\        return symIdent;
                \\    }
                \\
            );

            // Generate tryIdentAs* functions for each @as directive (skip "self" entries)
            // Matching mode per group:
            //   - Explicit "!" suffix (keyword!) -> permissive: action != 0 (reduce-aware)
            //   - After "self" checkpoint       -> permissive: action != 0
            //   - Before "self" (default)       -> strict: action > 0 (shift only)
            if (self.g.lang) |langName| {
                var seenSelf = false;
                for (self.g.asDirectives) |directive| {
                    if (!std.mem.eql(u8, directive.token, "ident")) continue;
                    if (std.mem.eql(u8, directive.rule, "self") or std.mem.eql(u8, directive.rule, directive.token)) {
                        seenSelf = true;
                        continue;
                    }
                    const actionCheck: []const u8 = if (directive.permissive or seenSelf) "!= 0" else "> 0";

                    const cap = capitalized(directive.rule);
                    const capName = cap[0..directive.rule.len];
                    try writer.print(
                        \\
                        \\    fn tryIdentAs{s}(self: *BaseParser, token: Token, text: []const u8) ?u16 {{
                        \\        _ = token;
                        \\        const state = self.stateStack.getLast();
                        \\        if ({s}.{s}As(text)) |id| {{
                        \\            const idIdx = @intFromEnum(id);
                        \\            const sym = {s}ToSymbol[idIdx];
                        \\            if (sym != 0 and getAction(state, sym) {s}) {{
                        \\                self.lastMatchedId = @intCast(idIdx);
                        \\                return sym;
                        \\            }}
                        \\            const fallback = {s}FallbackSymbol;
                        \\            if (fallback != 0 and getAction(state, fallback) {s}) {{
                        \\                self.lastMatchedId = @intCast(idIdx);
                        \\                return fallback;
                        \\            }}
                        \\        }}
                        \\        return null;
                        \\    }}
                        \\
                    , .{ capName, langName, directive.rule, directive.rule, actionCheck, directive.rule, actionCheck });
                }
            } else {
                // Inline: generate simple exact-match keyword functions
                var seenSelf2 = false;
                for (self.g.asDirectives) |directive| {
                    if (!std.mem.eql(u8, directive.token, "ident")) continue;
                    if (std.mem.eql(u8, directive.rule, "self") or std.mem.eql(u8, directive.rule, directive.token)) {
                        seenSelf2 = true;
                        continue;
                    }
                    const actionCheck: []const u8 = if (directive.permissive or seenSelf2) "!= 0" else "> 0";

                    const cap = capitalized(directive.rule);
                    const capName = cap[0..directive.rule.len];
                    try writer.print(
                        \\
                        \\    fn tryIdentAs{s}(self: *BaseParser, token: Token, text: []const u8) ?u16 {{
                        \\        _ = token;
                        \\        const state = self.stateStack.getLast();
                        \\        if ({s}As(text)) |id| {{
                        \\            const sym = {s}ToSymbol[@intFromEnum(id)];
                        \\            if (sym != 0 and getAction(state, sym) {s}) {{
                        \\                self.lastMatchedId = @intFromEnum(id);
                        \\                return sym;
                        \\            }}
                        \\        }}
                        \\        return null;
                        \\    }}
                        \\
                    , .{ capName, directive.rule, directive.rule, actionCheck });
                }
            }
        } else {
            // No @as directives - simple passthrough
            try writer.writeAll(
                \\
                \\    fn identToSymbol(_: *BaseParser, _: Token) u16 {
                \\        return symIdent;
                \\    }
                \\
            );
        }
    }

    /// BaseParser.parse<Start>() methods; closes BaseParser.
    fn emitStartMethods(self: *Codegen, writer: *std.Io.Writer) !void {
        // Generate parse functions for each start symbol
        for (self.g.startSymbols.items) |symId| {
            const name = self.g.symbols.items[symId].name;
            var fnameBuf: [64]u8 = undefined;
            fnameBuf[0] = if (name[0] >= 'a' and name[0] <= 'z') name[0] - 32 else name[0];
            @memcpy(fnameBuf[1..name.len], name[1..]);
            const fname = fnameBuf[0..name.len];

            var markerBuf: [128]u8 = undefined;
            const markerName = std.fmt.bufPrint(&markerBuf, "{s}!", .{name}) catch continue;
            if (self.g.getSymbol(markerName) != null) {
                try writer.print(
                    \\
                    \\    pub fn parse{s}(self: *BaseParser) !Sexp {{
                    \\        self.injectedToken = SYM_{s}_START;
                    \\        return self.doParse(SYM_{s});
                    \\    }}
                , .{ fname, name, name });
            }
        }

        try writer.writeAll("\n};\n\n");
    }

    /// The `Parser` alias and top-level parse<Start>(allocator, source) helpers.
    fn emitParserAlias(self: *Codegen, writer: *std.Io.Writer) !void {
        // Parser auto-wire: when @lang is set, allow the lang module to wrap
        // BaseParser with semantic rewriting. Mirrors the Lexer auto-wire.
        if (self.g.lang) |langName| {
            try writer.print(
                \\pub const Parser = if (@hasDecl({s}, "Parser")) {s}.Parser else BaseParser;
                \\
                \\
            , .{ langName, langName });
        }

        // Top-level parse{Start}(allocator, source) convenience helpers.
        //
        // The returned Sexp references arena-allocated memory owned by the
        // returned `parser`; the caller must keep the parser alive for the
        // lifetime of the tree and call `result.parser.deinit()` when done.
        // This mirrors the convention already used inside the generator
        // (`parseGrammarSexp` in src/frontend/frontend.zig).
        var hasTopLevelHelpers = false;
        for (self.g.startSymbols.items) |symId| {
            const name = self.g.symbols.items[symId].name;
            var markerBuf: [128]u8 = undefined;
            const markerName = std.fmt.bufPrint(&markerBuf, "{s}!", .{name}) catch continue;
            if (self.g.getSymbol(markerName) == null) continue;

            if (!hasTopLevelHelpers) {
                hasTopLevelHelpers = true;
                try writer.writeAll(
                    \\// =============================================================================
                    \\// Top-level convenience helpers (one per start symbol)
                    \\// =============================================================================
                    \\
                );
            }

            var fnameBuf: [64]u8 = undefined;
            fnameBuf[0] = if (name[0] >= 'a' and name[0] <= 'z') name[0] - 32 else name[0];
            @memcpy(fnameBuf[1..name.len], name[1..]);
            const fname = fnameBuf[0..name.len];

            const parserType: []const u8 = if (self.g.lang != null) "Parser" else "BaseParser";

            try writer.print(
                \\
                \\/// Convenience: instantiate the (lang-extended) parser and parse a whole
                \\/// {s}. Caller owns `result.parser` and must call `result.parser.deinit()`
                \\/// when done with the returned tree (the tree references arena-allocated
                \\/// memory owned by the parser).
                \\///
                \\/// The parser is returned by value, so the underlying type
                \\/// must be safely movable (no self-referential storage).
                \\/// `BaseParser` is movable by construction; custom `lang.Parser`
                \\/// wrappers must preserve this invariant.
                \\pub fn parse{s}(allocator: std.mem.Allocator, source: []const u8) !struct {{ parser: {s}, sexp: Sexp }} {{
                \\    var p = {s}.init(allocator, source);
                \\    errdefer p.deinit();
                \\    const sexp = try p.parse{s}();
                \\    return .{{ .parser = p, .sexp = sexp }};
                \\}}
                \\
            , .{ name, fname, parserType, parserType, fname });
        }
        if (hasTopLevelHelpers) try writer.writeAll("\n");
    }

    /// Start-symbol and IDENT symbol constants.
    fn emitSymbolIds(self: *Codegen, writer: *std.Io.Writer) !void {
        // Generate symbol constants
        try writer.writeAll("// Symbol IDs\n");
        for (self.g.startSymbols.items) |symId| {
            const name = self.g.symbols.items[symId].name;
            try writer.print("const SYM_{s}: u16 = {d};\n", .{ name, symId });
            // Marker token
            const markerName = try std.fmt.allocPrint(self.allocator, "{s}!", .{name});
            defer self.allocator.free(markerName);
            if (self.g.getSymbol(markerName)) |markerId| {
                try writer.print("const SYM_{s}_START: u16 = {d};\n", .{ name, markerId });
            }
        }

        // Generate SYM_IDENT for identToSymbol fallback
        if (self.g.getSymbol("IDENT")) |identId| {
            try writer.print("const symIdent: u16 = {d};\n", .{identId});
        } else {
            // Fallback to error symbol if IDENT not defined
            try writer.print("const symIdent: u16 = {d};\n", .{self.g.errorId});
        }
    }

    /// @as: <rule>Id -> symbol maps (and inline keyword matchers without @lang).
    fn emitAsMaps(self: *Codegen, writer: *std.Io.Writer) !void {
        // Generate *ToSymbol mapping arrays and keyword matchers for @as directives
        if (self.g.lang) |langName| {
            for (self.g.asDirectives) |directive| {
                if (std.mem.eql(u8, directive.rule, "self") or std.mem.eql(u8, directive.rule, directive.token)) continue;
                var specificTerminals: std.ArrayListUnmanaged(struct { name: []const u8, id: u16 }) = .empty;
                defer specificTerminals.deinit(self.allocator);

                // Collect ALL uppercase terminals as potential keyword targets.
                // @hasField at comptime filters to those in the lang module's enum.
                for (self.g.symbols.items) |sym| {
                    if (sym.kind != .terminal or sym.name.len == 0) continue;
                    if (sym.name[0] < 'A' or sym.name[0] > 'Z') continue;
                    if (sym.name[0] == '"') continue;
                    if (std.mem.endsWith(u8, sym.name, "!")) continue;
                    try specificTerminals.append(self.allocator, .{ .name = sym.name, .id = sym.id });
                }

                var fallbackNameBuf: [64]u8 = undefined;
                const fallbackName = std.ascii.upperString(fallbackNameBuf[0..directive.rule.len], directive.rule);
                var fallbackId: ?u16 = null;
                for (self.g.symbols.items) |sym| {
                    if (sym.kind == .terminal and std.mem.eql(u8, sym.name, fallbackName)) {
                        fallbackId = sym.id;
                        break;
                    }
                }

                const hasMappings = specificTerminals.items.len > 0;
                const hasFallback = fallbackId != null;
                const needsVar = hasMappings or hasFallback;

                const cap = capitalized(directive.rule);
                const capName = cap[0..directive.rule.len];
                try writer.print(
                    \\
                    \\// Mapping from {s}.{s}Id to grammar symbol IDs (computed at comptime)
                    \\const {s}ToSymbol = blk: {{
                    \\
                , .{ langName, capName, directive.rule });

                if (needsVar) {
                    try writer.writeAll("    var arr: [512]u16 = .{0} ** 512;\n");
                } else {
                    try writer.writeAll("    const arr: [512]u16 = .{0} ** 512;\n");
                }

                for (specificTerminals.items) |term| {
                    try writer.print("    if (@hasField({s}.{s}Id, \"{s}\")) arr[@intFromEnum({s}.{s}Id.{s})] = {d};\n", .{ langName, capName, term.name, langName, capName, term.name, term.id });
                }

                if (fallbackId) |fid| {
                    try writer.print(
                        \\    for (@typeInfo({s}.{s}Id).@"enum".fields) |field| {{
                        \\        if (arr[field.value] == 0) arr[field.value] = {d};
                        \\    }}
                        \\
                    , .{ langName, capName, fid });
                }

                try writer.writeAll("    break :blk arr;\n};\n");
                try writer.print("const {s}FallbackSymbol: u16 = {d};\n", .{ directive.rule, fallbackId orelse 0 });
            }
        } else {
            // Inline: generate Id enums, As functions, and ToSymbol mappings
            var emittedRules = std.StringHashMap(void).init(self.allocator);
            defer emittedRules.deinit();

            for (self.g.asDirectives) |directive| {
                if (std.mem.eql(u8, directive.rule, "self") or std.mem.eql(u8, directive.rule, directive.token)) continue;
                if (emittedRules.contains(directive.rule)) continue;
                emittedRules.put(directive.rule, {}) catch {};

                var upperBuf: [64]u8 = undefined;
                const upper = std.ascii.upperString(upperBuf[0..directive.rule.len], directive.rule);
                const cap = capitalized(directive.rule);
                const capName = cap[0..directive.rule.len];
                try writer.print("\nconst {s}Id = enum(u16) {{ {s} = 0 }};\n", .{ capName, upper });
                try writer.print("fn {s}As(name: []const u8) ?{s}Id {{ return if (std.mem.eql(u8, name, \"{s}\")) .{s} else null; }}\n", .{ directive.rule, capName, directive.rule, upper });
            }

            for (self.g.asDirectives) |directive| {
                if (std.mem.eql(u8, directive.rule, "self") or std.mem.eql(u8, directive.rule, directive.token)) continue;
                var specificTerminals: std.ArrayListUnmanaged(struct { name: []const u8, id: u16 }) = .empty;
                defer specificTerminals.deinit(self.allocator);

                for (self.g.symbols.items) |sym| {
                    if (sym.kind != .terminal or sym.name.len == 0) continue;
                    if (sym.name[0] < 'A' or sym.name[0] > 'Z') continue;
                    if (sym.name[0] == '"') continue;
                    for (self.g.symbols.items) |other| {
                        if (other.kind == .nonterminal and std.ascii.eqlIgnoreCase(sym.name, other.name)) {
                            try specificTerminals.append(self.allocator, .{ .name = sym.name, .id = sym.id });
                            break;
                        }
                    }
                }

                var fallbackNameBuf: [64]u8 = undefined;
                const fallbackName = std.ascii.upperString(fallbackNameBuf[0..directive.rule.len], directive.rule);
                var fallbackId: ?u16 = null;
                for (self.g.symbols.items) |sym| {
                    if (sym.kind == .terminal and std.mem.eql(u8, sym.name, fallbackName)) {
                        fallbackId = sym.id;
                        break;
                    }
                }

                const hasMappings = specificTerminals.items.len > 0;
                const hasFallback = fallbackId != null;
                const needsVar = hasMappings or hasFallback;

                const cap2 = capitalized(directive.rule);
                const capName2 = cap2[0..directive.rule.len];
                try writer.print(
                    \\
                    \\const {s}ToSymbol = blk: {{
                    \\
                , .{directive.rule});

                if (needsVar) {
                    try writer.writeAll("    var arr: [512]u16 = .{0} ** 512;\n");
                } else {
                    try writer.writeAll("    const arr: [512]u16 = .{0} ** 512;\n");
                }

                for (specificTerminals.items) |term| {
                    try writer.print("    if (@hasField({s}Id, \"{s}\")) arr[@intFromEnum({s}Id.{s})] = {d};\n", .{ capName2, term.name, capName2, term.name, term.id });
                }

                if (fallbackId) |fid| {
                    try writer.print(
                        \\    for (@typeInfo({s}Id).@"enum".fields) |field| {{
                        \\        if (arr[field.value] == 0) arr[field.value] = {d};
                        \\    }}
                        \\
                    , .{ capName2, fid });
                }

                try writer.writeAll("    break :blk arr;\n};\n");
            }
        }
    }

    /// Per-rule lhs symbol and rhs length.
    fn emitRuleTables(self: *Codegen, writer: *std.Io.Writer) !void {
        // Generate rule tables
        try writer.writeAll("\nconst ruleLhs = [_]u16{ ");
        for (self.g.rules.items, 0..) |rule, i| {
            if (i > 0) try writer.writeAll(", ");
            try writer.print("{d}", .{rule.lhs});
        }
        try writer.writeAll(" };\n");

        try writer.writeAll("const ruleLen = [_]u8{ ");
        for (self.g.rules.items, 0..) |rule, i| {
            if (i > 0) try writer.writeAll(", ");
            try writer.print("{d}", .{rule.rhs.len});
        }
        try writer.writeAll(" };\n");
    }

    /// The parse table (sparse rows expanded to a dense table at comptime).
    fn emitParseTable(self: *Codegen, writer: *std.Io.Writer) !void {
        const table = self.table.rows;
        const numStates = table.len;
        const numSymbols = self.g.symbols.items.len;

        try writer.print(
            \\
            \\// Parse Table: {d} states × {d} symbols
            \\const numStates = {d};
            \\const numSymbols = {d};
            \\
            \\const sparse = [numStates][]const i16{{
            \\
        , .{ numStates, numSymbols, numStates, numSymbols });

        for (table) |row| {
            try writer.writeAll("    &.{");
            var first = true;
            for (row, 0..) |action, sym| {
                const value: i16 = switch (action) {
                    .shift => |s| @as(i16, @intCast(s)),
                    .reduce => |r| -@as(i16, @intCast(r)) - 2,
                    .gotoState => |g| @as(i16, @intCast(g)),
                    .accept => -1,
                    .err => continue,
                };
                if (!first) try writer.writeAll(",");
                try writer.print("{d},{d}", .{ sym, value });
                first = false;
            }
            try writer.writeAll("},\n");
        }
        try writer.writeAll("};\n\n");

        try writer.writeAll(
            \\const parseTable = blk: {
            \\    @setEvalBranchQuota(100000);
            \\    var t: [numStates][numSymbols]i16 = .{.{0} ** numSymbols} ** numStates;
            \\    for (sparse, 0..) |row, state| {
            \\        var i: usize = 0;
            \\        while (i < row.len) : (i += 2) {
            \\            t[state][@intCast(row[i])] = row[i + 1];
            \\        }
            \\    }
            \\    break :blk t;
            \\};
            \\
            \\fn getAction(state: u16, sym: u16) i16 {
            \\    return parseTable[state][sym];
            \\}
            \\
        );
    }

    /// `X "c"` exclusions and the runtime shift override lookup.
    fn emitExcludes(self: *Codegen, writer: *std.Io.Writer) !void {
        // Generate X "c" exclude table - shift when pre==0 and char matches
        try writer.writeAll("// X \"c\" excludes: shift instead of reduce when pre==0 and char matches\n");
        try writer.writeAll("const xExcludes = [_]struct { state: u16, char: u8, shift: u16 }{\n");
        for (self.table.xExcludes.items) |x| {
            try writer.print("    .{{ .state = {d}, .char = '{c}', .shift = {d} }},\n", .{ x.state, x.char, x.shift });
        }
        try writer.writeAll("};\n\n");

        try writer.writeAll(
            \\fn getImmediateShift(state: u16, char: u8) ?i16 {
            \\    for (xExcludes) |x| {
            \\        if (x.state == state and x.char == char) return @intCast(x.shift);
            \\    }
            \\    return null;
            \\}
            \\
        );
    }

    /// Initial parser state per start symbol.
    fn emitStartStates(self: *Codegen, writer: *std.Io.Writer) !void {
        // Generate start state lookup
        try writer.writeAll("const startStates = [_]struct { sym: u16, state: u16 }{\n");
        for (self.g.startSymbols.items, self.automaton.startStates.items) |sym, state| {
            try writer.print("    .{{ .sym = {d}, .state = {d} }},\n", .{ sym, state });
        }
        try writer.writeAll("};\n\n");

        try writer.writeAll(
            \\fn getStartState(startSym: u16) u16 {
            \\    for (startStates) |entry| {
            \\        if (entry.sym == startSym) return entry.state;
            \\    }
            \\    return 0;
            \\}
            \\
        );
    }

    /// Augmented accept rules.
    fn emitAcceptRules(self: *Codegen, writer: *std.Io.Writer) !void {
        // Generate accept rules
        try writer.writeAll("\nconst acceptRules = [_]u16{ ");
        for (self.g.acceptRules.items, 0..) |ruleId, i| {
            if (i > 0) try writer.writeAll(", ");
            try writer.print("{d}", .{ruleId});
        }
        try writer.writeAll(" };\n\n");

        try writer.writeAll(
            \\fn isAcceptRule(ruleId: u16) bool {
            \\    for (acceptRules) |ar| if (ruleId == ar) return true;
            \\    return false;
            \\}
            \\
        );
    }
};
