//! Parser code generation. A generated module is composed of explicit
//! sections, in this order:
//!
//!   header        version line, `std`, the `@lang` import
//!   lexer         the lexer declarations from lexgen (TokenCat, Token,
//!                 BaseLexer, the Lexer alias)
//!   enums         Tag, Role, Start
//!   runtime       the template sections `sexp`, `parser` (with the
//!                 `parse<Start>` methods in its `startMethods` slot) and,
//!                 in schema mode, `ir` (with per-kind views)
//!   grammar       configuration, token mapping and `@as` promotion,
//!                 actions, `@as` symbol maps, rule tables and the parse
//!                 table (array literals), `X "c"` excludes, start states,
//!                 diagnostics names, trivia, repair, side labels, slots
//!   api           the `Parser` alias and `parse<Start>(allocator, source)`
//!
//! The runtime text comes from runtime_template.zig (see runtime.zig); this
//! file writes only what depends on the grammar.

const std = @import("std");
const Allocator = std.mem.Allocator;
const version = @import("../version.zig").version;
const diag = @import("../diag.zig");
const grammar = @import("../grammar.zig");
const Grammar = grammar.Grammar;
const LexerSpec = grammar.LexerSpec;
const Schema = grammar.Schema;
const Automaton = @import("../lr/automaton.zig").Automaton;
const Table = @import("../lr/table.zig").Table;
const actions = @import("actions.zig");
const semantics = @import("../semantics.zig");
const runtime = @import("runtime.zig");

pub const Options = struct {
    /// Write each rule as a comment above its action.
    emitComments: bool = false,
    /// Record node spans and rule ids (always on in schema mode).
    spans: bool = false,
    /// The grammar file, for `file:line:col` in generation errors.
    source: ?diag.Source = null,
};

/// Generate the parser module. `lexerDecls` is lexgen's declarations
/// output (no module header).
pub fn generate(
    allocator: Allocator,
    g: *const Grammar,
    automaton: *const Automaton,
    table: *const Table,
    lexerSpec: ?*const LexerSpec,
    lexerDecls: []const u8,
    options: Options,
) ![]const u8 {
    var c: Codegen = .{
        .allocator = allocator,
        .g = g,
        .automaton = automaton,
        .table = table,
        .lexerSpec = lexerSpec,
        .options = options,
    };
    return c.run(lexerDecls);
}

/// A module holding only the lexer (a grammar with no parser rules).
pub fn lexerModule(allocator: Allocator, lang: ?[]const u8, lexerDecls: []const u8) ![]const u8 {
    var output: std.Io.Writer.Allocating = .init(allocator);
    const w = &output.writer;
    try writeHeader(w, lang);
    try w.writeAll(lexerDecls);
    return output.toOwnedSlice();
}

fn writeHeader(w: *std.Io.Writer, lang: ?[]const u8) !void {
    try w.print("//! Generated by nexus v{s} — do not edit\n\nconst std = @import(\"std\");\n", .{version});
    // Imported as `lang` whatever its name, so the module's name can never
    // collide with an identifier in the generated code.
    if (lang) |name| try w.print("const lang = @import(\"{f}.zig\");\n", .{std.zig.fmtString(name)});
    try w.writeAll("\n");
}

fn banner(w: *std.Io.Writer, title: []const u8) !void {
    try w.print(
        \\
        \\// =============================================================================
        \\// {s}
        \\// =============================================================================
        \\
        \\
    , .{title});
}

/// `name` with its first letter upper-cased (start and `@as` rule names).
fn capitalized(allocator: Allocator, name: []const u8) ![]const u8 {
    const out = try allocator.dupe(u8, name);
    if (out.len > 0) out[0] = std.ascii.toUpper(out[0]);
    return out;
}

const Codegen = struct {
    allocator: Allocator,
    g: *const Grammar,
    automaton: *const Automaton,
    table: *const Table,
    lexerSpec: ?*const LexerSpec,
    options: Options,
    /// Without a schema, the Tag enum: the actions' tags, then `@tags`.
    tags: actions.TagSet = .{},
    /// Schema mode: the Tag and Role enums, in declaration order.
    schemaTags: std.ArrayList([]const u8) = .empty,
    roles: std.ArrayList([]const u8) = .empty,
    /// Some action builds a nested node (`self.nested`).
    usesNested: bool = false,
    /// The token `@as` promotes (TokenCat name, e.g. `ident`).
    promotable: ?[]const u8 = null,
    /// The executeAction function, generated before the configuration.
    actionsCode: []const u8 = "",
    /// Per rule, how the parser takes its value (see `emitRuleTables`).
    ruleValues: []u32 = &.{},

    fn schema(self: *const Codegen) ?Schema {
        return self.g.schema;
    }

    fn nodeStore(self: *const Codegen) bool {
        return self.g.schema != null or self.options.spans;
    }

    fn run(self: *Codegen, lexerDecls: []const u8) ![]const u8 {
        var output: std.Io.Writer.Allocating = .init(self.allocator);
        const w = &output.writer;

        try self.tags.collect(self.allocator, self.g.rules.items);
        for (self.g.extraTags) |t| try self.tags.register(self.allocator, t);
        if (self.schema()) |s| try self.collectSchema(s);
        try self.validate();

        self.actionsCode = try self.generateActions();

        try writeHeader(w, self.g.lang);
        try w.writeAll(lexerDecls);
        try self.emitEnums(w);
        try self.emitRuntime(w);
        try self.emitConfig(w);
        try self.emitTokenToSymbol(w);
        try self.emitIdentToSymbol(w);
        try w.writeAll(self.actionsCode);
        try self.emitAsMaps(w);
        try self.emitRuleTables(w);
        try self.emitParseTable(w);
        try self.emitExcludes(w);
        try self.emitStarts(w);
        try self.emitDiagnostics(w);
        try self.emitTrivia(w);
        try self.emitRepair(w);
        try self.emitSideLabels(w);
        try self.emitSlots(w);
        try self.emitApi(w);

        return output.toOwnedSlice();
    }

    // -------------------------------------------------------------------------
    // Checks
    // -------------------------------------------------------------------------

    fn collectSchema(self: *Codegen, s: Schema) !void {
        try self.schemaTags.appendSlice(self.allocator, try semantics.schemaTags(self.allocator, s));
        for (s.kinds) |k| {
            for (k.roles) |r| try self.addUnique(&self.roles, r.name);
            for (k.side) |r| try self.addUnique(&self.roles, r);
        }
    }

    fn addUnique(self: *Codegen, list: *std.ArrayList([]const u8), name: []const u8) !void {
        for (list.items) |existing| if (std.mem.eql(u8, existing, name)) return;
        try list.append(self.allocator, name);
    }

    /// Checks of what only the generator knows. The schema's checks (every
    /// tag an action produces is declared; side-band labels exist only for
    /// declared side roles, in schema mode) are semantics.resolve's.
    fn validate(self: *Codegen) !void {
        for (self.g.trivia) |name| {
            if (self.tokenCatOf(name) == null) {
                self.errDirective("@trivia", name, "@trivia names '{s}', which is not a lexer token", .{name});
                return error.UnknownTriviaToken;
            }
            if (self.terminalUsed(name)) |ruleId| {
                const rule = self.g.rules.items[ruleId];
                self.errDirective("@trivia", name, "@trivia token {s} is used by rule {s}; trivia never reaches the parser", .{ name, self.g.symbols.items[rule.lhs].name });
                return error.TriviaTokenInGrammar;
            }
        }

        for (self.g.asDirectives) |directive| {
            const token = self.promotable orelse directive.token;
            if (!std.mem.eql(u8, token, directive.token)) {
                self.errDirective("@as", directive.token, "@as promotes '{s}' and '{s}'; one grammar promotes one token", .{ token, directive.token });
                return error.MultiplePromotableTokens;
            }
            self.promotable = token;
            if (directive.via) |via| if (self.g.lang == null) {
                self.errDirective("@as", via, "@as via {s}: the lookup function lives in the @lang module, and the grammar has no @lang", .{via});
                return error.ViaWithoutLang;
            };
        }

        if (self.g.repair != null and self.table.repair == null) {
            self.errDirective("@repair", "", "the grammar has @repair but no repair table was computed", .{});
            return error.MissingRepairTable;
        }

        try self.checkNames();
    }

    /// A generation error at `line` (column 1 unless given).
    fn errLine(self: *const Codegen, line: u32, col: ?u32, comptime fmt: []const u8, args: anytype) void {
        const src = self.options.source orelse return diag.err(fmt, args);
        if (line == 0) return diag.err(fmt, args);
        diag.errLine(src.path, line, col orelse 1, fmt, args);
    }

    /// A generation error at `word` on the line of `directive` (`@trivia`),
    /// or at the directive itself.
    fn errDirective(self: *const Codegen, directive: []const u8, word: []const u8, comptime fmt: []const u8, args: anytype) void {
        const src = self.options.source orelse return diag.err(fmt, args);
        const text = src.text;
        var pos: usize = 0;
        while (pos < text.len) {
            const end = std.mem.findScalarPos(u8, text, pos, '\n') orelse text.len;
            const line = text[pos..end];
            if (std.mem.startsWith(u8, line, directive) and
                (line.len == directive.len or !std.ascii.isAlphanumeric(line[directive.len])))
            {
                var at = pos;
                if (word.len > 0) if (std.mem.find(u8, line[directive.len..], word)) |i| {
                    at = pos + directive.len + i;
                };
                const loc = src.at(at);
                return diag.errLine(src.path, loc.line, loc.col, fmt, args);
            }
            pos = end + 1;
        }
        diag.err(fmt, args);
    }

    /// The lexer token (TokenCat name) a grammar token name refers to.
    fn tokenCatOf(self: *const Codegen, name: []const u8) ?[]const u8 {
        const spec = self.lexerSpec orelse return null;
        for (spec.tokens.items) |tok| {
            if (std.ascii.eqlIgnoreCase(tok, name)) return tok;
        }
        return null;
    }

    /// A rule whose right-hand side uses terminal `name`.
    fn terminalUsed(self: *const Codegen, name: []const u8) ?u16 {
        for (self.g.symbols.items) |sym| {
            if (sym.kind != .terminal or !std.ascii.eqlIgnoreCase(sym.name, name)) continue;
            for (self.g.rules.items) |rule| {
                for (rule.rhs) |id| if (id == sym.id) return rule.id;
            }
        }
        return null;
    }

    // -------------------------------------------------------------------------
    // Enums and runtime
    // -------------------------------------------------------------------------

    fn emitEnums(self: *Codegen, w: *std.Io.Writer) !void {
        if (self.schema() != null) {
            try banner(w, "Tag and Role enums (from @schema)");
            const width: u8 = if (self.schemaTags.items.len <= 256) 8 else 16;
            try w.print("pub const Tag = enum(u{d}) {{\n", .{width});
            for (self.schemaTags.items) |t| try w.print("    @\"{f}\",\n", .{std.zig.fmtString(t)});
            try w.writeAll("};\n\npub const Role = enum(u16) {\n");
            for (self.roles.items) |r| try w.print("    @\"{f}\",\n", .{std.zig.fmtString(r)});
            // An empty exhaustive enum must be backed by `noreturn`; keep Role a u16.
            if (self.roles.items.len == 0) try w.writeAll("    _,\n");
            try w.writeAll("};\n");
        } else {
            try banner(w, "Tag enum (the tags the actions produce, then @tags)");
            const width: u8 = if (self.tags.list.items.len <= 256) 8 else 16;
            try w.print("pub const Tag = enum(u{d}) {{\n", .{width});
            for (self.tags.list.items) |t| try w.print("    @\"{f}\",\n", .{std.zig.fmtString(t)});
            // An empty exhaustive enum must be backed by `noreturn`.
            if (self.tags.list.items.len == 0) try w.writeAll("    _,\n");
            try w.writeAll("};\n\n/// Roles exist only in schema mode.\npub const Role = enum(u16) { _ };\n");
        }

        try w.writeAll("\n/// Start symbols; `BaseParser.parse(start)` parses one.\npub const Start = enum(u16) {\n");
        for (self.g.startSymbols.items) |symId| {
            if (try self.markerOf(symId) == null) continue;
            try w.print("    @\"{s}\" = {d},\n", .{ self.g.symbols.items[symId].name, symId });
        }
        try w.writeAll("};\n");
    }

    /// The marker token (`name!`) that selects start symbol `startSym`.
    fn markerOf(self: *const Codegen, startSym: u16) !?u16 {
        return self.g.getSymbol(try self.allocator.print("{s}!", .{self.g.symbols.items[startSym].name}));
    }

    fn emitRuntime(self: *Codegen, w: *std.Io.Writer) !void {
        try runtime.writeSection(w, "sexp", &.{});

        var methods: std.Io.Writer.Allocating = .init(self.allocator);
        for (self.g.startSymbols.items) |symId| {
            if (try self.markerOf(symId) == null) continue;
            const name = self.g.symbols.items[symId].name;
            try methods.writer.print(
                \\    pub fn parse{s}(self: *BaseParser) !Sexp {{
                \\        return self.parse(.@"{s}");
                \\    }}
                \\
                \\
            , .{ try capitalized(self.allocator, name), name });
        }
        try runtime.writeSection(w, "parser", &.{.{ .name = "startMethods", .text = methods.written() }});

        if (self.schema()) |s| {
            var views: std.Io.Writer.Allocating = .init(self.allocator);
            try self.writeViews(&views.writer, s);
            try runtime.writeSection(w, "ir", &.{.{ .name = "views", .text = views.written() }});
        }
    }

    /// `ir.Set.target(node)`: one namespace per kind, one function per role.
    fn writeViews(self: *Codegen, w: *std.Io.Writer, s: Schema) !void {
        var names: std.StringHashMapUnmanaged([]const u8) = .empty;
        for (s.kinds) |k| {
            const view = try viewName(self.allocator, k.tag);
            // The names `ir` refers to its own helpers by (see the runtime's
            // `ir` section); a view by one of them would shadow it.
            for ([_][]const u8{ "ir.Sexp", "ir.Tag", "ir.Role", "ir.at", "ir.restAt", "ir.check", "ir.node" }) |reserved| {
                if (std.mem.eql(u8, k.tag, reserved)) {
                    self.errLine(k.line, k.col, "@schema kind '{s}': the accessor namespace name '{s}' is reserved", .{ k.tag, reserved });
                    return error.ViewNameClash;
                }
            }
            if (names.get(view)) |other| {
                self.errLine(k.line, k.col, "@schema kinds '{s}' and '{s}' both map to the accessor namespace ir.{s}", .{ other, k.tag, view });
                return error.ViewNameClash;
            }
            try names.put(self.allocator, view, k.tag);
            const tag = std.zig.fmtString(k.tag);
            try w.print("    pub const {s} = struct {{\n", .{view});
            for (k.roles, 0..) |r, i| {
                const role = std.zig.fmtString(r.name);
                const what = std.zig.fmtString(try self.allocator.print("ir.{s}.{s}", .{ view, r.name }));
                if (r.rest) {
                    try w.print("        pub fn @\"{f}\"(@\"ir.node\": @\"ir.Sexp\") []const @\"ir.Sexp\" {{\n            return @\"ir.restAt\"(@\"ir.node\", .@\"{f}\", {d}, \"{f}\");\n        }}\n", .{ role, tag, i + 1, what });
                } else {
                    try w.print("        pub fn @\"{f}\"(@\"ir.node\": @\"ir.Sexp\") @\"ir.Sexp\" {{\n            return @\"ir.at\"(@\"ir.node\", .@\"{f}\", {d}, \"{f}\");\n        }}\n", .{ role, tag, i + 1, what });
                }
            }
            try w.writeAll("    };\n");
        }
    }

    // -------------------------------------------------------------------------
    // Grammar-specific code
    // -------------------------------------------------------------------------

    fn emitConfig(self: *Codegen, w: *std.Io.Writer) !void {
        try banner(w, "Grammar");
        try w.print(
            \\/// Node spans and rule ids are recorded (`@schema` or `--spans`).
            \\pub const nodeStore = {};
            \\/// Element extents are kept for side-band labels and nested nodes.
            \\const elemEnds = {};
            \\/// Lists keep trailing nils: positions are fixed by the schema.
            \\const keepTrailingNils = {};
            \\const hasTrivia = {};
            \\const hasRepair = {};
            \\/// `@as` groups the promotable token may become (see `promote`).
            \\const asGroups = {d};
            \\const numSymbols = {d};
            \\const endSymbol: u16 = {d};
            \\const errorSymbol: u16 = {d};
            \\
        , .{
            self.nodeStore(),
            self.nodeStore() and self.needsElemEnds(),
            self.schema() != null,
            self.g.trivia.len > 0,
            self.table.repair != null,
            self.asGroups(),
            self.g.symbols.items.len,
            self.g.endId,
            self.g.errorId,
        });
    }

    /// Whether some action records a side-band label or builds a nested node.
    fn needsElemEnds(self: *const Codegen) bool {
        for (self.g.rules.items) |rule| if (rule.sideLabels.len > 0) return true;
        return self.usesNested;
    }

    fn hasIdentAs(self: *const Codegen) bool {
        return self.promotable != null;
    }

    /// tokenToSymbol: TokenCat -> grammar symbol, computed once per token.
    fn emitTokenToSymbol(self: *Codegen, w: *std.Io.Writer) !void {
        try w.writeAll("\nfn tokenToSymbol(token: Token) u16 {\n    return switch (token.cat) {\n");
        try w.print("        .@\"eof\" => {d},\n", .{self.g.endId});
        // The promotable token's symbol depends on the state (`promote`).
        if (self.promotable) |tok| try w.print("        .@\"{s}\" => {s},\n", .{ tok, if (self.asGroups() > 0) "needsPromotion" else "promotableSymbol" });
        for (self.g.tokenMap) |m| try w.print("        .@\"{s}\" => {d},\n", .{ m.cat, m.sym });
        try w.print("        else => {d}, // error\n    }};\n}}\n", .{self.g.errorId});
    }

    /// @errors must name rules, @display tokens (of the grammar or the
    /// lexer), and @op must map to lexer tokens: a misspelled name would
    /// otherwise be ignored.
    fn checkNames(self: *Codegen) !void {
        var failed = false;
        for (self.g.errorNames) |e| {
            const sym = self.g.getSymbol(e.rule);
            if (sym == null or self.g.symbols.items[sym.?].kind != .nonterminal) {
                self.errLine(@max(e.line, 1), @max(e.col, 1), "@errors names '{s}', which is no rule of the grammar", .{e.rule});
                failed = true;
            }
        }
        for (self.g.displayNames) |d| {
            if (std.ascii.eqlIgnoreCase(d.token, "eof")) continue;
            const known = for (self.g.symbols.items) |sym| {
                if (sym.kind == .terminal and std.ascii.eqlIgnoreCase(sym.name, d.token)) break true;
            } else self.tokenCatOf(d.token) != null;
            if (!known) {
                self.errLine(@max(d.line, 1), @max(d.col, 1), "@display names {s}, which is no token of the grammar or the lexer", .{d.token});
                failed = true;
            }
        }
        for (self.g.opMappings) |m| {
            if (self.tokenCatOf(m.tok) == null) {
                self.errLine(@max(m.line, 1), @max(m.col, 1), "@op maps \"{s}\" to \"{s}\", which is no lexer token", .{ m.lit, m.tok });
                failed = true;
            }
        }
        if (failed) return error.UnknownName;
    }

    /// A generation error at the first rule that uses symbol `sym`.
    fn errAtUse(self: *const Codegen, sym: u16, comptime fmt: []const u8, args: anytype) void {
        for (self.g.rules.items) |rule| {
            if (rule.line > 0 and std.mem.findScalar(u16, rule.rhs, sym) != null) return self.errLine(rule.line, rule.col, fmt, args);
        }
        self.errLine(1, 1, fmt, args);
    }

    /// The `@as` groups a token may be promoted to (`self` excluded), in
    /// declared order; the runtime caches one keyword lookup per group.
    fn asGroups(self: *const Codegen) usize {
        var n: usize = 0;
        for (self.g.asDirectives) |directive| n += @intFromBool(!isSelf(directive));
        return n;
    }

    /// promote (`@as`): the promotable token becomes the first group
    /// keyword the state accepts, in declared order; `self` keeps the token
    /// itself if the state takes it. A group named after `self`, or with
    /// `!`, is permissive (any action), otherwise strict (shift only).
    fn emitIdentToSymbol(self: *Codegen, w: *std.Io.Writer) !void {
        if (self.asGroups() == 0) {
            try w.writeAll("\nfn promote(_: *BaseParser, _: Token) u16 {\n    unreachable; // no @as group\n}\n");
            return;
        }
        try w.writeAll(
            \\
            \\fn promote(self: *BaseParser, token: Token) u16 {
            \\    // The ordinal of a match made in an earlier state (before a
            \\    // reduction) is not this match's.
            \\    self.lastMatchedId = 0;
            \\    const text = self.source[token.pos..][0..token.len];
            \\    if (text.len == 0) return promotableSymbol;
            \\
        );
        var seenSelf = false;
        var group: usize = 0;
        for (self.g.asDirectives) |directive| {
            if (isSelf(directive)) {
                seenSelf = true;
                try w.writeAll("    if (getAction(self.stateStack.last().?, promotableSymbol) != 0) return promotableSymbol;\n");
                continue;
            }
            // The lang lookup is `via` when given, else `<group>As`.
            const lookup = if (self.g.lang != null)
                try self.allocator.print("lang.{s}", .{directive.via orelse try self.allocator.print("{s}As", .{directive.rule})})
            else
                try self.allocator.print("{s}As", .{directive.rule});
            const fallback = if (self.g.lang != null) try self.allocator.print("{s}FallbackSymbol", .{directive.rule}) else "0";
            try w.print("    if (self.tryPromote({d}, text, {s}, &{s}ToSymbol, {s}, {})) |sym| return sym;\n", .{
                group, lookup, directive.rule, fallback, directive.permissive or seenSelf,
            });
            group += 1;
        }
        try w.writeAll("    return promotableSymbol;\n}\n");
    }

    fn isSelf(directive: grammar.AsDirective) bool {
        return std.mem.eql(u8, directive.rule, "self") or std.mem.eql(u8, directive.rule, directive.token);
    }

    /// executeAction: one switch arm per rule whose action builds a value.
    /// A rule whose value is nil or one of its elements has no arm: the
    /// parser takes the value itself (`ruleValue`). Accept rules are never
    /// reduced (the table accepts on end of input before them).
    fn generateActions(self: *Codegen) ![]const u8 {
        var out: std.Io.Writer.Allocating = .init(self.allocator);
        const w = &out.writer;
        var arms: std.Io.Writer.Allocating = .init(self.allocator);
        const a = &arms.writer;
        const reaches = try actions.treeSymbols(self.allocator, self.g);
        var uses: actions.Uses = .{};
        self.ruleValues = try self.allocator.alloc(u32, self.g.rules.items.len);
        for (self.g.rules.items, self.ruleValues, 0..) |rule, *value, ruleIdx| {
            value.* = 0;
            if (self.g.isAcceptRule(@intCast(ruleIdx))) continue;
            if (actions.copyOf(rule)) |copy| {
                value.* = switch (copy) {
                    .nil => 1,
                    .element => |i| @as(u32, i) + 2,
                };
                continue;
            }
            if (self.options.emitComments) {
                try a.print("        // {s} =", .{self.g.symbols.items[rule.lhs].name});
                for (rule.rhs) |symId| try a.print(" {s}", .{self.g.symbols.items[symId].name});
                if (rule.actionTree) |tree| try a.print(" \xe2\x86\x92 {s}", .{try grammar.renderAction(self.allocator, tree)});
                try a.writeAll("\n");
            }
            try a.print("        {d} => ", .{ruleIdx});
            try actions.generateRuleAction(self.allocator, a, self.g, rule, reaches[rule.lhs], &uses);
            try a.writeAll(",\n");
        }
        self.usesNested = uses.nested;
        try w.writeAll("\nfn executeAction(self: *BaseParser, ruleId: u16, pass: []Sexp) Sexp {\n");
        if (!uses.self) try w.writeAll("    _ = self;\n");
        if (!uses.pass) try w.writeAll("    _ = pass;\n");
        try w.writeAll("    return switch (ruleId) {\n");
        try w.writeAll(arms.written());
        try w.writeAll("        else => unreachable,\n    };\n}\n");
        return out.written();
    }

    /// `@as`: <rule>Id -> symbol maps (and inline keyword matchers without @lang).
    fn emitAsMaps(self: *Codegen, w: *std.Io.Writer) !void {
        if (!self.hasIdentAs()) return;
        // The promotable token's own symbol (error when no rule uses it).
        var symbol = self.g.errorId;
        for (self.g.symbols.items) |sym| {
            if (sym.kind == .terminal and std.ascii.eqlIgnoreCase(sym.name, self.promotable.?)) {
                symbol = sym.id;
                break;
            }
        }
        try w.print("\nconst promotableSymbol: u16 = {d};\n", .{symbol});

        var emittedRules: std.StringHashMapUnmanaged(void) = .empty;
        for (self.g.asDirectives) |directive| {
            if (isSelf(directive)) continue;
            if (emittedRules.contains(directive.rule)) continue;
            try emittedRules.put(self.allocator, directive.rule, {});

            const cap = try capitalized(self.allocator, directive.rule);
            const upper = try std.ascii.allocUpperString(self.allocator, directive.rule);
            const idType = if (self.g.lang != null)
                try self.allocator.print("lang.{s}Id", .{cap})
            else
                try self.allocator.print("{s}Id", .{cap});

            if (self.g.lang == null) {
                // Inline: one keyword per group, matched exactly
                try w.print("\nconst {s}Id = enum(u16) {{ {s} = 0 }};\n", .{ cap, upper });
                try w.print("fn {s}As(name: []const u8) ?{s}Id {{\n    return if (std.mem.eql(u8, name, \"{s}\")) .{s} else null;\n}}\n", .{ directive.rule, cap, directive.rule, upper });
            }

            // Every UPPERCASE terminal is a potential target; `@hasField` at
            // comptime keeps those the Id enum names. Without @lang only
            // terminals that name a nonterminal are candidates.
            var targets: std.ArrayList(grammar.Symbol) = .empty;
            for (self.g.symbols.items) |sym| {
                if (sym.kind != .terminal or sym.name.len == 0) continue;
                if (sym.name[0] < 'A' or sym.name[0] > 'Z') continue;
                if (std.mem.endsWith(u8, sym.name, "!")) continue;
                if (self.g.lang == null) {
                    const matches = for (self.g.symbols.items) |other| {
                        if (other.kind == .nonterminal and std.ascii.eqlIgnoreCase(sym.name, other.name)) break true;
                    } else false;
                    if (!matches) continue;
                }
                try targets.append(self.allocator, sym);
            }

            var fallbackId: ?u16 = null;
            for (self.g.symbols.items) |sym| {
                if (sym.kind == .terminal and std.mem.eql(u8, sym.name, upper)) {
                    fallbackId = sym.id;
                    break;
                }
            }

            try w.print("\n/// {s} ordinal -> grammar symbol (0 = none)\nconst {s}ToSymbol = blk: {{\n", .{ idType, directive.rule });
            try w.print("    {s} arr: [idCount({s})]u16 = @splat(0);\n", .{ if (targets.items.len > 0 or fallbackId != null) "var" else "const", idType });
            for (targets.items) |term| {
                try w.print("    if (@hasField({s}, \"{s}\")) arr[@backingInt({s}.{s})] = {d};\n", .{ idType, term.name, idType, term.name, term.id });
            }
            if (fallbackId) |fid| {
                try w.print(
                    \\    for (@typeInfo({s}).@"enum".field_values) |value| {{
                    \\        if (arr[value] == 0) arr[value] = {d};
                    \\    }}
                    \\
                , .{ idType, fid });
            }
            try w.writeAll("    break :blk arr;\n};\n");
            if (self.g.lang != null) {
                try w.print("const {s}FallbackSymbol: u16 = {d};\n", .{ directive.rule, fallbackId orelse 0 });
            }
        }
        try self.emitKeywordCheck(w);
    }

    /// A terminal that is no lexer token reaches the parser only as a
    /// member of an `@as` group's Id enum; one no group names could never
    /// match. Without @lang the groups are known here (each matches its own
    /// name), so that is a generation error; with @lang the Id enums live
    /// in the lang module, so the parser fails to build naming it.
    fn emitKeywordCheck(self: *Codegen, w: *std.Io.Writer) !void {
        var groups: std.ArrayList([]const u8) = .empty;
        for (self.g.asDirectives) |directive| {
            if (isSelf(directive)) continue;
            try groups.append(self.allocator, directive.rule);
        }
        var any = false;
        for (self.g.symbols.items) |sym| {
            if (sym.kind != .terminal or sym.name.len == 0 or sym.name[0] < 'A' or sym.name[0] > 'Z') continue;
            if (std.mem.endsWith(u8, sym.name, "!")) continue;
            if (!self.g.isPromotedKeyword(self.lexerSpec, sym.name)) continue;
            if (std.ascii.eqlIgnoreCase(sym.name, self.promotable.?)) continue;
            const used = for (self.g.rules.items) |rule| {
                if (std.mem.findScalar(u16, rule.rhs, sym.id) != null) break true;
            } else false;
            if (!used) continue;
            // A terminal named like a group (CMD for `cmd`) is the group's
            // fallback: every Id without a terminal of its own becomes it.
            const named = for (groups.items) |group| {
                if (std.ascii.eqlIgnoreCase(group, sym.name)) break true;
            } else false;
            if (named) continue;
            if (self.g.lang == null) {
                self.errAtUse(sym.id, "{s} is no lexer token, and no @as group matches it (without @lang, group `x` promotes only the word `x`)", .{sym.name});
                return error.UnknownKeyword;
            }
            if (!any) try w.writeAll("\n// Every @as keyword terminal is a field of some group's Id enum.\ncomptime {\n");
            any = true;
            try w.writeAll("    if (!(");
            for (groups.items, 0..) |group, i| {
                if (i > 0) try w.writeAll(" or ");
                try w.print("@hasField(lang.{s}Id, \"{s}\")", .{ try capitalized(self.allocator, group), sym.name });
            }
            if (groups.items.len == 0) try w.writeAll("false");
            try w.print(")) @compileError(\"{s} is no lexer token, and no @as group's Id enum (", .{sym.name});
            for (groups.items, 0..) |group, i| {
                if (i > 0) try w.writeAll(", ");
                try w.print("lang.{s}Id", .{try capitalized(self.allocator, group)});
            }
            try w.print(") has a field {s}: rules using it could never match\");\n", .{sym.name});
        }
        if (any) try w.writeAll("}\n");
    }

    /// Per-rule lhs symbol and rhs length (u8 lengths unless some rule
    /// is longer).
    fn emitRuleTables(self: *Codegen, w: *std.Io.Writer) !void {
        try w.writeAll("\nconst ruleLhs = [_]u16{ ");
        var longest: usize = 0;
        for (self.g.rules.items, 0..) |rule, i| {
            if (i > 0) try w.writeAll(", ");
            try w.print("{d}", .{rule.lhs});
            longest = @max(longest, rule.rhs.len);
        }
        try w.print(" }};\nconst ruleLen = [_]{s}{{ ", .{if (longest > 255) "u16" else "u8"});
        for (self.g.rules.items, 0..) |rule, i| {
            if (i > 0) try w.writeAll(", ");
            try w.print("{d}", .{rule.rhs.len});
        }
        try w.print(" }};\n/// A rule's value: 0 = executeAction builds it, 1 = nil, n = element n - 2.\nconst ruleValue = [_]{s}{{ ", .{if (longest + 1 > 255) "u16" else "u8"});
        for (self.ruleValues, 0..) |value, i| {
            if (i > 0) try w.writeAll(", ");
            try w.print("{d}", .{value});
        }
        try w.writeAll(" };\n");
    }

    /// A table cell as the generated parser encodes it.
    fn actionValue(action: @import("../lr/table.zig").ParseAction) i16 {
        return switch (action) {
            .shift => |t| @intCast(t),
            .reduce => |r| -@as(i16, @intCast(r)) - 2,
            .gotoState => |t| @intCast(t),
            .accept => -1,
            .err => 0,
        };
    }

    /// The parse table as a literal, one row of actions per state: no
    /// comptime work, so its size meets no evaluation quota.
    fn emitParseTable(self: *Codegen, w: *std.Io.Writer) !void {
        const rows = self.table.rows;
        try w.print(
            \\
            \\// Parse table: {d} states x {d} symbols. 0 = error, > 0 = shift or
            \\// goto, -1 = accept, <= -2 = reduce rule (-a - 2), -32768 = a
            \\// reduction an `X "c"` hint overrides (`hinted`).
            \\const parseTable = [_][numSymbols]i16{{
            \\
        , .{ rows.len, self.g.symbols.items.len });
        const xs = self.table.xExcludes.items;
        for (rows, 0..) |row, state| {
            const hints = xs[self.table.xExcludeStart[state]..self.table.xExcludeStart[state + 1]];
            try w.writeAll("    .{");
            for (row, 0..) |action, sym| {
                const value: i16 = for (hints) |x| {
                    if (x.sym == sym) break std.math.minInt(i16);
                } else actionValue(action);
                if (sym > 0) try w.writeByte(',');
                try w.print("{d}", .{value});
            }
            try w.writeAll("},\n");
        }
        try w.writeAll("};\n");
    }

    /// `X "c"` exclusions (grouped by state): the runtime shift override,
    /// and the reduction the table holds otherwise.
    fn emitExcludes(self: *Codegen, w: *std.Io.Writer) !void {
        try w.writeAll("\n// X \"c\" excludes: shift the hinted token instead of reducing when it\n// touches the previous token (pre == 0)\n");
        try w.writeAll("const xExcludes = [_]struct { sym: u16, shift: u16, reduce: i16 }{\n");
        for (self.table.xExcludes.items) |x| {
            try w.print("    .{{ .sym = {d}, .shift = {d}, .reduce = {d} }},\n", .{ x.sym, x.shift, actionValue(self.table.rows[x.state][x.sym]) });
        }
        try w.writeAll("};\n/// State s's excludes: xExcludes[xExcludeStart[s]..xExcludeStart[s + 1]].\nconst xExcludeStart = [_]u32{");
        if (self.table.xExcludes.items.len > 0) try writeList(w, u32, self.table.xExcludeStart);
        try w.writeAll("};\n");
    }

    /// Initial state and marker token per start symbol.
    fn emitStarts(self: *Codegen, w: *std.Io.Writer) !void {
        var states: std.Io.Writer.Allocating = .init(self.allocator);
        var markers: std.Io.Writer.Allocating = .init(self.allocator);
        for (self.g.startSymbols.items, self.automaton.startStates.items) |sym, state| {
            const marker = try self.markerOf(sym) orelse continue;
            const name = self.g.symbols.items[sym].name;
            try states.writer.print("        .@\"{s}\" => {d},\n", .{ name, state });
            try markers.writer.print("        .@\"{s}\" => {d},\n", .{ name, marker });
        }
        try w.print(
            \\
            \\fn startState(start: Start) u16 {{
            \\    return switch (start) {{
            \\{s}    }};
            \\}}
            \\
            \\fn startMarker(start: Start) u16 {{
            \\    return switch (start) {{
            \\{s}    }};
            \\}}
            \\
        , .{ states.written(), markers.written() });
    }

    // -------------------------------------------------------------------------
    // Diagnostics names
    // -------------------------------------------------------------------------

    /// The reader-facing name of a symbol: `@display`, `@errors`, else the
    /// literal as written or the token name in lower case.
    fn displayName(self: *const Codegen, sym: grammar.Symbol) !?[]const u8 {
        if (sym.kind == .nonterminal) {
            // By symbol: an @errors rule may be an alias (`expr = @infix`).
            for (self.g.errorNames) |e| if (self.g.getSymbol(e.rule) == sym.id) return e.name;
            return null;
        }
        if (sym.id == self.g.errorId) return null;
        if (sym.id == self.g.endId) {
            for (self.g.displayNames) |d| if (std.ascii.eqlIgnoreCase(d.token, "eof")) return d.name;
            return "end of input";
        }
        if (sym.name.len == 0 or sym.name[0] == '$' or std.mem.endsWith(u8, sym.name, "!")) return null;
        for (self.g.displayNames) |d| if (std.mem.eql(u8, d.token, sym.name)) return d.name;
        for (self.g.displayNames) |d| if (std.ascii.eqlIgnoreCase(d.token, sym.name)) return d.name;
        if (sym.name[0] == '"') return sym.name;
        return try std.ascii.allocLowerString(self.allocator, sym.name);
    }

    /// Expected sets (from the LR stage) and symbol display names.
    fn emitDiagnostics(self: *Codegen, w: *std.Io.Writer) !void {
        const e = self.table.expected;
        try w.writeAll("\n/// Expected symbols per state: state s expects list i = expectedOf[s],\n/// expectedSymbols[expectedOffsets[i]..expectedOffsets[i + 1]].\nconst expectedSymbols = [_]u16{");
        try writeList(w, u16, e.symbols);
        try w.writeAll("};\nconst expectedOffsets = [_]u32{");
        try writeList(w, u32, e.offsets);
        try w.writeAll("};\nconst expectedOf = [_]u16{");
        try writeList(w, u16, e.ofState);
        var longest: usize = 0;
        for (0..e.numLists()) |i| longest = @max(longest, e.offsets[i + 1] - e.offsets[i]);
        try w.print("}};\n/// The most symbols a state expects: room for `BaseParser.expectedNames`.\npub const maxExpected = {d};\n", .{longest});

        try w.writeAll("\nfn symbolName(sym: u16) []const u8 {\n    return switch (sym) {\n");
        for (self.g.symbols.items) |sym| {
            const name = try self.displayName(sym) orelse continue;
            try w.print("        {d} => \"{f}\",\n", .{ sym.id, std.zig.fmtString(name) });
        }
        try w.writeAll("        else => \"\",\n    };\n}\n");
    }

    // -------------------------------------------------------------------------
    // Trivia, repair, side labels, schema slots
    // -------------------------------------------------------------------------

    fn emitTrivia(self: *Codegen, w: *std.Io.Writer) !void {
        if (self.g.trivia.len == 0) {
            try w.writeAll("\nfn isTrivia(_: TokenCat) bool {\n    return false;\n}\n");
            return;
        }
        try w.writeAll("\n/// `@trivia` tokens: kept on the trivia channel, never parsed.\nfn isTrivia(cat: TokenCat) bool {\n    return switch (cat) {\n");
        for (self.g.trivia) |name| try w.print("        .@\"{s}\" => true,\n", .{self.tokenCatOf(name).?});
        try w.writeAll("        else => false,\n    };\n}\n");
    }

    fn emitRepair(self: *Codegen, w: *std.Io.Writer) !void {
        const r = self.table.repair orelse {
            try w.writeAll("\nconst repairTokens = [_]u16{};\nconst repairOffsets = [_]u32{};\n");
            try w.writeAll("\nfn repairClass(_: u16) RepairClass {\n    return .none;\n}\n");
            return;
        };
        try w.writeAll("\n/// Tolerant repair: state s may insert, best first,\n/// repairTokens[repairOffsets[s]..repairOffsets[s + 1]].\nconst repairTokens = [_]u16{");
        try writeList(w, u16, r.tokens);
        try w.writeAll("};\nconst repairOffsets = [_]u32{");
        try writeList(w, u32, r.offsets);
        try w.writeAll(
            \\};
            \\
            \\/// The `@repair` class of a grammar symbol.
            \\fn repairClass(sym: u16) RepairClass {
            \\    return switch (sym) {
            \\
        );
        const spec = self.g.repair.?;
        const classes = [_]struct { []const []const u8, []const u8 }{
            .{ spec.holes, "hole" }, .{ spec.structure, "structure" }, .{ spec.terminators, "terminator" },
        };
        for (classes) |c| for (c[0]) |name| {
            try w.print("        {d} => .{s},\n", .{ self.g.getSymbol(name).?, c[1] });
        };
        try w.writeAll("        else => .none,\n    };\n}\n");
    }

    fn emitSideLabels(self: *Codegen, w: *std.Io.Writer) !void {
        try w.writeAll("\nfn ruleSideLabels(rule: u16) []const SideLabel {\n");
        var any = false;
        for (self.g.rules.items) |rule| {
            if (rule.sideLabels.len == 0) continue;
            if (!any) try w.writeAll("    return switch (rule) {\n");
            any = true;
            try w.print("        {d} => &.{{", .{rule.id});
            for (rule.sideLabels) |label| {
                try w.print(" .{{ .role = .@\"{f}\", .pass = {d} }},", .{ std.zig.fmtString(label.role), label.pos - 1 });
            }
            try w.writeAll(" },\n");
        }
        if (any) {
            try w.writeAll("        else => &.{},\n    };\n}\n");
        } else {
            try w.writeAll("    _ = rule;\n    return &.{};\n}\n");
        }
    }

    /// slotOf / restSlotOf / roleAt / restRoleOf: the schema's slot layout.
    fn emitSlots(self: *Codegen, w: *std.Io.Writer) !void {
        const s = self.schema() orelse {
            try w.writeAll(
                \\
                \\fn slotOf(_: Tag, _: Role) ?usize {
                \\    return null;
                \\}
                \\
                \\fn restSlotOf(_: Tag, _: Role) ?usize {
                \\    return null;
                \\}
                \\
                \\fn roleAt(_: Tag, _: usize) ?Role {
                \\    return null;
                \\}
                \\
                \\fn restRoleOf(_: Tag) ?struct { role: Role, slot: usize } {
                \\    return null;
                \\}
                \\
            );
            return;
        };
        try banner(w, "Schema slots");
        // The switches are exhaustive enums (Tag, Role): an `else` prong is
        // emitted only when some value is left, and a parameter no case
        // reads is discarded (Zig rejects both unreachable prongs and
        // unused parameters).
        const allTags = self.schemaTags.items.len;
        const allRoles = self.roles.items.len;
        var slotKinds: usize = 0;
        var restKinds: usize = 0;
        for (s.kinds) |k| {
            if (slotCount(k) > 0) slotKinds += 1;
            if (restRole(k) != null) restKinds += 1;
        }

        try w.writeAll("/// Slot of `role` in nodes of `kind` (the head is slot 0).\nfn slotOf(kind: Tag, role: Role) ?usize {\n");
        if (slotKinds == 0) try w.writeAll("    _ = role;\n");
        try w.writeAll("    return switch (kind) {\n");
        for (s.kinds) |k| {
            if (slotCount(k) == 0) continue;
            try w.print("        .@\"{f}\" => switch (role) {{\n", .{std.zig.fmtString(k.tag)});
            for (k.roles, 0..) |r, i| {
                if (r.rest) continue;
                try w.print("            .@\"{f}\" => {d},\n", .{ std.zig.fmtString(r.name), i + 1 });
            }
            if (slotCount(k) < allRoles) try w.writeAll("            else => null,\n");
            try w.writeAll("        },\n");
        }
        if (slotKinds < allTags) try w.writeAll("        else => null,\n");
        try w.writeAll("    };\n}\n");

        try w.writeAll("\n/// First slot of rest role `role` in nodes of `kind`.\nfn restSlotOf(kind: Tag, role: Role) ?usize {\n");
        if (restKinds == 0) try w.writeAll("    _ = role;\n");
        try w.writeAll("    return switch (kind) {\n");
        for (s.kinds) |k| {
            const i = restRole(k) orelse continue;
            try w.print("        .@\"{f}\" => if (role == .@\"{f}\") {d} else null,\n", .{ std.zig.fmtString(k.tag), std.zig.fmtString(k.roles[i].name), i + 1 });
        }
        if (restKinds < allTags) try w.writeAll("        else => null,\n");
        try w.writeAll("    };\n}\n");

        try w.writeAll("\n/// The slot role at `slot` of nodes of `kind`.\nfn roleAt(kind: Tag, slot: usize) ?Role {\n");
        if (slotKinds == 0) try w.writeAll("    _ = slot;\n");
        try w.writeAll("    return switch (kind) {\n");
        for (s.kinds) |k| {
            if (slotCount(k) == 0) continue;
            try w.print("        .@\"{f}\" => switch (slot) {{\n", .{std.zig.fmtString(k.tag)});
            for (k.roles, 0..) |r, i| {
                if (r.rest) continue;
                try w.print("            {d} => .@\"{f}\",\n", .{ i + 1, std.zig.fmtString(r.name) });
            }
            try w.writeAll("            else => null,\n        },\n");
        }
        if (slotKinds < allTags) try w.writeAll("        else => null,\n");
        try w.writeAll("    };\n}\n");

        try w.writeAll("\nfn restRoleOf(kind: Tag) ?struct { role: Role, slot: usize } {\n    return switch (kind) {\n");
        for (s.kinds) |k| {
            const i = restRole(k) orelse continue;
            try w.print("        .@\"{f}\" => .{{ .role = .@\"{f}\", .slot = {d} }},\n", .{ std.zig.fmtString(k.tag), std.zig.fmtString(k.roles[i].name), i + 1 });
        }
        if (restKinds < allTags) try w.writeAll("        else => null,\n");
        try w.writeAll("    };\n}\n");
    }

    // -------------------------------------------------------------------------
    // Public API
    // -------------------------------------------------------------------------

    /// The `Parser` alias and top-level parse<Start>(allocator, source)
    /// helpers. The returned tree lives in `result.parser`'s arena; the
    /// caller must `result.parser.deinit()` when done with it. The parser
    /// is returned by value, so a lang `Parser` wrapper must be movable.
    fn emitApi(self: *Codegen, w: *std.Io.Writer) !void {
        try banner(w, "API");
        if (self.g.lang != null) {
            try w.writeAll("pub const Parser = if (@hasDecl(lang, \"Parser\")) lang.Parser else BaseParser;\n");
        } else {
            try w.writeAll("pub const Parser = BaseParser;\n");
        }
        for (self.g.startSymbols.items) |symId| {
            if (try self.markerOf(symId) == null) continue;
            const name = self.g.symbols.items[symId].name;
            const fname = try capitalized(self.allocator, name);
            try w.print(
                \\
                \\/// Parse a whole {s} with a new `Parser`. The caller owns
                \\/// `result.parser` and must `deinit()` it when done with the tree.
                \\pub fn parse{s}(allocator: std.mem.Allocator, source: []const u8) !struct {{ parser: Parser, sexp: Sexp }} {{
                \\    var p = Parser.init(allocator, source);
                \\    errdefer p.deinit();
                \\    const sexp = try p.parse{s}();
                \\    return .{{ .parser = p, .sexp = sexp }};
                \\}}
                \\
            , .{ name, fname, fname });
        }
    }
};

/// ` a, b, c,` (24 values per line) for an array literal.
fn writeList(w: *std.Io.Writer, comptime T: type, values: []const T) !void {
    for (values, 0..) |v, i| {
        if (i % 24 == 0) try w.writeAll("\n   ");
        try w.print(" {d},", .{v});
    }
    if (values.len > 0) try w.writeAll("\n");
}

/// Accessor namespace for a kind: `if_stmt` -> `IfStmt`; kinds that are
/// not identifiers keep their text (`@"+"`).
fn viewName(allocator: Allocator, kind: []const u8) ![]const u8 {
    const ident = kind.len > 0 and (std.ascii.isAlphabetic(kind[0]) or kind[0] == '_') and for (kind) |c| {
        if (!std.ascii.isAlphanumeric(c) and c != '_') break false;
    } else true;
    if (!ident) return allocator.print("@\"{f}\"", .{std.zig.fmtString(kind)});
    var out: std.ArrayList(u8) = .empty;
    var upper = true;
    for (kind) |c| {
        if (c == '_') {
            upper = true;
            continue;
        }
        try out.append(allocator, if (upper) std.ascii.toUpper(c) else c);
        upper = false;
    }
    if (out.items.len == 0) return allocator.print("@\"{f}\"", .{std.zig.fmtString(kind)});
    return out.items;
}

/// Number of slot (non-rest) roles of a schema kind.
fn slotCount(k: anytype) usize {
    var n: usize = 0;
    for (k.roles) |r| n += @intFromBool(!r.rest);
    return n;
}

/// Index of the rest role of a schema kind, if it has one.
fn restRole(k: anytype) ?usize {
    for (k.roles, 0..) |r, i| if (r.rest) return i;
    return null;
}

// =============================================================================
// Tests
// =============================================================================

test "view names" {
    var arena: std.heap.ArenaAllocator = .init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();
    try std.testing.expectEqualStrings("Set", try viewName(a, "set"));
    try std.testing.expectEqualStrings("IfStmt", try viewName(a, "if_stmt"));
    try std.testing.expectEqualStrings("@\"+\"", try viewName(a, "+"));
    try std.testing.expectEqualStrings("@\"@name\"", try viewName(a, "@name"));
}
